MLIR: lib/IR/AffineExpr.cpp File Reference
AffineExpr.cpp File Reference
#include "mlir/IR/AffineExpr.h"
#include "AffineExprDetail.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Support/TypeID.h"
#include "llvm/ADT/STLExtras.h"
Functions
static bool isDivisibleBySymbol (AffineExpr expr, unsigned symbolPos, AffineExprKind opKind)
Returns true if the expression is divisible by the given symbol with position symbolPos.
static AffineExpr symbolicDivide (AffineExpr expr, unsigned symbolPos, AffineExprKind opKind)
Divides the given expression by the given symbol at position symbolPos.
static AffineExpr simplifySemiAffine (AffineExpr expr)
Simplify a semi-affine expression by handling modulo, floordiv, or ceildiv operations when the second operand simplifies to a symbol and the first operand is divisible by that symbol.
static AffineExpr getAffineDimOrSymbol (AffineExprKind kind, unsigned position, MLIRContext *context)
static AffineExpr simplifyAdd (AffineExpr lhs, AffineExpr rhs)
Simplify add expression. Return nullptr if it can't be simplified.
static AffineExpr simplifyMul (AffineExpr lhs, AffineExpr rhs)
Simplify a multiply expression. Return nullptr if it can't be simplified.
static AffineExpr simplifyFloorDiv (AffineExpr lhs, AffineExpr rhs)
static AffineExpr simplifyCeilDiv (AffineExpr lhs, AffineExpr rhs)
static AffineExpr simplifyMod (AffineExpr lhs, AffineExpr rhs)
Function Documentation
getAffineDimOrSymbol()
static AffineExpr getAffineDimOrSymbol (AffineExprKind kind, unsigned position, MLIRContext * context) static
Definition at line 444 of file AffineExpr.cpp.
References mlir::StorageUniquer::get(), and mlir::MLIRContext::getAffineUniquer().
Referenced by mlir::getAffineDimExpr(), and mlir::getAffineSymbolExpr().
isDivisibleBySymbol()
static bool isDivisibleBySymbol (AffineExpr expr, unsigned symbolPos, AffineExprKind opKind) static
Returns true if the expression is divisible by the given symbol with position symbolPos.
The argument opKind specifies here what kind of division or mod operation called this division. It helps in implementing the commutative property of the floordiv and ceildiv operations. If the argument exprKind is floordiv and expr is also a binary expression of a floordiv operation, then the commutative property can be used otherwise, the floordiv operation is not divisible. The same argument holds for ceildiv operation.
Definition at line 287 of file AffineExpr.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::CeilDiv, mlir::Constant, mlir::DimId, mlir::FloorDiv, mlir::AffineExpr::getKind(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineSymbolExpr::getPosition(), mlir::AffineBinaryOpExpr::getRHS(), mlir::AffineConstantExpr::getValue(), mlir::Mod, mlir::Mul, and mlir::SymbolId.
Referenced by simplifySemiAffine(), and symbolicDivide().
simplifyAdd()
static AffineExpr simplifyAdd (AffineExpr lhs, AffineExpr rhs) static
Simplify add expression. Return nullptr if it can't be simplified.
Definition at line 493 of file AffineExpr.cpp.
References mlir::Add, mlir::AffineExpr::dyn_cast(), mlir::FloorDiv, mlir::getAffineBinaryOpExpr(), mlir::getAffineConstantExpr(), mlir::AffineExpr::getContext(), mlir::AffineExpr::getKind(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineBinaryOpExpr::getRHS(), mlir::AffineConstantExpr::getValue(), mlir::AffineExpr::isa(), mlir::AffineExpr::isSymbolicOrConstant(), and mlir::Mul.
Referenced by mlir::AffineExpr::operator+().
simplifyCeilDiv()
static AffineExpr simplifyCeilDiv (AffineExpr lhs, AffineExpr rhs) static
Definition at line 730 of file AffineExpr.cpp.
References mlir::AffineExpr::ceilDiv(), mlir::AffineExpr::dyn_cast(), mlir::getAffineConstantExpr(), mlir::AffineExpr::getContext(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineConstantExpr::getValue(), and mlir::Mul.
Referenced by mlir::AffineExpr::ceilDiv().
simplifyFloorDiv()
static AffineExpr simplifyFloorDiv (AffineExpr lhs, AffineExpr rhs) static
Definition at line 673 of file AffineExpr.cpp.
References mlir::Add, mlir::AffineExpr::dyn_cast(), mlir::AffineExpr::floorDiv(), mlir::getAffineConstantExpr(), mlir::AffineExpr::getContext(), mlir::AffineExpr::getLargestKnownDivisor(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineConstantExpr::getValue(), and mlir::Mul.
Referenced by mlir::AffineExpr::floorDiv().
simplifyMod()
static AffineExpr simplifyMod (AffineExpr lhs, AffineExpr rhs) static
Definition at line 774 of file AffineExpr.cpp.
References mlir::Add, mlir::AffineExpr::dyn_cast(), mlir::getAffineConstantExpr(), mlir::AffineExpr::getContext(), mlir::AffineExpr::getLargestKnownDivisor(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineConstantExpr::getValue(), and mlir::mod().
Referenced by mlir::AffineExpr::operator%().
simplifyMul()
static AffineExpr simplifyMul (AffineExpr lhs, AffineExpr rhs) static
Simplify a multiply expression. Return nullptr if it can't be simplified.
Definition at line 602 of file AffineExpr.cpp.
References mlir::AffineExpr::dyn_cast(), mlir::getAffineConstantExpr(), mlir::AffineExpr::getContext(), mlir::AffineExpr::getKind(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineConstantExpr::getValue(), mlir::AffineExpr::isa(), mlir::AffineExpr::isSymbolicOrConstant(), and mlir::Mul.
Referenced by mlir::AffineExpr::operator*().
simplifySemiAffine()
static AffineExpr simplifySemiAffine (AffineExpr expr) static
Simplify a semi-affine expression by handling modulo, floordiv, or ceildiv operations when the second operand simplifies to a symbol and the first operand is divisible by that symbol.
It can be applied to any semi-affine expression. Returned expression can either be a semi-affine or pure affine expression.
Definition at line 405 of file AffineExpr.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::CeilDiv, mlir::Constant, mlir::DimId, mlir::AffineExpr::expr, mlir::FloorDiv, mlir::getAffineBinaryOpExpr(), mlir::getAffineConstantExpr(), mlir::AffineExpr::getContext(), mlir::AffineExpr::getKind(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineBinaryOpExpr::getRHS(), isDivisibleBySymbol(), mlir::Mod, mlir::Mul, symbolicDivide(), and mlir::SymbolId.
Referenced by mlir::simplifyAffineExpr().
symbolicDivide()
static AffineExpr symbolicDivide (AffineExpr expr, unsigned symbolPos, AffineExprKind opKind) static
Divides the given expression by the given symbol at position symbolPos.
It considers the divisibility condition is checked before calling itself. A null expression is returned whenever the divisibility condition fails.
Definition at line 348 of file AffineExpr.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::CeilDiv, mlir::Constant, mlir::DimId, mlir::FloorDiv, mlir::getAffineBinaryOpExpr(), mlir::getAffineConstantExpr(), mlir::AffineExpr::getContext(), mlir::AffineExpr::getKind(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineBinaryOpExpr::getRHS(), mlir::AffineConstantExpr::getValue(), isDivisibleBySymbol(), mlir::Mod, mlir::Mul, and mlir::SymbolId.
Referenced by simplifySemiAffine().