MLIR: lib/Dialect/Affine/IR/AffineOps.cpp File Reference
AffineOps.cpp File Reference
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
#include "mlir/Dialect/Affine/IR/AffineOps.cpp.inc"
Macros
#define DEBUG_TYPE "affine-analysis"
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static bool isTopLevelValue (Value value, Region *region)
A utility function to check if a value is defined at the top level of region or is an argument of region.
static Region * getAffineScope (Operation *op)
Returns the closest region enclosing op that is held by an operation with trait AffineScope; nullptr if there is no such region.
template<typename AnyMemRefDefOp >
static bool isMemRefSizeValidSymbol (AnyMemRefDefOp memrefDefOp, unsigned index, Region *region)
Returns true if the 'index' dimension of the memref defined by memrefDefOp is a statically shaped one or defined using a valid symbol for region.
static bool isDimOpValidSymbol (DimOp dimOp, Region *region)
Returns true if the result of the dim op is a valid symbol for region.
static bool isValidAffineIndexOperand (Value value, Region *region)
template<typename OpTy >
static LogicalResult verifyDimAndSymbolIdentifiers (OpTy &op, Operation::operand_range operands, unsigned numDims)
Utility function to verify that a set of operands are valid dimension and symbol identifiers.
static ParseResult parseAffineApplyOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, AffineApplyOp op)
static LogicalResult verify (AffineApplyOp op)
static llvm::SetVector< unsigned > indicesFromAffineApplyOp (ArrayRef< Value > operands)
static AffineMap promoteComposedSymbolsAsDims (AffineMap map, ArrayRef< Value > symbols)
static void composeAffineMapAndOperands (AffineMap *map, SmallVectorImpl< Value > *operands)
Implements map and operands composition and simplification to support makeComposedAffineApply.
template<class MapOrSet >
static void canonicalizePromotedSymbols (MapOrSet *mapOrSet, SmallVectorImpl< Value > *operands)
template<class MapOrSet >
static void canonicalizeMapOrSetAndOperands (MapOrSet *mapOrSet, SmallVectorImpl< Value > *operands)
static LogicalResult foldMemRefCast (Operation *op)
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
static LogicalResult verify (AffineForOp op)
static ParseResult parseBound (bool isLower, OperationState &result, OpAsmParser &p)
Parse a for operation loop bounds.
static ParseResult parseAffineForOp (OpAsmParser &parser, OperationState &result)
static void printBound (AffineMapAttr boundMap, Operation::operand_range boundOperands, const char *prefix, OpAsmPrinter &p)
static void print (OpAsmPrinter &p, AffineForOp op)
static LogicalResult foldLoopBounds (AffineForOp forOp)
Fold the constant bounds of a loop.
static LogicalResult canonicalizeLoopBounds (AffineForOp forOp)
Canonicalize the bounds of the given loop.
template<typename BoundListTy , typename LoopCreatorTy >
static void buildAffineLoopNestImpl (OpBuilder &builder, Location loc, BoundListTy lbs, BoundListTy ubs, ArrayRef< int64_t > steps, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuilderFn, LoopCreatorTy &&loopCreatorFn)
Builds an affine loop nest, using "loopCreatorFn" to create individual loop operations.
static AffineForOp buildAffineLoopFromConstants (OpBuilder &builder, Location loc, int64_t lb, int64_t ub, int64_t step, function_ref< void(OpBuilder &, Location, Value)> bodyBuilderFn)
Creates an affine loop from the bounds known to be constants.
static AffineForOp buildAffineLoopFromValues (OpBuilder &builder, Location loc, Value lb, Value ub, int64_t step, function_ref< void(OpBuilder &, Location, Value)> bodyBuilderFn)
Creates an affine loop from the bounds that may or may not be constants.
static LogicalResult verify (AffineIfOp op)
static ParseResult parseAffineIfOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, AffineIfOp op)
static ParseResult parseAffineLoadOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, AffineLoadOp op)
static LogicalResult verifyMemoryOpIndexing (Operation *op, AffineMapAttr mapAttr, Operation::operand_range mapOperands, MemRefType memrefType, unsigned numIndexOperands)
Verify common indexing invariants of affine.load, affine.store, affine.vector_load and affine.vector_store.
LogicalResult verify (AffineLoadOp op)
static ParseResult parseAffineStoreOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, AffineStoreOp op)
LogicalResult verify (AffineStoreOp op)
template<typename T >
static LogicalResult verifyAffineMinMaxOp (T op)
template<typename T >
static void printAffineMinMaxOp (OpAsmPrinter &p, T op)
template<typename T >
static ParseResult parseAffineMinMaxOp (OpAsmParser &parser, OperationState &result)
template<typename T >
static OpFoldResult foldMinMaxOp (T op, ArrayRef< Attribute > operands)
Fold an affine min or max operation with the given operands.
static ParseResult parseAffinePrefetchOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, AffinePrefetchOp op)
static LogicalResult verify (AffinePrefetchOp op)
static LogicalResult verify (AffineParallelOp op)
static void print (OpAsmPrinter &p, AffineParallelOp op)
static ParseResult parseAffineParallelOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (AffineYieldOp op)
static ParseResult parseAffineVectorLoadOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, AffineVectorLoadOp op)
static LogicalResult verifyVectorMemoryOp (Operation *op, MemRefType memrefType, VectorType vectorType)
Verify common invariants of affine.vector_load and affine.vector_store.
static LogicalResult verify (AffineVectorLoadOp op)
static ParseResult parseAffineVectorStoreOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, AffineVectorStoreOp op)
static LogicalResult verify (AffineVectorStoreOp op)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-analysis"
Definition at line 26 of file AffineOps.cpp.
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 2835 of file AffineOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
buildAffineLoopFromConstants()
static AffineForOp buildAffineLoopFromConstants (OpBuilder & builder, Location loc, int64_t lb, int64_t ub, int64_t step, function_ref< void(OpBuilder &, Location, Value)> bodyBuilderFn) static
Creates an affine loop from the bounds known to be constants.
Definition at line 1732 of file AffineOps.cpp.
References mlir::OpBuilder::create().
Referenced by buildAffineLoopFromValues(), and mlir::buildAffineLoopNest().
buildAffineLoopFromValues()
static AffineForOp buildAffineLoopFromValues (OpBuilder & builder, Location loc, Value lb, Value ub, int64_t step, function_ref< void(OpBuilder &, Location, Value)> bodyBuilderFn) static
Creates an affine loop from the bounds that may or may not be constants.
Definition at line 1739 of file AffineOps.cpp.
References buildAffineLoopFromConstants(), mlir::OpBuilder::create(), mlir::Value::getDefiningOp(), mlir::Builder::getDimIdentityMap(), and mlir::ConstantIndexOp::getValue().
Referenced by mlir::buildAffineLoopNest().
buildAffineLoopNestImpl()
template<typename BoundListTy , typename LoopCreatorTy > static void buildAffineLoopNestImpl (OpBuilder & builder, Location loc, BoundListTy lbs, BoundListTy ubs, ArrayRef< int64_t > steps, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuilderFn, LoopCreatorTy && loopCreatorFn) static
Builds an affine loop nest, using "loopCreatorFn" to create individual loop operations.
Definition at line 1692 of file AffineOps.cpp.
References mlir::OpBuilder::create(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by mlir::buildAffineLoopNest().
canonicalizeLoopBounds()
static LogicalResult canonicalizeLoopBounds (AffineForOp forOp) static
Canonicalize the bounds of the given loop.
Definition at line 1497 of file AffineOps.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::PatternRewriter::eraseOp(), mlir::failure(), foldLoopBounds(), mlir::AffineMapAttr::get(), mlir::AffineMap::getConstantMap(), getLowerBoundOperands(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::Value::getParentRegion(), getUpperBoundOperands(), mlir::OwningRewritePatternList::insert(), mlir::Region::isAncestor(), mlir::removeDuplicateExprs(), mlir::succeeded(), and mlir::success().
canonicalizeMapOrSetAndOperands()
template<class MapOrSet > static void canonicalizeMapOrSetAndOperands (MapOrSet * mapOrSet, SmallVectorImpl< Value > * operands) static
Definition at line 748 of file AffineOps.cpp.
References mlir::AffineExpr::dyn_cast(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::IntegerAttr::getValue(), mlir::m_Constant(), and mlir::matchPattern().
canonicalizePromotedSymbols()
template<class MapOrSet > static void canonicalizePromotedSymbols (MapOrSet * mapOrSet, SmallVectorImpl< Value > * operands) static
Definition at line 705 of file AffineOps.cpp.
References mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::AffineApplyNormalizer::getNumDims(), and mlir::isValidSymbol().
composeAffineMapAndOperands()
static void composeAffineMapAndOperands (AffineMap * map, SmallVectorImpl< Value > * operands) static
Implements map and operands composition and simplification to support makeComposedAffineApply.
This can be called to achieve the same effects on map and operands without creating an AffineApplyOp that needs to be immediately deleted.
Definition at line 672 of file AffineOps.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::AffineApplyNormalizer::getAffineMap(), and mlir::AffineApplyNormalizer::getOperands().
Referenced by mlir::canonicalizeSetAndOperands(), mlir::fullyComposeAffineMapAndOperands(), and mlir::makeComposedAffineApply().
foldLoopBounds()
static LogicalResult foldLoopBounds (AffineForOp forOp) static
Fold the constant bounds of a loop.
Definition at line 1451 of file AffineOps.cpp.
References mlir::AffineMap::constantFold(), mlir::failed(), mlir::failure(), mlir::AffineMap::getNumResults(), mlir::m_Constant(), mlir::matchPattern(), mlir::succeeded(), and mlir::success().
Referenced by canonicalizeLoopBounds().
foldMemRefCast()
static LogicalResult foldMemRefCast (Operation * op) static
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
It folds the source of any memref_cast into the root operation directly.
Definition at line 914 of file AffineOps.cpp.
References mlir::Operation::getOpOperands(), and mlir::success().
Referenced by mlir::AffineDmaStartOp::fold(), mlir::AffineDmaWaitOp::fold(), and verify().
foldMinMaxOp()
template<typename T > static OpFoldResult foldMinMaxOp (T op, ArrayRef< Attribute > operands) static
Fold an affine min or max operation with the given operands.
The operand list may contain nulls, which are interpreted as the operand not being a constant.
Definition at line 2213 of file AffineOps.cpp.
References mlir::IndexType::get(), mlir::AffineMapAttr::get(), mlir::IntegerAttr::get(), and mlir::OwningRewritePatternList::insert().
getAffineScope()
static Region* getAffineScope (Operation * op) static
Returns the closest region enclosing op that is held by an operation with trait AffineScope; nullptr if there is no such region.
Definition at line 117 of file AffineOps.cpp.
References mlir::Operation::getParentRegion().
Referenced by mlir::isValidDim(), mlir::isValidSymbol(), mlir::AffineDmaStartOp::verify(), mlir::AffineDmaWaitOp::verify(), verify(), verifyDimAndSymbolIdentifiers(), and verifyMemoryOpIndexing().
indicesFromAffineApplyOp()
static llvm::SetVector<unsigned> indicesFromAffineApplyOp (ArrayRef< Value > operands) static
Definition at line 455 of file AffineOps.cpp.
References mlir::detail::enumerate().
Referenced by promoteComposedSymbolsAsDims().
isDimOpValidSymbol()
static bool isDimOpValidSymbol (DimOp dimOp, Region * region) static
Returns true if the result of the dim op is a valid symbol for region.
Definition at line 196 of file AffineOps.cpp.
References isMemRefSizeValidSymbol(), and mlir::isTopLevelValue().
Referenced by mlir::isValidSymbol().
isMemRefSizeValidSymbol()
template<typename AnyMemRefDefOp > static bool isMemRefSizeValidSymbol (AnyMemRefDefOp memrefDefOp, unsigned index, Region * region) static
Returns true if the 'index' dimension of the memref defined by memrefDefOp is a statically shaped one or defined using a valid symbol for region.
Definition at line 183 of file AffineOps.cpp.
References mlir::isValidSymbol().
Referenced by isDimOpValidSymbol().
isTopLevelValue()
static bool isTopLevelValue (Value value, Region * region) static
A utility function to check if a value is defined at the top level of region or is an argument of region.
A value of index type defined at the top level of a AffineScope region is always a valid symbol for all uses in that region.
Definition at line 108 of file AffineOps.cpp.
References mlir::Value::dyn_cast(), mlir::Value::getDefiningOp(), and mlir::Operation::getParentRegion().
isValidAffineIndexOperand()
static bool isValidAffineIndexOperand (Value value, Region * region) static
Definition at line 291 of file AffineOps.cpp.
References mlir::isValidDim(), and mlir::isValidSymbol().
Referenced by mlir::AffineDmaStartOp::verify(), mlir::AffineDmaWaitOp::verify(), verify(), and verifyMemoryOpIndexing().
parseAffineApplyOp()
static ParseResult parseAffineApplyOp (OpAsmParser & parser, OperationState & result) static
Definition at line 324 of file AffineOps.cpp.
References mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OpAsmParser::getNameLoc(), mlir::AffineMapAttr::getValue(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::parseDimAndSymbolList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::success(), and mlir::OperationState::types.
parseAffineForOp()
static ParseResult parseAffineForOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1346 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), mlir::IntegerAttr::getValue(), mlir::OperationState::location, mlir::OpAsmParser::parseAttribute(), parseBound(), mlir::OpAsmParser::parseEqual(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), and mlir::OpAsmParser::parseRegionArgument().
parseAffineIfOp()
static ParseResult parseAffineIfOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1815 of file AffineOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getNameLoc(), mlir::AffineApplyNormalizer::getNumDims(), mlir::AffineApplyNormalizer::getNumSymbols(), mlir::IntegerSetAttr::getValue(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::parseDimAndSymbolList(), mlir::OpAsmParser::parseOptionalArrowTypeList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OperationState::regions, mlir::success(), and mlir::OperationState::types.
parseAffineLoadOp()
static ParseResult parseAffineLoadOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1989 of file AffineOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseAffineMapOfSSAIds(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseAffineMinMaxOp()
template<typename T > static ParseResult parseAffineMinMaxOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2191 of file AffineOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::OptionalSquare, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseAffineParallelOp()
static ParseResult parseAffineParallelOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2589 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::Builder::getArrayAttr(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getIndexType(), mlir::OpAsmParser::getNameLoc(), mlir::Builder::getNoneType(), mlir::AffineMapAttr::getValue(), mlir::StringAttr::getValue(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseAffineMapOfSSAIds(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseEqual(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOptionalArrowTypeList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgumentList(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), mlir::success(), and mlir::OperationState::types.
parseAffinePrefetchOp()
static ParseResult parseAffinePrefetchOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2280 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::Builder::getBoolAttr(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerType(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseAffineMapOfSSAIds(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseGreater(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseLess(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseAffineStoreOp()
static ParseResult parseAffineStoreOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2103 of file AffineOps.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseAffineMapOfSSAIds(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OpAsmParser::resolveOperands().
parseAffineVectorLoadOp()
static ParseResult parseAffineVectorLoadOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2717 of file AffineOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseAffineMapOfSSAIds(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseAffineVectorStoreOp()
static ParseResult parseAffineVectorStoreOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2780 of file AffineOps.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseAffineMapOfSSAIds(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::OpAsmParser::resolveOperands().
parseBound()
static ParseResult parseBound (bool isLower, OperationState & result, OpAsmParser & p) static
Parse a for operation loop bounds.
Definition at line 1255 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::Attribute::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::AffineMapAttr::get(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::parseDimAndSymbolList(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::NamedAttrList::pop_back(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
Referenced by parseAffineForOp().
print() [1/9]
static void print (OpAsmPrinter & p, AffineApplyOp op) static
Definition at line 347 of file AffineOps.cpp.
References mlir::printDimAndSymbolList(), and mlir::OpAsmPrinter::printOptionalAttrDict().
Referenced by mlir::Diagnostic::append(), mlir::tblgen::DagLeaf::DagLeaf(), mlir::Identifier::dump(), mlir::ModuleOp::dump(), mlir::AffineExpr::dump(), mlir::IntegerSet::dump(), mlir::SDBM::dump(), mlir::SDBMExpr::dump(), mlir::Attribute::dump(), mlir::AffineMap::dump(), mlir::Type::dump(), mlir::Operation::dump(), mlir::Value::dump(), mlir::Block::dump(), mlir::OperationName::dump(), mlir::Operation::emitError(), mlir::CallGraph::end(), mlir::tblgen::Operator::getDialect(), mlir::Value::getKind(), mlir::DmaWaitOp::getNumElements(), mlir::DmaStartOp::getOperationName(), mlir::Attribute::getTypeID(), mlir::Type::getTypeID(), isMemRefDereferencingOp(), mlir::OperationName::OperationName(), mlir::tblgen::DagNode::operator bool(), mlir::AffineExpr::operator!(), mlir::SDBMExpr::operator!(), mlir::AffineMap::operator!=(), mlir::IntegerSet::operator==(), mlir::ModuleOp::print(), impl::MemRefDataPrinter< T >::print(), mlir::Operation::print(), mlir::Block::print(), printDenseElementsAttrImpl(), printElidedElementsAttr(), impl::MemRefDataPrinter< T >::printFirst(), impl::MemRefDataPrinter< T >::printLast(), printMemRefMetaData(), printTimeEntry(), mlir::Diagnostic::str(), and mlir::OpState::verify().
print() [2/9]
static void print (OpAsmPrinter & p, AffineForOp op) static
Definition at line 1431 of file AffineOps.cpp.
References printBound(), and mlir::OpAsmPrinter::printOperand().
print() [3/9]
static void print (OpAsmPrinter & p, AffineIfOp op) static
Definition at line 1866 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::canonicalizeSetAndOperands(), mlir::Type::cast(), mlir::failure(), mlir::AffineMapAttr::get(), mlir::IntegerSetAttr::get(), mlir::Builder::getEmptyAffineMap(), mlir::Builder::getMultiDimIdentityMap(), mlir::AffineMap::getNumInputs(), mlir::AffineApplyNormalizer::getOperands(), mlir::Value::getType(), mlir::ValueRange::getType(), mlir::OwningRewritePatternList::insert(), mlir::OperationState::location, mlir::printDimAndSymbolList(), mlir::OpAsmPrinter::printOptionalArrowTypeList(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::Region::push_back(), mlir::success(), and mlir::OperationState::types.
print() [4/9]
static void print (OpAsmPrinter & p, AffineLoadOp op) static
Definition at line 2010 of file AffineOps.cpp.
References mlir::OpAsmPrinter::printAffineMapOfSSAIds(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [5/9]
static void print (OpAsmPrinter & p, AffineStoreOp op) static
Definition at line 2125 of file AffineOps.cpp.
References mlir::OpAsmPrinter::printAffineMapOfSSAIds(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [6/9]
static void print (OpAsmPrinter & p, AffinePrefetchOp op) static
Definition at line 2329 of file AffineOps.cpp.
References mlir::OpAsmPrinter::printAffineMapOfSSAIds(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [7/9]
static void print (OpAsmPrinter & p, AffineParallelOp op) static
Definition at line 2544 of file AffineOps.cpp.
References mlir::OpAsmPrinter::printAffineMapOfSSAIds(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
print() [8/9]
static void print (OpAsmPrinter & p, AffineVectorLoadOp op) static
Definition at line 2740 of file AffineOps.cpp.
References mlir::OpAsmPrinter::printAffineMapOfSSAIds(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [9/9]
static void print (OpAsmPrinter & p, AffineVectorStoreOp op) static
Definition at line 2804 of file AffineOps.cpp.
References mlir::OpAsmPrinter::printAffineMapOfSSAIds(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printAffineMinMaxOp()
template<typename T > static void printAffineMinMaxOp (OpAsmPrinter & p, T op) static
Definition at line 2178 of file AffineOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printBound()
static void printBound (AffineMapAttr boundMap, Operation::operand_range boundOperands, const char * prefix, OpAsmPrinter & p) static
Definition at line 1390 of file AffineOps.cpp.
References mlir::AffineExpr::dyn_cast(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResult(), mlir::AffineMapAttr::getValue(), mlir::printDimAndSymbolList(), and mlir::OpAsmPrinter::printOperand().
Referenced by print().
promoteComposedSymbolsAsDims()
static AffineMap promoteComposedSymbolsAsDims (AffineMap map, ArrayRef< Value > symbols) static
Definition at line 476 of file AffineOps.cpp.
References mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), indicesFromAffineApplyOp(), mlir::isValidSymbol(), and mlir::AffineMap::replaceDimsAndSymbols().
Referenced by mlir::AffineApplyNormalizer::AffineApplyNormalizer().
verify() [1/10]
static LogicalResult verify (AffineApplyOp op) static
Definition at line 354 of file AffineOps.cpp.
References mlir::failed(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::AffineMap::getContext(), mlir::Value::getContext(), mlir::isValidDim(), mlir::isValidSymbol(), mlir::AffineMap::replaceDimsAndSymbols(), and mlir::success().
verify() [2/10]
static LogicalResult verify (AffineForOp op) static
Lower bound.
Upper bound.
Definition at line 1225 of file AffineOps.cpp.
References mlir::failed(), mlir::failure(), mlir::AffineMap::getNumInputs(), mlir::success(), and verifyDimAndSymbolIdentifiers().
verify() [3/10]
static LogicalResult verify (AffineIfOp op) static
Definition at line 1792 of file AffineOps.cpp.
References mlir::failed(), mlir::failure(), mlir::IntegerSet::getNumDims(), mlir::IntegerSet::getNumInputs(), mlir::success(), and verifyDimAndSymbolIdentifiers().
verify() [4/10]
LogicalResult verify (AffineLoadOp op)
Definition at line 2049 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::Type::cast(), mlir::failed(), mlir::failure(), foldMemRefCast(), mlir::AffineMapAttr::get(), mlir::Builder::getEmptyAffineMap(), mlir::Builder::getMultiDimIdentityMap(), mlir::AffineMap::getNumInputs(), mlir::Value::getType(), mlir::OwningRewritePatternList::insert(), mlir::succeeded(), mlir::success(), and verifyMemoryOpIndexing().
verify() [5/10]
LogicalResult verify (AffineStoreOp op)
Definition at line 2136 of file AffineOps.cpp.
References mlir::failed(), mlir::failure(), foldMemRefCast(), mlir::OwningRewritePatternList::insert(), mlir::success(), and verifyMemoryOpIndexing().
verify() [6/10]
static LogicalResult verify (AffinePrefetchOp op) static
Definition at line 2346 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::AffineValueMap::difference(), mlir::AffineExpr::dyn_cast(), foldMemRefCast(), mlir::Region::front(), mlir::AffineMap::get(), mlir::IndexType::get(), mlir::AffineMapAttr::get(), mlir::Builder::getAffineConstantExpr(), getAffineScope(), mlir::Builder::getArrayAttr(), mlir::Builder::getContext(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getI64IntegerAttr(), mlir::AffineApplyNormalizer::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineValueMap::getNumResults(), mlir::AffineMap::getNumResults(), mlir::AffineApplyNormalizer::getOperands(), mlir::Value::getParentRegion(), mlir::AffineValueMap::getResult(), mlir::OwningRewritePatternList::insert(), mlir::Region::isAncestor(), isValidAffineIndexOperand(), mlir::OperationState::location, and mlir::success().
verify() [7/10]
static LogicalResult verify (AffineParallelOp op) static
Lower bounds.
Upper bounds.
Definition at line 2513 of file AffineOps.cpp.
References mlir::failed(), mlir::failure(), mlir::success(), and verifyDimAndSymbolIdentifiers().
verify() [8/10]
static LogicalResult verify (AffineYieldOp op) static
Definition at line 2693 of file AffineOps.cpp.
References mlir::success().
verify() [9/10]
static LogicalResult verify (AffineVectorLoadOp op) static
Definition at line 2760 of file AffineOps.cpp.
References mlir::failed(), mlir::failure(), mlir::success(), verifyMemoryOpIndexing(), and verifyVectorMemoryOp().
verify() [10/10]
static LogicalResult verify (AffineVectorStoreOp op) static
Definition at line 2815 of file AffineOps.cpp.
References mlir::failed(), mlir::failure(), mlir::success(), verifyMemoryOpIndexing(), and verifyVectorMemoryOp().
verifyAffineMinMaxOp()
template<typename T > static LogicalResult verifyAffineMinMaxOp (T op) static
Definition at line 2169 of file AffineOps.cpp.
References mlir::success().
verifyDimAndSymbolIdentifiers()
template<typename OpTy > static LogicalResult verifyDimAndSymbolIdentifiers (OpTy & op, Operation::operand_range operands, unsigned numDims) static
Utility function to verify that a set of operands are valid dimension and symbol identifiers.
The operands should be laid out such that the dimension operands are before the symbol operands. This function returns failure if there was an invalid operand. An operation is provided to emit any necessary errors.
Definition at line 302 of file AffineOps.cpp.
References getAffineScope(), mlir::isValidDim(), mlir::isValidSymbol(), and mlir::success().
Referenced by verify().
verifyMemoryOpIndexing()
static LogicalResult verifyMemoryOpIndexing (Operation * op, AffineMapAttr mapAttr, Operation::operand_range mapOperands, MemRefType memrefType, unsigned numIndexOperands) static
Verify common indexing invariants of affine.load, affine.store, affine.vector_load and affine.vector_store.
Definition at line 2023 of file AffineOps.cpp.
References mlir::Operation::emitOpError(), getAffineScope(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMapAttr::getValue(), isValidAffineIndexOperand(), and mlir::success().
Referenced by verify().
verifyVectorMemoryOp()
static LogicalResult verifyVectorMemoryOp (Operation * op, MemRefType memrefType, VectorType vectorType) static
Verify common invariants of affine.vector_load and affine.vector_store.
Definition at line 2751 of file AffineOps.cpp.
References mlir::Operation::emitOpError(), and mlir::success().
Referenced by verify().