MLIR: lib/IR/AsmPrinter.cpp File Reference
AsmPrinter.cpp File Reference
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/StandardTypes.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopedHashTable.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/SaveAndRestore.h"
#include "mlir/IR/OpAsmInterface.cpp.inc"
Classes
class mlir::detail::AsmStateImpl
Namespaces
mlir
mlir::detail
Functions
static bool shouldPrintElementsAttrWithHex (int64_t numElements)
Returns true if an ElementsAttr with the given number of elements should be printed with hex.
static raw_ostream & operator<< (raw_ostream &os, NewLineCounter &newLine)
static bool canRegisterAlias (StringRef name, llvm::StringSet<> &usedAliases)
static bool isPunct (char c)
Returns true if 'c' is an allowable punctuation character: [$._-] Returns false otherwise.
static void printFloatValue (const APFloat &apValue, raw_ostream &os)
Print a floating point value in a way that the parser will be able to round-trip losslessly.
static bool isDialectSymbolSimpleEnoughForPrettyForm (StringRef symName)
Returns if the given dialect symbol data is simple enough to print in the pretty form, i.e.
static void printDialectSymbol (raw_ostream &os, StringRef symPrefix, StringRef dialectName, StringRef symString)
Print the given dialect symbol to the stream.
static bool isBareIdentifier (StringRef name)
Returns if the given string can be represented as a bare identifier.
static void printSymbolReference (StringRef symbolRef, raw_ostream &os)
Print the given string as a symbol reference.
static void printElidedElementsAttr (raw_ostream &os)
static void printDenseIntElement (const APInt &value, raw_ostream &os, bool isSigned)
Print the integer element of a DenseElementsAttr.
static void printDenseElementsAttrImpl (bool isSplat, ShapedType type, raw_ostream &os, function_ref< void(unsigned)> printEltFn)
Variables
static llvm::ManagedStatic< AsmPrinterOptions > clOptions
Function Documentation
canRegisterAlias()
static bool canRegisterAlias (StringRef name, llvm::StringSet<> & usedAliases) static
Definition at line 286 of file AsmPrinter.cpp.
References mlir::StandardAttributes::AffineMap, mlir::Value::cast(), mlir::Attribute::dyn_cast(), mlir::Value::dyn_cast(), mlir::Type::dyn_cast(), mlir::Region::empty(), mlir::AffineMapAttr::get(), mlir::Region::getArgument(), mlir::Block::getArguments(), mlir::Operation::getAttrs(), mlir::Value::getDefiningOp(), mlir::Operation::getDialect(), mlir::DialectInterfaceCollection< InterfaceType >::getInterfaceFor(), mlir::Attribute::getKind(), mlir::Region::getNumArguments(), mlir::Operation::getNumResults(), mlir::Operation::getOperandTypes(), mlir::BlockArgument::getOwner(), mlir::OpResult::getOwner(), mlir::Block::getParentOp(), mlir::Region::getParentOp(), mlir::Operation::getRegions(), mlir::Operation::getResult(), mlir::OpResult::getResultNumber(), mlir::Operation::getResultTypes(), mlir::StandardAttributes::IntegerSet, mlir::Block::isEntryBlock(), mlir::Operation::isKnownIsolatedFromAbove(), and mlir::Operation::walk().
isBareIdentifier()
static bool isBareIdentifier (StringRef name) static
Returns if the given string can be represented as a bare identifier.
Definition at line 1237 of file AsmPrinter.cpp.
Referenced by printDenseElementsAttrImpl(), and printSymbolReference().
isDialectSymbolSimpleEnoughForPrettyForm()
static bool isDialectSymbolSimpleEnoughForPrettyForm (StringRef symName) static
Returns if the given dialect symbol data is simple enough to print in the pretty form, i.e.
without the enclosing "".
Definition at line 1148 of file AsmPrinter.cpp.
Referenced by printDialectSymbol().
isPunct()
static bool isPunct (char c) static
Returns true if 'c' is an allowable punctuation character: [$._-] Returns false otherwise.
Definition at line 803 of file AsmPrinter.cpp.
operator<<()
static raw_ostream& operator<< (raw_ostream & os, NewLineCounter & newLine) static
Definition at line 218 of file AsmPrinter.cpp.
printDenseElementsAttrImpl()
static void printDenseElementsAttrImpl (bool isSplat, ShapedType type, raw_ostream & os, function_ref< void(unsigned)> printEltFn) static
Definition at line 1441 of file AsmPrinter.cpp.
References mlir::Add, mlir::Block::args_empty(), mlir::StandardTypes::BF16, mlir::AffineExpr::cast(), mlir::Attribute::cast(), mlir::Type::cast(), mlir::CeilDiv, mlir::Constant, mlir::DimId, mlir::AffineExpr::dyn_cast(), mlir::Attribute::dyn_cast(), mlir::Region::empty(), mlir::StandardTypes::F16, mlir::StandardTypes::F32, mlir::StandardTypes::F64, mlir::FloorDiv, mlir::Region::front(), mlir::Operation::getAbstractOperation(), mlir::Block::getArguments(), mlir::Operation::getAttrs(), mlir::Region::getBlocks(), mlir::Attribute::getDialect(), mlir::Type::getDialect(), mlir::ShapedType::getElementType(), mlir::AffineExpr::getKind(), mlir::Type::getKind(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::AffineMap::getNumDims(), mlir::ShapedType::getNumElements(), mlir::Operation::getNumRegions(), mlir::Operation::getNumResults(), mlir::Operation::getNumSuccessors(), mlir::AffineMap::getNumSymbols(), mlir::Operation::getOperands(), mlir::Op< ConcreteType, Traits >::getOperation(), mlir::Block::getOperations(), mlir::Block::getParent(), mlir::Block::getPredecessors(), mlir::ShapedType::getRank(), mlir::Operation::getRegions(), mlir::Operation::getResult(), mlir::AffineMap::getResults(), mlir::FunctionType::getResults(), mlir::ShapedType::getShape(), mlir::Block::getSinglePredecessor(), mlir::detail::AsmStateImpl::getSSANameState(), mlir::OperationName::getStringRef(), mlir::Operation::getSuccessors(), mlir::Value::getType(), mlir::AffineMapAttr::getValue(), mlir::IntegerType::getWidth(), mlir::Block::hasNoPredecessors(), mlir::StandardTypes::Index, mlir::StandardTypes::Integer, mlir::Type::isa(), isBareIdentifier(), mlir::Type::isUnsignedInteger(), mlir::Mod, mlir::Mul, mlir::StandardAttributes::Opaque, print(), printDenseIntElement(), printDialectSymbol(), printFloatValue(), printGenericOp(), printSymbolReference(), mlir::LLVM::detail::printType(), mlir::StandardTypes::RankedTensor, shouldPrintElementsAttrWithHex(), mlir::SymbolId, mlir::StandardTypes::UnrankedTensor, and mlir::StandardTypes::Vector.
printDenseIntElement()
static void printDenseIntElement (const APInt & value, raw_ostream & os, bool isSigned) static
Print the integer element of a DenseElementsAttr.
Definition at line 1432 of file AsmPrinter.cpp.
Referenced by printDenseElementsAttrImpl().
printDialectSymbol()
static void printDialectSymbol (raw_ostream & os, StringRef symPrefix, StringRef dialectName, StringRef symString) static
Print the given dialect symbol to the stream.
Definition at line 1221 of file AsmPrinter.cpp.
References isDialectSymbolSimpleEnoughForPrettyForm().
Referenced by printDenseElementsAttrImpl(), and printElidedElementsAttr().
printElidedElementsAttr()
static void printElidedElementsAttr (raw_ostream & os) static
Definition at line 1279 of file AsmPrinter.cpp.
References mlir::Attribute::dyn_cast(), mlir::Attribute::getType(), mlir::Attribute::isa(), print(), printDialectSymbol(), printFloatValue(), and mlir::LLVM::detail::printType().
printFloatValue()
static void printFloatValue (const APFloat & apValue, raw_ostream & os) static
Print a floating point value in a way that the parser will be able to round-trip losslessly.
Definition at line 1088 of file AsmPrinter.cpp.
Referenced by printDenseElementsAttrImpl(), and printElidedElementsAttr().
printSymbolReference()
static void printSymbolReference (StringRef symbolRef, raw_ostream & os) static
Print the given string as a symbol reference.
A symbol reference is represented as a string prefixed with '@'. The reference is surrounded with ""'s and escaped if it has any special or non-printable characters in it.
Definition at line 1255 of file AsmPrinter.cpp.
References isBareIdentifier().
Referenced by printDenseElementsAttrImpl().
shouldPrintElementsAttrWithHex()
static bool shouldPrintElementsAttrWithHex (int64_t numElements) static
Returns true if an ElementsAttr with the given number of elements should be printed with hex.
Definition at line 190 of file AsmPrinter.cpp.
References clOptions.
Referenced by printDenseElementsAttrImpl().
Variable Documentation
clOptions
llvm::ManagedStatic<AsmPrinterOptions> clOptions static
Definition at line 103 of file AsmPrinter.cpp.
Referenced by mlir::OpPrintingFlags::OpPrintingFlags(), mlir::registerAsmPrinterCLOptions(), and shouldPrintElementsAttrWithHex().