MLIR: lib/IR/Attributes.cpp File Reference
Attributes.cpp File Reference
#include "mlir/IR/Attributes.h"
#include "AttributeDetail.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/Types.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/Endian.h"
Functions
template<bool inPlace>
static bool dictionaryAttrSort (ArrayRef< NamedAttribute > value, SmallVectorImpl< NamedAttribute > &storage)
Helper function that does either an in place sort or sorts from source array into destination.
static LogicalResult verifyFloatTypeInvariants (Location loc, Type type)
Verify construction invariants.
static LogicalResult verifyIntegerTypeInvariants (Location loc, Type type)
static size_t getDenseElementStorageWidth (size_t origWidth)
Get the bitwidth of a dense element type within the buffer.
static size_t getDenseElementStorageWidth (Type elementType)
static void setBit (char *rawData, size_t bitPos, bool value)
Set a bit to a specific value.
static bool getBit (const char *rawData, size_t bitPos)
Return the value of the specified bit.
static char * getAPIntDataPos (APInt &value, size_t bitWidth)
Get start position of actual data in value.
static void readAPInt (APInt &value, size_t bitWidth, char *outData)
Read APInt value from appropriate position.
static void writeAPInt (const char *inData, size_t bitWidth, APInt &value)
Write inData to appropriate position of APInt value.
static void writeBits (char *rawData, size_t bitPos, APInt value)
Writes value to the bit position bitPos in array rawData.
static APInt readBits (const char *rawData, size_t bitPos, size_t bitWidth)
Reads the next bitWidth bits from the bit position bitPos in array rawData.
template<typename Values >
static bool hasSameElementsOrSplat (ShapedType type, const Values &values)
Returns if 'values' corresponds to a splat, i.e.
static bool isValidIntOrFloat (Type type, int64_t dataEltSize, bool isInt, bool isSigned)
Check the information for a C++ data type, check if this type is valid for the current attribute.
template<typename APRangeT >
static void writeAPIntsToBuffer (size_t storageWidth, std::vector< char > &data, APRangeT &&values)
Utility method to write a range of APInt values to a buffer.
template<typename Fn , typename Attr >
static ShapedType mappingHelper (Fn mapping, Attr &attr, ShapedType inType, Type newElementType, llvm::SmallVectorImpl< char > &data)
Function Documentation
dictionaryAttrSort()
template<bool inPlace> static bool dictionaryAttrSort (ArrayRef< NamedAttribute > value, SmallVectorImpl< NamedAttribute > & storage) static
Helper function that does either an in place sort or sorts from source array into destination.
If inPlace then storage is both the source and the destination, else value is the source and storage destination. Returns whether source was sorted.
Definition at line 88 of file Attributes.cpp.
Referenced by mlir::DictionaryAttr::sort(), and mlir::DictionaryAttr::sortInPlace().
getAPIntDataPos()
static char* getAPIntDataPos (APInt & value, size_t bitWidth) static
Get start position of actual data in value.
Actual data is stored in last bitWidth/CHAR_BIT bytes in big endian.
Definition at line 555 of file Attributes.cpp.
Referenced by readAPInt(), and writeAPInt().
getBit()
static bool getBit (const char * rawData, size_t bitPos) static
Return the value of the specified bit.
Definition at line 549 of file Attributes.cpp.
Referenced by mlir::DenseElementsAttr::BoolElementIterator::operator*(), and readBits().
getDenseElementStorageWidth() [1/2]
static size_t getDenseElementStorageWidth (size_t origWidth) static
Get the bitwidth of a dense element type within the buffer.
DenseElementsAttr requires bitwidths greater than 1 to be aligned by 8.
Definition at line 533 of file Attributes.cpp.
Referenced by mlir::DenseElementsAttr::get(), getDenseElementStorageWidth(), mlir::DenseElementsAttr::isValidRawBuffer(), mappingHelper(), mlir::DenseElementsAttr::IntElementIterator::operator*(), and mlir::DenseElementsAttr::ComplexIntElementIterator::operator*().
getDenseElementStorageWidth() [2/2]
static size_t getDenseElementStorageWidth (Type elementType) static
Definition at line 536 of file Attributes.cpp.
References mlir::detail::getDenseElementBitWidth(), and getDenseElementStorageWidth().
hasSameElementsOrSplat()
template<typename Values > static bool hasSameElementsOrSplat (ShapedType type, const Values & values) static
Returns if 'values' corresponds to a splat, i.e.
one element, or has the same element count as 'type'.
Definition at line 606 of file Attributes.cpp.
References mlir::Attribute::getAsOpaquePointer(), and mlir::ShapedType::getNumElements().
Referenced by mlir::DenseElementsAttr::get().
isValidIntOrFloat()
static bool isValidIntOrFloat (Type type, int64_t dataEltSize, bool isInt, bool isSigned) static
Check the information for a C++ data type, check if this type is valid for the current attribute.
This method is used to verify specific type invariants that the templatized 'getValues' method cannot.
Definition at line 870 of file Attributes.cpp.
References mlir::Type::dyn_cast(), mlir::detail::getDenseElementBitWidth(), mlir::Type::isa(), mlir::Type::isIndex(), and mlir::IntegerType::isSigned().
Referenced by mlir::DenseIntOrFPElementsAttr::getRawComplex(), mlir::DenseIntOrFPElementsAttr::getRawIntOrFloat(), mlir::DenseElementsAttr::getValues(), mlir::DenseElementsAttr::isValidComplex(), mlir::DenseElementsAttr::isValidIntOrFloat(), and mlir::DenseElementsAttr::raw_int_end().
mappingHelper()
template<typename Fn , typename Attr > static ShapedType mappingHelper (Fn mapping, Attr & attr, ShapedType inType, Type newElementType, llvm::SmallVectorImpl< char > & data) static
Definition at line 1139 of file Attributes.cpp.
References mlir::VectorType::get(), mlir::RankedTensorType::get(), mlir::detail::getDenseElementBitWidth(), getDenseElementStorageWidth(), mlir::ShapedType::getNumElements(), mlir::ShapedType::getShape(), mlir::Type::isa(), and writeBits().
Referenced by mlir::DenseFPElementsAttr::mapValues(), and mlir::DenseIntElementsAttr::mapValues().
readAPInt()
static void readAPInt (APInt & value, size_t bitWidth, char * outData) static
Read APInt value from appropriate position.
Definition at line 565 of file Attributes.cpp.
References getAPIntDataPos().
Referenced by writeBits().
readBits()
static APInt readBits (const char * rawData, size_t bitPos, size_t bitWidth) static
Reads the next bitWidth bits from the bit position bitPos in array rawData.
Definition at line 591 of file Attributes.cpp.
References getBit(), and writeAPInt().
Referenced by mlir::DenseElementsAttr::IntElementIterator::operator*(), and mlir::DenseElementsAttr::ComplexIntElementIterator::operator*().
setBit()
static void setBit (char * rawData, size_t bitPos, bool value) static
Set a bit to a specific value.
Definition at line 541 of file Attributes.cpp.
Referenced by mlir::DenseElementsAttr::get(), and writeBits().
verifyFloatTypeInvariants()
static LogicalResult verifyFloatTypeInvariants (Location loc, Type type) static
Verify construction invariants.
Definition at line 251 of file Attributes.cpp.
References mlir::emitError(), mlir::Type::isa(), and mlir::success().
Referenced by mlir::FloatAttr::verifyConstructionInvariants().
verifyIntegerTypeInvariants()
static LogicalResult verifyIntegerTypeInvariants (Location loc, Type type) static
Definition at line 341 of file Attributes.cpp.
References mlir::emitError(), mlir::Type::isa(), and mlir::success().
Referenced by mlir::IntegerAttr::verifyConstructionInvariants().
writeAPInt()
static void writeAPInt (const char * inData, size_t bitWidth, APInt & value) static
Write inData to appropriate position of APInt value.
Definition at line 571 of file Attributes.cpp.
References getAPIntDataPos().
Referenced by readBits().
writeAPIntsToBuffer()
template<typename APRangeT > static void writeAPIntsToBuffer (size_t storageWidth, std::vector< char > & data, APRangeT && values) static
Utility method to write a range of APInt values to a buffer.
Definition at line 1056 of file Attributes.cpp.
References writeBits().
Referenced by mlir::DenseIntOrFPElementsAttr::getRaw().
writeBits()
static void writeBits (char * rawData, size_t bitPos, APInt value) static
Writes value to the bit position bitPos in array rawData.
Definition at line 577 of file Attributes.cpp.
References readAPInt(), and setBit().
Referenced by mlir::DenseElementsAttr::get(), mappingHelper(), and writeAPIntsToBuffer().