MLIR: mlir::ArrayAttr Class Reference
mlir::ArrayAttr Class Reference
Array attributes are lists of other attributes.
#include "mlir/IR/Attributes.h"
Public Types
using ValueType = ArrayRef< Attribute >
using iterator = llvm::ArrayRef< Attribute >::iterator
Support range iteration.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
ArrayRef< Attribute > getValue () const
Attribute operator[] (unsigned idx) const
iterator begin () const
iterator end () const
size_t size () const
bool empty () const
template<typename AttrTy >
llvm::iterator_range< attr_value_iterator< AttrTy > > getAsRange ()
template<typename AttrTy , typename UnderlyingTy >
auto getAsRange ()
Static Public Member Functions
static ArrayAttr get (ArrayRef< Attribute > value, MLIRContext *context)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Array attributes are lists of other attributes.
They are not necessarily type homogenous given that attributes don't, in general, carry types.
Definition at line 246 of file Attributes.h.
Member Typedef Documentation
iterator
using mlir::ArrayAttr::iterator = llvm::ArrayRef<Attribute>::iterator
Support range iteration.
Definition at line 258 of file Attributes.h.
ValueType
using mlir::ArrayAttr::ValueType = ArrayRef<Attribute>
Definition at line 250 of file Attributes.h.
Member Function Documentation
begin()
iterator mlir::ArrayAttr::begin () const inline
Definition at line 259 of file Attributes.h.
empty()
bool mlir::ArrayAttr::empty () const inline
Definition at line 262 of file Attributes.h.
References mlir::operator*().
end()
iterator mlir::ArrayAttr::end () const inline
Definition at line 260 of file Attributes.h.
get()
ArrayAttr ArrayAttr::get (ArrayRef< Attribute > value, MLIRContext * context) static
Definition at line 68 of file Attributes.cpp.
References mlir::StandardAttributes::Array.
Referenced by collapseReassociationMaps(), mlir::Builder::getArrayAttr(), getTransferOpAdapter(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::indexing_maps(), mlir::linalg::interchange(), mlir::isColumnMajorMatmul(), mlir::isRowMajorMatmul(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::iterator_types(), makeI64ArrayAttr(), rebuildAttrAfterRAUW(), replaceUnitDims(), replaceUnitExtents(), and mlir::gpu::setMappingAttr().
getAsRange() [1/2]
template<typename AttrTy > llvm::iterator_range<attr_value_iterator<AttrTy> > mlir::ArrayAttr::getAsRange () inline
Definition at line 279 of file Attributes.h.
Referenced by extractVector(), and getI64SubArray().
getAsRange() [2/2]
template<typename AttrTy , typename UnderlyingTy > auto mlir::ArrayAttr::getAsRange () inline
Definition at line 284 of file Attributes.h.
getValue()
ArrayRef< Attribute > ArrayAttr::getValue () const
Definition at line 72 of file Attributes.cpp.
Referenced by mlir::spirv::VerCapExtAttr::getCapabilities(), mlir::spirv::VerCapExtAttr::getExtensions(), getNumDynamicEntriesUpToIdx(), getPhiIncomingBlock(), mlir::spirv::VerCapExtAttr::verifyConstructionInvariants(), verifySubViewOpPart(), and walkSymbolRefs().
operator[]()
Attribute ArrayAttr::operator[] (unsigned idx) const
Definition at line 74 of file Attributes.cpp.
size()
size_t mlir::ArrayAttr::size () const inline
Definition at line 261 of file Attributes.h.
Referenced by getI64SubArray(), getPhiIncomingBlock(), inferExtractOpResultType(), inferStridedSliceOpResultType(), isIntegerArrayAttrConfinedToShape(), isIntegerArrayAttrSmallerThanShape(), isSumOfIntegerArrayAttrConfinedToShape(), parseShuffleVectorOp(), verify(), verifySubViewOpPart(), and verifyTransferOp().
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp