MLIR: mlir::BufferAssignmentPlacer Class Reference
mlir::BufferAssignmentPlacer Class Reference
Prepares a buffer placement phase.
#include "mlir/Transforms/BufferPlacement.h"
Public Member Functions
BufferAssignmentPlacer (Operation *op)
Creates a new assignment builder.
Operation * getOperation () const
Returns the operation this analysis was constructed from.
OpBuilder::InsertPoint computeAllocPosition (OpResult result)
Computes the actual position to place allocs for the given result.
Detailed Description
Prepares a buffer placement phase.
It can place (user-defined) alloc nodes. This simplifies the integration of the actual buffer-placement pass. Sample usage: BufferAssignmentPlacer baHelper(regionOp); -> determine alloc positions auto allocPosition = baHelper.computeAllocPosition(value); -> place alloc allocBuilder.setInsertionPoint(positions.getAllocPosition()); <create alloc>=""> Note: this class is intended to be used during legalization. In order to move alloc and dealloc nodes into the right places you can use the createBufferPlacementPass() function.
Definition at line 39 of file BufferPlacement.h.
Constructor & Destructor Documentation
BufferAssignmentPlacer()
BufferAssignmentPlacer::BufferAssignmentPlacer (Operation * op) explicit
Creates a new assignment builder.
Creates a new assignment placer.
Definition at line 689 of file BufferPlacement.cpp.
Member Function Documentation
computeAllocPosition()
OpBuilder::InsertPoint BufferAssignmentPlacer::computeAllocPosition (OpResult result)
Computes the actual position to place allocs for the given result.
Computes the actual position to place allocs for the given value.
Definition at line 693 of file BufferPlacement.cpp.
References mlir::Operation::getBlock(), and mlir::OpResult::getOwner().
Referenced by getOperation().
getOperation()
Operation* mlir::BufferAssignmentPlacer::getOperation () const inline
Returns the operation this analysis was constructed from.
Definition at line 45 of file BufferPlacement.h.
References computeAllocPosition().
The documentation for this class was generated from the following files:
include/mlir/Transforms/BufferPlacement.h
lib/Transforms/BufferPlacement.cpp