MLIR: mlir::UnrankedMemRefDescriptor Class Reference
mlir::UnrankedMemRefDescriptor Class Reference
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
Public Member Functions
UnrankedMemRefDescriptor (Value descriptor)
Construct a helper for the given descriptor value.
Value rank (OpBuilder &builder, Location loc)
Builds IR extracting the rank from the descriptor.
void setRank (OpBuilder &builder, Location loc, Value value)
Builds IR setting the rank in the descriptor.
Value memRefDescPtr (OpBuilder &builder, Location loc)
Builds IR extracting ranked memref descriptor ptr.
void setMemRefDescPtr (OpBuilder &builder, Location loc, Value value)
Builds IR setting ranked memref descriptor ptr.
Public Member Functions inherited from mlir::StructBuilder
StructBuilder (Value v)
Construct a helper for the given value.
operator Value ()
Static Public Member Functions
static UnrankedMemRefDescriptor undef (OpBuilder &builder, Location loc, Type descriptorType)
Builds IR creating an undef value of the descriptor type.
static Value pack (OpBuilder &builder, Location loc, LLVMTypeConverter &converter, UnrankedMemRefType type, ValueRange values)
Builds IR populating an unranked MemRef descriptor structure from a list of individual constituent values in the following order:
static void unpack (OpBuilder &builder, Location loc, Value packed, SmallVectorImpl< Value > &results)
Builds IR extracting individual elements that compose an unranked memref descriptor and returns them as results list.
static unsigned getNumUnpackedValues ()
Returns the number of non-aggregate values that would be produced by unpack.
static void computeSizes (OpBuilder &builder, Location loc, LLVMTypeConverter &typeConverter, ArrayRef< UnrankedMemRefDescriptor > values, SmallVectorImpl< Value > &sizes)
Builds IR computing the sizes in bytes (suitable for opaque allocation) and appends the corresponding values into sizes.
Static Public Member Functions inherited from mlir::StructBuilder
static StructBuilder undef (OpBuilder &builder, Location loc, Type descriptorType)
Builds IR creating an undef value of the descriptor type.
Additional Inherited Members
Protected Member Functions inherited from mlir::StructBuilder
Value extractPtr (OpBuilder &builder, Location loc, unsigned pos)
Builds IR to extract a value from the struct at position pos.
void setPtr (OpBuilder &builder, Location loc, unsigned pos, Value ptr)
Builds IR to set a value in the struct at position pos.
Protected Attributes inherited from mlir::StructBuilder
Value value
Type structType
Detailed Description
Definition at line 341 of file ConvertStandardToLLVM.h.
Constructor & Destructor Documentation
UnrankedMemRefDescriptor()
UnrankedMemRefDescriptor::UnrankedMemRefDescriptor (Value descriptor) explicit
Construct a helper for the given descriptor value.
Definition at line 739 of file StandardToLLVM.cpp.
Referenced by undef().
Member Function Documentation
computeSizes()
void UnrankedMemRefDescriptor::computeSizes (OpBuilder & builder, Location loc, LLVMTypeConverter & typeConverter, ArrayRef< UnrankedMemRefDescriptor > values, SmallVectorImpl< Value > & sizes) static
Builds IR computing the sizes in bytes (suitable for opaque allocation) and appends the corresponding values into sizes.
Definition at line 793 of file StandardToLLVM.cpp.
References mlir::ceilDiv(), mlir::OpBuilder::create(), createIndexAttrConstant(), mlir::LLVMTypeConverter::getIndexType(), mlir::LLVMTypeConverter::getIndexTypeBitwidth(), mlir::LLVMTypeConverter::getPointerBitwidth(), and rank().
Referenced by mlir::LLVM::detail::vectorOneToOneRewrite().
getNumUnpackedValues()
static unsigned mlir::UnrankedMemRefDescriptor::getNumUnpackedValues () inline static
Returns the number of non-aggregate values that would be produced by unpack.
Definition at line 373 of file ConvertStandardToLLVM.h.
Referenced by wrapExternalFunction().
memRefDescPtr()
Value UnrankedMemRefDescriptor::memRefDescPtr (OpBuilder & builder, Location loc)
Builds IR extracting ranked memref descriptor ptr.
Definition at line 757 of file StandardToLLVM.cpp.
References mlir::StructBuilder::extractPtr(), and kPtrInUnrankedMemRefDescriptor.
Referenced by unpack(), and mlir::LLVM::detail::vectorOneToOneRewrite().
pack()
Value UnrankedMemRefDescriptor::pack (OpBuilder & builder, Location loc, LLVMTypeConverter & converter, UnrankedMemRefType type, ValueRange values) static
Builds IR populating an unranked MemRef descriptor structure from a list of individual constituent values in the following order:
rank of the memref;
pointer to the memref descriptor.
Definition at line 770 of file StandardToLLVM.cpp.
References mlir::TypeConverter::convertType(), kPtrInUnrankedMemRefDescriptor, kRankInUnrankedMemRefDescriptor, and undef().
Referenced by mlir::LLVMTypeConverter::LLVMTypeConverter(), and wrapExternalFunction().
rank()
Value UnrankedMemRefDescriptor::rank (OpBuilder & builder, Location loc)
Builds IR extracting the rank from the descriptor.
Definition at line 750 of file StandardToLLVM.cpp.
References mlir::StructBuilder::extractPtr(), and kRankInUnrankedMemRefDescriptor.
Referenced by computeSizes(), unpack(), and mlir::LLVM::detail::vectorOneToOneRewrite().
setMemRefDescPtr()
void UnrankedMemRefDescriptor::setMemRefDescPtr (OpBuilder & builder, Location loc, Value value)
Builds IR setting ranked memref descriptor ptr.
Definition at line 761 of file StandardToLLVM.cpp.
References kPtrInUnrankedMemRefDescriptor, and mlir::StructBuilder::setPtr().
setRank()
void UnrankedMemRefDescriptor::setRank (OpBuilder & builder, Location loc, Value value)
Builds IR setting the rank in the descriptor.
Definition at line 753 of file StandardToLLVM.cpp.
References kRankInUnrankedMemRefDescriptor, and mlir::StructBuilder::setPtr().
undef()
UnrankedMemRefDescriptor UnrankedMemRefDescriptor::undef (OpBuilder & builder, Location loc, Type descriptorType) static
Builds IR creating an undef value of the descriptor type.
Definition at line 743 of file StandardToLLVM.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), and UnrankedMemRefDescriptor().
Referenced by pack(), and mlir::LLVM::detail::vectorOneToOneRewrite().
unpack()
void UnrankedMemRefDescriptor::unpack (OpBuilder & builder, Location loc, Value packed, SmallVectorImpl< Value > & results) static
Builds IR extracting individual elements that compose an unranked memref descriptor and returns them as results list.
Definition at line 784 of file StandardToLLVM.cpp.
References memRefDescPtr(), and rank().
Referenced by mlir::LLVMTypeConverter::promoteOperands(), and wrapForExternalCallers().
The documentation for this class was generated from the following files:
include/mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h
lib/Conversion/StandardToLLVM/StandardToLLVM.cpp