MLIR: mlir::MemRefType Class Reference
mlir::MemRefType Class Reference
MemRef types represent a region of memory that have a shape with a fixed number of dimensions.
#include "mlir/IR/StandardTypes.h"
Classes
class Builder
This is a builder type that keeps local references to arguments.
Public Member Functions
ArrayRef< int64_t > getShape () const
ArrayRef< AffineMap > getAffineMaps () const
Returns an array of affine map pointers representing the memref affine map composition.
unsigned getMemorySpace () const
Returns the memory space in which data referred to by this memref resides.
Static Public Member Functions
static MemRefType get (ArrayRef< int64_t > shape, Type elementType, ArrayRef< AffineMap > affineMapComposition={}, unsigned memorySpace=0)
Get or create a new MemRefType based on shape, element type, affine map composition, and memory space.
static MemRefType getChecked (ArrayRef< int64_t > shape, Type elementType, ArrayRef< AffineMap > affineMapComposition, unsigned memorySpace, Location location)
Get or create a new MemRefType based on shape, element type, affine map composition, and memory space declared at the given location.
static int64_t getDynamicStrideOrOffset ()
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
MemRef types represent a region of memory that have a shape with a fixed number of dimensions.
Each shape element can be a non-negative integer or unknown (represented by -1). MemRef types also have an affine map composition, represented as an array AffineMap pointers.
Definition at line 445 of file StandardTypes.h.
Member Function Documentation
get()
MemRefType MemRefType::get (ArrayRef< int64_t > shape, Type elementType, ArrayRef< AffineMap > affineMapComposition = {}, unsigned memorySpace = 0) static
Get or create a new MemRefType based on shape, element type, affine map composition, and memory space.
Assumes the arguments define a well-formed MemRef type. Use getChecked to gracefully handle MemRefType construction failures.
Definition at line 379 of file StandardTypes.cpp.
Referenced by allocBuffer(), mlir::BufferAssignmentTypeConverter::BufferAssignmentTypeConverter(), createPrivateMemRef(), createScopedFullPartialVectorTransferRead(), defaultAllocBufferCallBack(), extractShape(), generateCopy(), getCastCompatibleMemRefType(), insertCopies(), makeMemRefType(), mlir::detail::Parser::parseMemRefType(), mlir::vector::splitFullAndPartialTransfer(), mlir::VectorTransferRewriter< TransferOpTy >::tmpMemRefType(), and mlir::LLVM::detail::vectorOneToOneRewrite().
getAffineMaps()
ArrayRef< AffineMap > MemRefType::getAffineMaps () const
Returns an array of affine map pointers representing the memref affine map composition.
Definition at line 457 of file StandardTypes.cpp.
Referenced by mlir::canonicalizeStridedLayout(), generateCopy(), mlir::MemRefRegion::getRegionSize(), mlir::getStridesAndOffset(), isMemRefNormalizable(), mlir::normalizeMemRef(), mlir::normalizeMemRefType(), mlir::LLVM::detail::vectorOneToOneRewrite(), and verify().
getChecked()
MemRefType MemRefType::getChecked (ArrayRef< int64_t > shape, Type elementType, ArrayRef< AffineMap > affineMapComposition, unsigned memorySpace, Location location) static
Get or create a new MemRefType based on shape, element type, affine map composition, and memory space declared at the given location.
If the location is unknown, the last argument should be an instance of UnknownLoc. If the MemRefType defined by the arguments would be ill-formed, emits errors (to the handler registered with the context or to the error stream) and returns nullptr.
Definition at line 394 of file StandardTypes.cpp.
References mlir::emitError(), mlir::emitOptionalError(), mlir::Type::getContext(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl(), mlir::BaseMemRefType::isValidElementType(), and mlir::StandardTypes::MemRef.
getDynamicStrideOrOffset()
static int64_t mlir::MemRefType::getDynamicStrideOrOffset () inline static
Definition at line 526 of file StandardTypes.h.
Referenced by mlir::MemRefDescriptor::fromStaticShape(), mlir::spirv::getElementPtr(), mlir::ConvertToLLVMPattern::getStridedElementPtr(), getTypeNumBytes(), mlir::makeStridedLinearLayoutMap(), mlir::detail::Parser::parseStridedLayout(), mlir::detail::Parser::parseStrideList(), mlir::LLVM::detail::vectorOneToOneRewrite(), and verify().
getMemorySpace()
unsigned MemRefType::getMemorySpace () const
Returns the memory space in which data referred to by this memref resides.
Definition at line 461 of file StandardTypes.cpp.
Referenced by convertMemrefType(), convertMemRefTypeToBarePtr(), extractShape(), getAtomicOpScope(), getBase(), mlir::ConvertToLLVMPattern::getElementPtrType(), getTransferOpAdapter(), isAllocationSupported(), replaceTransferOpWithMubuf(), mlir::LLVM::detail::vectorOneToOneRewrite(), and verify().
getShape()
ArrayRef< int64_t > MemRefType::getShape () const
Definition at line 455 of file StandardTypes.cpp.
Referenced by mlir::canFoldIntoConsumerOp(), mlir::canonicalizeStridedLayout(), computeReshapeCollapsedType(), extractShape(), getCastCompatibleMemRefType(), mlir::ConvertToLLVMPattern::getMemRefDescriptorSizes(), getMemRefSizes(), mlir::getStridesAndOffset(), insertCopies(), mlir::normalizeMemRefType(), mlir::linalg::vectorizeLinalgOp(), and verify().
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/StandardTypes.cpp