MLIR: mlir::spirv::MatrixType Class Reference
mlir::spirv::MatrixType Class Reference
#include "mlir/Dialect/SPIRV/SPIRVTypes.h"
Public Member Functions
Type getColumnType () const
unsigned getNumRows () const
Returns the number of rows.
unsigned getNumColumns () const
Returns the number of columns.
unsigned getNumElements () const
Returns total number of elements (rows*columns).
Type getElementType () const
Returns the elements' type (i.e, single element type).
void getExtensions (SPIRVType::ExtensionArrayRefVector &extensions, Optional< spirv::StorageClass > storage=llvm::None)
void getCapabilities (SPIRVType::CapabilityArrayRefVector &capabilities, Optional< spirv::StorageClass > storage=llvm::None)
Static Public Member Functions
static MatrixType get (Type columnType, uint32_t columnCount)
static MatrixType getChecked (Type columnType, uint32_t columnCount, Location location)
static LogicalResult verifyConstructionInvariants (Location loc, Type columnType, uint32_t columnCount)
static bool isValidColumnType (Type columnType)
Returns true if the matrix elements are vectors of float elements.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 396 of file SPIRVTypes.h.
Member Function Documentation
get()
MatrixType MatrixType::get (Type columnType, uint32_t columnCount) static
Definition at line 986 of file SPIRVTypes.cpp.
References mlir::Type::getContext(), and mlir::spirv::TypeKind::Matrix.
Referenced by isFnEntryBlock(), and parseMatrixType().
getCapabilities()
void MatrixType::getCapabilities (SPIRVType::CapabilityArrayRefVector & capabilities, Optional< spirv::StorageClass > storage = llvm::None)
Definition at line 1046 of file SPIRVTypes.cpp.
References mlir::spirv::TypeKind::Matrix.
getChecked()
MatrixType MatrixType::getChecked (Type columnType, uint32_t columnCount, Location location) static
Definition at line 991 of file SPIRVTypes.cpp.
References mlir::spirv::TypeKind::Matrix.
getColumnType()
Type MatrixType::getColumnType () const
Definition at line 1025 of file SPIRVTypes.cpp.
Referenced by mlir::spirv::CompositeType::getElementType(), and print().
getElementType()
Type MatrixType::getElementType () const
Returns the elements' type (i.e, single element type).
Definition at line 1027 of file SPIRVTypes.cpp.
References mlir::Type::cast(), and getElementType().
Referenced by verifyMatrixTimesMatrix(), verifyMatrixTimesScalar(), and verifyTranspose().
getExtensions()
void MatrixType::getExtensions (SPIRVType::ExtensionArrayRefVector & extensions, Optional< spirv::StorageClass > storage = llvm::None)
Definition at line 1041 of file SPIRVTypes.cpp.
getNumColumns()
unsigned MatrixType::getNumColumns () const
Returns the number of columns.
Definition at line 1031 of file SPIRVTypes.cpp.
Referenced by print(), verifyMatrixTimesMatrix(), verifyMatrixTimesScalar(), and verifyTranspose().
getNumElements()
unsigned MatrixType::getNumElements () const
Returns total number of elements (rows*columns).
Definition at line 1037 of file SPIRVTypes.cpp.
getNumRows()
unsigned MatrixType::getNumRows () const
Returns the number of rows.
Definition at line 1033 of file SPIRVTypes.cpp.
References getShape().
Referenced by verifyMatrixTimesMatrix(), verifyMatrixTimesScalar(), and verifyTranspose().
isValidColumnType()
bool MatrixType::isValidColumnType (Type columnType) static
Returns true if the matrix elements are vectors of float elements.
Definition at line 1017 of file SPIRVTypes.cpp.
References mlir::Type::dyn_cast().
verifyConstructionInvariants()
LogicalResult MatrixType::verifyConstructionInvariants (Location loc, Type columnType, uint32_t columnCount) static
The underlying vectors (columns) must be of size 2, 3, or 4
Definition at line 996 of file SPIRVTypes.cpp.
References mlir::Type::cast(), mlir::emitError(), getShape(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/SPIRVTypes.h
lib/Dialect/SPIRV/SPIRVTypes.cpp