MLIR: mlir::PatternApplicator Class Reference
mlir::PatternApplicator Class Reference
This class manages the application of a group of rewrite patterns, with a user-provided cost model.
#include "mlir/IR/PatternMatch.h"
Public Types
using CostModel = function_ref< PatternBenefit(const RewritePattern &)>
The cost model dynamically assigns a PatternBenefit to a particular pattern.
Public Member Functions
PatternApplicator (const OwningRewritePatternList &owningPatternList)
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter, function_ref< bool(const RewritePattern &)> canApply={}, function_ref< void(const RewritePattern &)> onFailure={}, function_ref< LogicalResult(const RewritePattern &)> onSuccess={})
Attempt to match and rewrite the given op with any pattern, allowing a predicate to decide if a pattern can be applied or not, and hooks for if the pattern match was a success or failure.
void applyCostModel (CostModel model)
Apply a cost model to the patterns within this applicator.
void applyDefaultCostModel ()
Apply the default cost model that solely uses the pattern's static benefit.
void walkAllPatterns (function_ref< void(const RewritePattern &)> walk)
Walk all of the rewrite patterns within the applicator.
Detailed Description
This class manages the application of a group of rewrite patterns, with a user-provided cost model.
Definition at line 487 of file PatternMatch.h.
Member Typedef Documentation
CostModel
using mlir::PatternApplicator::CostModel = function_ref<PatternBenefit(const RewritePattern &)>
The cost model dynamically assigns a PatternBenefit to a particular pattern.
Users can query contained patterns and pass analysis results to applyCostModel. Patterns to be discarded should have a benefit of impossibleToMatch.
Definition at line 493 of file PatternMatch.h.
Constructor & Destructor Documentation
PatternApplicator()
mlir::PatternApplicator::PatternApplicator (const OwningRewritePatternList & owningPatternList) inline explicit
Definition at line 495 of file PatternMatch.h.
Member Function Documentation
applyCostModel()
void PatternApplicator::applyCostModel (CostModel model)
Apply a cost model to the patterns within this applicator.
Definition at line 182 of file PatternMatch.cpp.
applyDefaultCostModel()
void mlir::PatternApplicator::applyDefaultCostModel () inline
Apply the default cost model that solely uses the pattern's static benefit.
Definition at line 518 of file PatternMatch.h.
References mlir::applyOpPatternsAndFold(), mlir::applyPatternsAndFoldGreedily(), and mlir::Pattern::getBenefit().
matchAndRewrite()
LogicalResult PatternApplicator::matchAndRewrite (Operation * op, PatternRewriter & rewriter, function_ref< bool(const RewritePattern &)> canApply = {}, function_ref< void(const RewritePattern &)> onFailure = {}, function_ref< LogicalResult(const RewritePattern &)> onSuccess = {})
Attempt to match and rewrite the given op with any pattern, allowing a predicate to decide if a pattern can be applied or not, and hooks for if the pattern match was a success or failure.
canApply: called before each match and rewrite attempt; return false to skip pattern. onFailure: called when a pattern fails to match to perform cleanup. onSuccess: called when a pattern match succeeds; return failure() to invalidate the match and try another pattern.
Definition at line 231 of file PatternMatch.cpp.
References mlir::failure(), mlir::Operation::getName(), mlir::RewritePattern::matchAndRewrite(), mlir::OpBuilder::setInsertionPoint(), mlir::succeeded(), and mlir::success().
walkAllPatterns()
void PatternApplicator::walkAllPatterns (function_ref< void(const RewritePattern &)> walk)
Walk all of the rewrite patterns within the applicator.
Definition at line 225 of file PatternMatch.cpp.
The documentation for this class was generated from the following files:
include/mlir/IR/PatternMatch.h
lib/IR/PatternMatch.cpp