MLIR: mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits > Class Template Reference
mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits > Class Template Reference
Utility class for implementing users of storage classes uniqued by a StorageUniquer.
#include "mlir/IR/StorageUniquerSupport.h"
Inherits BaseT, and Traits< ConcreteT >.
Inherited by mlir::AffineMapAttr, mlir::ArrayAttr, mlir::CallSiteLoc, mlir::ComplexType, mlir::DenseIntOrFPElementsAttr, mlir::DenseStringElementsAttr, mlir::DictionaryAttr, mlir::FileLineColLoc, mlir::FloatAttr, mlir::FloatType, mlir::FunctionType, mlir::FusedLoc, mlir::IndexType, mlir::IntegerAttr, mlir::IntegerSetAttr, mlir::IntegerType, mlir::linalg::RangeType, mlir::LLVM::LLVMArrayType, mlir::LLVM::LLVMFixedVectorType, mlir::LLVM::LLVMFunctionType, mlir::LLVM::LLVMIntegerType, mlir::LLVM::LLVMPointerType, mlir::LLVM::LLVMScalableVectorType, mlir::LLVM::LLVMStructType, mlir::MemRefType, mlir::NameLoc, mlir::NoneType, mlir::OpaqueAttr, mlir::OpaqueElementsAttr, mlir::OpaqueLoc, mlir::OpaqueType, mlir::quant::AnyQuantizedType, mlir::quant::UniformQuantizedPerAxisType, mlir::quant::UniformQuantizedType, mlir::RankedTensorType, mlir::shape::ComponentType, mlir::shape::ElementType, mlir::shape::ShapeType, mlir::shape::SizeType, mlir::shape::ValueShapeType, mlir::shape::WitnessType, mlir::SparseElementsAttr, mlir::spirv::ArrayType, mlir::spirv::CooperativeMatrixNVType, mlir::spirv::ImageType, mlir::spirv::InterfaceVarABIAttr, mlir::spirv::MatrixType, mlir::spirv::PointerType, mlir::spirv::RuntimeArrayType, mlir::spirv::StructType, mlir::spirv::TargetEnvAttr, mlir::spirv::VerCapExtAttr, mlir::StringAttr, mlir::SymbolRefAttr, mlir::TupleType, mlir::TypeAttr, mlir::UnitAttr, mlir::UnknownLoc, mlir::UnrankedMemRefType, mlir::UnrankedTensorType, and mlir::VectorType.
Public Types
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Static Public Member Functions
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Protected Member Functions
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
template<typename ConcreteT, typename BaseT, typename StorageT, typename UniquerT, template< typename T > class... Traits>
class mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
Utility class for implementing users of storage classes uniqued by a StorageUniquer.
Clients are not expected to interact with this class directly.
Definition at line 60 of file StorageUniquerSupport.h.
Member Typedef Documentation
Base
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT , template< typename T > class... Traits> using mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::Base = StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT, Traits...>
Utility declarations for the concrete attribute class.
Definition at line 65 of file StorageUniquerSupport.h.
ImplType
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT , template< typename T > class... Traits> using mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::ImplType = StorageT
Definition at line 66 of file StorageUniquerSupport.h.
Member Function Documentation
classof()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT , template< typename T > class... Traits> template<typename T > static bool mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::classof (T val) inline static
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
Definition at line 73 of file StorageUniquerSupport.h.
get()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT , template< typename T > class... Traits> template<typename... Args> static ConcreteT mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get (MLIRContext * ctx, unsigned kind, Args... args) inline static protected
Get or create a new ConcreteT instance within the ctx.
This function is guaranteed to return a non null object and will assert if the arguments provided are invalid.
Definition at line 90 of file StorageUniquerSupport.h.
References mlir::detail::generateUnknownStorageLocation(), and mlir::succeeded().
Referenced by mlir::linalg::RangeType::get(), and mlir::spirv::TargetEnvAttr::get().
getChecked()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT , template< typename T > class... Traits> template<typename LocationT , typename... Args> static ConcreteT mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getChecked (LocationT loc, unsigned kind, Args... args) inline static protected
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
If the arguments provided are invalid then emit errors and return a null object.
Definition at line 101 of file StorageUniquerSupport.h.
References mlir::failed().
getImpl()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT , template< typename T > class... Traits> ImplType* mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl () const inline protected
Utility for easy access to the storage instance.
Definition at line 122 of file StorageUniquerSupport.h.
Referenced by mlir::spirv::VerCapExtAttr::getCapabilitiesAttr(), mlir::MemRefType::getChecked(), mlir::spirv::VerCapExtAttr::getExtensionsAttr(), mlir::spirv::TargetEnvAttr::getResourceLimits(), and mlir::spirv::TargetEnvAttr::getTripleAttr().
getInterfaceMap()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT , template< typename T > class... Traits> static detail::InterfaceMap mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getInterfaceMap () inline static
Returns an interface map for the interfaces registered to this storage user.
This should not be used directly.
Definition at line 81 of file StorageUniquerSupport.h.
getTypeID()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT , template< typename T > class... Traits> static TypeID mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getTypeID () inline static
Return a unique identifier for the concrete type.
Definition at line 69 of file StorageUniquerSupport.h.
Referenced by mlir::OpTrait::util::getBroadcastedType().
mutate()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT , template< typename T > class... Traits> template<typename... Args> LogicalResult mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::mutate (Args &&... args) inline protected
Mutate the current storage instance.
This will not change the unique key. The arguments are forwarded to 'ConcreteT::mutate'.
Definition at line 110 of file StorageUniquerSupport.h.
verifyConstructionInvariants()
template<typename ConcreteT , typename BaseT , typename StorageT , typename UniquerT , template< typename T > class... Traits> template<typename... Args> static LogicalResult mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::verifyConstructionInvariants (Args... args) inline static protected
Default implementation that just returns success.
Definition at line 117 of file StorageUniquerSupport.h.
References mlir::success().
The documentation for this class was generated from the following file:
include/mlir/IR/StorageUniquerSupport.h