MLIR: mlir::PassManager::PassTimingConfig Class Reference
mlir::PassManager::PassTimingConfig Class Reference
A configuration struct provided to the pass timing feature.
#include "mlir/Pass/PassManager.h"
Public Types
using PrintCallbackFn = function_ref< void(raw_ostream &)>
Public Member Functions
PassTimingConfig (PassDisplayMode displayMode=PassDisplayMode::Pipeline)
Initialize the configuration.
virtual ~PassTimingConfig ()
virtual void printTiming (PrintCallbackFn printCallback)
A hook that may be overridden by a derived config to control the printing.
PassDisplayMode getDisplayMode ()
Return the PassDisplayMode this config was created with.
Detailed Description
A configuration struct provided to the pass timing feature.
Definition at line 249 of file PassManager.h.
Member Typedef Documentation
PrintCallbackFn
using mlir::PassManager::PassTimingConfig::PrintCallbackFn = function_ref<void(raw_ostream &)>
Definition at line 251 of file PassManager.h.
Constructor & Destructor Documentation
PassTimingConfig()
mlir::PassManager::PassTimingConfig::PassTimingConfig (PassDisplayMode displayMode = PassDisplayMode::Pipeline) inline explicit
Initialize the configuration.
'displayMode' switch between list or pipeline display (see the PassDisplayMode enum documentation).
Definition at line 256 of file PassManager.h.
~PassTimingConfig()
PassManager::PassTimingConfig::~PassTimingConfig () virtual
Definition at line 460 of file PassTiming.cpp.
Member Function Documentation
getDisplayMode()
PassDisplayMode mlir::PassManager::PassTimingConfig::getDisplayMode () inline
Return the PassDisplayMode this config was created with.
Definition at line 268 of file PassManager.h.
References mlir::applyPassManagerCLOptions(), and mlir::registerPassManagerCLOptions().
printTiming()
void PassManager::PassTimingConfig::printTiming (PrintCallbackFn printCallback) virtual
A hook that may be overridden by a derived config to control the printing.
The callback is supplied by the framework and the config is responsible to call it back with a stream for the output.
Definition at line 383 of file PassTiming.cpp.
References mlir::Pipeline, printResultsAsList(), printResultsAsPipeline(), and printTimeEntry().
The documentation for this class was generated from the following files:
include/mlir/Pass/PassManager.h
lib/Pass/PassTiming.cpp