MLIR: mlir::OwningOpRefBase< OpTy > Class Template Reference
mlir::OwningOpRefBase< OpTy > Class Template Reference
This class acts as an owning reference to an op, and will automatically destroy the held op on destruction if the held op is valid.
#include "mlir/IR/OwningOpRefBase.h"
Public Member Functions
OwningOpRefBase (std::nullptr_t=nullptr)
OwningOpRefBase (OpTy op)
OwningOpRefBase (OwningOpRefBase &&other)
~OwningOpRefBase ()
OwningOpRefBase & operator= (OwningOpRefBase &&other)
OpTy get () const
Allow accessing the internal op.
OpTy operator* () const
OpTy * operator-> ()
operator bool () const
OpTy release ()
Release the referenced op.
Detailed Description
template<typename OpTy>
class mlir::OwningOpRefBase< OpTy >
This class acts as an owning reference to an op, and will automatically destroy the held op on destruction if the held op is valid.
Note that OpBuilder and related functionality should be highly preferred instead, and this should only be used in situations where existing solutions are not viable.
Definition at line 27 of file OwningOpRefBase.h.
Constructor & Destructor Documentation
OwningOpRefBase() [1/3]
template<typename OpTy> mlir::OwningOpRefBase< OpTy >::OwningOpRefBase (std::nullptr_t = nullptr) inline
Definition at line 29 of file OwningOpRefBase.h.
OwningOpRefBase() [2/3]
template<typename OpTy> mlir::OwningOpRefBase< OpTy >::OwningOpRefBase (OpTy op) inline
Definition at line 30 of file OwningOpRefBase.h.
OwningOpRefBase() [3/3]
template<typename OpTy> mlir::OwningOpRefBase< OpTy >::OwningOpRefBase (OwningOpRefBase< OpTy > && other) inline
Definition at line 31 of file OwningOpRefBase.h.
~OwningOpRefBase()
template<typename OpTy> mlir::OwningOpRefBase< OpTy >::~OwningOpRefBase () inline
Definition at line 32 of file OwningOpRefBase.h.
Member Function Documentation
get()
template<typename OpTy> OpTy mlir::OwningOpRefBase< OpTy >::get () const inline
Allow accessing the internal op.
Definition at line 46 of file OwningOpRefBase.h.
Referenced by mlir::translateLLVMIRToModule().
operator bool()
template<typename OpTy> mlir::OwningOpRefBase< OpTy >::operator bool () const inline explicit
Definition at line 49 of file OwningOpRefBase.h.
operator*()
template<typename OpTy> OpTy mlir::OwningOpRefBase< OpTy >::operator* () const inline
Definition at line 47 of file OwningOpRefBase.h.
operator->()
template<typename OpTy> OpTy* mlir::OwningOpRefBase< OpTy >::operator-> () inline
Definition at line 48 of file OwningOpRefBase.h.
operator=()
template<typename OpTy> OwningOpRefBase& mlir::OwningOpRefBase< OpTy >::operator= (OwningOpRefBase< OpTy > && other) inline
Definition at line 38 of file OwningOpRefBase.h.
release()
template<typename OpTy> OpTy mlir::OwningOpRefBase< OpTy >::release () inline
Release the referenced op.
Definition at line 52 of file OwningOpRefBase.h.
Referenced by deserializeModule(), mlirModuleCreateParse(), and roundTripModule().
The documentation for this class was generated from the following file:
include/mlir/IR/OwningOpRefBase.h