MLIR: mlir::DictionaryAttr Class Reference
mlir::DictionaryAttr Class Reference
Dictionary attribute is an attribute that represents a sorted collection of named attribute values.
#include "mlir/IR/Attributes.h"
Public Types
using ValueType = ArrayRef< NamedAttribute >
using iterator = llvm::ArrayRef< NamedAttribute >::iterator
Support range iteration.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
ArrayRef< NamedAttribute > getValue () const
Attribute get (StringRef name) const
Return the specified attribute if present, null otherwise.
Attribute get (Identifier name) const
Optional< NamedAttribute > getNamed (StringRef name) const
Return the specified named attribute if present, None otherwise.
Optional< NamedAttribute > getNamed (Identifier name) const
iterator begin () const
iterator end () const
bool empty () const
size_t size () const
Static Public Member Functions
static DictionaryAttr get (ArrayRef< NamedAttribute > value, MLIRContext *context)
Construct a dictionary attribute with the provided list of named attributes.
static DictionaryAttr getWithSorted (ArrayRef< NamedAttribute > value, MLIRContext *context)
Construct a dictionary with an array of values that is known to already be sorted by name and uniqued.
static bool sort (ArrayRef< NamedAttribute > values, SmallVectorImpl< NamedAttribute > &storage)
Sorts the NamedAttributes in the array ordered by name as expected by getWithSorted and returns whether the values were sorted.
static bool sortInPlace (SmallVectorImpl< NamedAttribute > &array)
Sorts the NamedAttributes in the array ordered by name as expected by getWithSorted in place on an array and returns whether the values needed to be sorted.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Dictionary attribute is an attribute that represents a sorted collection of named attribute values.
The elements are sorted by name, and each name must be unique within the collection.
Definition at line 306 of file Attributes.h.
Member Typedef Documentation
iterator
using mlir::DictionaryAttr::iterator = llvm::ArrayRef<NamedAttribute>::iterator
Support range iteration.
Definition at line 336 of file Attributes.h.
ValueType
using mlir::DictionaryAttr::ValueType = ArrayRef<NamedAttribute>
Definition at line 311 of file Attributes.h.
Member Function Documentation
begin()
DictionaryAttr::iterator DictionaryAttr::begin () const
Definition at line 208 of file Attributes.cpp.
empty()
bool mlir::DictionaryAttr::empty () const inline
Definition at line 339 of file Attributes.h.
end()
DictionaryAttr::iterator DictionaryAttr::end () const
Definition at line 211 of file Attributes.cpp.
get() [1/3]
DictionaryAttr DictionaryAttr::get (ArrayRef< NamedAttribute > value, MLIRContext * context) static
Construct a dictionary attribute with the provided list of named attributes.
This method assumes that the provided list is unordered. If the caller can guarantee that the attributes are ordered by name, getWithSorted should be used instead.
Definition at line 145 of file Attributes.cpp.
References mlir::StandardAttributes::Dictionary.
Referenced by mlir::FuncOp::cloneInto(), mlir::MutableDictionaryAttr::getDictionary(), mlir::Builder::getDictionaryAttr(), print(), printGenericOp(), rebuildAttrAfterRAUW(), mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttrs(), mlir::MutableDictionaryAttr::setAttrs(), and mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttrs().
get() [2/3]
Attribute DictionaryAttr::get (StringRef name) const
Return the specified attribute if present, null otherwise.
Definition at line 185 of file Attributes.cpp.
get() [3/3]
Attribute DictionaryAttr::get (Identifier name) const
Definition at line 189 of file Attributes.cpp.
getNamed() [1/2]
Optional< NamedAttribute > DictionaryAttr::getNamed (StringRef name) const
Return the specified named attribute if present, None otherwise.
Definition at line 195 of file Attributes.cpp.
getNamed() [2/2]
Optional< NamedAttribute > DictionaryAttr::getNamed (Identifier name) const
Definition at line 201 of file Attributes.cpp.
getValue()
ArrayRef< NamedAttribute > DictionaryAttr::getValue () const
Definition at line 180 of file Attributes.cpp.
Referenced by parseContractionOp(), and parseGenericOp().
getWithSorted()
DictionaryAttr DictionaryAttr::getWithSorted (ArrayRef< NamedAttribute > value, MLIRContext * context) static
Construct a dictionary with an array of values that is known to already be sorted by name and uniqued.
Definition at line 162 of file Attributes.cpp.
References mlir::StandardAttributes::Dictionary.
Referenced by mlir::NamedAttrList::getDictionary(), mlir::MutableDictionaryAttr::remove(), and mlir::MutableDictionaryAttr::set().
size()
size_t DictionaryAttr::size () const
Definition at line 214 of file Attributes.cpp.
sort()
bool DictionaryAttr::sort (ArrayRef< NamedAttribute > values, SmallVectorImpl< NamedAttribute > & storage) static
Sorts the NamedAttributes in the array ordered by name as expected by getWithSorted and returns whether the values were sorted.
Requires: uniquely named attributes.
Definition at line 136 of file Attributes.cpp.
References dictionaryAttrSort().
Referenced by mlir::NamedAttrList::assign().
sortInPlace()
bool DictionaryAttr::sortInPlace (SmallVectorImpl< NamedAttribute > & array) static
Sorts the NamedAttributes in the array ordered by name as expected by getWithSorted in place on an array and returns whether the values needed to be sorted.
Requires: uniquely named attributes.
Definition at line 141 of file Attributes.cpp.
References dictionaryAttrSort().
Referenced by mlir::NamedAttrList::getDictionary().
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp
lib/IR/MLIRContext.cpp