MLIR: mlir::PatternRewriter Class Reference
mlir::PatternRewriter Class Reference
This class coordinates the application of a pattern to the current function, providing a way to create operations and keep track of what gets deleted.
#include "mlir/IR/PatternMatch.h"
Public Member Functions
template<typename OpTy , typename... Args>
OpTy create (Location location, Args... args)
Create operation of specific op type at the current insertion point without verifying to see if it is valid.
template<typename OpTy , typename... Args>
OpTy createChecked (Location location, Args... args)
Creates an operation of specific op type at the current insertion point.
virtual void inlineRegionBefore (Region &region, Region &parent, Region::iterator before)
Move the blocks that belong to "region" before the given position in another region "parent".
void inlineRegionBefore (Region &region, Block *before)
virtual void cloneRegionBefore (Region &region, Region &parent, Region::iterator before, BlockAndValueMapping &mapping)
Clone the blocks that belong to "region" before the given position in another region "parent".
void cloneRegionBefore (Region &region, Region &parent, Region::iterator before)
void cloneRegionBefore (Region &region, Block *before)
virtual void replaceOp (Operation *op, ValueRange newValues)
This method performs the final replacement for a pattern, where the results of the operation are updated to use the specified list of SSA values.
template<typename OpTy , typename... Args>
void replaceOpWithNewOp (Operation *op, Args &&... args)
Replaces the result op with a new op that is created without verification.
virtual void eraseOp (Operation *op)
This method erases an operation that is known to have no uses.
virtual void eraseBlock (Block *block)
This method erases all operations in a block.
virtual void mergeBlocks (Block *source, Block *dest, ValueRange argValues=llvm::None)
Merge the operations of block 'source' into the end of block 'dest'.
virtual Block * splitBlock (Block *block, Block::iterator before)
Split the operations starting at "before" (inclusive) out of the given block into a new block, and return it.
virtual void startRootUpdate (Operation *op)
This method is used to notify the rewriter that an in-place operation modification is about to happen.
virtual void finalizeRootUpdate (Operation *op)
This method is used to signal the end of a root update on the given operation.
virtual void cancelRootUpdate (Operation *op)
This method cancels a pending root update.
template<typename CallableT >
void updateRootInPlace (Operation *root, CallableT &&callable)
This method is a utility wrapper around a root update of an operation.
template<typename CallbackT >
std::enable_if_t<!std::is_convertible< CallbackT, Twine >::value, LogicalResult > notifyMatchFailure (Operation *op, CallbackT &&reasonCallback)
Notify the pattern rewriter that the pattern is failing to match the given operation, and provide a callback to populate a diagnostic with the reason why the failure occurred.
LogicalResult notifyMatchFailure (Operation *op, const Twine &msg)
LogicalResult notifyMatchFailure (Operation *op, const char *msg)
Public Member Functions inherited from mlir::OpBuilder
OpBuilder (MLIRContext *ctx, Listener *listener=nullptr)
Create a builder with the given context.
OpBuilder (Region *region, Listener *listener=nullptr)
Create a builder and set the insertion point to the start of the region.
OpBuilder (Region &region, Listener *listener=nullptr)
OpBuilder (Operation *op, Listener *listener=nullptr)
Create a builder and set insertion point to the given operation, which will cause subsequent insertions to go right before it.
OpBuilder (Block *block, Block::iterator insertPoint, Listener *listener=nullptr)
void setListener (Listener *newListener)
Sets the listener of this builder to the one provided.
Listener * getListener () const
Returns the current listener of this builder, or nullptr if this builder doesn't have a listener.
void clearInsertionPoint ()
Reset the insertion point to no location.
InsertPoint saveInsertionPoint () const
Return a saved insertion point.
void restoreInsertionPoint (InsertPoint ip)
Restore the insert point to a previously saved point.
void setInsertionPoint (Block *block, Block::iterator insertPoint)
Set the insertion point to the specified location.
void setInsertionPoint (Operation *op)
Sets the insertion point to the specified operation, which will cause subsequent insertions to go right before it.
void setInsertionPointAfter (Operation *op)
Sets the insertion point to the node after the specified operation, which will cause subsequent insertions to go right after it.
void setInsertionPointToStart (Block *block)
Sets the insertion point to the start of the specified block.
void setInsertionPointToEnd (Block *block)
Sets the insertion point to the end of the specified block.
Block * getInsertionBlock () const
Return the block the current insertion point belongs to.
Block::iterator getInsertionPoint () const
Returns the current insertion point of the builder.
Block * getBlock () const
Returns the current block of the builder.
Block * createBlock (Region *parent, Region::iterator insertPt={}, TypeRange argTypes=llvm::None)
Add new block with 'argTypes' arguments and set the insertion point to the end of it.
Block * createBlock (Block *insertBefore, TypeRange argTypes=llvm::None)
Add new block with 'argTypes' arguments and set the insertion point to the end of it.
Operation * insert (Operation *op)
Insert the given operation at the current insertion point and return it.
Operation * createOperation (const OperationState &state)
Creates an operation given the fields represented as an OperationState.
template<typename OpTy , typename... Args>
OpTy create (Location location, Args &&... args)
Create an operation of specific op type at the current insertion point.
template<typename OpTy , typename... Args>
void createOrFold (SmallVectorImpl< Value > &results, Location location, Args &&... args)
Create an operation of specific op type at the current insertion point, and immediately try to fold it.
template<typename OpTy , typename... Args>
std::enable_if< OpTy::template hasTrait< OpTrait::OneResult >), Value >::type createOrFold (Location location, Args &&... args)
Overload to create or fold a single result operation.
template<typename OpTy , typename... Args>
std::enable_if< OpTy::template hasTrait< OpTrait::ZeroResult >), OpTy >::type createOrFold (Location location, Args &&... args)
Overload to create or fold a zero result operation.
LogicalResult tryFold (Operation *op, SmallVectorImpl< Value > &results)
Attempts to fold the given operation and places new results within 'results'.
Operation * clone (Operation &op, BlockAndValueMapping &mapper)
Creates a deep copy of the specified operation, remapping any operands that use values outside of the operation using the map that is provided (leaving them alone if no entry is present).
Operation * clone (Operation &op)
Operation * cloneWithoutRegions (Operation &op, BlockAndValueMapping &mapper)
Creates a deep copy of this operation but keep the operation regions empty.
Operation * cloneWithoutRegions (Operation &op)
template<typename OpT >
OpT cloneWithoutRegions (OpT op)
Public Member Functions inherited from mlir::Builder
Builder (MLIRContext *context)
Builder (ModuleOp module)
MLIRContext * getContext () const
Identifier getIdentifier (StringRef str)
Location getUnknownLoc ()
Location getFileLineColLoc (Identifier filename, unsigned line, unsigned column)
Location getFusedLoc (ArrayRef< Location > locs, Attribute metadata=Attribute())
FloatType getBF16Type ()
FloatType getF16Type ()
FloatType getF32Type ()
FloatType getF64Type ()
IndexType getIndexType ()
IntegerType getI1Type ()
IntegerType getI32Type ()
IntegerType getI64Type ()
IntegerType getIntegerType (unsigned width)
IntegerType getIntegerType (unsigned width, bool isSigned)
FunctionType getFunctionType (TypeRange inputs, TypeRange results)
TupleType getTupleType (TypeRange elementTypes)
NoneType getNoneType ()
template<typename Ty , typename... Args>
Ty getType (Args... args)
Get or construct an instance of the type 'ty' with provided arguments.
NamedAttribute getNamedAttr (StringRef name, Attribute val)
UnitAttr getUnitAttr ()
BoolAttr getBoolAttr (bool value)
DictionaryAttr getDictionaryAttr (ArrayRef< NamedAttribute > value)
IntegerAttr getIntegerAttr (Type type, int64_t value)
IntegerAttr getIntegerAttr (Type type, const APInt &value)
FloatAttr getFloatAttr (Type type, double value)
FloatAttr getFloatAttr (Type type, const APFloat &value)
StringAttr getStringAttr (StringRef bytes)
ArrayAttr getArrayAttr (ArrayRef< Attribute > value)
FlatSymbolRefAttr getSymbolRefAttr (Operation *value)
FlatSymbolRefAttr getSymbolRefAttr (StringRef value)
SymbolRefAttr getSymbolRefAttr (StringRef value, ArrayRef< FlatSymbolRefAttr > nestedReferences)
Attribute getZeroAttr (Type type)
FloatAttr getF16FloatAttr (float value)
FloatAttr getF32FloatAttr (float value)
FloatAttr getF64FloatAttr (double value)
IntegerAttr getI8IntegerAttr (int8_t value)
IntegerAttr getI16IntegerAttr (int16_t value)
IntegerAttr getI32IntegerAttr (int32_t value)
IntegerAttr getI64IntegerAttr (int64_t value)
IntegerAttr getIndexAttr (int64_t value)
IntegerAttr getSI32IntegerAttr (int32_t value)
Signed and unsigned integer attribute getters.
IntegerAttr getUI32IntegerAttr (uint32_t value)
DenseIntElementsAttr getBoolVectorAttr (ArrayRef< bool > values)
Vector-typed DenseIntElementsAttr getters. values must not be empty.
DenseIntElementsAttr getI32VectorAttr (ArrayRef< int32_t > values)
DenseIntElementsAttr getI64VectorAttr (ArrayRef< int64_t > values)
DenseIntElementsAttr getI32TensorAttr (ArrayRef< int32_t > values)
Tensor-typed DenseIntElementsAttr getters.
DenseIntElementsAttr getI64TensorAttr (ArrayRef< int64_t > values)
DenseIntElementsAttr getIndexTensorAttr (ArrayRef< int64_t > values)
ArrayAttr getAffineMapArrayAttr (ArrayRef< AffineMap > values)
ArrayAttr getBoolArrayAttr (ArrayRef< bool > values)
ArrayAttr getI32ArrayAttr (ArrayRef< int32_t > values)
ArrayAttr getI64ArrayAttr (ArrayRef< int64_t > values)
ArrayAttr getIndexArrayAttr (ArrayRef< int64_t > values)
ArrayAttr getF32ArrayAttr (ArrayRef< float > values)
ArrayAttr getF64ArrayAttr (ArrayRef< double > values)
ArrayAttr getStrArrayAttr (ArrayRef< StringRef > values)
AffineExpr getAffineDimExpr (unsigned position)
AffineExpr getAffineSymbolExpr (unsigned position)
AffineExpr getAffineConstantExpr (int64_t constant)
AffineMap getEmptyAffineMap ()
Returns a zero result affine map with no dimensions or symbols: () -> ().
AffineMap getConstantAffineMap (int64_t val)
Returns a single constant result affine map with 0 dimensions and 0 symbols.
AffineMap getDimIdentityMap ()
AffineMap getMultiDimIdentityMap (unsigned rank)
AffineMap getSymbolIdentityMap ()
AffineMap getSingleDimShiftAffineMap (int64_t shift)
Returns a map that shifts its (single) input dimension by 'shift'.
AffineMap getShiftedAffineMap (AffineMap map, int64_t shift)
Returns an affine map that is a translation (shift) of all result expressions in 'map' by 'shift'.
Public Member Functions inherited from mlir::OpBuilder::Listener
virtual ~Listener ()
virtual void notifyOperationInserted (Operation *op)
Notification handler for when an operation is inserted into the builder.
virtual void notifyBlockCreated (Block *block)
Notification handler for when a block is created using the builder.
Protected Member Functions
PatternRewriter (MLIRContext *ctx)
Initialize the builder with this rewriter as the listener.
~PatternRewriter () override
virtual void notifyRootReplaced (Operation *op)
These are the callback methods that subclasses can choose to implement if they would like to be notified about certain types of mutations.
virtual void notifyOperationRemoved (Operation *op)
This is called on an operation that a pattern match is removing, right before the operation is deleted.
virtual LogicalResult notifyMatchFailure (Operation *op, function_ref< void(Diagnostic &)> reasonCallback)
Notify the pattern rewriter that the pattern is failing to match the given operation, and provide a callback to populate a diagnostic with the reason why the failure occurred.
Additional Inherited Members
Static Public Member Functions inherited from mlir::OpBuilder
static OpBuilder atBlockBegin (Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to before the first operation in the block but still inside the block.
static OpBuilder atBlockEnd (Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to after the last operation in the block but still inside the block.
static OpBuilder atBlockTerminator (Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to before the block terminator.
Protected Attributes inherited from mlir::Builder
MLIRContext * context
Detailed Description
This class coordinates the application of a pattern to the current function, providing a way to create operations and keep track of what gets deleted.
These class serves two purposes: 1) it is the interface that patterns interact with to make mutations to the IR they are being applied to. 2) It is a base class that clients of the PatternMatcher use when they want to apply patterns and observe their effects (e.g. to keep worklists or other data structures up to date).
Definition at line 248 of file PatternMatch.h.
Constructor & Destructor Documentation
PatternRewriter()
mlir::PatternRewriter::PatternRewriter (MLIRContext * ctx) inline explicit protected
Initialize the builder with this rewriter as the listener.
Definition at line 383 of file PatternMatch.h.
~PatternRewriter()
PatternRewriter::~PatternRewriter () override protected
Definition at line 73 of file PatternMatch.cpp.
Member Function Documentation
cancelRootUpdate()
virtual void mlir::PatternRewriter::cancelRootUpdate (Operation * op) inline virtual
This method cancels a pending root update.
This can only be called on operations that were provided to a call to startRootUpdate.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 347 of file PatternMatch.h.
Referenced by mlir::vector::VectorTransferFullPartialRewriter::matchAndRewrite(), and mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite().
cloneRegionBefore() [1/3]
void PatternRewriter::cloneRegionBefore (Region & region, Region & parent, Region::iterator before, BlockAndValueMapping & mapping) virtual
Clone the blocks that belong to "region" before the given position in another region "parent".
The two regions must be different. The caller is responsible for creating or updating the operation transferring flow of control to the region and passing it the correct block arguments.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 164 of file PatternMatch.cpp.
References mlir::Region::cloneInto().
Referenced by mlir::ConversionPatternRewriter::cloneRegionBefore(), createLinalgOpOfSameType(), and mlir::scf::getParallelForInductionVarOwner().
cloneRegionBefore() [2/3]
void PatternRewriter::cloneRegionBefore (Region & region, Region & parent, Region::iterator before)
Definition at line 169 of file PatternMatch.cpp.
cloneRegionBefore() [3/3]
void PatternRewriter::cloneRegionBefore (Region & region, Block * before)
Definition at line 174 of file PatternMatch.cpp.
References mlir::Block::getParent().
create()
template<typename OpTy , typename... Args> OpTy mlir::PatternRewriter::create (Location location, Args... args) inline
Create operation of specific op type at the current insertion point without verifying to see if it is valid.
Definition at line 253 of file PatternMatch.h.
Referenced by mlir::applyCmpPredicate(), broadcast(), mlir::canFoldIntoConsumerOp(), convertStructType(), createConstantAllBitsSet(), createFPConstant(), createI32ConstantOf(), createLinalgOpOfSameType(), deriveStaticUpperBound(), extractCompositeElement(), extractOne(), fuseLinalgOpsGreedily(), getAtomicOpScope(), getBasePtr(), mlir::ConvertToLLVMPattern::getCumulativeSizeInBytes(), getDefaultABIAttrs(), getIndexedPtrs(), getLibraryCallSymbolRef(), getLocalInvocationDimSize(), getNumDynamicEntriesUpToIdx(), mlir::scf::getParallelForInductionVarOwner(), mlir::ConvertToLLVMPattern::getStridedElementPtr(), getTransferOpAdapter(), handleMultidimensionalVectors(), insertOne(), isIdentitySuffix(), mlir::ConvertToLLVMPattern::linearizeSubscripts(), mlir::lowerAffineLowerBound(), lowerAsEntryFunction(), lowerEntryPointABIAttr(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), mlir::ContractionOpToOuterProductOpLowering::matchAndRewrite(), mlir::ContractionOpToDotLowering::matchAndRewrite(), mlir::ContractionOpLowering::matchAndRewrite(), mlir::linalg::LinalgCopyVTRForwardingPattern::matchAndRewrite(), mlir::linalg::LinalgCopyVTWForwardingPattern::matchAndRewrite(), matchAndRewriteOneToOne(), matchSimpleAtomicOp(), mlir::LLVM::detail::oneToOneRewrite(), optionallyTruncateOrExtend(), processParallelLoop(), replaceSCFOutputValue(), replaceTransferOpWithMasked(), replaceTransferOpWithMubuf(), replaceUnitExtents(), reshapeLoad(), reshapeStore(), resolveSourceIndices(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), and wrapExternalFunction().
createChecked()
template<typename OpTy , typename... Args> OpTy mlir::PatternRewriter::createChecked (Location location, Args... args) inline
Creates an operation of specific op type at the current insertion point.
If the result is an invalid op (the verifier hook fails), emit an error and return null.
Definition at line 266 of file PatternMatch.h.
eraseBlock()
void PatternRewriter::eraseBlock (Block * block) virtual
This method erases all operations in a block.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 100 of file PatternMatch.cpp.
References mlir::Block::erase().
Referenced by mlir::buildAffineLoopNest(), and mlir::lowerAffineLowerBound().
eraseOp()
void PatternRewriter::eraseOp (Operation * op) virtual
This method erases an operation that is known to have no uses.
The uses of the given operation must be known to be dead.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 94 of file PatternMatch.cpp.
References mlir::Operation::erase(), and mlir::Operation::use_empty().
Referenced by mlir::ConstantIndexOp::build(), canonicalizeLoopBounds(), collapseBranch(), extractCompositeElement(), mlir::linalg::fuseTensorOps(), getInputAndOutputIndices(), isIdentitySuffix(), mlir::lowerAffineLowerBound(), mlir::linalg::LinalgBaseTilingPattern::matchAndRewrite(), mlir::linalg::LinalgBaseVectorizationPattern::matchAndRewrite(), mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite(), mlir::linalg::LinalgCopyVTRForwardingPattern::matchAndRewrite(), mlir::linalg::LinalgCopyVTWForwardingPattern::matchAndRewrite(), mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite(), EraseDeadLinalgOp::matchAndRewrite(), print(), processParallelLoop(), and verify().
finalizeRootUpdate()
virtual void mlir::PatternRewriter::finalizeRootUpdate (Operation * op) inline virtual
This method is used to signal the end of a root update on the given operation.
This can only be called on operations that were provided to a call to startRootUpdate.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 343 of file PatternMatch.h.
Referenced by mlir::buildAffineLoopNest(), mlir::vector::VectorTransferFullPartialRewriter::matchAndRewrite(), mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), and replaceUnitDims().
inlineRegionBefore() [1/2]
void PatternRewriter::inlineRegionBefore (Region & region, Region & parent, Region::iterator before) virtual
Move the blocks that belong to "region" before the given position in another region "parent".
Move the blocks that belong to "region" before the given position in another region.
The two regions must be different. The caller is responsible for creating or updating the operation transferring flow of control to the region and passing it the correct block arguments.
The two regions must be different. The caller is in charge to update create the operation transferring the control flow to the region and pass it the correct block arguments.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 152 of file PatternMatch.cpp.
References mlir::Region::getBlocks().
Referenced by mlir::ConversionPatternRewriter::inlineRegionBefore(), mlir::lowerAffineLowerBound(), print(), and replaceUnitExtents().
inlineRegionBefore() [2/2]
void PatternRewriter::inlineRegionBefore (Region & region, Block * before)
Definition at line 156 of file PatternMatch.cpp.
References mlir::Block::getParent().
mergeBlocks()
void PatternRewriter::mergeBlocks (Block * source, Block * dest, ValueRange argValues = llvm::None) virtual
Merge the operations of block 'source' into the end of block 'dest'.
'source's predecessors must either be empty or only contain 'dest`. 'argValues' is used to replace the block arguments of 'source' after merging.
'source's predecessors must be empty or only contain 'dest`. 'argValues' is used to replace the block arguments of 'source' after merging.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 112 of file PatternMatch.cpp.
References mlir::IRObjectWithUseList< OperandType >::dropAllUses(), mlir::Block::end(), mlir::Block::erase(), mlir::Block::getArguments(), mlir::Block::getNumArguments(), mlir::Block::getOperations(), and mlir::Block::getPredecessors().
Referenced by collapseBranch(), and print().
notifyMatchFailure() [1/4]
template<typename CallbackT > std::enable_if_t<!std::is_convertible<CallbackT, Twine>::value, LogicalResult> mlir::PatternRewriter::notifyMatchFailure (Operation * op, CallbackT && reasonCallback) inline
Notify the pattern rewriter that the pattern is failing to match the given operation, and provide a callback to populate a diagnostic with the reason why the failure occurred.
This method allows for derived rewriters to optionally hook into the reason why a pattern failed, and display it to users.
Definition at line 366 of file PatternMatch.h.
References mlir::failure().
Referenced by mlir::linalg::LinalgMarker::checkAndNotify().
notifyMatchFailure() [2/4]
LogicalResult mlir::PatternRewriter::notifyMatchFailure (Operation * op, const Twine & msg) inline
Definition at line 374 of file PatternMatch.h.
References diag().
notifyMatchFailure() [3/4]
LogicalResult mlir::PatternRewriter::notifyMatchFailure (Operation * op, const char * msg) inline
Definition at line 377 of file PatternMatch.h.
notifyMatchFailure() [4/4]
virtual LogicalResult mlir::PatternRewriter::notifyMatchFailure (Operation * op, function_ref< void(Diagnostic &)> reasonCallback) inline protected virtual
Notify the pattern rewriter that the pattern is failing to match the given operation, and provide a callback to populate a diagnostic with the reason why the failure occurred.
This method allows for derived rewriters to optionally hook into the reason why a pattern failed, and display it to users.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 406 of file PatternMatch.h.
References mlir::failure().
notifyOperationRemoved()
virtual void mlir::PatternRewriter::notifyOperationRemoved (Operation * op) inline protected virtual
This is called on an operation that a pattern match is removing, right before the operation is deleted.
At this point, the operation has zero uses.
Definition at line 398 of file PatternMatch.h.
notifyRootReplaced()
virtual void mlir::PatternRewriter::notifyRootReplaced (Operation * op) inline protected virtual
These are the callback methods that subclasses can choose to implement if they would like to be notified about certain types of mutations.
Notify the pattern rewriter that the specified operation is about to be replaced with another set of operations. This is called before the uses of the operation have been changed.
Definition at line 393 of file PatternMatch.h.
replaceOp()
void PatternRewriter::replaceOp (Operation * op, ValueRange newValues) virtual
This method performs the final replacement for a pattern, where the results of the operation are updated to use the specified list of SSA values.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 80 of file PatternMatch.cpp.
References mlir::Operation::erase(), mlir::Operation::getNumResults(), and mlir::Operation::replaceAllUsesWith().
Referenced by mlir::linalg::fuseTensorOps(), getInputAndOutputIndices(), mlir::scf::getParallelForInductionVarOwner(), getTransferOpAdapter(), isIdentitySuffix(), mlir::lowerAffineLowerBound(), mlir::vector::UnrollVectorPattern< OpTy >::matchAndRewrite(), mlir::ContractionOpToOuterProductOpLowering::matchAndRewrite(), mlir::ContractionOpToDotLowering::matchAndRewrite(), mlir::ContractionOpLowering::matchAndRewrite(), mlir::linalg::LinalgCopyVTRForwardingPattern::matchAndRewrite(), mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite(), print(), replaceUnitExtents(), and verify().
replaceOpWithNewOp()
template<typename OpTy , typename... Args> void mlir::PatternRewriter::replaceOpWithNewOp (Operation * op, Args &&... args) inline
Replaces the result op with a new op that is created without verification.
The result values of the two ops must be the same types.
Definition at line 311 of file PatternMatch.h.
References mlir::Operation::getLoc().
Referenced by mlir::applyCmpPredicate(), mlir::canFoldIntoConsumerOp(), mlir::canonicalizeSetAndOperands(), collapseBranch(), collapseReassociationMaps(), convertRangeType(), convertStructType(), extractCompositeElement(), getAtomicOpScope(), getDefaultABIAttrs(), getInputAndOutputIndices(), getLaunchConfigIndex(), getLibraryCallSymbolRef(), getNumDynamicEntriesUpToIdx(), getTransferOpAdapter(), isIdentitySuffix(), mlir::lowerAffineLowerBound(), mlir::GPUReturnOpLowering::matchAndRewrite(), mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), mlir::linalg::AffineMinSCFCanonicalizationPattern::matchAndRewrite(), matchSimpleAtomicOp(), parseConstShapeOp(), replaceTransferOpWithLoadOrStore(), replaceTransferOpWithMasked(), replaceTransferOpWithMubuf(), replaceWithLoadOrStore(), mlir::LLVM::detail::vectorOneToOneRewrite(), and verify().
splitBlock()
Block * PatternRewriter::splitBlock (Block * block, Block::iterator before) virtual
Split the operations starting at "before" (inclusive) out of the given block into a new block, and return it.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 133 of file PatternMatch.cpp.
References mlir::Operation::getNumResults(), mlir::Operation::getResult(), mlir::Operation::getResults(), and mlir::Block::splitBlock().
Referenced by print(), and mlir::ConversionPatternRewriter::splitBlock().
startRootUpdate()
virtual void mlir::PatternRewriter::startRootUpdate (Operation * op) inline virtual
This method is used to notify the rewriter that an in-place operation modification is about to happen.
A call to this function must be followed by a call to either finalizeRootUpdate or cancelRootUpdate. This is a minor efficiency win (it avoids creating a new operation and removing the old one) but also often allows simpler code in the client.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 338 of file PatternMatch.h.
Referenced by mlir::buildAffineLoopNest(), mlir::vector::VectorTransferFullPartialRewriter::matchAndRewrite(), mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), and replaceUnitDims().
updateRootInPlace()
template<typename CallableT > void mlir::PatternRewriter::updateRootInPlace (Operation * root, CallableT && callable) inline
This method is a utility wrapper around a root update of an operation.
It wraps calls to startRootUpdate and finalizeRootUpdate around the given callable.
Definition at line 353 of file PatternMatch.h.
Referenced by mlir::TypeConverter::convertBlockSignature(), lowerEntryPointABIAttr(), and mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite().
The documentation for this class was generated from the following files:
include/mlir/IR/PatternMatch.h
lib/IR/PatternMatch.cpp