MLIR: mlir::UnrankedMemRefType Class Reference
mlir::UnrankedMemRefType Class Reference
Unranked MemRef type represent multi-dimensional MemRefs that have an unknown rank.
#include "mlir/IR/StandardTypes.h"
Public Member Functions
ArrayRef< int64_t > getShape () const
unsigned getMemorySpace () const
Returns the memory space in which data referred to by this memref resides.
Static Public Member Functions
static UnrankedMemRefType get (Type elementType, unsigned memorySpace)
Get or create a new UnrankedMemRefType of the provided element type and memory space.
static UnrankedMemRefType getChecked (Type elementType, unsigned memorySpace, Location location)
Get or create a new UnrankedMemRefType of the provided element type and memory space declared at the given, potentially unknown, location.
static LogicalResult verifyConstructionInvariants (Location loc, Type elementType, unsigned memorySpace)
Verify the construction of a unranked memref type.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Unranked MemRef type represent multi-dimensional MemRefs that have an unknown rank.
Definition at line 545 of file StandardTypes.h.
Member Function Documentation
get()
UnrankedMemRefType UnrankedMemRefType< T >::get (Type elementType, unsigned memorySpace) static
Get or create a new UnrankedMemRefType of the provided element type and memory space.
Definition at line 467 of file StandardTypes.cpp.
References mlir::Type::getContext(), and mlir::StandardTypes::UnrankedMemRef.
Referenced by mlir::BufferAssignmentTypeConverter::BufferAssignmentTypeConverter(), and mlir::detail::Parser::parseMemRefType().
getChecked()
UnrankedMemRefType UnrankedMemRefType< T >::getChecked (Type elementType, unsigned memorySpace, Location location) static
Get or create a new UnrankedMemRefType of the provided element type and memory space declared at the given, potentially unknown, location.
If the UnrankedMemRefType defined by the arguments would be ill-formed, emit errors and return a nullptr-wrapping type.
Definition at line 473 of file StandardTypes.cpp.
References mlir::StandardTypes::UnrankedMemRef.
getMemorySpace()
unsigned UnrankedMemRefType< T >::getMemorySpace () const
Returns the memory space in which data referred to by this memref resides.
Definition at line 480 of file StandardTypes.cpp.
Referenced by verify().
getShape()
ArrayRef<int64_t> mlir::UnrankedMemRefType::getShape () const inline
Definition at line 567 of file StandardTypes.h.
verifyConstructionInvariants()
LogicalResult UnrankedMemRefType< T >::verifyConstructionInvariants (Location loc, Type elementType, unsigned memorySpace) static
Verify the construction of a unranked memref type.
Definition at line 485 of file StandardTypes.cpp.
References mlir::emitError(), mlir::BaseMemRefType::isValidElementType(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/StandardTypes.cpp