MLIR: mlir::ExecutionEngine Class Reference
mlir::ExecutionEngine Class Reference
JIT-backed execution engine for MLIR modules.
#include "mlir/ExecutionEngine/ExecutionEngine.h"
Public Member Functions
ExecutionEngine (bool enableObjectCache, bool enableGDBNotificationListener, bool enablePerfNotificationListener)
llvm::Expected< void(*)(void **)> lookup (StringRef name) const
Looks up a packed-argument function with the given name and returns a pointer to it.
llvm::Error invoke (StringRef name, MutableArrayRef< void *> args=llvm::None)
Invokes the function with the given name passing it the list of arguments as a list of opaque pointers.
void dumpToObjectFile (StringRef filename)
Dump object code to output file filename.
void registerSymbols (llvm::function_ref< llvm::orc::SymbolMap(llvm::orc::MangleAndInterner)> symbolMap)
Register symbols with this ExecutionEngine.
Static Public Member Functions
static llvm::Expected< std::unique_ptr< ExecutionEngine > > create (ModuleOp m, llvm::function_ref< llvm::Error(llvm::Module *)> transformer={}, Optional< llvm::CodeGenOpt::Level > jitCodeGenOptLevel=llvm::None, ArrayRef< StringRef > sharedLibPaths={}, bool enableObjectCache=true, bool enableGDBNotificationListener=true, bool enablePerfNotificationListener=true)
Creates an execution engine for the given module.
static bool setupTargetTriple (llvm::Module *llvmModule)
Set the target triple on the module.
Detailed Description
JIT-backed execution engine for MLIR modules.
Assumes the module can be converted to LLVM IR. For each function, creates a wrapper function with the fixed interface
void _mlir_funcName(void **)
where the only argument is interpreted as a list of pointers to the actual arguments of the function, followed by a pointer to the result. This allows the engine to provide the caller with a generic function pointer that can be used to invoke the JIT-compiled function.
Definition at line 61 of file ExecutionEngine.h.
Constructor & Destructor Documentation
ExecutionEngine()
ExecutionEngine::ExecutionEngine (bool enableObjectCache, bool enableGDBNotificationListener, bool enablePerfNotificationListener)
Definition at line 205 of file ExecutionEngine.cpp.
Member Function Documentation
create()
Expected< std::unique_ptr< ExecutionEngine > > ExecutionEngine::create (ModuleOp m, llvm::function_ref< llvm::Error(llvm::Module *)> transformer = {}, Optional< llvm::CodeGenOpt::Level > jitCodeGenOptLevel = llvm::None, ArrayRef< StringRef > sharedLibPaths = {}, bool enableObjectCache = true, bool enableGDBNotificationListener = true, bool enablePerfNotificationListener = true) static
Creates an execution engine for the given module.
If transformer is provided, it will be called on the LLVM module during JIT-compilation and can be used, e.g., for reporting or optimization.
jitCodeGenOptLevel, when provided, is used as the optimization level for target code generation.
If sharedLibPaths are provided, the underlying JIT-compilation will open and link the shared libraries for symbol resolution.
If enableObjectCache is set, the JIT compiler will create one to store the object generated for the given module.
If enable enableGDBNotificationListener is set, the JIT compiler will notify the llvm's global GDB notification listener.
If enablePerfNotificationListener is set, the JIT compiler will notify the llvm's global Perf notification listener.
Definition at line 216 of file ExecutionEngine.cpp.
References make_string_error(), packFunctionArguments(), setupTargetTriple(), and mlir::translateModuleToLLVMIR().
Referenced by compileAndExecute().
dumpToObjectFile()
void ExecutionEngine::dumpToObjectFile (StringRef filename)
Dump object code to output file filename.
Definition at line 101 of file ExecutionEngine.cpp.
invoke()
Error ExecutionEngine::invoke (StringRef name, MutableArrayRef< void *> args = llvm::None)
Invokes the function with the given name passing it the list of arguments as a list of opaque pointers.
Definition at line 333 of file ExecutionEngine.cpp.
References lookup(), and mlir::success().
lookup()
Expected< void(*)(void **)> ExecutionEngine::lookup (StringRef name) const
Looks up a packed-argument function with the given name and returns a pointer to it.
Propagates errors in case of failure.
Definition at line 309 of file ExecutionEngine.cpp.
References make_string_error(), and makePackedFunctionName().
Referenced by invoke().
registerSymbols()
void ExecutionEngine::registerSymbols (llvm::function_ref< llvm::orc::SymbolMap(llvm::orc::MangleAndInterner)> symbolMap)
Register symbols with this ExecutionEngine.
Definition at line 105 of file ExecutionEngine.cpp.
setupTargetTriple()
bool ExecutionEngine::setupTargetTriple (llvm::Module * llvmModule) static
Set the target triple on the module.
This is implicitly done when creating the engine.
Definition at line 114 of file ExecutionEngine.cpp.
Referenced by create().
The documentation for this class was generated from the following files:
include/mlir/ExecutionEngine/ExecutionEngine.h
lib/ExecutionEngine/ExecutionEngine.cpp