MLIR: mlir::Region Class Reference
mlir::Region Class Reference
This class contains a list of basic blocks and a link to the parent operation it is attached to.
#include "mlir/IR/Region.h"
Classes
class OpIterator
This class provides iteration over the held operations of blocks directly within a region.
Public Types
using BlockListType = llvm::iplist< Block >
using iterator = BlockListType::iterator
using reverse_iterator = BlockListType::reverse_iterator
using BlockArgListType = MutableArrayRef< BlockArgument >
using args_iterator = BlockArgListType::iterator
using reverse_args_iterator = BlockArgListType::reverse_iterator
template<typename OpT >
using op_iterator = detail::op_iterator< OpT, OpIterator >
This class provides iteration over the held operations of a region for a specific operation type.
Public Member Functions
Region ()=default
Region (Operation *container)
~Region ()
MLIRContext * getContext ()
Return the context this region is inserted in.
Location getLoc ()
Return a location for this region.
BlockListType & getBlocks ()
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
bool empty ()
void push_back (Block *block)
void push_front (Block *block)
Block & back ()
Block & front ()
BlockArgListType getArguments ()
ValueTypeRange< BlockArgListType > getArgumentTypes ()
Return a range containing the types of the arguments for this region.
args_iterator args_begin ()
args_iterator args_end ()
reverse_args_iterator args_rbegin ()
reverse_args_iterator args_rend ()
bool args_empty ()
BlockArgument addArgument (Type type)
Add one value to the argument list.
BlockArgument insertArgument (args_iterator it, Type type)
Insert one value to the position in the argument list indicated by the given iterator.
iterator_range< args_iterator > addArguments (TypeRange types)
Add one argument to the argument list for each type specified in the list.
BlockArgument insertArgument (unsigned index, Type type)
Add one value to the argument list at the specified position.
void eraseArgument (unsigned index)
Erase the argument at 'index' and remove it from the argument list.
unsigned getNumArguments ()
BlockArgument getArgument (unsigned i)
OpIterator op_begin ()
Return iterators that walk the operations nested directly within this region.
OpIterator op_end ()
iterator_range< OpIterator > getOps ()
template<typename OpT >
op_iterator< OpT > op_begin ()
Return iterators that walk operations of type 'T' nested directly within this region.
template<typename OpT >
op_iterator< OpT > op_end ()
template<typename OpT >
iterator_range< op_iterator< OpT > > getOps ()
Region * getParentRegion ()
Return the region containing this region or nullptr if the region is attached to a top-level operation.
Operation * getParentOp ()
Return the parent operation this region is attached to.
template<typename ParentT >
ParentT getParentOfType ()
Find the first parent operation of the given type, or nullptr if there is no ancestor operation.
unsigned getRegionNumber ()
Return the number of this region in the parent operation.
bool isProperAncestor (Region *other)
Return true if this region is a proper ancestor of the other region.
bool isAncestor (Region *other)
Return true if this region is ancestor of the other region.
void cloneInto (Region *dest, BlockAndValueMapping &mapper)
Clone the internal blocks from this region into dest.
void cloneInto (Region *dest, Region::iterator destPos, BlockAndValueMapping &mapper)
Clone this region into 'dest' before the given position in 'dest'.
void takeBody (Region &other)
Takes body of another region (that region will have no body after this operation completes).
bool isIsolatedFromAbove (Optional< Location > noteLoc=llvm::None)
Check that this does not use any value defined outside it.
Block * findAncestorBlockInRegion (Block &block)
Returns 'block' if 'block' lies in this region, or otherwise finds the ancestor of 'block' that lies in this region.
void dropAllReferences ()
Drop all operand uses from operations within this region, which is an essential step in breaking cyclic dependences between references when they are to be deleted.
template<typename FnT , typename RetT = detail::walkResultType<FnT>>
std::enable_if< std::is_same< RetT, void >::value, RetT >::type walk (FnT &&callback)
Walk the operations in this region in postorder, calling the callback for each operation.
template<typename FnT , typename RetT = detail::walkResultType<FnT>>
std::enable_if< std::is_same< RetT, WalkResult >::value, RetT >::type walk (FnT &&callback)
Walk the operations in this region in postorder, calling the callback for each operation.
void viewGraph (const Twine &regionName)
Displays the CFG in a window.
void viewGraph ()
Static Public Member Functions
static BlockListType Region::* getSublistAccess (Block *)
getSublistAccess() - Returns pointer to member of region.
Detailed Description
This class contains a list of basic blocks and a link to the parent operation it is attached to.
Definition at line 26 of file Region.h.
Member Typedef Documentation
args_iterator
using mlir::Region::args_iterator = BlockArgListType::iterator
Definition at line 80 of file Region.h.
BlockArgListType
using mlir::Region::BlockArgListType = MutableArrayRef<BlockArgument>
Definition at line 73 of file Region.h.
BlockListType
using mlir::Region::BlockListType = llvm::iplist<Block>
Definition at line 44 of file Region.h.
iterator
using mlir::Region::iterator = BlockListType::iterator
Definition at line 48 of file Region.h.
op_iterator
template<typename OpT > using mlir::Region::op_iterator = detail::op_iterator<OpT, OpIterator>
This class provides iteration over the held operations of a region for a specific operation type.
Definition at line 153 of file Region.h.
reverse_args_iterator
using mlir::Region::reverse_args_iterator = BlockArgListType::reverse_iterator
Definition at line 81 of file Region.h.
reverse_iterator
using mlir::Region::reverse_iterator = BlockListType::reverse_iterator
Definition at line 49 of file Region.h.
Constructor & Destructor Documentation
Region() [1/2]
mlir::Region::Region () default
Region() [2/2]
Region::Region (Operation * container) explicit
Definition at line 14 of file Region.cpp.
~Region()
Region::~Region ()
Definition at line 16 of file Region.cpp.
References dropAllReferences().
Member Function Documentation
addArgument()
BlockArgument mlir::Region::addArgument (Type type) inline
Add one value to the argument list.
Definition at line 90 of file Region.h.
References mlir::Block::addArgument(), and front().
Referenced by verify().
addArguments()
iterator_range< Region::args_iterator > Region::addArguments (TypeRange types)
Add one argument to the argument list for each type specified in the list.
Definition at line 42 of file Region.cpp.
References mlir::Block::addArguments(), and front().
Referenced by insertArgument().
args_begin()
args_iterator mlir::Region::args_begin () inline
Definition at line 82 of file Region.h.
References getArguments().
args_empty()
bool mlir::Region::args_empty () inline
Definition at line 87 of file Region.h.
References getArguments().
args_end()
args_iterator mlir::Region::args_end () inline
Definition at line 83 of file Region.h.
References getArguments().
args_rbegin()
reverse_args_iterator mlir::Region::args_rbegin () inline
Definition at line 84 of file Region.h.
References getArguments().
args_rend()
reverse_args_iterator mlir::Region::args_rend () inline
Definition at line 85 of file Region.h.
References getArguments().
back()
Block& mlir::Region::back () inline
Definition at line 60 of file Region.h.
Referenced by mlir::impl::ensureRegionTerminator(), and isFnEntryBlock().
begin()
iterator mlir::Region::begin () inline
Definition at line 51 of file Region.h.
Referenced by createLinalgOpOfSameType(), eraseUnreachableBlocks(), getAtomicOpScope(), getOrInsertBuiltinVariable(), mlir::inlineRegion(), llvm::GraphTraits< mlir::Region * >::nodes_begin(), and mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyTrait().
cloneInto() [1/2]
void Region::cloneInto (Region * dest, BlockAndValueMapping & mapper)
Clone the internal blocks from this region into dest.
Clone the internal blocks from this region into dest.
Any cloned blocks are appended to the back of dest. If the mapper contains entries for block arguments, these arguments are not included in the respective cloned block.
Any cloned blocks are appended to the back of dest.
Definition at line 73 of file Region.cpp.
References end().
Referenced by mlir::PatternRewriter::cloneRegionBefore(), mlir::inlineRegion(), and isAncestor().
cloneInto() [2/2]
void Region::cloneInto (Region * dest, Region::iterator destPos, BlockAndValueMapping & mapper)
Clone this region into 'dest' before the given position in 'dest'.
Definition at line 79 of file Region.cpp.
References mlir::Block::addArgument(), mlir::BlockAndValueMapping::contains(), empty(), front(), mlir::Block::getArguments(), getBlocks(), mlir::BlockAndValueMapping::lookup(), mlir::BlockAndValueMapping::lookupOrNull(), mlir::BlockAndValueMapping::map(), and mlir::Block::push_back().
dropAllReferences()
void Region::dropAllReferences ()
Drop all operand uses from operations within this region, which is an essential step in breaking cyclic dependences between references when they are to be deleted.
Definition at line 135 of file Region.cpp.
References mlir::Block::dropAllReferences().
Referenced by takeBody(), and ~Region().
empty()
bool mlir::Region::empty () inline
Definition at line 56 of file Region.h.
Referenced by mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), canRegisterAlias(), cloneInto(), mlir::ConversionPatternRewriter::cloneRegionBefore(), mlir::detail::ConversionPatternRewriterImpl::convertRegionTypes(), deleteDeadness(), mlir::impl::ensureRegionTerminator(), eraseUnreachableBlocks(), getArguments(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::getBody(), mlir::inlineCall(), mlir::inlineRegion(), mergeIdenticalBlocks(), mlirRegionGetFirstBlock(), mlir::OpBuilder::OpBuilder(), mlir::Region::OpIterator::OpIterator(), print(), printDenseElementsAttrImpl(), mlir::impl::printFunctionSignature(), printGlobalOp(), propagateLiveness(), mlir::detail::DominanceInfoBase< true >::recalculate(), and mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyTrait().
end()
iterator mlir::Region::end () inline
Definition at line 52 of file Region.h.
Referenced by cloneInto(), mlir::OpBuilder::createBlock(), eraseUnreachableBlocks(), mlir::inlineRegion(), llvm::GraphTraits< mlir::Region * >::nodes_end(), mlir::Region::OpIterator::operator++(), mlir::detail::ConversionPatternRewriterImpl::undoBlockActions(), and mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyTrait().
eraseArgument()
void mlir::Region::eraseArgument (unsigned index) inline
Erase the argument at 'index' and remove it from the argument list.
Definition at line 108 of file Region.h.
References mlir::Block::eraseArgument(), and front().
findAncestorBlockInRegion()
Block * Region::findAncestorBlockInRegion (Block & block)
Returns 'block' if 'block' lies in this region, or otherwise finds the ancestor of 'block' that lies in this region.
Returns nullptr if the latter fails.
Definition at line 124 of file Region.cpp.
References mlir::Operation::getBlock(), and mlir::Operation::getParentOp().
Referenced by takeBody().
front()
Block& mlir::Region::front () inline
Definition at line 61 of file Region.h.
Referenced by addArgument(), addArguments(), mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), buildNamedStructuredOpRegionAndAttributes(), mlir::scf::buildTerminatedBody(), cloneInto(), mlir::ConversionPatternRewriter::cloneRegionBefore(), mlir::detail::ConversionPatternRewriterImpl::convertRegionTypes(), deleteDeadness(), eraseArgument(), eraseUnreachableBlocks(), getArguments(), mlir::ModuleOp::getBody(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::getBody(), llvm::GraphTraits< mlir::Region * >::getEntryNode(), mlir::LLVM::ModuleTranslation::getModuleBody(), mlir::OperationFolder::getOrCreateConstant(), hasMultiplyAddBody(), injectGpuIndexOperations(), mlir::inlineCall(), mlir::inlineRegion(), mlir::SymbolTable::insert(), insertArgument(), insertCopies(), mlir::SymbolTable::lookupSymbolIn(), mlirRegionGetFirstBlock(), mlir::OpBuilder::OpBuilder(), mlir::outlineIfOp(), outlineKernelFuncImpl(), printDenseElementsAttrImpl(), propagateLiveness(), mlir::SymbolTable::SymbolTable(), verify(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyTrait(), and walkReturnOperations().
getArgument()
BlockArgument mlir::Region::getArgument (unsigned i) inline
Definition at line 111 of file Region.h.
References getArguments().
Referenced by canRegisterAlias(), hasMultiplyAddBody(), mlir::impl::printFunctionSignature(), and verifyRegionAttribute().
getArguments()
BlockArgListType mlir::Region::getArguments () inline
Definition at line 74 of file Region.h.
References empty(), front(), mlir::Block::getArguments(), and getArgumentTypes().
Referenced by args_begin(), args_empty(), args_end(), args_rbegin(), args_rend(), getArgument(), getArgumentTypes(), and getNumArguments().
getArgumentTypes()
auto Region::getArgumentTypes ()
Return a range containing the types of the arguments for this region.
Definition at line 37 of file Region.cpp.
References getArguments().
Referenced by getArguments().
getBlocks()
BlockListType& mlir::Region::getBlocks () inline
Definition at line 45 of file Region.h.
Referenced by cloneInto(), mlir::OpBuilder::createBlock(), deleteDeadness(), mlir::inlineRegion(), mlir::PatternRewriter::inlineRegionBefore(), mlir::Block::insertBefore(), logFailure(), mlir::Block::moveBefore(), mlir::outlineIfOp(), mlir::detail::Parser::parseToken(), printDenseElementsAttrImpl(), takeBody(), mlir::detail::ConversionPatternRewriterImpl::undoBlockActions(), and verify().
getContext()
MLIRContext * Region::getContext ()
Return the context this region is inserted in.
The region must have a valid parent container.
Definition at line 24 of file Region.cpp.
References mlir::Operation::getContext().
Referenced by insertCopies().
getLoc()
Location Region::getLoc ()
Return a location for this region.
This is the location attached to the parent container. The region must have a valid parent container.
Definition at line 31 of file Region.cpp.
References mlir::Operation::getLoc().
Referenced by mlir::ConversionPatternRewriter::cloneRegionBefore().
getNumArguments()
unsigned mlir::Region::getNumArguments () inline
Definition at line 110 of file Region.h.
References getArguments().
Referenced by canRegisterAlias(), and verifyTypesAlongAllEdges().
getOps() [1/2]
iterator_range<OpIterator> mlir::Region::getOps () inline
Definition at line 159 of file Region.h.
References op_begin(), and op_end().
Referenced by walkReferencedSymbolNodes().
getOps() [2/2]
template<typename OpT > iterator_range<op_iterator<OpT> > mlir::Region::getOps () inline
Definition at line 169 of file Region.h.
References getParentOp(), getParentRegion(), op_begin(), and op_end().
getParentOfType()
template<typename ParentT > ParentT mlir::Region::getParentOfType () inline
Find the first parent operation of the given type, or nullptr if there is no ancestor operation.
Definition at line 188 of file Region.h.
References getParentRegion(), getRegionNumber(), and isProperAncestor().
Referenced by generateCopy().
getParentOp()
Operation * Region::getParentOp ()
Return the parent operation this region is attached to.
Definition at line 51 of file Region.cpp.
Referenced by canRegisterAlias(), collectCallOps(), collectSymbolScopes(), containsReturn(), mlir::getForInductionVarOwner(), getInsertionRegion(), getOps(), mlir::CallGraph::getOrAddNode(), getRegionNumber(), inlineCallsInSCC(), insertCopyLoops(), mlir::InlinerInterface::isLegalToInline(), mlir::isValidSymbol(), logFailure(), mlir::CallGraph::print(), mlir::DominanceInfo::properlyDominates(), traverseAncestors(), walkReferencedSymbolNodes(), and walkReturnOperations().
getParentRegion()
Region * Region::getParentRegion ()
Return the region containing this region or nullptr if the region is attached to a top-level operation.
Definition at line 46 of file Region.cpp.
References mlir::Operation::getParentRegion().
Referenced by llvm::ilist_traits<::mlir::Block >::addNodeToList(), collectCallOps(), getOps(), getParentOfType(), mlir::Value::getParentRegion(), mlir::Op< AffineDmaStartOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >::getParentRegion(), isProperAncestor(), llvm::ilist_traits<::mlir::Block >::transferNodesFromList(), and mlir::visitUsedValuesDefinedAbove().
getRegionNumber()
unsigned Region::getRegionNumber ()
Return the number of this region in the parent operation.
Definition at line 65 of file Region.cpp.
References getParentOp(), and mlir::Operation::getRegions().
Referenced by getParentOfType(), mlir::DominanceInfo::properlyDominates(), and mlir::PostDominanceInfo::properlyPostDominates().
getSublistAccess()
static BlockListType Region::* mlir::Region::getSublistAccess (Block *) inline static
getSublistAccess() - Returns pointer to member of region.
Definition at line 64 of file Region.h.
Referenced by isIsolatedFromAbove().
insertArgument() [1/2]
BlockArgument mlir::Region::insertArgument (args_iterator it, Type type) inline
Insert one value to the position in the argument list indicated by the given iterator.
The existing arguments are shifted. The block is expected not to have predecessors.
Definition at line 95 of file Region.h.
References addArguments(), front(), and mlir::Block::insertArgument().
insertArgument() [2/2]
BlockArgument mlir::Region::insertArgument (unsigned index, Type type) inline
Add one value to the argument list at the specified position.
Definition at line 103 of file Region.h.
References front(), and mlir::Block::insertArgument().
isAncestor()
bool mlir::Region::isAncestor (Region * other) inline
Return true if this region is ancestor of the other region.
A region is considered as its own ancestor, use isProperAncestor to avoid this.
Definition at line 205 of file Region.h.
References cloneInto(), and isProperAncestor().
Referenced by canonicalizeLoopBounds(), isIsolatedAbove(), mlir::DominanceInfo::properlyDominates(), mlir::replaceAllUsesInRegionWith(), verify(), and mlir::visitUsedValuesDefinedAbove().
isIsolatedFromAbove()
bool Region::isIsolatedFromAbove (Optional< Location > noteLoc = llvm::None)
Check that this does not use any value defined outside it.
Emit errors if noteLoc is provided; this location is used to point to the operation containing the region, the actual error is reported at the operation with an offending use.
Definition at line 190 of file Region.cpp.
References getSublistAccess(), and isIsolatedAbove().
Referenced by takeBody().
isProperAncestor()
bool Region::isProperAncestor (Region * other)
Return true if this region is a proper ancestor of the other region.
Definition at line 53 of file Region.cpp.
References getParentRegion().
Referenced by getParentOfType(), and isAncestor().
op_begin() [1/2]
OpIterator mlir::Region::op_begin () inline
Return iterators that walk the operations nested directly within this region.
Definition at line 157 of file Region.h.
References mlir::Region::OpIterator::OpIterator().
Referenced by getOps(), and op_begin().
op_begin() [2/2]
template<typename OpT > op_iterator<OpT> mlir::Region::op_begin () inline
Return iterators that walk operations of type 'T' nested directly within this region.
Definition at line 163 of file Region.h.
References op_begin(), and op_end().
op_end() [1/2]
OpIterator mlir::Region::op_end () inline
Definition at line 158 of file Region.h.
References mlir::Region::OpIterator::OpIterator().
Referenced by getOps(), op_begin(), and op_end().
op_end() [2/2]
template<typename OpT > op_iterator<OpT> mlir::Region::op_end () inline
Definition at line 166 of file Region.h.
References op_end().
push_back()
void mlir::Region::push_back (Block * block) inline
Definition at line 57 of file Region.h.
Referenced by buildNamedStructuredOpRegionAndAttributes(), mlir::scf::buildTerminatedBody(), mlir::AffineDmaWaitOp::fold(), fuseLinalgOpsGreedily(), parseShuffleOp(), mlir::detail::Parser::parseToken(), print(), and verify().
push_front()
void mlir::Region::push_front (Block * block) inline
Definition at line 58 of file Region.h.
rbegin()
reverse_iterator mlir::Region::rbegin () inline
Definition at line 53 of file Region.h.
rend()
reverse_iterator mlir::Region::rend () inline
Definition at line 54 of file Region.h.
takeBody()
void mlir::Region::takeBody (Region & other) inline
Takes body of another region (that region will have no body after this operation completes).
The current body of this region is cleared.
Definition at line 220 of file Region.h.
References dropAllReferences(), findAncestorBlockInRegion(), getBlocks(), and isIsolatedFromAbove().
Referenced by mlir::Operation::create().
viewGraph() [1/2]
void mlir::Region::viewGraph (const Twine & regionName)
Displays the CFG in a window.
This is for use from the debugger and depends on Graphviz to generate the graph. This function is defined in ViewRegionGraph and only works with that target linked.
Definition at line 57 of file ViewRegionGraph.cpp.
References mlir::viewGraph().
viewGraph() [2/2]
void mlir::Region::viewGraph ()
Definition at line 60 of file ViewRegionGraph.cpp.
References mlir::viewGraph(), and mlir::writeGraph().
Referenced by walk().
walk() [1/2]
template<typename FnT , typename RetT = detail::walkResultType<FnT>> std::enable_if<std::is_same<RetT, void>::value, RetT>::type mlir::Region::walk (FnT && callback) inline
Walk the operations in this region in postorder, calling the callback for each operation.
This method is invoked for void-returning callbacks. See Operation::walk for more details.
Definition at line 250 of file Region.h.
References mlir::Block::walk().
Referenced by mlir::greedilyMapParallelSCFToGPU(), and mlir::visitUsedValuesDefinedAbove().
walk() [2/2]
template<typename FnT , typename RetT = detail::walkResultType<FnT>> std::enable_if<std::is_same<RetT, WalkResult>::value, RetT>::type mlir::Region::walk (FnT && callback) inline
Walk the operations in this region in postorder, calling the callback for each operation.
This method is invoked for interruptible callbacks. See Operation::walk for more details.
Definition at line 260 of file Region.h.
References mlir::WalkResult::advance(), mlir::WalkResult::interrupt(), viewGraph(), and mlir::Block::walk().
The documentation for this class was generated from the following files:
include/mlir/IR/Region.h
lib/IR/Region.cpp
lib/Transforms/ViewRegionGraph.cpp