MLIR: mlir::OwningRewritePatternList Class Reference
mlir::OwningRewritePatternList Class Reference
#include "mlir/IR/PatternMatch.h"
Public Member Functions
OwningRewritePatternList ()=default
template<typename T >
OwningRewritePatternList (T &&t)
Construct a OwningRewritePatternList populated with the pattern t of type T.
PatternListT::iterator begin ()
PatternListT::iterator end ()
PatternListT::const_iterator begin () const
PatternListT::const_iterator end () const
PatternListT::size_type size () const
void clear ()
template<typename... Ts, typename ConstructorArg , typename... ConstructorArgs, typename = std::enable_if_t<sizeof...(Ts) != 0>>
OwningRewritePatternList & insert (ConstructorArg &&arg, ConstructorArgs &&... args)
Add an instance of each of the pattern types 'Ts' to the pattern list with the given arguments.
template<typename... Ts>
OwningRewritePatternList & insert ()
Add an instance of each of the pattern types 'Ts'.
void insert (std::unique_ptr< RewritePattern > pattern)
Add the given pattern to the pattern list.
Detailed Description
Definition at line 424 of file PatternMatch.h.
Constructor & Destructor Documentation
OwningRewritePatternList() [1/2]
mlir::OwningRewritePatternList::OwningRewritePatternList () default
OwningRewritePatternList() [2/2]
template<typename T > mlir::OwningRewritePatternList::OwningRewritePatternList (T && t) inline
Construct a OwningRewritePatternList populated with the pattern t of type T.
Definition at line 433 of file PatternMatch.h.
Member Function Documentation
begin() [1/2]
PatternListT::iterator mlir::OwningRewritePatternList::begin () inline
Definition at line 437 of file PatternMatch.h.
begin() [2/2]
PatternListT::const_iterator mlir::OwningRewritePatternList::begin () const inline
Definition at line 439 of file PatternMatch.h.
clear()
void mlir::OwningRewritePatternList::clear () inline
Definition at line 442 of file PatternMatch.h.
end() [1/2]
PatternListT::iterator mlir::OwningRewritePatternList::end () inline
Definition at line 438 of file PatternMatch.h.
end() [2/2]
PatternListT::const_iterator mlir::OwningRewritePatternList::end () const inline
Definition at line 440 of file PatternMatch.h.
insert() [1/3]
template<typename... Ts, typename ConstructorArg , typename... ConstructorArgs, typename = std::enable_if_t<sizeof...(Ts) != 0>> OwningRewritePatternList& mlir::OwningRewritePatternList::insert (ConstructorArg && arg, ConstructorArgs &&... args) inline
Add an instance of each of the pattern types 'Ts' to the pattern list with the given arguments.
Return a reference to this for chaining insertions. Note: ConstructorArg is necessary here to separate the two variadic lists.
Definition at line 454 of file PatternMatch.h.
Referenced by mlir::applyCmpPredicate(), mlir::canFoldIntoConsumerOp(), canonicalizeLoopBounds(), mlir::canonicalizeSetAndOperands(), collapseBranch(), extractCompositeElement(), foldMinMaxOp(), getInputAndOutputIndices(), mlir::scf::getParallelForInductionVarOwner(), lowerEntryPointABIAttr(), parseConstShapeOp(), mlir::populateAffineToStdConversionPatterns(), mlir::populateAffineToVectorConversionPatterns(), mlir::populateAVX512ToLLVMConversionPatterns(), mlir::populateBuiltinFuncToSPIRVPatterns(), mlir::populateCallOpTypeConversionPattern(), mlir::populateExpandTanhPattern(), mlir::populateFuncOpTypeConversionPattern(), mlir::populateGpuRewritePatterns(), mlir::populateGpuToLLVMConversionPatterns(), mlir::populateGpuToNVVMConversionPatterns(), mlir::populateGpuToROCDLConversionPatterns(), mlir::populateGPUToSPIRVPatterns(), mlir::populateLinalgFoldUnitExtentDimsPatterns(), mlir::populateLinalgTensorOpsFusionPatterns(), mlir::populateLinalgToLLVMConversionPatterns(), mlir::populateLinalgToSPIRVPatterns(), mlir::populateLinalgToStandardConversionPatterns(), mlir::populateLoopToStdConversionPatterns(), mlir::populateParallelLoopToGPUPatterns(), mlir::populateRemoveShapeConstraintsPatterns(), mlir::populateSCFToSPIRVPatterns(), mlir::populateShapeRewritePatterns(), mlir::populateShapeToSCFConversionPatterns(), mlir::populateShapeToStandardConversionPatterns(), populateSPIRVLayoutInfoPatterns(), mlir::populateSPIRVToLLVMConversionPatterns(), mlir::populateSPIRVToLLVMFunctionConversionPatterns(), mlir::populateSPIRVToLLVMModuleConversionPatterns(), mlir::populateStandardToSPIRVPatterns(), mlir::populateStdLegalizationPatternsForSPIRVLowering(), mlir::populateStdToLLVMFuncOpConversionPattern(), mlir::populateStdToLLVMMemoryConversionPatterns(), mlir::populateStdToLLVMNonMemoryConversionPatterns(), mlir::vector::populateVectorContractLoweringPatterns(), mlir::vector::populateVectorSlicesLoweringPatterns(), mlir::populateVectorToLLVMConversionPatterns(), mlir::populateVectorToLLVMMatrixConversionPatterns(), mlir::populateVectorToROCDLConversionPatterns(), mlir::populateVectorToSCFConversionPatterns(), mlir::vector::populateVectorToVectorCanonicalizationPatterns(), mlir::vector::populateVectorToVectorTransformationPatterns(), mlir::populateWithBufferAssignmentOpConversionPatterns(), print(), mlir::linalg::tileLinalgOp(), and verify().
insert() [2/3]
template<typename... Ts> OwningRewritePatternList& mlir::OwningRewritePatternList::insert () inline
Add an instance of each of the pattern types 'Ts'.
Return a reference to this for chaining insertions.
Definition at line 467 of file PatternMatch.h.
insert() [3/3]
void mlir::OwningRewritePatternList::insert (std::unique_ptr< RewritePattern > pattern) inline
Add the given pattern to the pattern list.
Definition at line 474 of file PatternMatch.h.
size()
PatternListT::size_type mlir::OwningRewritePatternList::size () const inline
Definition at line 441 of file PatternMatch.h.
The documentation for this class was generated from the following file:
include/mlir/IR/PatternMatch.h