MLIR: mlir::DenseIntElementsAttr Class Reference
mlir::DenseIntElementsAttr Class Reference
An attribute that represents a reference to a dense integer vector or tensor object.
#include "mlir/IR/Attributes.h"
Public Types
using iterator = DenseElementsAttr::IntElementIterator
DenseIntElementsAttr iterates on APInt, so we can use the raw element iterator directly.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
DenseElementsAttr mapValues (Type newElementType, function_ref< APInt(const APInt &)> mapping) const
Generates a new DenseElementsAttr by mapping each value attribute, and constructing the DenseElementsAttr given the new element type.
iterator begin () const
Iterator access to the integer element values.
iterator end () const
Static Public Member Functions
template<typename Arg >
static DenseIntElementsAttr get (const ShapedType &type, Arg &&arg)
Get an instance of a DenseIntElementsAttr with the given arguments.
template<typename T >
static DenseIntElementsAttr get (const ShapedType &type, const std::initializer_list< T > &list)
static bool classof (Attribute attr)
Method for supporting type inquiry through isa, cast and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::DenseIntOrFPElementsAttr
static DenseElementsAttr getRaw (ShapedType type, size_t storageWidth, ArrayRef< APFloat > values, bool isSplat)
Constructs a dense elements attribute from an array of raw APFloat values.
static DenseElementsAttr getRaw (ShapedType type, size_t storageWidth, ArrayRef< APInt > values, bool isSplat)
Constructs a dense elements attribute from an array of raw APInt values.
static DenseElementsAttr getRaw (ShapedType type, ArrayRef< char > data, bool isSplat)
Get or create a new dense elements attribute instance with the given raw data buffer.
static DenseElementsAttr getRawComplex (ShapedType type, ArrayRef< char > data, int64_t dataEltSize, bool isInt, bool isSigned)
Overload of the raw 'get' method that asserts that the given type is of complex type.
static DenseElementsAttr getRawIntOrFloat (ShapedType type, ArrayRef< char > data, int64_t dataEltSize, bool isInt, bool isSigned)
Overload of the raw 'get' method that asserts that the given type is of integer or floating-point type.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Protected Attributes inherited from mlir::DenseIntOrFPElementsAttr
friend DenseElementsAttr
Detailed Description
An attribute that represents a reference to a dense integer vector or tensor object.
Definition at line 1273 of file Attributes.h.
Member Typedef Documentation
iterator
using mlir::DenseIntElementsAttr::iterator = DenseElementsAttr::IntElementIterator
DenseIntElementsAttr iterates on APInt, so we can use the raw element iterator directly.
Definition at line 1277 of file Attributes.h.
Member Function Documentation
begin()
iterator mlir::DenseIntElementsAttr::begin () const inline
Iterator access to the integer element values.
Definition at line 1301 of file Attributes.h.
Referenced by getLocalInvocationDimSize().
classof()
bool DenseIntElementsAttr::classof (Attribute attr) static
Method for supporting type inquiry through isa, cast and dyn_cast.
Definition at line 1207 of file Attributes.cpp.
References mlir::Type::cast(), getElementType(), mlir::Attribute::getType(), mlir::Attribute::isa(), and mlir::Type::isIntOrIndex().
end()
iterator mlir::DenseIntElementsAttr::end () const inline
Definition at line 1302 of file Attributes.h.
get() [1/2]
template<typename Arg > static DenseIntElementsAttr mlir::DenseIntElementsAttr::get (const ShapedType & type, Arg && arg) inline static
Get an instance of a DenseIntElementsAttr with the given arguments.
This simply wraps the DenseElementsAttr::get calls.
Definition at line 1284 of file Attributes.h.
References mlir::DenseElementsAttr::get().
Referenced by convertDenseFPElementsAttr(), mlir::Builder::getBoolVectorAttr(), mlir::Builder::getI32TensorAttr(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getI64TensorAttr(), mlir::Builder::getI64VectorAttr(), mlir::Builder::getIndexTensorAttr(), mlir::MutableOperandRange::operator OperandRange(), and verify().
get() [2/2]
template<typename T > static DenseIntElementsAttr mlir::DenseIntElementsAttr::get (const ShapedType & type, const std::initializer_list< T > & list) inline static
Definition at line 1289 of file Attributes.h.
References mlir::DenseElementsAttr::get().
mapValues()
DenseElementsAttr DenseIntElementsAttr::mapValues (Type newElementType, function_ref< APInt(const APInt &)> mapping) const
Generates a new DenseElementsAttr by mapping each value attribute, and constructing the DenseElementsAttr given the new element type.
Definition at line 1197 of file Attributes.cpp.
References mlir::AttributeStorage::getType(), and mappingHelper().
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp