MLIR: mlir::SideEffects::EffectInstance< EffectT > Class Template Reference
mlir::SideEffects::EffectInstance< EffectT > Class Template Reference
This class represents a specific instance of an effect.
#include "mlir/Interfaces/SideEffectInterfaces.h"
Public Member Functions
EffectInstance (EffectT *effect, Resource *resource=DefaultResource::get())
EffectInstance (EffectT *effect, Value value, Resource *resource=DefaultResource::get())
EffectT * getEffect () const
Return the effect being applied.
Value getValue () const
Return the value the effect is applied on, or nullptr if there isn't a known value being affected.
Resource * getResource () const
Return the resource that the effect applies to.
Detailed Description
template<typename EffectT>
class mlir::SideEffects::EffectInstance< EffectT >
This class represents a specific instance of an effect.
It contains the effect being applied, a resource that corresponds to where the effect is applied, and an optional value(either operand, result, or region entry argument) that the effect is applied to.
Definition at line 136 of file SideEffectInterfaces.h.
Constructor & Destructor Documentation
EffectInstance() [1/2]
template<typename EffectT > mlir::SideEffects::EffectInstance< EffectT >::EffectInstance (EffectT * effect, Resource * resource = DefaultResource::get()) inline
Definition at line 138 of file SideEffectInterfaces.h.
EffectInstance() [2/2]
template<typename EffectT > mlir::SideEffects::EffectInstance< EffectT >::EffectInstance (EffectT * effect, Value value, Resource * resource = DefaultResource::get()) inline
Definition at line 140 of file SideEffectInterfaces.h.
Member Function Documentation
getEffect()
template<typename EffectT > EffectT* mlir::SideEffects::EffectInstance< EffectT >::getEffect () const inline
Return the effect being applied.
Definition at line 145 of file SideEffectInterfaces.h.
Referenced by walkReturnOperations(), and wouldOpBeTriviallyDeadImpl().
getResource()
template<typename EffectT > Resource* mlir::SideEffects::EffectInstance< EffectT >::getResource () const inline
Return the resource that the effect applies to.
Definition at line 152 of file SideEffectInterfaces.h.
Referenced by walkReturnOperations().
getValue()
template<typename EffectT > Value mlir::SideEffects::EffectInstance< EffectT >::getValue () const inline
Return the value the effect is applied on, or nullptr if there isn't a known value being affected.
Definition at line 149 of file SideEffectInterfaces.h.
Referenced by walkReturnOperations(), and wouldOpBeTriviallyDeadImpl().
The documentation for this class was generated from the following file:
include/mlir/Interfaces/SideEffectInterfaces.h