MLIR: mlir::OpState Class Reference
mlir::OpState Class Reference
This is the concrete base class that holds the operation pointer and has non-generic methods that only depend on State (to avoid having them instantiated on template types that don't affect them.
#include "mlir/IR/OpDefinition.h"
Public Types
using dialect_attr_iterator = Operation::dialect_attr_iterator
A utility iterator that filters out non-dialect attributes.
using dialect_attr_range = Operation::dialect_attr_range
Public Member Functions
operator bool ()
Ops are pointer-like, so we allow implicit conversion to bool.
operator Operation * () const
This implicitly converts to Operation*.
Operation * getOperation ()
Return the operation that this refers to.
Operation * getParentOp ()
Returns the closest surrounding operation that contains this operation or nullptr if this is a top-level operation.
template<typename OpTy >
OpTy getParentOfType ()
Return the closest surrounding parent operation that is of type 'OpTy'.
template<template< typename T > class Trait>
Operation * getParentWithTrait ()
Returns the closest surrounding parent operation with trait Trait.
MLIRContext * getContext ()
Return the context this operation belongs to.
void print (raw_ostream &os, OpPrintingFlags flags=llvm::None)
Print the operation to the given stream.
void print (raw_ostream &os, AsmState &asmState, OpPrintingFlags flags=llvm::None)
void dump ()
Dump this operation.
Location getLoc ()
The source location the operation was defined or derived from.
void setLoc (Location loc)
ArrayRef< NamedAttribute > getAttrs ()
Return all of the attributes on this operation.
dialect_attr_range getDialectAttrs ()
Return a range corresponding to the dialect attributes for this operation.
dialect_attr_iterator dialect_attr_begin ()
dialect_attr_iterator dialect_attr_end ()
Attribute getAttr (StringRef name)
Return an attribute with the specified name.
template<typename AttrClass >
AttrClass getAttrOfType (StringRef name)
If the operation has an attribute of the specified type, return it.
void setAttr (Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
void setAttr (StringRef name, Attribute value)
void setAttrs (ArrayRef< NamedAttribute > attributes)
Set the attributes held by this operation.
void setAttrs (MutableDictionaryAttr newAttrs)
template<typename DialectAttrs >
void setDialectAttrs (DialectAttrs &&attrs)
Set the dialect attributes for this operation, and preserve all dependent.
MutableDictionaryAttr::RemoveResult removeAttr (Identifier name)
Remove the attribute with the specified name if it exists.
MutableDictionaryAttr::RemoveResult removeAttr (StringRef name)
bool use_empty ()
Return true if there are no users of any results of this operation.
void erase ()
Remove this operation from its parent block and delete it.
InFlightDiagnostic emitOpError (const Twine &message={})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
InFlightDiagnostic emitError (const Twine &message={})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitWarning (const Twine &message={})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitRemark (const Twine &message={})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
template<typename FnT , typename RetT = detail::walkResultType<FnT>>
RetT walk (FnT &&callback)
Walk the operation in postorder, calling the callback for each nested operation(including this one).
Static Public Member Functions
static void getCanonicalizationPatterns (OwningRewritePatternList &results, MLIRContext *context)
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Protected Member Functions
LogicalResult verify ()
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
void print (OpAsmPrinter &p)
OpState (Operation *state)
Mutability management is handled by the OpWrapper/OpConstWrapper classes, so we can cast it away here.
Static Protected Member Functions
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Unless overridden, the custom assembly form of an op is always rejected.
Detailed Description
This is the concrete base class that holds the operation pointer and has non-generic methods that only depend on State (to avoid having them instantiated on template types that don't affect them.
This also has the fallback implementations of customization hooks for when they aren't customized.
Definition at line 96 of file OpDefinition.h.
Member Typedef Documentation
dialect_attr_iterator
using mlir::OpState::dialect_attr_iterator = Operation::dialect_attr_iterator
A utility iterator that filters out non-dialect attributes.
Definition at line 145 of file OpDefinition.h.
dialect_attr_range
using mlir::OpState::dialect_attr_range = Operation::dialect_attr_range
Definition at line 146 of file OpDefinition.h.
Constructor & Destructor Documentation
OpState()
mlir::OpState::OpState (Operation * state) inline explicit protected
Mutability management is handled by the OpWrapper/OpConstWrapper classes, so we can cast it away here.
Definition at line 244 of file OpDefinition.h.
Member Function Documentation
dialect_attr_begin()
dialect_attr_iterator mlir::OpState::dialect_attr_begin () inline
Definition at line 150 of file OpDefinition.h.
dialect_attr_end()
dialect_attr_iterator mlir::OpState::dialect_attr_end () inline
Definition at line 153 of file OpDefinition.h.
dump()
void mlir::OpState::dump () inline
Dump this operation.
Definition at line 135 of file OpDefinition.h.
emitError()
InFlightDiagnostic OpState::emitError (const Twine & message = {})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
Definition at line 657 of file Operation.cpp.
Referenced by hasSizeMismatch(), and serializeModule().
emitOpError()
InFlightDiagnostic OpState::emitOpError (const Twine & message = {})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
Definition at line 663 of file Operation.cpp.
Referenced by mlir::ModuleOp::verify(), mlir::FuncOp::verify(), verify(), and verifyReshapeLikeTypes().
emitRemark()
InFlightDiagnostic OpState::emitRemark (const Twine & message = {})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
Definition at line 675 of file Operation.cpp.
Referenced by vectorizeRootMatch().
emitWarning()
InFlightDiagnostic OpState::emitWarning (const Twine & message = {})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
Definition at line 669 of file Operation.cpp.
erase()
void mlir::OpState::erase () inline
Remove this operation from its parent block and delete it.
Definition at line 196 of file OpDefinition.h.
References mlir::emitError(), mlir::emitRemark(), and mlir::emitWarning().
Referenced by mlir::createMemRefDataFlowOptPass().
getAttr()
Attribute mlir::OpState::getAttr (StringRef name) inline
Return an attribute with the specified name.
Definition at line 156 of file OpDefinition.h.
Referenced by mlir::AffineDmaStartOp::getDstMapAttr(), mlir::AffineDmaStartOp::getSrcMapAttr(), mlir::AffineDmaStartOp::getTagMapAttr(), and mlir::AffineDmaWaitOp::getTagMapAttr().
getAttrOfType()
template<typename AttrClass > AttrClass mlir::OpState::getAttrOfType (StringRef name) inline
If the operation has an attribute of the specified type, return it.
Definition at line 159 of file OpDefinition.h.
Referenced by wrapExternalFunction().
getAttrs()
ArrayRef<NamedAttribute> mlir::OpState::getAttrs () inline
Return all of the attributes on this operation.
Definition at line 142 of file OpDefinition.h.
Referenced by mlir::FuncOp::cloneInto(), mlir::ModuleOp::print(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), mlir::ModuleOp::verify(), wrapExternalFunction(), and wrapForExternalCallers().
getCanonicalizationPatterns()
static void mlir::OpState::getCanonicalizationPatterns (OwningRewritePatternList & results, MLIRContext * context) inline static
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Definition at line 226 of file OpDefinition.h.
getContext()
MLIRContext* mlir::OpState::getContext () inline
Return the context this operation belongs to.
Definition at line 123 of file OpDefinition.h.
Referenced by applyTilingToLoopPatterns(), mlir::FuncOp::clone(), mlir::FuncOp::cloneInto(), mlir::TypeConverter::convertBlockSignature(), mlir::FuncOp::eraseArguments(), fuseLinalgOpsGreedily(), mlir::AffineDmaStartOp::getAffineMapAttrForMemRef(), mlir::AffineDmaWaitOp::getAffineMapAttrForMemRef(), and mlir::populateLinalgFoldUnitExtentDimsPatterns().
getDialectAttrs()
dialect_attr_range mlir::OpState::getDialectAttrs () inline
Return a range corresponding to the dialect attributes for this operation.
Definition at line 149 of file OpDefinition.h.
getLoc()
Location mlir::OpState::getLoc () inline
The source location the operation was defined or derived from.
Definition at line 138 of file OpDefinition.h.
Referenced by canFuseSrcWhichWritesToLiveOut(), mlir::createAffineDataCopyGenerationPass(), generateCopy(), mlir::lowerAffineLowerBound(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), and wrapExternalFunction().
getOperation()
Operation* mlir::OpState::getOperation () inline
Return the operation that this refers to.
Definition at line 105 of file OpDefinition.h.
Referenced by mlir::OpTrait::TraitBase< ConcreteType, ReturnLike >::getOperation(), mlir::Op< AffineDmaStartOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >::getOperation(), mlir::operator!=(), and mlir::operator==().
getParentOfType()
template<typename OpTy > OpTy mlir::OpState::getParentOfType () inline
Return the closest surrounding parent operation that is of type 'OpTy'.
Definition at line 112 of file OpDefinition.h.
Referenced by generateCopy(), and mlir::vector::splitFullAndPartialTransfer().
getParentOp()
Operation* mlir::OpState::getParentOp () inline
Returns the closest surrounding operation that contains this operation or nullptr if this is a top-level operation.
Definition at line 109 of file OpDefinition.h.
References mlir::Operation::getParentOp().
getParentWithTrait()
template<template< typename T > class Trait> Operation* mlir::OpState::getParentWithTrait () inline
Returns the closest surrounding parent operation with trait Trait.
Definition at line 118 of file OpDefinition.h.
References mlir::Operation::getParentWithTrait().
operator bool()
mlir::OpState::operator bool () inline
Ops are pointer-like, so we allow implicit conversion to bool.
Definition at line 99 of file OpDefinition.h.
operator Operation *()
mlir::OpState::operator Operation * () const inline
This implicitly converts to Operation*.
Definition at line 102 of file OpDefinition.h.
parse()
ParseResult OpState::parse (OpAsmParser & parser, OperationState & result) static protected
Unless overridden, the custom assembly form of an op is always rejected.
Op implementations should implement this to return failure. On success, they should fill in result with the fields to use.
Definition at line 648 of file Operation.cpp.
References mlir::OpAsmParser::emitError(), and mlir::OpAsmParser::getNameLoc().
print() [1/3]
void mlir::OpState::print (raw_ostream & os, OpPrintingFlags flags = llvm::None) inline
Print the operation to the given stream.
Definition at line 126 of file OpDefinition.h.
Referenced by mlir::operator<<().
print() [2/3]
void mlir::OpState::print (raw_ostream & os, AsmState & asmState, OpPrintingFlags flags = llvm::None) inline
Definition at line 129 of file OpDefinition.h.
print() [3/3]
void OpState::print (OpAsmPrinter & p) protected
Definition at line 653 of file Operation.cpp.
References mlir::OpAsmPrinter::printGenericOp().
removeAttr() [1/2]
MutableDictionaryAttr::RemoveResult mlir::OpState::removeAttr (Identifier name) inline
Remove the attribute with the specified name if it exists.
The return value indicates whether the attribute was present or not.
Definition at line 185 of file OpDefinition.h.
removeAttr() [2/2]
MutableDictionaryAttr::RemoveResult mlir::OpState::removeAttr (StringRef name) inline
Definition at line 188 of file OpDefinition.h.
References mlir::Identifier::get().
setAttr() [1/2]
void mlir::OpState::setAttr (Identifier name, Attribute value) inline
If the an attribute exists with the specified name, change it to the new value.
Otherwise, add a new attribute with the specified name/value.
Definition at line 165 of file OpDefinition.h.
Referenced by getLibraryCallSymbolRef().
setAttr() [2/2]
void mlir::OpState::setAttr (StringRef name, Attribute value) inline
Definition at line 168 of file OpDefinition.h.
References mlir::Identifier::get().
setAttrs() [1/2]
void mlir::OpState::setAttrs (ArrayRef< NamedAttribute > attributes) inline
Set the attributes held by this operation.
Definition at line 173 of file OpDefinition.h.
Referenced by mlir::detail::Parser::parseToken().
setAttrs() [2/2]
void mlir::OpState::setAttrs (MutableDictionaryAttr newAttrs) inline
Definition at line 176 of file OpDefinition.h.
setDialectAttrs()
template<typename DialectAttrs > void mlir::OpState::setDialectAttrs (DialectAttrs && attrs) inline
Set the dialect attributes for this operation, and preserve all dependent.
Definition at line 179 of file OpDefinition.h.
setLoc()
void mlir::OpState::setLoc (Location loc) inline
Definition at line 139 of file OpDefinition.h.
Referenced by mlir::detail::Parser::parseToken().
use_empty()
bool mlir::OpState::use_empty () inline
Return true if there are no users of any results of this operation.
Definition at line 193 of file OpDefinition.h.
verify()
LogicalResult mlir::OpState::verify () inline protected
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
Definition at line 232 of file OpDefinition.h.
References print(), and mlir::success().
walk()
template<typename FnT , typename RetT = detail::walkResultType<FnT>> RetT mlir::OpState::walk (FnT && callback) inline
Walk the operation in postorder, calling the callback for each nested operation(including this one).
See Operation::walk for more details.
Definition at line 218 of file OpDefinition.h.
Referenced by applyTilingToLoopPatterns(), mlir::linalg::LinalgDependenceGraph::buildDependenceGraph(), mlir::createMemRefDataFlowOptPass(), mlir::createNormalizeMemRefsPass(), fuseLinalgOpsGreedily(), gatherInnermostLoops(), mlir::linalg::hoistRedundantVectorTransfers(), mlir::linalg::hoistViewAllocOps(), isMemRefNormalizable(), mlir::NestedPattern::match(), mlir::promoteSingleIterationLoops(), serializeModule(), and vectorizeRootMatch().
The documentation for this class was generated from the following files:
include/mlir/IR/OpDefinition.h
lib/IR/Operation.cpp