MLIR: mlir::spirv::StructType Class Reference
mlir::spirv::StructType Class Reference
#include "mlir/Dialect/SPIRV/SPIRVTypes.h"
Classes
class ElementTypeRange
Range class for element types.
struct MemberDecorationInfo
Public Types
using OffsetInfo = uint32_t
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
unsigned getNumElements () const
Type getElementType (unsigned) const
ElementTypeRange getElementTypes () const
bool hasOffset () const
uint64_t getMemberOffset (unsigned) const
void getMemberDecorations (SmallVectorImpl< StructType::MemberDecorationInfo > &memberDecorations) const
void getMemberDecorations (unsigned i, SmallVectorImpl< StructType::MemberDecorationInfo > &decorationsInfo) const
void getExtensions (SPIRVType::ExtensionArrayRefVector &extensions, Optional< spirv::StorageClass > storage=llvm::None)
void getCapabilities (SPIRVType::CapabilityArrayRefVector &capabilities, Optional< spirv::StorageClass > storage=llvm::None)
Static Public Member Functions
static StructType get (ArrayRef< Type > memberTypes, ArrayRef< OffsetInfo > offsetInfo={}, ArrayRef< MemberDecorationInfo > memberDecorations={})
Construct a StructType with at least one member.
static StructType getEmpty (MLIRContext *context)
Construct a struct with no members.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 279 of file SPIRVTypes.h.
Member Typedef Documentation
OffsetInfo
using mlir::spirv::StructType::OffsetInfo = uint32_t
Definition at line 285 of file SPIRVTypes.h.
Member Function Documentation
get()
StructType StructType::get (ArrayRef< Type > memberTypes, ArrayRef< OffsetInfo > offsetInfo = {}, ArrayRef< MemberDecorationInfo > memberDecorations = {}) static
Construct a StructType with at least one member.
Definition at line 879 of file SPIRVTypes.cpp.
References mlir::spirv::TypeKind::Struct.
Referenced by convertMemrefType(), createGlobalVarForEntryPointArgument(), mlir::VulkanLayoutUtils::decorateType(), isFnEntryBlock(), and parseStructType().
getCapabilities()
void StructType::getCapabilities (SPIRVType::CapabilityArrayRefVector & capabilities, Optional< spirv::StorageClass > storage = llvm::None)
Definition at line 947 of file SPIRVTypes.cpp.
getElementType()
Type StructType::getElementType (unsigned index) const
Definition at line 899 of file SPIRVTypes.cpp.
Referenced by mlir::VulkanLayoutUtils::decorateType(), mlir::spirv::CompositeType::getElementType(), and print().
getElementTypes()
StructType::ElementTypeRange StructType::getElementTypes () const
Definition at line 904 of file SPIRVTypes.cpp.
Referenced by convertStructTypePacked().
getEmpty()
StructType StructType::getEmpty (MLIRContext * context) static
Construct a struct with no members.
Definition at line 891 of file SPIRVTypes.cpp.
References mlir::spirv::TypeKind::Struct.
Referenced by isFnEntryBlock(), and parseStructType().
getExtensions()
void StructType::getExtensions (SPIRVType::ExtensionArrayRefVector & extensions, Optional< spirv::StorageClass > storage = llvm::None)
Definition at line 941 of file SPIRVTypes.cpp.
getMemberDecorations() [1/2]
void StructType::getMemberDecorations (SmallVectorImpl< StructType::MemberDecorationInfo > & memberDecorations) const
Definition at line 915 of file SPIRVTypes.cpp.
Referenced by convertStructType(), mlir::VulkanLayoutUtils::decorateType(), and print().
getMemberDecorations() [2/2]
void StructType::getMemberDecorations (unsigned i, SmallVectorImpl< StructType::MemberDecorationInfo > & decorationsInfo) const
Definition at line 924 of file SPIRVTypes.cpp.
getMemberOffset()
uint64_t StructType::getMemberOffset (unsigned index) const
Definition at line 910 of file SPIRVTypes.cpp.
Referenced by print().
getNumElements()
unsigned StructType::getNumElements () const
Definition at line 897 of file SPIRVTypes.cpp.
Referenced by mlir::VulkanLayoutUtils::decorateType(), mlir::VulkanLayoutUtils::isLegalType(), and print().
hasOffset()
bool StructType::hasOffset () const
Definition at line 908 of file SPIRVTypes.cpp.
Referenced by convertStructType(), mlir::VulkanLayoutUtils::isLegalType(), and print().
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/SPIRVTypes.h
lib/Dialect/SPIRV/SPIRVTypes.cpp