MLIR: mlir::spirv::InterfaceVarABIAttr Class Reference
mlir::spirv::InterfaceVarABIAttr Class Reference
An attribute that specifies the information regarding the interface variable: descriptor set, binding, storage class.
#include "mlir/Dialect/SPIRV/SPIRVAttributes.h"
Public Member Functions
uint32_t getDescriptorSet ()
Returns descriptor set.
uint32_t getBinding ()
Returns binding.
Optional< StorageClass > getStorageClass ()
Returns spirv::StorageClass.
Static Public Member Functions
static InterfaceVarABIAttr get (uint32_t descirptorSet, uint32_t binding, Optional< StorageClass > storageClass, MLIRContext *context)
Gets a InterfaceVarABIAttr.
static InterfaceVarABIAttr get (IntegerAttr descriptorSet, IntegerAttr binding, IntegerAttr storageClass)
static StringRef getKindName ()
Returns the attribute kind's name (without the 'spv.' prefix).
static LogicalResult verifyConstructionInvariants (Location loc, IntegerAttr descriptorSet, IntegerAttr binding, IntegerAttr storageClass)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
An attribute that specifies the information regarding the interface variable: descriptor set, binding, storage class.
Definition at line 46 of file SPIRVAttributes.h.
Member Function Documentation
get() [1/2]
static InterfaceVarABIAttr mlir::spirv::InterfaceVarABIAttr::get (uint32_t descirptorSet, uint32_t binding, Optional< StorageClass > storageClass, MLIRContext * context) static
Gets a InterfaceVarABIAttr.
Referenced by mlir::spirv::getInterfaceVarABIAttrName(), and parseInterfaceVarABIAttr().
get() [2/2]
spirv::InterfaceVarABIAttr spirv::InterfaceVarABIAttr::get (IntegerAttr descriptorSet, IntegerAttr binding, IntegerAttr storageClass) static
Definition at line 119 of file SPIRVAttributes.cpp.
References mlir::spirv::AttrKind::InterfaceVarABI.
getBinding()
uint32_t spirv::InterfaceVarABIAttr::getBinding ()
Returns binding.
Definition at line 131 of file SPIRVAttributes.cpp.
Referenced by createGlobalVarForEntryPointArgument(), and print().
getDescriptorSet()
uint32_t spirv::InterfaceVarABIAttr::getDescriptorSet ()
Returns descriptor set.
Definition at line 135 of file SPIRVAttributes.cpp.
Referenced by createGlobalVarForEntryPointArgument(), and print().
getKindName()
StringRef spirv::InterfaceVarABIAttr::getKindName () static
Returns the attribute kind's name (without the 'spv.' prefix).
Definition at line 127 of file SPIRVAttributes.cpp.
Referenced by parseTargetEnvAttr(), and print().
getStorageClass()
Optional< spirv::StorageClass > spirv::InterfaceVarABIAttr::getStorageClass ()
Returns spirv::StorageClass.
Definition at line 139 of file SPIRVAttributes.cpp.
References mlir::spirv::detail::InterfaceVarABIAttributeStorage::storageClass.
Referenced by createGlobalVarForEntryPointArgument(), and print().
verifyConstructionInvariants()
LogicalResult spirv::InterfaceVarABIAttr::verifyConstructionInvariants (Location loc, IntegerAttr descriptorSet, IntegerAttr binding, IntegerAttr storageClass) static
Definition at line 146 of file SPIRVAttributes.cpp.
References mlir::emitError(), mlir::spirv::VerCapExtAttr::get(), mlir::Builder::getArrayAttr(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getStringAttr(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/SPIRVAttributes.h
lib/Dialect/SPIRV/SPIRVAttributes.cpp