MLIR: mlir::IntegerAttr Class Reference
mlir::IntegerAttr Class Reference
#include "mlir/IR/Attributes.h"
Public Types
using ValueType = APInt
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
APInt getValue () const
int64_t getInt () const
Return the integer value as a 64-bit int.
int64_t getSInt () const
Return the integer value as a signed 64-bit int.
uint64_t getUInt () const
Return the integer value as a unsigned 64-bit int.
Static Public Member Functions
static IntegerAttr get (Type type, int64_t value)
static IntegerAttr get (Type type, const APInt &value)
static LogicalResult verifyConstructionInvariants (Location loc, Type type, int64_t value)
static LogicalResult verifyConstructionInvariants (Location loc, Type type, const APInt &value)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 397 of file Attributes.h.
Member Typedef Documentation
ValueType
using mlir::IntegerAttr::ValueType = APInt
Definition at line 402 of file Attributes.h.
Member Function Documentation
get() [1/2]
IntegerAttr IntegerAttr::get (Type type, int64_t value) static
Definition at line 312 of file Attributes.cpp.
References mlir::Type::cast(), mlir::Type::isIndex(), and mlir::IndexType::kInternalStorageBitWidth.
Referenced by allocBuffer(), mlir::applyCmpPredicate(), mlir::AffineMap::constantFold(), convertPrimitiveValueAttr(), foldMinMaxOp(), mlir::spirv::getDefaultResourceLimits(), mlir::spirv::getElementPtr(), mlir::Builder::getI16IntegerAttr(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getI8IntegerAttr(), mlir::Builder::getIndexAttr(), mlir::Builder::getIntegerAttr(), getLaunchConfigIndex(), getPhiIncomingBlock(), mlir::Builder::getSI32IntegerAttr(), mlir::Builder::getUI32IntegerAttr(), mlir::SparseElementsAttr::getValue(), mlir::edsc::makeGenericLinalgOp(), makeI64ArrayAttr(), makeIntegerAttr(), mlir::DenseElementsAttr::AttributeElementIterator::operator*(), parseConstShapeOp(), mlir::LLVMTypeConverter::promoteOneMemRefDescriptor(), and verify().
get() [2/2]
IntegerAttr IntegerAttr::get (Type type, const APInt & value) static
Definition at line 306 of file Attributes.cpp.
References mlir::BoolAttr::get(), mlir::Type::getContext(), mlir::StandardAttributes::Integer, and mlir::Type::isSignlessInteger().
getInt()
int64_t IntegerAttr::getInt () const
Return the integer value as a 64-bit int.
The attribute must be a signless integer.
Definition at line 323 of file Attributes.cpp.
References mlir::AttributeStorage::getType().
Referenced by convertIntegerAttr(), getNumDynamicEntriesUpToIdx(), getPhiIncomingBlock(), inferStridedSliceOpResultType(), isIdentitySuffix(), mlir::lowerAffineLowerBound(), parseConstShapeOp(), parseExecutionModeOp(), parseListOfOperandsOrIntegers(), parseTupleGetOp(), populateFromInt64AttrArray(), printGroupNonUniformArithmeticOp(), printVariableDecorations(), verify(), and verifySubViewOpPart().
getSInt()
int64_t IntegerAttr::getSInt () const
Return the integer value as a signed 64-bit int.
The attribute must be a signed integer.
Definition at line 330 of file Attributes.cpp.
References mlir::AttributeStorage::getType().
getUInt()
uint64_t IntegerAttr::getUInt () const
Return the integer value as a unsigned 64-bit int.
The attribute must be an unsigned integer.
Definition at line 335 of file Attributes.cpp.
References mlir::AttributeStorage::getType().
getValue()
APInt IntegerAttr::getValue () const
Definition at line 321 of file Attributes.cpp.
Referenced by mlir::applyCmpPredicate(), canonicalizeMapOrSetAndOperands(), mlir::spirv::VerCapExtAttr::cap_iterator::cap_iterator(), convertIntegerAttr(), mlir::LLVM::ModuleTranslation::convertOperation(), getPhiIncomingBlock(), parseAffineForOp(), parseConstShapeOp(), and verify().
verifyConstructionInvariants() [1/2]
LogicalResult IntegerAttr::verifyConstructionInvariants (Location loc, Type type, int64_t value) static
Definition at line 347 of file Attributes.cpp.
References verifyIntegerTypeInvariants().
verifyConstructionInvariants() [2/2]
LogicalResult IntegerAttr::verifyConstructionInvariants (Location loc, Type type, const APInt & value) static
Definition at line 352 of file Attributes.cpp.
References mlir::Type::dyn_cast(), mlir::emitError(), mlir::failed(), mlir::failure(), mlir::success(), and verifyIntegerTypeInvariants().
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp