MLIR: mlir::tblgen::Operator Class Reference
mlir::tblgen::Operator Class Reference
#include "mlir/TableGen/Operator.h"
Classes
struct ArgOrType
struct OperandOrAttribute
struct VariableDecorator
A class used to represent the decorators of an operator variable, i.e.
struct VariableDecoratorIterator
Public Types
using var_decorator_iterator = VariableDecoratorIterator
using var_decorator_range = llvm::iterator_range< VariableDecoratorIterator >
using value_iterator = NamedTypeConstraint *
using value_range = llvm::iterator_range< value_iterator >
using attribute_iterator = const NamedAttribute *
using arg_iterator = const Argument *
using arg_range = llvm::iterator_range< arg_iterator >
using const_region_iterator = const NamedRegion *
using const_successor_iterator = const NamedSuccessor *
using const_trait_iterator = const OpTrait *
Public Member Functions
Operator (const llvm::Record &def)
Operator (const llvm::Record *def)
StringRef getDialectName () const
std::string getOperationName () const
StringRef getCppClassName () const
std::string getQualCppClassName () const
std::string getAdaptorName () const
bool isVariadic () const
bool skipDefaultBuilders () const
value_iterator result_begin ()
value_iterator result_end ()
value_range getResults ()
int getNumResults () const
NamedTypeConstraint & getResult (int index)
const NamedTypeConstraint & getResult (int index) const
TypeConstraint getResultTypeConstraint (int index) const
StringRef getResultName (int index) const
var_decorator_range getResultDecorators (int index) const
unsigned getNumVariableLengthResults () const
attribute_iterator attribute_begin () const
attribute_iterator attribute_end () const
llvm::iterator_range< attribute_iterator > getAttributes () const
int getNumAttributes () const
int getNumNativeAttributes () const
NamedAttribute & getAttribute (int index)
value_iterator operand_begin ()
value_iterator operand_end ()
value_range getOperands ()
int getNumOperands () const
NamedTypeConstraint & getOperand (int index)
const NamedTypeConstraint & getOperand (int index) const
unsigned getNumVariableLengthOperands () const
int getNumArgs () const
arg_iterator arg_begin () const
arg_iterator arg_end () const
arg_range getArgs () const
Argument getArg (int index) const
StringRef getArgName (int index) const
var_decorator_range getArgDecorators (int index) const
const OpTrait * getTrait (llvm::StringRef trait) const
const_region_iterator region_begin () const
const_region_iterator region_end () const
llvm::iterator_range< const_region_iterator > getRegions () const
unsigned getNumRegions () const
const NamedRegion & getRegion (unsigned index) const
unsigned getNumVariadicRegions () const
const_successor_iterator successor_begin () const
const_successor_iterator successor_end () const
llvm::iterator_range< const_successor_iterator > getSuccessors () const
unsigned getNumSuccessors () const
const NamedSuccessor & getSuccessor (unsigned index) const
unsigned getNumVariadicSuccessors () const
const_trait_iterator trait_begin () const
const_trait_iterator trait_end () const
llvm::iterator_range< const_trait_iterator > getTraits () const
ArrayRef< llvm::SMLoc > getLoc () const
bool hasDescription () const
StringRef getDescription () const
bool hasSummary () const
StringRef getSummary () const
bool hasAssemblyFormat () const
StringRef getAssemblyFormat () const
StringRef getExtraClassDeclaration () const
const llvm::Record & getDef () const
const Dialect & getDialect () const
void print (llvm::raw_ostream &os) const
bool allResultTypesKnown () const
ArrayRef< ArgOrType > getSameTypeAsResult (int index) const
OperandOrAttribute getArgToOperandOrAttribute (int index) const
Detailed Description
Definition at line 43 of file Operator.h.
Member Typedef Documentation
arg_iterator
using mlir::tblgen::Operator::arg_iterator = const Argument *
Definition at line 154 of file Operator.h.
arg_range
using mlir::tblgen::Operator::arg_range = llvm::iterator_range<arg_iterator>
Definition at line 155 of file Operator.h.
attribute_iterator
using mlir::tblgen::Operator::attribute_iterator = const NamedAttribute *
Definition at line 126 of file Operator.h.
const_region_iterator
using mlir::tblgen::Operator::const_region_iterator = const NamedRegion *
Definition at line 173 of file Operator.h.
const_successor_iterator
using mlir::tblgen::Operator::const_successor_iterator = const NamedSuccessor *
Definition at line 187 of file Operator.h.
const_trait_iterator
using mlir::tblgen::Operator::const_trait_iterator = const OpTrait *
Definition at line 201 of file Operator.h.
value_iterator
using mlir::tblgen::Operator::value_iterator = NamedTypeConstraint *
Definition at line 92 of file Operator.h.
value_range
using mlir::tblgen::Operator::value_range = llvm::iterator_range<value_iterator>
Definition at line 93 of file Operator.h.
var_decorator_iterator
using mlir::tblgen::Operator::var_decorator_iterator = VariableDecoratorIterator
Definition at line 89 of file Operator.h.
var_decorator_range
using mlir::tblgen::Operator::var_decorator_range = llvm::iterator_range<VariableDecoratorIterator>
Definition at line 90 of file Operator.h.
Constructor & Destructor Documentation
Operator() [1/2]
tblgen::Operator::Operator (const llvm::Record & def) explicit
Definition at line 35 of file Operator.cpp.
Operator() [2/2]
mlir::tblgen::Operator::Operator (const llvm::Record * def) inline explicit
Definition at line 46 of file Operator.h.
Member Function Documentation
allResultTypesKnown()
bool mlir::tblgen::Operator::allResultTypesKnown () const inline
Definition at line 235 of file Operator.h.
Referenced by getSameTypeAsResult().
arg_begin()
tblgen::Operator::arg_iterator tblgen::Operator::arg_begin () const
Definition at line 137 of file Operator.cpp.
Referenced by getArgs().
arg_end()
tblgen::Operator::arg_iterator tblgen::Operator::arg_end () const
Definition at line 141 of file Operator.cpp.
Referenced by getArgs().
attribute_begin()
auto tblgen::Operator::attribute_begin () const
Definition at line 237 of file Operator.cpp.
Referenced by getAttributes().
attribute_end()
auto tblgen::Operator::attribute_end () const
Definition at line 240 of file Operator.cpp.
Referenced by getAttributes().
getAdaptorName()
std::string tblgen::Operator::getAdaptorName () const
Definition at line 62 of file Operator.cpp.
References getCppClassName().
getArg()
auto tblgen::Operator::getArg (int index) const
Definition at line 258 of file Operator.cpp.
Referenced by mlir::tblgen::SymbolInfoMap::bindOpArgument(), mlir::tblgen::SymbolInfoMap::SymbolInfo::getVarDecl(), and isVariadic().
getArgDecorators()
auto tblgen::Operator::getArgDecorators (int index) const
Definition at line 154 of file Operator.cpp.
References getDef().
getArgName()
StringRef tblgen::Operator::getArgName (int index) const
Definition at line 149 of file Operator.cpp.
getArgs()
tblgen::Operator::arg_range tblgen::Operator::getArgs () const
Definition at line 145 of file Operator.cpp.
References arg_begin(), and arg_end().
getArgToOperandOrAttribute()
auto tblgen::Operator::getArgToOperandOrAttribute (int index) const
Definition at line 589 of file Operator.cpp.
getAssemblyFormat()
StringRef tblgen::Operator::getAssemblyFormat () const
Definition at line 568 of file Operator.cpp.
getAttribute()
NamedAttribute& mlir::tblgen::Operator::getAttribute (int index) inline
Definition at line 135 of file Operator.h.
getAttributes()
auto tblgen::Operator::getAttributes () const
Definition at line 243 of file Operator.cpp.
References attribute_begin(), and attribute_end().
getCppClassName()
StringRef tblgen::Operator::getCppClassName () const
Definition at line 68 of file Operator.cpp.
Referenced by getAdaptorName().
getDef()
const llvm::Record & tblgen::Operator::getDef () const
Definition at line 89 of file Operator.cpp.
Referenced by getArgDecorators(), getResultDecorators(), isVariadic(), and mlir::tblgen::Operator::VariableDecoratorIterator::unwrap().
getDescription()
StringRef tblgen::Operator::getDescription () const
Definition at line 551 of file Operator.cpp.
getDialect()
const Dialect& mlir::tblgen::Operator::getDialect () const inline
Definition at line 228 of file Operator.h.
References print().
getDialectName()
StringRef tblgen::Operator::getDialectName () const
Definition at line 66 of file Operator.cpp.
References mlir::tblgen::Dialect::getName().
getExtraClassDeclaration()
StringRef tblgen::Operator::getExtraClassDeclaration () const
Definition at line 82 of file Operator.cpp.
getLoc()
ArrayRef< llvm::SMLoc > tblgen::Operator::getLoc () const
Definition at line 545 of file Operator.cpp.
getNumArgs()
int mlir::tblgen::Operator::getNumArgs () const inline
Definition at line 152 of file Operator.h.
Referenced by mlir::tblgen::Pattern::getLocation().
getNumAttributes()
int mlir::tblgen::Operator::getNumAttributes () const inline
Definition at line 131 of file Operator.h.
getNumNativeAttributes()
int mlir::tblgen::Operator::getNumNativeAttributes () const inline
Definition at line 132 of file Operator.h.
getNumOperands()
int mlir::tblgen::Operator::getNumOperands () const inline
Definition at line 142 of file Operator.h.
getNumRegions()
unsigned tblgen::Operator::getNumRegions () const
Definition at line 190 of file Operator.cpp.
getNumResults()
int tblgen::Operator::getNumResults () const
Definition at line 77 of file Operator.cpp.
Referenced by mlir::tblgen::SymbolInfoMap::getValuePackName(), mlir::tblgen::SymbolInfoMap::SymbolInfo::getVarDecl(), and isVariadic().
getNumSuccessors()
unsigned tblgen::Operator::getNumSuccessors () const
Definition at line 212 of file Operator.cpp.
getNumVariableLengthOperands()
unsigned tblgen::Operator::getNumVariableLengthOperands () const
Definition at line 131 of file Operator.cpp.
References mlir::tblgen::NamedTypeConstraint::constraint, and mlir::tblgen::TypeConstraint::isVariableLength().
getNumVariableLengthResults()
unsigned tblgen::Operator::getNumVariableLengthResults () const
Definition at line 125 of file Operator.cpp.
References mlir::tblgen::NamedTypeConstraint::constraint, and mlir::tblgen::TypeConstraint::isVariableLength().
getNumVariadicRegions()
unsigned tblgen::Operator::getNumVariadicRegions () const
Definition at line 196 of file Operator.cpp.
References mlir::tblgen::NamedRegion::isVariadic().
getNumVariadicSuccessors()
unsigned tblgen::Operator::getNumVariadicSuccessors () const
Definition at line 221 of file Operator.cpp.
References mlir::tblgen::NamedSuccessor::isVariadic().
getOperand() [1/2]
NamedTypeConstraint& mlir::tblgen::Operator::getOperand (int index) inline
Definition at line 143 of file Operator.h.
getOperand() [2/2]
const NamedTypeConstraint& mlir::tblgen::Operator::getOperand (int index) const inline
Definition at line 144 of file Operator.h.
getOperands()
auto tblgen::Operator::getOperands ()
Definition at line 254 of file Operator.cpp.
References operand_begin(), and operand_end().
getOperationName()
std::string tblgen::Operator::getOperationName () const
Definition at line 54 of file Operator.cpp.
References mlir::tblgen::Dialect::getName().
Referenced by mlir::tblgen::Pattern::getLocation(), and print().
getQualCppClassName()
std::string tblgen::Operator::getQualCppClassName () const
Definition at line 70 of file Operator.cpp.
References mlir::tblgen::Dialect::getCppNamespace().
Referenced by mlir::tblgen::SymbolInfoMap::SymbolInfo::getVarDecl().
getRegion()
const tblgen::NamedRegion & tblgen::Operator::getRegion (unsigned index) const
Definition at line 192 of file Operator.cpp.
getRegions()
auto tblgen::Operator::getRegions () const
Definition at line 185 of file Operator.cpp.
References region_begin(), and region_end().
getResult() [1/2]
NamedTypeConstraint& mlir::tblgen::Operator::getResult (int index) inline
Definition at line 110 of file Operator.h.
Referenced by mlir::tblgen::SymbolInfoMap::SymbolInfo::getVarDecl().
getResult() [2/2]
const NamedTypeConstraint& mlir::tblgen::Operator::getResult (int index) const inline
Definition at line 111 of file Operator.h.
getResultDecorators()
auto tblgen::Operator::getResultDecorators (int index) const
Definition at line 116 of file Operator.cpp.
References getDef().
getResultName()
StringRef tblgen::Operator::getResultName (int index) const
Definition at line 111 of file Operator.cpp.
getResults()
auto tblgen::Operator::getResults ()
Definition at line 101 of file Operator.cpp.
References result_begin(), and result_end().
getResultTypeConstraint()
tblgen::TypeConstraint tblgen::Operator::getResultTypeConstraint (int index) const
Definition at line 106 of file Operator.cpp.
Referenced by isVariadic().
getSameTypeAsResult()
auto tblgen::Operator::getSameTypeAsResult (int index) const
Definition at line 539 of file Operator.cpp.
References allResultTypesKnown().
getSuccessor()
const tblgen::NamedSuccessor & tblgen::Operator::getSuccessor (unsigned index) const
Definition at line 217 of file Operator.cpp.
getSuccessors()
auto tblgen::Operator::getSuccessors () const
Definition at line 207 of file Operator.cpp.
References successor_begin(), and successor_end().
getSummary()
StringRef tblgen::Operator::getSummary () const
Definition at line 559 of file Operator.cpp.
getTrait()
const tblgen::OpTrait * tblgen::Operator::getTrait (llvm::StringRef trait) const
Definition at line 163 of file Operator.cpp.
Referenced by isVariadic().
getTraits()
auto tblgen::Operator::getTraits () const
Definition at line 232 of file Operator.cpp.
References trait_begin(), and trait_end().
hasAssemblyFormat()
bool tblgen::Operator::hasAssemblyFormat () const
Definition at line 563 of file Operator.cpp.
hasDescription()
bool tblgen::Operator::hasDescription () const
Definition at line 547 of file Operator.cpp.
hasSummary()
bool tblgen::Operator::hasSummary () const
Definition at line 555 of file Operator.cpp.
isVariadic()
bool tblgen::Operator::isVariadic () const
Definition at line 267 of file Operator.cpp.
References mlir::tblgen::Operator::OperandOrAttribute::Attribute, mlir::tblgen::OpTrait::create(), getArg(), getDef(), getNumResults(), getResultTypeConstraint(), getTrait(), mlir::tblgen::inferTypeOpInterface, mlir::tblgen::NamedTypeConstraint::isVariadic(), mlir::tblgen::Operator::OperandOrAttribute::Operand, print(), and resultIndex().
operand_begin()
auto tblgen::Operator::operand_begin ()
Definition at line 248 of file Operator.cpp.
Referenced by getOperands().
operand_end()
auto tblgen::Operator::operand_end ()
Definition at line 251 of file Operator.cpp.
Referenced by getOperands().
print()
void tblgen::Operator::print (llvm::raw_ostream & os) const
Definition at line 574 of file Operator.cpp.
References getOperationName().
Referenced by isVariadic().
region_begin()
auto tblgen::Operator::region_begin () const
Definition at line 179 of file Operator.cpp.
Referenced by getRegions().
region_end()
auto tblgen::Operator::region_end () const
Definition at line 182 of file Operator.cpp.
Referenced by getRegions().
result_begin()
auto tblgen::Operator::result_begin ()
Definition at line 95 of file Operator.cpp.
Referenced by getResults().
result_end()
auto tblgen::Operator::result_end ()
Definition at line 99 of file Operator.cpp.
Referenced by getResults().
skipDefaultBuilders()
bool tblgen::Operator::skipDefaultBuilders () const
Definition at line 91 of file Operator.cpp.
successor_begin()
auto tblgen::Operator::successor_begin () const
Definition at line 201 of file Operator.cpp.
Referenced by getSuccessors().
successor_end()
auto tblgen::Operator::successor_end () const
Definition at line 204 of file Operator.cpp.
Referenced by getSuccessors().
trait_begin()
auto tblgen::Operator::trait_begin () const
Definition at line 226 of file Operator.cpp.
Referenced by getTraits().
trait_end()
auto tblgen::Operator::trait_end () const
Definition at line 229 of file Operator.cpp.
Referenced by getTraits().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Operator.h
lib/TableGen/Operator.cpp