MLIR: mlir::tblgen::Dialect Class Reference
mlir::tblgen::Dialect Class Reference
#include "mlir/TableGen/Dialect.h"
Public Member Functions
Dialect (const llvm::Record *def)
StringRef getName () const
StringRef getCppNamespace () const
std::string getCppClassName () const
StringRef getSummary () const
StringRef getDescription () const
llvm::Optional< StringRef > getExtraClassDeclaration () const
bool hasConstantMaterializer () const
bool hasOperationAttrVerify () const
Returns if this dialect has an operation attribute verifier.
bool hasRegionArgAttrVerify () const
Returns if this dialect has a region argument attribute verifier.
bool hasRegionResultAttrVerify () const
Returns if this dialect has a region result attribute verifier.
bool operator== (const Dialect &other) const
bool operator< (const Dialect &other) const
operator bool () const
Detailed Description
Definition at line 26 of file Dialect.h.
Constructor & Destructor Documentation
Dialect()
mlir::tblgen::Dialect::Dialect (const llvm::Record * def) inline explicit
Definition at line 28 of file Dialect.h.
References mlir::operator<(), and mlir::operator==().
Member Function Documentation
getCppClassName()
std::string mlir::tblgen::Dialect::getCppClassName () const
Definition at line 27 of file Dialect.cpp.
getCppNamespace()
StringRef mlir::tblgen::Dialect::getCppNamespace () const
Definition at line 23 of file Dialect.cpp.
Referenced by mlir::tblgen::StructAttr::getCppNamespace(), and mlir::tblgen::Operator::getQualCppClassName().
getDescription()
StringRef mlir::tblgen::Dialect::getDescription () const
Definition at line 47 of file Dialect.cpp.
References mlir::tblgen::getAsStringOrEmpty().
getExtraClassDeclaration()
llvm::Optional< StringRef > mlir::tblgen::Dialect::getExtraClassDeclaration () const
Definition at line 51 of file Dialect.cpp.
getName()
StringRef mlir::tblgen::Dialect::getName () const
Definition at line 19 of file Dialect.cpp.
Referenced by mlir::tblgen::Operator::getDialectName(), mlir::tblgen::Operator::getOperationName(), and operator<().
getSummary()
StringRef mlir::tblgen::Dialect::getSummary () const
Definition at line 43 of file Dialect.cpp.
References mlir::tblgen::getAsStringOrEmpty().
hasConstantMaterializer()
bool mlir::tblgen::Dialect::hasConstantMaterializer () const
Definition at line 56 of file Dialect.cpp.
hasOperationAttrVerify()
bool mlir::tblgen::Dialect::hasOperationAttrVerify () const
Returns if this dialect has an operation attribute verifier.
Definition at line 60 of file Dialect.cpp.
hasRegionArgAttrVerify()
bool mlir::tblgen::Dialect::hasRegionArgAttrVerify () const
Returns if this dialect has a region argument attribute verifier.
Definition at line 64 of file Dialect.cpp.
hasRegionResultAttrVerify()
bool mlir::tblgen::Dialect::hasRegionResultAttrVerify () const
Returns if this dialect has a region result attribute verifier.
Definition at line 68 of file Dialect.cpp.
operator bool()
mlir::tblgen::Dialect::operator bool () const inline
Definition at line 69 of file Dialect.h.
operator<()
bool mlir::tblgen::Dialect::operator< (const Dialect & other) const
Definition at line 76 of file Dialect.cpp.
References getName().
operator==()
bool mlir::tblgen::Dialect::operator== (const Dialect & other) const
Definition at line 72 of file Dialect.cpp.
The documentation for this class was generated from the following files:
include/mlir/TableGen/Dialect.h
lib/TableGen/Dialect.cpp