MLIR: mlir::TypeAttr Class Reference
mlir::TypeAttr Class Reference
#include "mlir/IR/Attributes.h"
Public Types
using ValueType = Type
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
Type getValue () const
Static Public Member Functions
static TypeAttr get (Type value)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 584 of file Attributes.h.
Member Typedef Documentation
ValueType
using mlir::TypeAttr::ValueType = Type
Definition at line 588 of file Attributes.h.
Member Function Documentation
get()
TypeAttr TypeAttr::get (Type value) static
Definition at line 441 of file Attributes.cpp.
References mlir::Type::getContext(), and mlir::StandardAttributes::Type.
Referenced by mlir::FuncOp::build(), getAtomicOpScope(), getLinkageAttrName(), isFnEntryBlock(), mlir::detail::Parser::parseAttribute(), parseFuncOp(), mlir::impl::parseFunctionLikeOp(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseLLVMFuncOp(), mlir::detail::Parser::parseOptionalAttribute(), parseShuffleVectorOp(), print(), printGPUFuncOp(), mlir::OpTrait::FunctionLike< ConcreteType >::setType(), and verify().
getValue()
Type TypeAttr::getValue () const
Definition at line 445 of file Attributes.cpp.
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp