MLIR: mlir::OpaqueLoc Class Reference
mlir::OpaqueLoc Class Reference
Represents a location that is external to MLIR.
#include "mlir/IR/Location.h"
Public Member Functions
uintptr_t getUnderlyingLocation () const
Returns a pointer to the corresponding object.
TypeID getUnderlyingTypeID () const
Returns a TypeID that represents the underlying objects c++ type.
Location getFallbackLocation () const
Returns a fallback location.
Static Public Member Functions
template<typename T >
static Location get (T underlyingLocation, MLIRContext *context)
Returns an instance of opaque location which contains a given pointer to an object.
template<typename T >
static Location get (T underlyingLocation, Location fallbackLocation)
Returns an instance of opaque location which contains a given pointer to an object and an additional MLIR location.
template<typename T >
static T getUnderlyingLocation (Location location)
Returns a pointer to some data structure that opaque location stores.
template<typename T >
static T getUnderlyingLocationOrNull (Location location)
Returns a pointer to some data structure that opaque location stores.
template<typename T >
static bool isa (Location location)
Checks whether provided location is opaque location and contains a pointer to an object of particular type.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Represents a location that is external to MLIR.
Contains a pointer to some data structure and an optional location that can be used if the first one is not suitable. Since it contains an external structure, only optional location is used during serialization. The class also provides a number of methods for making type-safe casts between a pointer to an object and opaque location.
Definition at line 203 of file Location.h.
Member Function Documentation
get() [1/2]
template<typename T > static Location mlir::OpaqueLoc::get (T underlyingLocation, MLIRContext * context) inline static
Returns an instance of opaque location which contains a given pointer to an object.
The corresponding MLIR location is set to UnknownLoc.
Definition at line 211 of file Location.h.
References mlir::UnknownLoc::get().
Referenced by mlir::NameLoc::getChildLoc().
get() [2/2]
template<typename T > static Location mlir::OpaqueLoc::get (T underlyingLocation, Location fallbackLocation) inline static
Returns an instance of opaque location which contains a given pointer to an object and an additional MLIR location.
Definition at line 219 of file Location.h.
getFallbackLocation()
Location OpaqueLoc::getFallbackLocation () const
Returns a fallback location.
Definition at line 145 of file Location.cpp.
Referenced by mlir::LLVM::detail::DebugTranslation::translateLoc(), and mlir::AsmState::~AsmState().
getUnderlyingLocation() [1/2]
template<typename T > static T mlir::OpaqueLoc::getUnderlyingLocation (Location location) inline static
Returns a pointer to some data structure that opaque location stores.
Definition at line 225 of file Location.h.
References mlir::Location::cast().
Referenced by getUnderlyingLocationOrNull().
getUnderlyingLocation() [2/2]
uintptr_t OpaqueLoc::getUnderlyingLocation () const
Returns a pointer to the corresponding object.
Definition at line 139 of file Location.cpp.
getUnderlyingLocationOrNull()
template<typename T > static T mlir::OpaqueLoc::getUnderlyingLocationOrNull (Location location) inline static
Returns a pointer to some data structure that opaque location stores.
Returns nullptr if provided location is not opaque location or if it contains a pointer of different type.
Definition at line 235 of file Location.h.
References mlir::Location::cast(), and getUnderlyingLocation().
getUnderlyingTypeID()
TypeID OpaqueLoc::getUnderlyingTypeID () const
Returns a TypeID that represents the underlying objects c++ type.
Definition at line 143 of file Location.cpp.
Referenced by isa().
isa()
template<typename T > static bool mlir::OpaqueLoc::isa (Location location) inline static
Checks whether provided location is opaque location and contains a pointer to an object of particular type.
Definition at line 244 of file Location.h.
References mlir::Location::dyn_cast(), and getUnderlyingTypeID().
The documentation for this class was generated from the following files:
include/mlir/IR/Location.h
lib/IR/Location.cpp