MLIR: mlir::FunctionType Class Reference
mlir::FunctionType Class Reference
Function types map from a list of inputs to a list of results.
#include "mlir/IR/Types.h"
Public Member Functions
unsigned getNumInputs () const
Type getInput (unsigned i) const
ArrayRef< Type > getInputs () const
unsigned getNumResults () const
Type getResult (unsigned i) const
ArrayRef< Type > getResults () const
Static Public Member Functions
static FunctionType get (TypeRange inputs, TypeRange results, MLIRContext *context)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Function types map from a list of inputs to a list of results.
Definition at line 254 of file Types.h.
Member Function Documentation
get()
FunctionType FunctionType::get (TypeRange inputs, TypeRange results, MLIRContext * context) static
Definition at line 34 of file Types.cpp.
Referenced by mlir::FuncOp::clone(), mlir::TypeConverter::convertBlockSignature(), mlir::FuncOp::eraseArguments(), mlir::Builder::getFunctionType(), getLibraryCallSymbolRef(), isFnEntryBlock(), isMemRefNormalizable(), makeFunctionType(), mlir::outlineIfOp(), outlineKernelFuncImpl(), printAllocaOp(), printCallOp(), and verify().
getInput()
Type mlir::FunctionType::getInput (unsigned i) const inline
Definition at line 264 of file Types.h.
Referenced by mlir::FuncOp::clone().
getInputs()
ArrayRef< Type > FunctionType::getInputs () const
Definition at line 41 of file Types.cpp.
Referenced by mlir::TypeConverter::convertBlockSignature(), mlir::LLVMTypeConverter::convertFunctionSignature(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), getPhiIncomingBlock(), mlir::TypeConverter::isSignatureLegal(), parseInvokeOp(), mlir::FuncOp::print(), printGPUFuncOp(), verify(), and wrapExternalFunction().
getNumInputs()
unsigned FunctionType::getNumInputs () const
Definition at line 39 of file Types.cpp.
Referenced by mlir::FuncOp::build(), mlir::FuncOp::clone(), mlir::TypeConverter::convertBlockSignature(), parseGPUFuncOp(), parseInvokeOp(), printGPUFuncOp(), mlir::OpTrait::FunctionLike< ConcreteType >::setType(), and wrapExternalFunction().
getNumResults()
unsigned FunctionType::getNumResults () const
Definition at line 45 of file Types.cpp.
Referenced by mlir::LLVMTypeConverter::convertFunctionSignature(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), getPhiIncomingBlock(), parseInvokeOp(), print(), printGPUFuncOp(), and mlir::OpTrait::FunctionLike< ConcreteType >::setType().
getResult()
Type mlir::FunctionType::getResult (unsigned i) const inline
Definition at line 269 of file Types.h.
Referenced by getPhiIncomingBlock(), parseInvokeOp(), and print().
getResults()
ArrayRef< Type > FunctionType::getResults () const
Definition at line 47 of file Types.cpp.
Referenced by mlir::FuncOp::clone(), mlir::TypeConverter::convertBlockSignature(), mlir::LLVMTypeConverter::convertFunctionSignature(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), isMemRefNormalizable(), mlir::TypeConverter::isSignatureLegal(), parseInvokeOp(), mlir::FuncOp::print(), printDenseElementsAttrImpl(), and printGPUFuncOp().
The documentation for this class was generated from the following files:
include/mlir/IR/Types.h
lib/IR/Types.cpp