MLIR: mlir::ContractionOpLowering Class Reference
mlir::ContractionOpLowering Class Reference
Progressive lowering of ContractionOp.
#include "mlir/Dialect/Vector/VectorTransforms.h"
Public Types
using FilterConstraintType = std::function< LogicalResult(vector::ContractionOp op)>
Public Member Functions
ContractionOpLowering (vector::VectorTransformsOptions vectorTransformsOptions, MLIRContext *context, FilterConstraintType constraint=defaultFilter)
LogicalResult matchAndRewrite (vector::ContractionOp op, PatternRewriter &rewriter) const override
Progressive lowering of ContractionOp.
Public Member Functions inherited from mlir::OpRewritePattern< vector::ContractionOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
virtual void rewrite (vector::ContractionOp op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult match (vector::ContractionOp op) const
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
Static Public Member Functions
static LogicalResult defaultFilter (vector::ContractionOp op)
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a rewrite pattern with a certain benefit that matches any operation type.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a rewrite pattern that may match any operation type.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
This constructor is used for patterns that match against a specific operation type.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag)
This constructor is used when a pattern may match against multiple different types of operations.
Protected Attributes inherited from mlir::RewritePattern
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Detailed Description
Progressive lowering of ContractionOp.
One: x = vector.contract with at least one free/batch dimension is replaced by: a = vector.contract with one less free/batch dimension b = vector.contract with one less free/batch dimension .. x = combine a b .. until a pure contraction is reached (no free/batch dimensions), which is replaced by a dot-product.
This only kicks in when either VectorTransformsOptions is set to Dot or when other contraction patterns fail.
Definition at line 320 of file VectorTransforms.h.
Member Typedef Documentation
FilterConstraintType
using mlir::ContractionOpLowering::FilterConstraintType = std::function<LogicalResult(vector::ContractionOp op)>
Definition at line 324 of file VectorTransforms.h.
Constructor & Destructor Documentation
ContractionOpLowering()
mlir::ContractionOpLowering::ContractionOpLowering (vector::VectorTransformsOptions vectorTransformsOptions, MLIRContext * context, FilterConstraintType constraint = defaultFilter) inline
Definition at line 330 of file VectorTransforms.h.
Member Function Documentation
defaultFilter()
static LogicalResult mlir::ContractionOpLowering::defaultFilter (vector::ContractionOp op) inline static
Definition at line 326 of file VectorTransforms.h.
References mlir::success().
matchAndRewrite()
LogicalResult mlir::ContractionOpLowering::matchAndRewrite (vector::ContractionOp op, PatternRewriter & rewriter) const override virtual
Progressive lowering of ContractionOp.
One: x = vector.contract with at least one free/batch dimension is replaced by: a = vector.contract with one less free/batch dimension b = vector.contract with one less free/batch dimension .. x = combine a b .. until a pure contraction is reached (no free/batch dimensions), which is replaced by a dot-product.
This only kicks in when either VectorTransformsOptions is set to DOT or when other contraction patterns fail.
Reimplemented from mlir::OpRewritePattern< vector::ContractionOp >.
Definition at line 1890 of file VectorTransforms.cpp.
References adjustIter(), adjustMap(), mlir::PatternRewriter::create(), mlir::failed(), mlir::failure(), mlir::Builder::getAffineMapArrayAttr(), mlir::Builder::getArrayAttr(), mlir::getElementTypeOrSelf(), mlir::Value::getLoc(), getResultIndex(), mlir::Builder::getStringAttr(), mlir::Builder::getZeroAttr(), mlir::Type::isa(), mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), mlir::ContractionOpToOuterProductOpLowering::matchAndRewrite(), mlir::ContractionOpToDotLowering::matchAndRewrite(), mlir::PatternRewriter::replaceOp(), reshapeLoad(), reshapeStore(), mlir::succeeded(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Vector/VectorTransforms.h
lib/Dialect/Vector/VectorTransforms.cpp