MLIR: mlir::IntegerSetAttr Class Reference
mlir::IntegerSetAttr Class Reference
#include "mlir/IR/Attributes.h"
Public Types
using ValueType = IntegerSet
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
IntegerSet getValue () const
Static Public Member Functions
static IntegerSetAttr get (IntegerSet value)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 452 of file Attributes.h.
Member Typedef Documentation
ValueType
using mlir::IntegerSetAttr::ValueType = IntegerSet
Definition at line 457 of file Attributes.h.
Member Function Documentation
get()
IntegerSetAttr IntegerSetAttr::get (IntegerSet value) static
Definition at line 381 of file Attributes.cpp.
References mlir::IntegerSet::getConstraint(), mlir::AffineExpr::getContext(), and mlir::StandardAttributes::IntegerSet.
Referenced by mlir::detail::Parser::parseAttribute(), and print().
getValue()
IntegerSet IntegerSetAttr::getValue () const
Definition at line 386 of file Attributes.cpp.
Referenced by parseAffineIfOp().
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp