MLIR: mlir::LLVM::TypeToLLVMIRTranslator Class Reference
mlir::LLVM::TypeToLLVMIRTranslator Class Reference
Utility class to translate MLIR LLVM dialect types to LLVM IR.
#include "mlir/Target/LLVMIR/TypeTranslation.h"
Public Member Functions
TypeToLLVMIRTranslator (llvm::LLVMContext &context)
~TypeToLLVMIRTranslator ()
unsigned getPreferredAlignment (LLVM::LLVMType type, const llvm::DataLayout &layout)
Returns the perferred alignment for the type given the data layout.
llvm::Type * translateType (LLVM::LLVMType type)
Translates the given MLIR LLVM dialect type to LLVM IR.
Detailed Description
Utility class to translate MLIR LLVM dialect types to LLVM IR.
Stores the translation state, in particular any identified structure types that can be reused in further translation.
Definition at line 41 of file TypeTranslation.h.
Constructor & Destructor Documentation
TypeToLLVMIRTranslator()
LLVM::TypeToLLVMIRTranslator::TypeToLLVMIRTranslator (llvm::LLVMContext & context)
Definition at line 170 of file TypeTranslation.cpp.
~TypeToLLVMIRTranslator()
LLVM::TypeToLLVMIRTranslator::~TypeToLLVMIRTranslator ()
Definition at line 173 of file TypeTranslation.cpp.
Member Function Documentation
getPreferredAlignment()
unsigned LLVM::TypeToLLVMIRTranslator::getPreferredAlignment (LLVM::LLVMType type, const llvm::DataLayout & layout)
Returns the perferred alignment for the type given the data layout.
Note that this will perform type conversion and store its results for future uses.
Definition at line 179 of file TypeTranslation.cpp.
References translateType().
Referenced by getMemRefAlignment().
translateType()
llvm::Type * LLVM::TypeToLLVMIRTranslator::translateType (LLVM::LLVMType type)
Translates the given MLIR LLVM dialect type to LLVM IR.
Definition at line 175 of file TypeTranslation.cpp.
Referenced by mlir::LLVM::ModuleTranslation::convertType(), getPreferredAlignment(), and mlir::LLVM::detail::TypeFromLLVMIRTranslatorImpl::translateType().
The documentation for this class was generated from the following files:
include/mlir/Target/LLVMIR/TypeTranslation.h
lib/Target/LLVMIR/TypeTranslation.cpp