MLIR: mlir::ContractionOpToMatmulOpLowering Class Reference
mlir::ContractionOpToMatmulOpLowering Class Reference
Progressive lowering of a vector.contract a, b, c with row-major matmul semantics to:
%flattened_a = vector.shape_cast %a
%flattened_b = vector.shape_cast %b
%flattened_d = vector.matmul %flattened_a, %flattened_b
%d = vector.shape_cast %%flattened_d
%e = add %c, %d
vector.matmul later lowers to llvm.matrix.multiply.
#include "mlir/Dialect/Vector/VectorTransforms.h"
Public Types
using FilterConstraintType = std::function< LogicalResult(vector::ContractionOp op)>
Public Member Functions
ContractionOpToMatmulOpLowering (vector::VectorTransformsOptions vectorTransformsOptions, MLIRContext *context, FilterConstraintType constraint=defaultFilter)
LogicalResult matchAndRewrite (vector::ContractionOp op, PatternRewriter &rewriter) const override
Progressively lower a vector.contract a, b, c with row-major matmul semantics to:
%flattened_a = vector.shape_cast %a
%flattened_b = vector.shape_cast %b
%flattened_d = vector.matmul %flattened_a, %flattened_b
%d = vector.shape_cast %%flattened_d
%e = add %c, %d
vector.matmul later lowers to llvm.matrix.multiply.
Public Member Functions inherited from mlir::OpRewritePattern< vector::ContractionOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
virtual void rewrite (vector::ContractionOp op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult match (vector::ContractionOp op) const
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
Static Public Member Functions
static LogicalResult defaultFilter (vector::ContractionOp op)
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a rewrite pattern with a certain benefit that matches any operation type.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a rewrite pattern that may match any operation type.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
This constructor is used for patterns that match against a specific operation type.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag)
This constructor is used when a pattern may match against multiple different types of operations.
Protected Attributes inherited from mlir::RewritePattern
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Detailed Description
Progressive lowering of a vector.contract a, b, c with row-major matmul semantics to:
%flattened_a = vector.shape_cast %a
%flattened_b = vector.shape_cast %b
%flattened_d = vector.matmul %flattened_a, %flattened_b
%d = vector.shape_cast %%flattened_d
%e = add %c, %d
vector.matmul later lowers to llvm.matrix.multiply.
This only kicks in when VectorTransformsOptions is set to OuterProduct and the vector.contract op is a row-major matrix multiply.
Definition at line 194 of file VectorTransforms.h.
Member Typedef Documentation
FilterConstraintType
using mlir::ContractionOpToMatmulOpLowering::FilterConstraintType = std::function<LogicalResult(vector::ContractionOp op)>
Definition at line 199 of file VectorTransforms.h.
Constructor & Destructor Documentation
ContractionOpToMatmulOpLowering()
mlir::ContractionOpToMatmulOpLowering::ContractionOpToMatmulOpLowering (vector::VectorTransformsOptions vectorTransformsOptions, MLIRContext * context, FilterConstraintType constraint = defaultFilter) inline
Definition at line 205 of file VectorTransforms.h.
Member Function Documentation
defaultFilter()
static LogicalResult mlir::ContractionOpToMatmulOpLowering::defaultFilter (vector::ContractionOp op) inline static
Definition at line 201 of file VectorTransforms.h.
References mlir::success().
matchAndRewrite()
LogicalResult mlir::ContractionOpToMatmulOpLowering::matchAndRewrite (vector::ContractionOp op, PatternRewriter & rewriter) const override virtual
Progressively lower a vector.contract a, b, c with row-major matmul semantics to:
%flattened_a = vector.shape_cast %a
%flattened_b = vector.shape_cast %b
%flattened_d = vector.matmul %flattened_a, %flattened_b
%d = vector.shape_cast %%flattened_d
%e = add %c, %d
vector.matmul later lowers to llvm.matrix.multiply.
This only kicks in when VectorTransformsOptions is set to OuterProduct and the vector.contract op is a row-major matrix multiply.
Reimplemented from mlir::OpRewritePattern< vector::ContractionOp >.
Definition at line 1579 of file VectorTransforms.cpp.
References mlir::PatternRewriter::create(), mlir::failed(), mlir::failure(), mlir::VectorType::get(), mlir::Type::isa(), mlir::Type::isIntOrFloat(), mlir::isParallelIterator(), mlir::isReductionIterator(), mlir::isRowMajorMatmul(), mlir::vector::Matmul, mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
Referenced by mlir::ContractionOpLowering::matchAndRewrite().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Vector/VectorTransforms.h
lib/Dialect/Vector/VectorTransforms.cpp