MLIR: mlir::ConversionPattern Class Reference
mlir::ConversionPattern Class Reference
Base class for the conversion patterns.
#include "mlir/Transforms/DialectConversion.h"
Public Member Functions
virtual void rewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement rewriting.
virtual LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement combined matching and rewriting.
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
Public Member Functions inherited from mlir::RewritePattern
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
LogicalResult match (Operation *op) const override
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
Protected Member Functions
ConversionPattern (StringRef rootName, PatternBenefit benefit, TypeConverter &typeConverter, MLIRContext *ctx)
Construct a conversion pattern that matches an operation with the given root name.
ConversionPattern (PatternBenefit benefit, TypeConverter &typeConverter, MatchAnyOpTypeTag tag)
Construct a conversion pattern that matches any operation type.
Protected Member Functions inherited from mlir::RewritePattern
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a rewrite pattern with a certain benefit that matches any operation type.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a rewrite pattern that may match any operation type.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
This constructor is used for patterns that match against a specific operation type.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag)
This constructor is used when a pattern may match against multiple different types of operations.
Protected Attributes
TypeConverter * typeConverter = nullptr
An optional type converter for use by this pattern.
Protected Attributes inherited from mlir::RewritePattern
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Detailed Description
Base class for the conversion patterns.
This pattern class enables type conversions, and other uses specific to the conversion framework. As such, patterns of this type can only be used with the 'apply*' methods below.
Definition at line 316 of file DialectConversion.h.
Constructor & Destructor Documentation
ConversionPattern() [1/2]
mlir::ConversionPattern::ConversionPattern (StringRef rootName, PatternBenefit benefit, TypeConverter & typeConverter, MLIRContext * ctx) inline protected
Construct a conversion pattern that matches an operation with the given root name.
This constructor allows for providing a type converter to use within the pattern.
Definition at line 353 of file DialectConversion.h.
ConversionPattern() [2/2]
mlir::ConversionPattern::ConversionPattern (PatternBenefit benefit, TypeConverter & typeConverter, MatchAnyOpTypeTag tag) inline protected
Construct a conversion pattern that matches any operation type.
This constructor allows for providing a type converter to use within the pattern. MatchAnyOpTypeTag is just a tag to ensure that the "match any" behavior is what the user actually desired, MatchAnyOpTypeTag() should always be supplied here.
Definition at line 361 of file DialectConversion.h.
Member Function Documentation
getTypeConverter()
TypeConverter* mlir::ConversionPattern::getTypeConverter () const inline
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
Definition at line 344 of file DialectConversion.h.
References mlir::RewritePattern::RewritePattern().
matchAndRewrite() [1/2]
virtual LogicalResult mlir::ConversionPattern::matchAndRewrite (Operation * op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline virtual
Hook for derived classes to implement combined matching and rewriting.
Reimplemented in mlir::VectorConvertToLLVMPattern< SourceOp, TargetOp >, mlir::OneToOneConvertToLLVMPattern< SourceOp, TargetOp >, mlir::OpConversionPattern< SourceOp >, mlir::OpConversionPattern< FuncOp >, mlir::OpConversionPattern< CallOp >, mlir::OpConversionPattern< SPIRVOp >, mlir::OpConversionPattern< ReturnOpSourceTy >, mlir::GPUReturnOpLowering, mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >, mlir::OpToFuncCallLowering< SourceOp >, and mlir::GPUFuncOpLowering< AllocaAddrSpace >.
Definition at line 330 of file DialectConversion.h.
References mlir::failed(), mlir::failure(), and mlir::success().
Referenced by mlir::OpConversionPattern< ReturnOpSourceTy >::matchAndRewrite().
matchAndRewrite() [2/2]
LogicalResult ConversionPattern::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const final virtual
Attempt to match and rewrite the IR root at the specified operation.
Reimplemented from mlir::RewritePattern.
Definition at line 1428 of file DialectConversion.cpp.
References mlir::detail::ConversionPatternRewriterImpl::argConverter, mlir::detail::ConversionPatternRewriterImpl::blockActions, mlir::detail::ConversionPatternRewriterImpl::convertBlockSignature(), mlir::detail::ConversionPatternRewriterImpl::createdOps, mlir::failed(), mlir::failure(), mlir::detail::ConversionPatternRewriterImpl::getCurrentState(), mlir::RewritePattern::getGeneratedOps(), mlir::ConversionPatternRewriter::getImpl(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::Block::getNumArguments(), mlir::Operation::getNumRegions(), mlir::Operation::getOperands(), mlir::Block::getParentOp(), mlir::Pattern::getRootKind(), mlir::RewritePattern::hasBoundedRewriteRecursion(), mlir::PatternBenefit::impossibleToMatch(), mlir::OpBuilder::insert(), mlir::detail::ConversionPatternRewriterImpl::isOpIgnored(), logFailure(), mlir::detail::ConversionPatternRewriterImpl::logger, logSuccess(), mlir::detail::ConversionPatternRewriterImpl::markNestedOpsIgnored(), mlir::Operation::print(), mlir::OpPrintingFlags::printGenericOpForm(), mlir::ConversionPatternRewriter::replaceOp(), mlir::detail::ConversionPatternRewriterImpl::rootUpdates, mlir::OpBuilder::setInsertionPoint(), mlir::succeeded(), mlir::success(), and mlir::OpBuilder::tryFold().
rewrite()
virtual void mlir::ConversionPattern::rewrite (Operation * op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline virtual
Hook for derived classes to implement rewriting.
op is the (first) operation matched by the pattern, operands is a list of the rewritten operand values that are passed to op, rewriter can be used to emit the new operations. This function should not fail. If some specific cases of the operation are not supported, these cases should not be matched.
Reimplemented in mlir::OpConversionPattern< SourceOp >, mlir::OpConversionPattern< FuncOp >, mlir::OpConversionPattern< CallOp >, mlir::OpConversionPattern< SPIRVOp >, and mlir::OpConversionPattern< ReturnOpSourceTy >.
Definition at line 323 of file DialectConversion.h.
Member Data Documentation
typeConverter
TypeConverter* mlir::ConversionPattern::typeConverter = nullptr protected
An optional type converter for use by this pattern.
Definition at line 367 of file DialectConversion.h.
The documentation for this class was generated from the following files:
include/mlir/Transforms/DialectConversion.h
lib/Transforms/DialectConversion.cpp