MLIR: mlir::LLVM::LLVMFunctionType Class Reference
mlir::LLVM::LLVMFunctionType Class Reference
LLVM dialect function type.
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
Public Member Functions
LLVMType getReturnType ()
Returns the result type of the function.
unsigned getNumParams ()
Returns the number of arguments to the function.
LLVMType getParamType (unsigned i)
Returns i-th argument of the function. Asserts on out-of-bounds.
bool isVarArg ()
Returns whether the function is variadic.
ArrayRef< LLVMType > getParams ()
Returns a list of argument types of the function.
ArrayRef< LLVMType > params ()
Static Public Member Functions
static LLVMFunctionType get (LLVMType result, ArrayRef< LLVMType > arguments, bool isVarArg=false)
Gets or creates an instance of LLVM dialect function in the same context as the result type.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
LLVM dialect function type.
It consists of a single return type (unlike MLIR which can have multiple), a list of parameter types and can optionally be variadic.
Definition at line 308 of file LLVMTypes.h.
Member Function Documentation
get()
LLVMFunctionType LLVMFunctionType::get (LLVMType result, ArrayRef< LLVMType > arguments, bool isVarArg = false) static
Gets or creates an instance of LLVM dialect function in the same context as the result type.
Definition at line 243 of file LLVMTypes.cpp.
References mlir::LLVM::LLVMType::FunctionType, and mlir::Type::getContext().
Referenced by mlir::LLVM::LLVMType::getFunctionTy(), and mlir::LLVM::detail::TypeFromLLVMIRTranslatorImpl::translateType().
getNumParams()
unsigned LLVMFunctionType::getNumParams ()
Returns the number of arguments to the function.
Definition at line 255 of file LLVMTypes.cpp.
getParams()
ArrayRef< LLVMType > LLVMFunctionType::getParams ()
Returns a list of argument types of the function.
Definition at line 265 of file LLVMTypes.cpp.
Referenced by mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType().
getParamType()
LLVMType LLVMFunctionType::getParamType (unsigned i)
Returns i-th argument of the function. Asserts on out-of-bounds.
Definition at line 259 of file LLVMTypes.cpp.
getReturnType()
LLVMType LLVMFunctionType::getReturnType ()
Returns the result type of the function.
Definition at line 251 of file LLVMTypes.cpp.
Referenced by mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType().
isVarArg()
bool LLVMFunctionType::isVarArg ()
Returns whether the function is variadic.
Definition at line 263 of file LLVMTypes.cpp.
Referenced by mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType().
params()
ArrayRef<LLVMType> mlir::LLVM::LLVMFunctionType::params () inline
Definition at line 334 of file LLVMTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/LLVMIR/LLVMTypes.h
lib/Dialect/LLVMIR/IR/LLVMTypes.cpp