MLIR: mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl Class Reference
mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl Class Reference
Support for translating MLIR LLVM dialect types to LLVM IR.
Public Member Functions
TypeToLLVMIRTranslatorImpl (llvm::LLVMContext &context)
Constructs a class creating types in the given LLVM context.
llvm::Type * translateType (LLVM::LLVMType type)
Translates a single type.
Detailed Description
Support for translating MLIR LLVM dialect types to LLVM IR.
Definition at line 24 of file TypeTranslation.cpp.
Constructor & Destructor Documentation
TypeToLLVMIRTranslatorImpl()
mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::TypeToLLVMIRTranslatorImpl (llvm::LLVMContext & context) inline
Constructs a class creating types in the given LLVM context.
Definition at line 27 of file TypeTranslation.cpp.
Member Function Documentation
translateType()
llvm::Type* mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType (LLVM::LLVMType type) inline
Translates a single type.
Definition at line 30 of file TypeTranslation.cpp.
References mlir::LLVM::LLVMPointerType::getAddressSpace(), mlir::LLVM::LLVMIntegerType::getBitWidth(), mlir::LLVM::LLVMStructType::getBody(), mlir::LLVM::LLVMArrayType::getElementType(), mlir::LLVM::LLVMPointerType::getElementType(), mlir::LLVM::LLVMScalableVectorType::getMinNumElements(), mlir::LLVM::LLVMStructType::getName(), mlir::LLVM::LLVMArrayType::getNumElements(), mlir::LLVM::LLVMFixedVectorType::getNumElements(), mlir::LLVM::LLVMFunctionType::getParams(), mlir::LLVM::LLVMFunctionType::getReturnType(), mlir::LLVM::LLVMStructType::isIdentified(), mlir::LLVM::LLVMStructType::isOpaque(), mlir::LLVM::LLVMStructType::isPacked(), mlir::LLVM::LLVMFunctionType::isVarArg(), and mlir::StandardAttributes::Type.
The documentation for this class was generated from the following file:
lib/Target/LLVMIR/TypeTranslation.cpp