MLIR: mlir::ReductionTreePass< Reducer, mode > Class Template Reference
mlir::ReductionTreePass< Reducer, mode > Class Template Reference
This class defines the Reduction Tree Pass.
#include "mlir/Reducer/ReductionTreePass.h"
Public Member Functions
ReductionTreePass (const Tester *test)
ReductionTreePass (const ReductionTreePass &pass)
void runOnOperation () override
Runs the pass instance in the pass pipeline.
Detailed Description
template<typename Reducer, TraversalMode mode>
class mlir::ReductionTreePass< Reducer, mode >
This class defines the Reduction Tree Pass.
It provides a framework to to implement a reduction pass using a tree structure to keep track of the generated reduced variants.
Definition at line 44 of file ReductionTreePass.h.
Constructor & Destructor Documentation
ReductionTreePass() [1/2]
template<typename Reducer , TraversalMode mode> mlir::ReductionTreePass< Reducer, mode >::ReductionTreePass (const Tester * test) inline
Definition at line 47 of file ReductionTreePass.h.
ReductionTreePass() [2/2]
template<typename Reducer , TraversalMode mode> mlir::ReductionTreePass< Reducer, mode >::ReductionTreePass (const ReductionTreePass< Reducer, mode > & pass) inline
Definition at line 49 of file ReductionTreePass.h.
Member Function Documentation
runOnOperation()
template<typename Reducer , TraversalMode mode> void mlir::ReductionTreePass< Reducer, mode >::runOnOperation () inline override
Runs the pass instance in the pass pipeline.
Definition at line 54 of file ReductionTreePass.h.
References mlir::ReductionNode::getVariant(), mlir::ReductionNode::organizeVariants(), mlir::SinglePath, mlir::ReductionTreeUtils::updateGoldenModule(), and mlir::ReductionNode::variantsEmpty().
The documentation for this class was generated from the following file:
include/mlir/Reducer/ReductionTreePass.h