MLIR: mlir::MutableDictionaryAttr Class Reference
mlir::MutableDictionaryAttr Class Reference
A MutableDictionaryAttr is a mutable wrapper around a DictionaryAttr.
#include "mlir/IR/Attributes.h"
Public Types
enum RemoveResult { RemoveResult::Removed, RemoveResult::NotFound }
Public Member Functions
MutableDictionaryAttr (DictionaryAttr attrs=nullptr)
MutableDictionaryAttr (ArrayRef< NamedAttribute > attributes)
bool operator!= (const MutableDictionaryAttr &other) const
bool operator== (const MutableDictionaryAttr &other) const
DictionaryAttr getDictionary (MLIRContext *context) const
Return the underlying dictionary attribute.
ArrayRef< NamedAttribute > getAttrs () const
Return all of the attributes on this operation.
void setAttrs (ArrayRef< NamedAttribute > attributes)
Replace the held attributes with ones provided in 'newAttrs'.
Attribute get (StringRef name) const
Return the specified attribute if present, null otherwise.
Attribute get (Identifier name) const
Return the specified attribute if present, null otherwise.
Optional< NamedAttribute > getNamed (StringRef name) const
Return the specified named attribute if present, None otherwise.
Optional< NamedAttribute > getNamed (Identifier name) const
void set (Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
RemoveResult remove (Identifier name)
Remove the attribute with the specified name if it exists.
bool empty () const
Friends
::llvm::hash_code hash_value (const MutableDictionaryAttr &arg)
Detailed Description
A MutableDictionaryAttr is a mutable wrapper around a DictionaryAttr.
It provides additional interfaces for adding, removing, replacing attributes within a DictionaryAttr.
We assume there will be relatively few attributes on a given operation (maybe a dozen or so, but not hundreds or thousands) so we use linear searches for everything.
Definition at line 1645 of file Attributes.h.
Member Enumeration Documentation
RemoveResult
enum mlir::MutableDictionaryAttr::RemoveResult strong
Enumerator
Removed
NotFound
Definition at line 1679 of file Attributes.h.
Constructor & Destructor Documentation
MutableDictionaryAttr() [1/2]
mlir::MutableDictionaryAttr::MutableDictionaryAttr (DictionaryAttr attrs = nullptr) inline
Definition at line 1647 of file Attributes.h.
MutableDictionaryAttr() [2/2]
MutableDictionaryAttr::MutableDictionaryAttr (ArrayRef< NamedAttribute > attributes)
Definition at line 1362 of file Attributes.cpp.
Member Function Documentation
empty()
bool mlir::MutableDictionaryAttr::empty () const inline
Definition at line 1685 of file Attributes.h.
References mlir::hash_value().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttrs(), and walkSymbolRefs().
get() [1/2]
Attribute MutableDictionaryAttr::get (StringRef name) const
Return the specified attribute if present, null otherwise.
Definition at line 1390 of file Attributes.cpp.
Referenced by mlir::Operation::getAttr().
get() [2/2]
Attribute MutableDictionaryAttr::get (Identifier name) const
Return the specified attribute if present, null otherwise.
Definition at line 1395 of file Attributes.cpp.
getAttrs()
ArrayRef< NamedAttribute > MutableDictionaryAttr::getAttrs () const
Return all of the attributes on this operation.
Definition at line 1376 of file Attributes.cpp.
Referenced by mlir::Operation::getAttrs(), and mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttrs().
getDictionary()
DictionaryAttr MutableDictionaryAttr::getDictionary (MLIRContext * context) const
Return the underlying dictionary attribute.
Definition at line 1369 of file Attributes.cpp.
References mlir::DictionaryAttr::get().
Referenced by mlir::Operation::getAttrDictionary(), mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttrs(), mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttr(), and mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttrs().
getNamed() [1/2]
Optional< NamedAttribute > MutableDictionaryAttr::getNamed (StringRef name) const
Return the specified named attribute if present, None otherwise.
Definition at line 1400 of file Attributes.cpp.
getNamed() [2/2]
Optional< NamedAttribute > MutableDictionaryAttr::getNamed (Identifier name) const
Definition at line 1404 of file Attributes.cpp.
operator!=()
bool mlir::MutableDictionaryAttr::operator!= (const MutableDictionaryAttr & other) const inline
Definition at line 1651 of file Attributes.h.
operator==()
bool mlir::MutableDictionaryAttr::operator== (const MutableDictionaryAttr & other) const inline
Definition at line 1654 of file Attributes.h.
remove()
auto MutableDictionaryAttr::remove (Identifier name)
Remove the attribute with the specified name if it exists.
The return value indicates whether the attribute was present or not.
Definition at line 1440 of file Attributes.cpp.
References mlir::DictionaryAttr::getWithSorted().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::removeArgAttr(), mlir::Operation::removeAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::removeResultAttr(), and mlir::LLVM::detail::vectorOneToOneRewrite().
set()
void MutableDictionaryAttr::set (Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
Otherwise, add a new attribute with the specified name/value.
Definition at line 1410 of file Attributes.cpp.
References mlir::Attribute::getContext(), and mlir::DictionaryAttr::getWithSorted().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttr(), mlir::Operation::setAttr(), and mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttr().
setAttrs()
void MutableDictionaryAttr::setAttrs (ArrayRef< NamedAttribute > attributes)
Replace the held attributes with ones provided in 'newAttrs'.
Definition at line 1381 of file Attributes.cpp.
References mlir::DictionaryAttr::get().
Friends And Related Function Documentation
hash_value
::llvm::hash_code hash_value (const MutableDictionaryAttr & arg) friend
Definition at line 1693 of file Attributes.h.
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp