MLIR: mlir::UnknownLoc Class Reference
mlir::UnknownLoc Class Reference
Represents an unknown location.
#include "mlir/IR/Location.h"
Static Public Member Functions
static Location get (MLIRContext *context)
Get an instance of the UnknownLoc.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Represents an unknown location.
This is always a singleton for a given MLIRContext.
Definition at line 188 of file Location.h.
Member Function Documentation
get()
Location UnknownLoc::get (MLIRContext * context) static
Get an instance of the UnknownLoc.
Definition at line 769 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::emptyDictionaryAttr, mlir::MLIRContext::getImpl(), and mlir::MLIRContextImpl::unknownLocAttr.
Referenced by deserializeModule(), diag(), mlir::FusedLoc::get(), mlir::NameLoc::get(), mlir::OpaqueLoc::get(), getLLVMAtomicOrdering(), mlir::Value::getLoc(), mlir::Builder::getUnknownLoc(), isFnEntryBlock(), mlirLocationUnknownGet(), mlir::detail::Parser::parseLocationInstance(), mlir::parseSourceFile(), translateLLVMIRToModule(), and unwrap().
The documentation for this class was generated from the following files:
include/mlir/IR/Location.h
lib/IR/MLIRContext.cpp