MLIR: mlir::edsc::TemplatedIndexedValue< Load, Store > Class Template Reference
mlir::edsc::TemplatedIndexedValue< Load, Store > Class Template Reference
A TemplatedIndexedValue brings an index notation over the template Load and Store parameters.
#include "mlir/EDSC/Builders.h"
Public Member Functions
TemplatedIndexedValue (Value v)
TemplatedIndexedValue (const TemplatedIndexedValue &rhs)=default
TemplatedIndexedValue operator() ()
TemplatedIndexedValue operator() (Value index)
Returns a new TemplatedIndexedValue.
template<typename... Args>
TemplatedIndexedValue operator() (Value index, Args... indices)
TemplatedIndexedValue operator() (ArrayRef< Value > indices)
Store operator= (const TemplatedIndexedValue &rhs)
Emits a store.
Store operator= (Value rhs)
operator Value () const
Emits a load when converting to a Value.
Value getBase () const
Returns the base memref.
MemRefType getMemRefType () const
Returns the underlying memref.
template<typename T >
T getElementalTypeAs () const
Returns the underlying MemRef elemental type cast as T.
Value operator+ (Value e)
Arithmetic operator overloadings.
Value operator- (Value e)
Value operator* (Value e)
Value operator/ (Value e)
Value operator% (Value e)
Value operator^ (Value e)
Value operator+ (TemplatedIndexedValue e)
Value operator- (TemplatedIndexedValue e)
Value operator* (TemplatedIndexedValue e)
Value operator/ (TemplatedIndexedValue e)
Value operator% (TemplatedIndexedValue e)
Value operator^ (TemplatedIndexedValue e)
Store operator+= (Value e)
Assignment-arithmetic operator overloadings.
Store operator-= (Value e)
Store operator*= (Value e)
Store operator/= (Value e)
Store operator%= (Value e)
Store operator^= (Value e)
Store operator+= (TemplatedIndexedValue e)
Store operator-= (TemplatedIndexedValue e)
Store operator*= (TemplatedIndexedValue e)
Store operator/= (TemplatedIndexedValue e)
Store operator%= (TemplatedIndexedValue e)
Store operator^= (TemplatedIndexedValue e)
Value operator && (Value e)
Logical operator overloadings.
Value operator|| (Value e)
Value operator && (TemplatedIndexedValue e)
Value operator|| (TemplatedIndexedValue e)
Value eq (Value e)
Comparison operator overloadings.
Value ne (Value e)
Value slt (Value e)
Value sle (Value e)
Value sgt (Value e)
Value sge (Value e)
Value ult (Value e)
Value ule (Value e)
Value ugt (Value e)
Value uge (Value e)
Value slt (TemplatedIndexedValue e)
Value sle (TemplatedIndexedValue e)
Value sgt (TemplatedIndexedValue e)
Value sge (TemplatedIndexedValue e)
Value ult (TemplatedIndexedValue e)
Value ule (TemplatedIndexedValue e)
Value ugt (TemplatedIndexedValue e)
Value uge (TemplatedIndexedValue e)
Detailed Description
template<typename Load, typename Store>
class mlir::edsc::TemplatedIndexedValue< Load, Store >
A TemplatedIndexedValue brings an index notation over the template Load and Store parameters.
Assigning to an IndexedValue emits an actual Store operation, while converting an IndexedValue to a Value emits an actual Load operation.
Definition at line 176 of file Builders.h.
Constructor & Destructor Documentation
TemplatedIndexedValue() [1/2]
template<typename Load , typename Store > mlir::edsc::TemplatedIndexedValue< Load, Store >::TemplatedIndexedValue (Value v) inline explicit
Definition at line 178 of file Builders.h.
TemplatedIndexedValue() [2/2]
template<typename Load , typename Store > mlir::edsc::TemplatedIndexedValue< Load, Store >::TemplatedIndexedValue (const TemplatedIndexedValue< Load, Store > & rhs) default
Member Function Documentation
eq()
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::eq (Value e)
Comparison operator overloadings.
Definition at line 158 of file Builders.h.
References mlir::edsc::op::eq().
getBase()
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::getBase () const inline
Returns the base memref.
Definition at line 207 of file Builders.h.
getElementalTypeAs()
template<typename Load , typename Store > template<typename T > T mlir::edsc::TemplatedIndexedValue< Load, Store >::getElementalTypeAs () const inline
Returns the underlying MemRef elemental type cast as T.
Definition at line 216 of file Builders.h.
References getElementType(), mlir::edsc::op::operator%(), mlir::operator*(), mlir::operator+(), mlir::operator-(), mlir::edsc::op::operator/(), and mlir::edsc::op::operator^().
getMemRefType()
template<typename Load , typename Store > MemRefType mlir::edsc::TemplatedIndexedValue< Load, Store >::getMemRefType () const inline
Returns the underlying memref.
Definition at line 210 of file Builders.h.
ne()
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::ne (Value e)
Definition at line 162 of file Builders.h.
References mlir::edsc::op::ne().
operator &&() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator&& (Value e)
Logical operator overloadings.
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^=().
operator &&() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator&& (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 278 of file Builders.h.
operator Value()
template<typename Load , typename Store > mlir::edsc::TemplatedIndexedValue< Load, Store >::operator Value () const inline
Emits a load when converting to a Value.
Definition at line 204 of file Builders.h.
operator%() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator% (Value e)
Definition at line 102 of file Builders.h.
operator%() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator% (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 242 of file Builders.h.
operator%=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator%= (Value e)
Definition at line 134 of file Builders.h.
References getBase().
operator%=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator%= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 268 of file Builders.h.
operator()() [1/4]
template<typename Load , typename Store > TemplatedIndexedValue mlir::edsc::TemplatedIndexedValue< Load, Store >::operator() () inline
Definition at line 182 of file Builders.h.
operator()() [2/4]
template<typename Load , typename Store > TemplatedIndexedValue mlir::edsc::TemplatedIndexedValue< Load, Store >::operator() (Value index) inline
Returns a new TemplatedIndexedValue.
Definition at line 184 of file Builders.h.
operator()() [3/4]
template<typename Load , typename Store > template<typename... Args> TemplatedIndexedValue mlir::edsc::TemplatedIndexedValue< Load, Store >::operator() (Value index, Args... indices) inline
Definition at line 190 of file Builders.h.
operator()() [4/4]
template<typename Load , typename Store > TemplatedIndexedValue mlir::edsc::TemplatedIndexedValue< Load, Store >::operator() (ArrayRef< Value > indices) inline
Definition at line 193 of file Builders.h.
operator*() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator* (Value e)
Definition at line 92 of file Builders.h.
operator*() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator* (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 236 of file Builders.h.
operator*=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator*= (Value e)
Definition at line 124 of file Builders.h.
References getBase().
operator*=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator*= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 262 of file Builders.h.
operator+() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator+ (Value e)
Arithmetic operator overloadings.
Definition at line 82 of file Builders.h.
operator+() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator+ (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 230 of file Builders.h.
operator+=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator+= (Value e)
Assignment-arithmetic operator overloadings.
Definition at line 114 of file Builders.h.
References getBase().
operator+=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator+= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 256 of file Builders.h.
operator-() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator- (Value e)
Definition at line 87 of file Builders.h.
operator-() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator- (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 233 of file Builders.h.
operator-=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator-= (Value e)
Definition at line 119 of file Builders.h.
References getBase().
operator-=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator-= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 259 of file Builders.h.
operator/() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator/ (Value e)
Definition at line 97 of file Builders.h.
operator/() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator/ (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 239 of file Builders.h.
operator/=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator/= (Value e)
Definition at line 129 of file Builders.h.
References getBase().
operator/=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator/= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 265 of file Builders.h.
operator=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator= (const TemplatedIndexedValue< Load, Store > & rhs) inline
Emits a store.
Definition at line 198 of file Builders.h.
operator=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator= (Value rhs) inline
Definition at line 201 of file Builders.h.
operator^() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^ (Value e)
Definition at line 107 of file Builders.h.
operator^() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^ (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 245 of file Builders.h.
operator^=() [1/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^= (Value e)
Definition at line 139 of file Builders.h.
References getBase(), and mlir::edsc::TemplatedIndexedValue< Load, Store >::operator &&().
operator^=() [2/2]
template<typename Load , typename Store > Store mlir::edsc::TemplatedIndexedValue< Load, Store >::operator^= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 271 of file Builders.h.
References mlir::edsc::op::operator &&(), and mlir::edsc::op::operator||().
operator||() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator|| (Value e)
Definition at line 151 of file Builders.h.
operator||() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator|| (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 281 of file Builders.h.
References mlir::edsc::op::eq(), mlir::edsc::op::ne(), mlir::edsc::op::sge(), mlir::edsc::op::sgt(), mlir::edsc::op::sle(), mlir::edsc::op::slt(), mlir::edsc::op::uge(), mlir::edsc::op::ugt(), mlir::edsc::op::ule(), and mlir::edsc::op::ult().
sge() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::sge (Value e)
Definition at line 181 of file Builders.h.
References mlir::edsc::op::sge().
sge() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::sge (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 305 of file Builders.h.
References mlir::edsc::op::sge().
sgt() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::sgt (Value e)
Definition at line 176 of file Builders.h.
References mlir::edsc::op::sgt().
sgt() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::sgt (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 302 of file Builders.h.
References mlir::edsc::op::sgt().
sle() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::sle (Value e)
Definition at line 171 of file Builders.h.
References mlir::edsc::op::sle().
sle() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::sle (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 299 of file Builders.h.
References mlir::edsc::op::sle().
slt() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::slt (Value e)
Definition at line 166 of file Builders.h.
References mlir::edsc::op::slt().
slt() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::slt (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 296 of file Builders.h.
References mlir::edsc::op::slt().
uge() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::uge (Value e)
Definition at line 201 of file Builders.h.
References mlir::edsc::op::uge().
uge() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::uge (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 317 of file Builders.h.
References mlir::edsc::op::uge().
ugt() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::ugt (Value e)
Definition at line 196 of file Builders.h.
References mlir::edsc::op::ugt().
ugt() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::ugt (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 314 of file Builders.h.
References mlir::edsc::op::ugt().
ule() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::ule (Value e)
Definition at line 191 of file Builders.h.
References mlir::edsc::op::ule().
ule() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::ule (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 311 of file Builders.h.
References mlir::edsc::op::ule().
ult() [1/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::ult (Value e)
Definition at line 186 of file Builders.h.
References mlir::edsc::op::ult().
ult() [2/2]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::ult (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 308 of file Builders.h.
References mlir::edsc::op::ult().
The documentation for this class was generated from the following file:
include/mlir/EDSC/Builders.h