MLIR: mlir::RankedTensorType Class Reference
mlir::RankedTensorType Class Reference
Ranked tensor types represent multi-dimensional arrays that have a shape with a fixed number of dimensions.
#include "mlir/IR/StandardTypes.h"
Public Member Functions
ArrayRef< int64_t > getShape () const
Static Public Member Functions
static RankedTensorType get (ArrayRef< int64_t > shape, Type elementType)
Get or create a new RankedTensorType of the provided shape and element type.
static RankedTensorType getChecked (ArrayRef< int64_t > shape, Type elementType, Location location)
Get or create a new RankedTensorType of the provided shape and element type declared at the given, potentially unknown, location.
static LogicalResult verifyConstructionInvariants (Location loc, ArrayRef< int64_t > shape, Type elementType)
Verify the construction of a ranked tensor type.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Ranked tensor types represent multi-dimensional arrays that have a shape with a fixed number of dimensions.
Each shape element can be a non-negative integer or unknown (represented by -1).
Definition at line 367 of file StandardTypes.h.
Member Function Documentation
get()
RankedTensorType RankedTensorType::get (ArrayRef< int64_t > shape, Type elementType) static
Get or create a new RankedTensorType of the provided shape and element type.
Assumes the arguments define a well-formed type.
Definition at line 325 of file StandardTypes.cpp.
References mlir::Type::getContext(), and mlir::StandardTypes::RankedTensor.
Referenced by mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castFromStorageType(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), computeTensorReshapeCollapsedType(), mlir::quant::ExpressedToQuantizedConverter::convert(), diag(), getAtomicOpScope(), mlir::OpTrait::util::getBroadcastedType(), mlir::shape::getExtentTensorType(), getI1SameShape(), mlir::Builder::getI32TensorAttr(), mlir::Builder::getI64TensorAttr(), mlir::Builder::getIndexTensorAttr(), getTensorTypeFromMemRefType(), mlir::detail::inferReturnTensorTypes(), mappingHelper(), mlir::detail::Parser::parseSparseElementsAttr(), mlir::detail::Parser::parseTensorType(), replaceUnitExtents(), and verify().
getChecked()
RankedTensorType RankedTensorType::getChecked (ArrayRef< int64_t > shape, Type elementType, Location location) static
Get or create a new RankedTensorType of the provided shape and element type declared at the given, potentially unknown, location.
If the RankedTensorType defined by the arguments would be ill-formed, emit errors and return a nullptr-wrapping type.
Definition at line 331 of file StandardTypes.cpp.
References mlir::StandardTypes::RankedTensor.
getShape()
ArrayRef< int64_t > RankedTensorType::getShape () const
Definition at line 347 of file StandardTypes.cpp.
Referenced by mlir::BufferAssignmentTypeConverter::BufferAssignmentTypeConverter(), mlir::quant::QuantizedType::castFromStorageType(), computeTensorReshapeCollapsedType(), and replaceUnitExtents().
verifyConstructionInvariants()
LogicalResult RankedTensorType::verifyConstructionInvariants (Location loc, ArrayRef< int64_t > shape, Type elementType) static
Verify the construction of a ranked tensor type.
Definition at line 338 of file StandardTypes.cpp.
References checkTensorElementType(), and mlir::emitError().
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/StandardTypes.cpp