MLIR: mlir::ComplexType Class Reference
mlir::ComplexType Class Reference
The 'complex' type represents a complex number with a parameterized element type, which is composed of a real and imaginary value of that element type.
#include "mlir/IR/StandardTypes.h"
Public Member Functions
Type getElementType ()
Static Public Member Functions
static ComplexType get (Type elementType)
Get or create a ComplexType with the provided element type.
static ComplexType getChecked (Type elementType, Location location)
Get or create a ComplexType with the provided element type.
static LogicalResult verifyConstructionInvariants (Location loc, Type elementType)
Verify the construction of an integer type.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
The 'complex' type represents a complex number with a parameterized element type, which is composed of a real and imaginary value of that element type.
The element must be a floating point or integer scalar type.
Definition at line 77 of file StandardTypes.h.
Member Function Documentation
get()
ComplexType ComplexType::get (Type elementType) static
Get or create a ComplexType with the provided element type.
ComplexType.
Definition at line 97 of file StandardTypes.cpp.
References mlir::StandardTypes::Complex, and mlir::Type::getContext().
Referenced by mlir::detail::Parser::parseComplexType().
getChecked()
ComplexType ComplexType::getChecked (Type elementType, Location location) static
Get or create a ComplexType with the provided element type.
This emits and error at the specified location and returns null if the element type isn't supported.
Definition at line 102 of file StandardTypes.cpp.
References mlir::StandardTypes::Complex.
getElementType()
Type ComplexType::getElementType ()
Definition at line 114 of file StandardTypes.cpp.
References mlir::IntegerType::kMaxWidth.
Referenced by mlir::DenseElementsAttr::get().
verifyConstructionInvariants()
LogicalResult ComplexType::verifyConstructionInvariants (Location loc, Type elementType) static
Verify the construction of an integer type.
Definition at line 107 of file StandardTypes.cpp.
References mlir::emitError(), mlir::Type::isIntOrFloat(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/StandardTypes.cpp