MLIR: mlir::LLVM::ModuleTranslation Class Reference
mlir::LLVM::ModuleTranslation Class Reference
Implementation class for module translation.
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
Static Public Member Functions
template<typename T = ModuleTranslation>
static std::unique_ptr< llvm::Module > translateModule (Operation *m, llvm::LLVMContext &llvmContext, StringRef name="LLVMDialectModule")
static Block & getModuleBody (Operation *m)
A helper method to get the single Block in an operation honoring LLVM's module requirements.
Protected Member Functions
ModuleTranslation (Operation *module, std::unique_ptr< llvm::Module > llvmModule)
Translate the given MLIR module expressed in MLIR LLVM IR dialect into an LLVM IR module.
virtual ~ModuleTranslation ()
virtual LogicalResult convertOperation (Operation &op, llvm::IRBuilder<> &builder)
Given a single MLIR operation, create the corresponding LLVM IR operation using the builder.
virtual LogicalResult convertOmpOperation (Operation &op, llvm::IRBuilder<> &builder)
Given an OpenMP MLIR operation, create the corresponding LLVM IR (including OpenMP runtime calls).
virtual LogicalResult convertOmpParallel (Operation &op, llvm::IRBuilder<> &builder)
Convert the OpenMP parallel Operation to LLVM IR.
llvm::Type * convertType (LLVMType type)
Converts the type from MLIR LLVM dialect to LLVM.
SmallVector< llvm::Value *, 8 > lookupValues (ValueRange values)
A helper to look up remapped operands in the value remapping table.
Static Protected Member Functions
static std::unique_ptr< llvm::Module > prepareLLVMModule (Operation *m, llvm::LLVMContext &llvmContext, StringRef name)
Protected Attributes
llvm::StringMap< llvm::Function * > functionMapping
Mappings between original and translated values, used for lookups.
DenseMap< Value, llvm::Value * > valueMapping
DenseMap< Block *, llvm::BasicBlock * > blockMapping
Detailed Description
Implementation class for module translation.
Holds a reference to the module being translated, and the mappings between the original and the translated functions, basic blocks and values. It is practically easier to hold these mappings in one class since the conversion of control flow operations needs to look up block and function mappings.
Definition at line 50 of file ModuleTranslation.h.
Constructor & Destructor Documentation
ModuleTranslation()
ModuleTranslation::ModuleTranslation (Operation * module, std::unique_ptr< llvm::Module > llvmModule) protected
Translate the given MLIR module expressed in MLIR LLVM IR dialect into an LLVM IR module.
The MLIR LLVM IR dialect holds a pointer to an LLVMContext, the LLVM IR module will be created in that context.
Definition at line 300 of file ModuleTranslation.cpp.
References mlir::LLVM::satisfiesLLVMModule().
Referenced by createDeviceFunctionCall(), and getShflBflyIntrinsicId().
~ModuleTranslation()
ModuleTranslation::~ModuleTranslation () protected virtual
Definition at line 311 of file ModuleTranslation.cpp.
Member Function Documentation
convertOmpOperation()
LogicalResult ModuleTranslation::convertOmpOperation (Operation & opInst, llvm::IRBuilder<> & builder) protected virtual
Given an OpenMP MLIR operation, create the corresponding LLVM IR (including OpenMP runtime calls).
Definition at line 477 of file ModuleTranslation.cpp.
References convertOmpParallel(), mlir::Operation::emitError(), mlir::Operation::getName(), and mlir::success().
Referenced by convertOperation().
convertOmpParallel()
LogicalResult ModuleTranslation::convertOmpParallel (Operation & op, llvm::IRBuilder<> & builder) protected virtual
Convert the OpenMP parallel Operation to LLVM IR.
Definition at line 391 of file ModuleTranslation.cpp.
References blockMapping, connectPHINodes(), mlir::detail::enumerate(), mlir::failed(), mlir::Block::isEntryBlock(), mlir::success(), mlir::topologicalSort(), and valueMapping.
Referenced by convertOmpOperation().
convertOperation()
LogicalResult ModuleTranslation::convertOperation (Operation & opInst, llvm::IRBuilder<> & builder) protected virtual
Given a single MLIR operation, create the corresponding LLVM IR operation using the builder.
LLVM IR Builder does not have a generic interface so this has to be a long chain of ifs calling different functions with a different number of arguments.
Definition at line 521 of file ModuleTranslation.cpp.
References blockMapping, mlir::Constant, convertOmpOperation(), convertType(), mlir::emitError(), mlir::Operation::emitError(), mlir::failed(), mlir::failure(), functionMapping, mlir::Operation::getAttrOfType(), mlir::Operation::getDialect(), getModuleBody(), mlir::Operation::getName(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::Operation::getResult(), mlir::IntegerAttr::getValue(), lookupValues(), mlir::success(), mlir::StandardAttributes::Type, and valueMapping.
Referenced by createDeviceFunctionCall(), and getShflBflyIntrinsicId().
convertType()
llvm::Type * ModuleTranslation::convertType (LLVMType type) protected
Converts the type from MLIR LLVM dialect to LLVM.
Definition at line 929 of file ModuleTranslation.cpp.
References mlir::LLVM::TypeToLLVMIRTranslator::translateType().
Referenced by convertOperation(), and forwardPassthroughAttributes().
getModuleBody()
static Block& mlir::LLVM::ModuleTranslation::getModuleBody (Operation * m) inline static
A helper method to get the single Block in an operation honoring LLVM's module requirements.
Definition at line 78 of file ModuleTranslation.h.
References mlir::Constant, mlir::Region::front(), mlir::Operation::getRegion(), and mlir::StandardAttributes::Type.
Referenced by convertOperation(), and forwardPassthroughAttributes().
lookupValues()
SmallVector< llvm::Value *, 8 > ModuleTranslation::lookupValues (ValueRange values) protected
A helper to look up remapped operands in the value remapping table.
A helper to look up remapped operands in the value remapping table.`.
Definition at line 935 of file ModuleTranslation.cpp.
References valueMapping.
Referenced by convertOperation().
prepareLLVMModule()
std::unique_ptr< llvm::Module > ModuleTranslation::prepareLLVMModule (Operation * m, llvm::LLVMContext & llvmContext, StringRef name) static protected
Definition at line 945 of file ModuleTranslation.cpp.
References mlir::Operation::getContext(), and mlir::MLIRContext::getRegisteredDialect().
translateModule()
template<typename T = ModuleTranslation> static std::unique_ptr<llvm::Module> mlir::LLVM::ModuleTranslation::translateModule (Operation * m, llvm::LLVMContext & llvmContext, StringRef name = "LLVMDialectModule") inline static
Definition at line 54 of file ModuleTranslation.h.
References mlir::LLVM::ensureDistinctSuccessors(), mlir::failed(), and mlir::LLVM::satisfiesLLVMModule().
Member Data Documentation
blockMapping
DenseMap<Block *, llvm::BasicBlock *> mlir::LLVM::ModuleTranslation::blockMapping protected
Definition at line 139 of file ModuleTranslation.h.
Referenced by convertOmpParallel(), convertOperation(), and forwardPassthroughAttributes().
functionMapping
llvm::StringMap<llvm::Function *> mlir::LLVM::ModuleTranslation::functionMapping protected
Mappings between original and translated values, used for lookups.
Definition at line 137 of file ModuleTranslation.h.
Referenced by convertOperation(), and forwardPassthroughAttributes().
valueMapping
DenseMap<Value, llvm::Value *> mlir::LLVM::ModuleTranslation::valueMapping protected
Definition at line 138 of file ModuleTranslation.h.
Referenced by convertOmpParallel(), convertOperation(), forwardPassthroughAttributes(), and lookupValues().
The documentation for this class was generated from the following files:
include/mlir/Target/LLVMIR/ModuleTranslation.h
lib/Target/LLVMIR/ModuleTranslation.cpp