MLIR: mlir::tblgen::OpConstructor Class Reference
mlir::tblgen::OpConstructor Class Reference
#include "mlir/TableGen/OpClass.h"
Public Member Functions
OpConstructor (StringRef retType, StringRef name, StringRef params, Property property, bool declOnly)
void addMemberInitializer (StringRef name, StringRef value)
void writeDefTo (raw_ostream &os, StringRef namePrefix) const override
Public Member Functions inherited from mlir::tblgen::OpMethod
OpMethod (StringRef retType, StringRef name, StringRef params, Property property, bool declOnly)
virtual ~OpMethod ()=default
OpMethodBody & body ()
bool isStatic () const
bool isPrivate () const
virtual void writeDeclTo (raw_ostream &os) const
Additional Inherited Members
Public Types inherited from mlir::tblgen::OpMethod
enum Property { MP_None = 0x0, MP_Static = 0x1, MP_Constructor = 0x2, MP_Private = 0x4 }
Protected Attributes inherited from mlir::tblgen::OpMethod
Property properties
bool isDeclOnly
OpMethodSignature methodSignature
OpMethodBody methodBody
Detailed Description
Definition at line 115 of file OpClass.h.
Constructor & Destructor Documentation
OpConstructor()
mlir::tblgen::OpConstructor::OpConstructor (StringRef retType, StringRef name, StringRef params, Property property, bool declOnly) inline
Definition at line 117 of file OpClass.h.
References mlir::tblgen::OpMethodSignature::writeDefTo().
Member Function Documentation
addMemberInitializer()
void mlir::tblgen::OpConstructor::addMemberInitializer (StringRef name, StringRef value)
Definition at line 126 of file OpClass.cpp.
writeDefTo()
void mlir::tblgen::OpConstructor::writeDefTo (raw_ostream & os, StringRef namePrefix) const override virtual
Reimplemented from mlir::tblgen::OpMethod.
Definition at line 132 of file OpClass.cpp.
References mlir::tblgen::OpMethod::isDeclOnly, mlir::tblgen::OpMethod::methodBody, mlir::tblgen::OpMethod::methodSignature, mlir::tblgen::OpMethodSignature::writeDefTo(), and mlir::tblgen::OpMethodBody::writeTo().
The documentation for this class was generated from the following files:
include/mlir/TableGen/OpClass.h
lib/TableGen/OpClass.cpp