MLIR: mlir::detail::PassOptions::ListOption< DataType, OptionParser > Class Template Reference
mlir::detail::PassOptions::ListOption< DataType, OptionParser > Class Template Reference
This class represents a specific pass option that contains a list of values of the provided data type.
#include "mlir/Pass/PassOptions.h"
Public Member Functions
template<typename... Args>
ListOption (PassOptions &parent, StringRef arg, Args &&... args)
~ListOption () override=default
ListOption< DataType, OptionParser > & operator= (const ListOption< DataType, OptionParser > &other)
ListOption< DataType, OptionParser > & operator= (ArrayRef< DataType > values)
Allow assigning from an ArrayRef.
MutableArrayRef< DataType > operator-> () const
Detailed Description
template<typename DataType, typename OptionParser = OptionParser<DataType>>
class mlir::detail::PassOptions::ListOption< DataType, OptionParser >
This class represents a specific pass option that contains a list of values of the provided data type.
Definition at line 154 of file PassOptions.h.
Constructor & Destructor Documentation
ListOption()
template<typename DataType, typename OptionParser = OptionParser<DataType>> template<typename... Args> mlir::detail::PassOptions::ListOption< DataType, OptionParser >::ListOption (PassOptions & parent, StringRef arg, Args &&... args) inline
Definition at line 159 of file PassOptions.h.
~ListOption()
template<typename DataType, typename OptionParser = OptionParser<DataType>> mlir::detail::PassOptions::ListOption< DataType, OptionParser >::~ListOption () override default
Member Function Documentation
operator->()
template<typename DataType, typename OptionParser = OptionParser<DataType>> MutableArrayRef<DataType> mlir::detail::PassOptions::ListOption< DataType, OptionParser >::operator-> () const inline
Definition at line 184 of file PassOptions.h.
References mlir::detail::PassOptions::copyOptionValuesFrom(), mlir::detail::PassOptions::getOptionWidth(), mlir::detail::PassOptions::parseFromString(), mlir::detail::PassOptions::PassOptions(), mlir::detail::PassOptions::print(), and mlir::detail::PassOptions::printHelp().
operator=() [1/2]
template<typename DataType, typename OptionParser = OptionParser<DataType>> ListOption<DataType, OptionParser>& mlir::detail::PassOptions::ListOption< DataType, OptionParser >::operator= (const ListOption< DataType, OptionParser > & other) inline
Definition at line 171 of file PassOptions.h.
operator=() [2/2]
template<typename DataType, typename OptionParser = OptionParser<DataType>> ListOption<DataType, OptionParser>& mlir::detail::PassOptions::ListOption< DataType, OptionParser >::operator= (ArrayRef< DataType > values) inline
Allow assigning from an ArrayRef.
Definition at line 178 of file PassOptions.h.
The documentation for this class was generated from the following file:
include/mlir/Pass/PassOptions.h