MLIR: mlir::ConvertToLLVMPattern Class Reference
mlir::ConvertToLLVMPattern Class Reference
Base class for operation conversions targeting the LLVM IR dialect.
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
Public Member Functions
ConvertToLLVMPattern (StringRef rootOpName, MLIRContext *context, LLVMTypeConverter &typeConverter, PatternBenefit benefit=1)
LLVM::LLVMDialect & getDialect () const
Returns the LLVM dialect.
LLVM::LLVMType getIndexType () const
Gets the MLIR type wrapping the LLVM integer type whose bit width is defined by the used type converter.
LLVM::LLVMType getVoidType () const
Gets the MLIR type wrapping the LLVM void type.
LLVM::LLVMType getVoidPtrType () const
Get the MLIR type wrapping the LLVM i8* type.
Value createIndexConstant (ConversionPatternRewriter &builder, Location loc, uint64_t value) const
Create an LLVM dialect operation defining the given index constant.
Value linearizeSubscripts (ConversionPatternRewriter &builder, Location loc, ArrayRef< Value > indices, ArrayRef< Value > allocSizes) const
Value getStridedElementPtr (Location loc, Type elementTypePtr, Value descriptor, ValueRange indices, ArrayRef< int64_t > strides, int64_t offset, ConversionPatternRewriter &rewriter) const
Value getDataPtr (Location loc, MemRefType type, Value memRefDesc, ValueRange indices, ConversionPatternRewriter &rewriter) const
Type getElementPtrType (MemRefType type) const
Returns the type of a pointer to an element of the memref.
void getMemRefDescriptorSizes (Location loc, MemRefType memRefType, ArrayRef< Value > dynSizes, ConversionPatternRewriter &rewriter, SmallVectorImpl< Value > &sizes) const
Determines sizes to be used in the memref descriptor.
Value getCumulativeSizeInBytes (Location loc, Type elementType, ArrayRef< Value > shape, ConversionPatternRewriter &rewriter) const
Computes total size in bytes of to store the given shape.
Public Member Functions inherited from mlir::ConversionPattern
virtual void rewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement rewriting.
virtual LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement combined matching and rewriting.
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
Public Member Functions inherited from mlir::RewritePattern
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
LogicalResult match (Operation *op) const override
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
Protected Attributes
LLVMTypeConverter & typeConverter
Reference to the type converter, with potential extensions.
Protected Attributes inherited from mlir::ConversionPattern
TypeConverter * typeConverter = nullptr
An optional type converter for use by this pattern.
Protected Attributes inherited from mlir::RewritePattern
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Additional Inherited Members
Protected Member Functions inherited from mlir::ConversionPattern
ConversionPattern (StringRef rootName, PatternBenefit benefit, TypeConverter &typeConverter, MLIRContext *ctx)
Construct a conversion pattern that matches an operation with the given root name.
ConversionPattern (PatternBenefit benefit, TypeConverter &typeConverter, MatchAnyOpTypeTag tag)
Construct a conversion pattern that matches any operation type.
Protected Member Functions inherited from mlir::RewritePattern
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a rewrite pattern with a certain benefit that matches any operation type.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a rewrite pattern that may match any operation type.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
This constructor is used for patterns that match against a specific operation type.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag)
This constructor is used when a pattern may match against multiple different types of operations.
Detailed Description
Base class for operation conversions targeting the LLVM IR dialect.
It provides the conversion patterns with access to the LLVMTypeConverter and the LowerToLLVMOptions. The class captures the LLVMTypeConverter and the LowerToLLVMOptions by reference meaning the references have to remain alive during the entire pattern lifetime.
Definition at line 388 of file ConvertStandardToLLVM.h.
Constructor & Destructor Documentation
ConvertToLLVMPattern()
ConvertToLLVMPattern::ConvertToLLVMPattern (StringRef rootOpName, MLIRContext * context, LLVMTypeConverter & typeConverter, PatternBenefit benefit = 1)
Definition at line 418 of file StandardToLLVM.cpp.
Member Function Documentation
createIndexConstant()
Value ConvertToLLVMPattern::createIndexConstant (ConversionPatternRewriter & builder, Location loc, uint64_t value) const
Create an LLVM dialect operation defining the given index constant.
Definition at line 854 of file StandardToLLVM.cpp.
References createIndexAttrConstant().
getCumulativeSizeInBytes()
Value ConvertToLLVMPattern::getCumulativeSizeInBytes (Location loc, Type elementType, ArrayRef< Value > shape, ConversionPatternRewriter & rewriter) const
Computes total size in bytes of to store the given shape.
Definition at line 930 of file StandardToLLVM.cpp.
References mlir::PatternRewriter::create().
getDataPtr()
Value ConvertToLLVMPattern::getDataPtr (Location loc, MemRefType type, Value memRefDesc, ValueRange indices, ConversionPatternRewriter & rewriter) const
Definition at line 899 of file StandardToLLVM.cpp.
References mlir::MemRefDescriptor::getElementType(), mlir::getStridesAndOffset(), and mlir::succeeded().
getDialect()
LLVM::LLVMDialect & ConvertToLLVMPattern::getDialect () const
Returns the LLVM dialect.
Definition at line 838 of file StandardToLLVM.cpp.
getElementPtrType()
Type ConvertToLLVMPattern::getElementPtrType (MemRefType type) const
Returns the type of a pointer to an element of the memref.
Definition at line 912 of file StandardToLLVM.cpp.
References mlir::MemRefType::getMemorySpace().
getIndexType()
LLVM::LLVMType ConvertToLLVMPattern::getIndexType () const
Gets the MLIR type wrapping the LLVM integer type whose bit width is defined by the used type converter.
Definition at line 842 of file StandardToLLVM.cpp.
getMemRefDescriptorSizes()
void ConvertToLLVMPattern::getMemRefDescriptorSizes (Location loc, MemRefType memRefType, ArrayRef< Value > dynSizes, ConversionPatternRewriter & rewriter, SmallVectorImpl< Value > & sizes) const
Determines sizes to be used in the memref descriptor.
Definition at line 919 of file StandardToLLVM.cpp.
References mlir::MemRefType::getShape(), and mlir::ShapedType::kDynamicSize.
getStridedElementPtr()
Value ConvertToLLVMPattern::getStridedElementPtr (Location loc, Type elementTypePtr, Value descriptor, ValueRange indices, ArrayRef< int64_t > strides, int64_t offset, ConversionPatternRewriter & rewriter) const
Definition at line 876 of file StandardToLLVM.cpp.
References mlir::MemRefDescriptor::alignedPtr(), mlir::PatternRewriter::create(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::MemRefDescriptor::offset(), and mlir::MemRefDescriptor::stride().
getVoidPtrType()
LLVM::LLVMType ConvertToLLVMPattern::getVoidPtrType () const
Get the MLIR type wrapping the LLVM i8* type.
Definition at line 850 of file StandardToLLVM.cpp.
References mlir::LLVM::LLVMType::getInt8PtrTy().
getVoidType()
LLVM::LLVMType ConvertToLLVMPattern::getVoidType () const
Gets the MLIR type wrapping the LLVM void type.
Definition at line 846 of file StandardToLLVM.cpp.
References mlir::LLVM::LLVMType::getVoidTy().
linearizeSubscripts()
Value ConvertToLLVMPattern::linearizeSubscripts (ConversionPatternRewriter & builder, Location loc, ArrayRef< Value > indices, ArrayRef< Value > allocSizes) const
Definition at line 859 of file StandardToLLVM.cpp.
References mlir::PatternRewriter::create().
Member Data Documentation
typeConverter
LLVMTypeConverter& mlir::ConvertToLLVMPattern::typeConverter protected
Reference to the type converter, with potential extensions.
Definition at line 450 of file ConvertStandardToLLVM.h.
Referenced by mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite().
The documentation for this class was generated from the following files:
include/mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h
lib/Conversion/StandardToLLVM/StandardToLLVM.cpp