MLIR: mlir::AbstractAttribute Class Reference
mlir::AbstractAttribute Class Reference
This class contains all of the static information common to all instances of a registered Attribute.
#include "mlir/IR/AttributeSupport.h"
Public Member Functions
Dialect & getDialect () const
Return the dialect this attribute was registered to.
template<typename T >
T::Concept * getInterface () const
Returns an instance of the concept object for the given interface if it was registered to this attribute, null otherwise.
TypeID getTypeID () const
Return the unique identifier representing the concrete attribute class.
Static Public Member Functions
static const AbstractAttribute & lookup (TypeID typeID, MLIRContext *context)
Look up the specified abstract attribute in the MLIRContext and return a reference to it.
template<typename T >
static AbstractAttribute get (Dialect &dialect)
This method is used by Dialect objects when they register the list of attributes they contain.
Detailed Description
This class contains all of the static information common to all instances of a registered Attribute.
Definition at line 30 of file AttributeSupport.h.
Member Function Documentation
get()
template<typename T > static AbstractAttribute mlir::AbstractAttribute::get (Dialect & dialect) inline static
This method is used by Dialect objects when they register the list of attributes they contain.
Definition at line 38 of file AttributeSupport.h.
getDialect()
Dialect& mlir::AbstractAttribute::getDialect () const inline
Return the dialect this attribute was registered to.
Definition at line 43 of file AttributeSupport.h.
getInterface()
template<typename T > T::Concept* mlir::AbstractAttribute::getInterface () const inline
Returns an instance of the concept object for the given interface if it was registered to this attribute, null otherwise.
This should not be used directly.
Definition at line 48 of file AttributeSupport.h.
References mlir::detail::InterfaceMap::lookup().
getTypeID()
TypeID mlir::AbstractAttribute::getTypeID () const inline
Return the unique identifier representing the concrete attribute class.
Definition at line 53 of file AttributeSupport.h.
lookup()
const AbstractAttribute & AbstractAttribute::lookup (TypeID typeID, MLIRContext * context) static
Look up the specified abstract attribute in the MLIRContext and return a reference to it.
Get the dialect that registered the attribute with the provided typeid.
Definition at line 595 of file MLIRContext.cpp.
References mlir::MLIRContext::getImpl().
Referenced by mlir::MLIRContext::getAttributeUniquer().
The documentation for this class was generated from the following files:
include/mlir/IR/AttributeSupport.h
lib/IR/MLIRContext.cpp