MLIR: mlir::NamedAttrList Class Reference
mlir::NamedAttrList Class Reference
NamedAttrList is array of NamedAttributes that tracks whether it is sorted and does some basic work to remain sorted.
#include "mlir/IR/OperationSupport.h"
Public Types
using const_iterator = SmallVectorImpl< NamedAttribute >::const_iterator
using const_reference = const NamedAttribute &
using reference = NamedAttribute &
using size_type = size_t
Public Member Functions
NamedAttrList ()
NamedAttrList (ArrayRef< NamedAttribute > attributes)
NamedAttrList (const_iterator in_start, const_iterator in_end)
bool operator!= (const NamedAttrList &other) const
bool operator== (const NamedAttrList &other) const
void append (StringRef name, Attribute attr)
Add an attribute with the specified name.
void append (Identifier name, Attribute attr)
Add an attribute with the specified name.
void append (ArrayRef< NamedAttribute > newAttributes)
Add an array of named attributes.
void append (const_iterator in_start, const_iterator in_end)
Add a range of named attributes.
void assign (const_iterator in_start, const_iterator in_end)
Replaces the attributes with new list of attributes.
void assign (ArrayRef< NamedAttribute > range)
Replaces the attributes with new list of attributes.
bool empty () const
void reserve (size_type N)
void push_back (NamedAttribute newAttribute)
Add an attribute with the specified name.
void pop_back ()
Pop last element from list.
DictionaryAttr getDictionary (MLIRContext *context) const
Return a dictionary attribute for the underlying dictionary.
ArrayRef< NamedAttribute > getAttrs () const
Return all of the attributes on this operation.
Attribute get (Identifier name) const
Return the specified attribute if present, null otherwise.
Attribute get (StringRef name) const
Return the specified attribute if present, null otherwise.
Optional< NamedAttribute > getNamed (StringRef name) const
Return the specified named attribute if present, None otherwise.
Optional< NamedAttribute > getNamed (Identifier name) const
void set (Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
void set (StringRef name, Attribute value)
const_iterator begin () const
const_iterator end () const
NamedAttrList & operator= (const SmallVectorImpl< NamedAttribute > &rhs)
operator ArrayRef< NamedAttribute > () const
operator MutableDictionaryAttr () const
Detailed Description
NamedAttrList is array of NamedAttributes that tracks whether it is sorted and does some basic work to remain sorted.
Definition at line 199 of file OperationSupport.h.
Member Typedef Documentation
const_iterator
using mlir::NamedAttrList::const_iterator = SmallVectorImpl<NamedAttribute>::const_iterator
Definition at line 201 of file OperationSupport.h.
const_reference
using mlir::NamedAttrList::const_reference = const NamedAttribute &
Definition at line 202 of file OperationSupport.h.
reference
using mlir::NamedAttrList::reference = NamedAttribute &
Definition at line 203 of file OperationSupport.h.
size_type
using mlir::NamedAttrList::size_type = size_t
Definition at line 204 of file OperationSupport.h.
Constructor & Destructor Documentation
NamedAttrList() [1/3]
mlir::NamedAttrList::NamedAttrList () inline
Definition at line 206 of file OperationSupport.h.
NamedAttrList() [2/3]
NamedAttrList::NamedAttrList (ArrayRef< NamedAttribute > attributes)
Definition at line 25 of file OperationSupport.cpp.
References assign().
NamedAttrList() [3/3]
NamedAttrList::NamedAttrList (const_iterator in_start, const_iterator in_end)
Definition at line 29 of file OperationSupport.cpp.
References assign().
Member Function Documentation
append() [1/4]
void NamedAttrList::append (StringRef name, Attribute attr)
Add an attribute with the specified name.
Definition at line 52 of file OperationSupport.cpp.
References mlir::Identifier::get(), and mlir::Attribute::getContext().
Referenced by append(), mlir::FuncOp::build(), getLinkageAttrName(), parseShuffleVectorOp(), and print().
append() [2/4]
void NamedAttrList::append (Identifier name, Attribute attr)
Add an attribute with the specified name.
Definition at line 57 of file OperationSupport.cpp.
References push_back().
append() [3/4]
void NamedAttrList::append (ArrayRef< NamedAttribute > newAttributes)
Add an array of named attributes.
Definition at line 62 of file OperationSupport.cpp.
References append().
append() [4/4]
void NamedAttrList::append (const_iterator in_start, const_iterator in_end)
Add a range of named attributes.
Definition at line 67 of file OperationSupport.cpp.
assign() [1/2]
void NamedAttrList::assign (const_iterator in_start, const_iterator in_end)
Replaces the attributes with new list of attributes.
Definition at line 75 of file OperationSupport.cpp.
References mlir::DictionaryAttr::sort().
Referenced by NamedAttrList(), operator=(), parseContractionOp(), and parseGenericOp().
assign() [2/2]
void mlir::NamedAttrList::assign (ArrayRef< NamedAttribute > range) inline
Replaces the attributes with new list of attributes.
Definition at line 233 of file OperationSupport.h.
begin()
const_iterator mlir::NamedAttrList::begin () const inline
Definition at line 267 of file OperationSupport.h.
empty()
bool mlir::NamedAttrList::empty () const inline
Definition at line 237 of file OperationSupport.h.
end()
const_iterator mlir::NamedAttrList::end () const inline
Definition at line 268 of file OperationSupport.h.
get() [1/2]
Attribute NamedAttrList::get (Identifier name) const
Return the specified attribute if present, null otherwise.
Definition at line 112 of file OperationSupport.cpp.
References findAttr().
Referenced by parseTransferReadOp(), and parseTransferWriteOp().
get() [2/2]
Attribute NamedAttrList::get (StringRef name) const
Return the specified attribute if present, null otherwise.
Definition at line 106 of file OperationSupport.cpp.
References findAttr().
getAttrs()
ArrayRef< NamedAttribute > NamedAttrList::getAttrs () const
Return all of the attributes on this operation.
Definition at line 33 of file OperationSupport.cpp.
getDictionary()
DictionaryAttr NamedAttrList::getDictionary (MLIRContext * context) const
Return a dictionary attribute for the underlying dictionary.
This will return an empty dictionary attribute if empty rather than null.
Definition at line 35 of file OperationSupport.cpp.
References mlir::DictionaryAttr::getWithSorted(), and mlir::DictionaryAttr::sortInPlace().
Referenced by operator MutableDictionaryAttr(), and mlir::detail::Parser::parseAttribute().
getNamed() [1/2]
Optional< NamedAttribute > NamedAttrList::getNamed (StringRef name) const
Return the specified named attribute if present, None otherwise.
Definition at line 118 of file OperationSupport.cpp.
References findAttr().
getNamed() [2/2]
Optional< NamedAttribute > NamedAttrList::getNamed (Identifier name) const
Definition at line 122 of file OperationSupport.cpp.
References findAttr().
operator ArrayRef< NamedAttribute >()
NamedAttrList::operator ArrayRef< NamedAttribute > () const
Definition at line 159 of file OperationSupport.cpp.
operator MutableDictionaryAttr()
NamedAttrList::operator MutableDictionaryAttr () const
Definition at line 45 of file OperationSupport.cpp.
References getDictionary().
operator!=()
bool mlir::NamedAttrList::operator!= (const NamedAttrList & other) const inline
Definition at line 210 of file OperationSupport.h.
operator=()
NamedAttrList & NamedAttrList::operator= (const SmallVectorImpl< NamedAttribute > & rhs)
Definition at line 154 of file OperationSupport.cpp.
References assign().
operator==()
bool mlir::NamedAttrList::operator== (const NamedAttrList & other) const inline
Definition at line 213 of file OperationSupport.h.
pop_back()
void mlir::NamedAttrList::pop_back () inline
Pop last element from list.
Definition at line 245 of file OperationSupport.h.
Referenced by parseBound().
push_back()
void NamedAttrList::push_back (NamedAttribute newAttribute)
Add an attribute with the specified name.
Definition at line 80 of file OperationSupport.cpp.
Referenced by append(), mlir::ModuleOp::build(), mlir::detail::Parser::parseAttributeDict(), mlir::detail::Parser::parseToken(), and verify().
reserve()
void mlir::NamedAttrList::reserve (size_type N) inline
Definition at line 239 of file OperationSupport.h.
Referenced by mlirOperationCreate().
set() [1/2]
void NamedAttrList::set (Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
Otherwise, add a new attribute with the specified name/value.
Definition at line 129 of file OperationSupport.cpp.
References findAttr().
Referenced by parseCmpOp(), parseTransferReadOp(), and parseTransferWriteOp().
set() [2/2]
void NamedAttrList::set (StringRef name, Attribute value)
Definition at line 148 of file OperationSupport.cpp.
References mlir::Identifier::get(), and mlir::Attribute::getContext().
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/OperationSupport.cpp