MLIR: mlir::ReductionNode Class Reference
mlir::ReductionNode Class Reference
This class defines the ReductionNode which is used to wrap the module of a generated variant and keep track of the necessary metadata for the reduction pass.
#include "mlir/Reducer/ReductionNode.h"
Public Member Functions
ReductionNode (ModuleOp module, ReductionNode *parent)
void measureAndTest (const Tester *test)
Calculates and initializes the size and interesting values of the node.
ModuleOp getModule () const
Returns the module.
bool isEvaluated () const
Returns true if the size and interestingness have been calculated.
int getSize () const
Returns the size in bytes of the module.
bool isInteresting () const
Returns true if the module exhibits the interesting behavior.
ReductionNode * getVariant (unsigned long index) const
Returns the pointer to a child variant by index.
bool variantsEmpty () const
Returns true if the vector containing the child variants is empty.
void organizeVariants (const Tester *test)
Sort the child variants and remove the uninteresting ones.
Detailed Description
This class defines the ReductionNode which is used to wrap the module of a generated variant and keep track of the necessary metadata for the reduction pass.
The nodes are linked together in a reduction tree stucture which defines the relationship between all the different generated variants.
Definition at line 31 of file ReductionNode.h.
Constructor & Destructor Documentation
ReductionNode()
mlir::ReductionNode::ReductionNode (ModuleOp module, ReductionNode * parent)
Member Function Documentation
getModule()
ModuleOp mlir::ReductionNode::getModule () const inline
Returns the module.
Definition at line 39 of file ReductionNode.h.
References getSize(), getVariant(), isEvaluated(), isInteresting(), organizeVariants(), and variantsEmpty().
getSize()
int mlir::ReductionNode::getSize () const
Returns the size in bytes of the module.
Referenced by getModule().
getVariant()
ReductionNode* mlir::ReductionNode::getVariant (unsigned long index) const
Returns the pointer to a child variant by index.
Referenced by getModule(), and mlir::ReductionTreePass< Reducer, mode >::runOnOperation().
isEvaluated()
bool mlir::ReductionNode::isEvaluated () const
Returns true if the size and interestingness have been calculated.
Referenced by getModule().
isInteresting()
bool mlir::ReductionNode::isInteresting () const
Returns true if the module exhibits the interesting behavior.
Referenced by getModule().
measureAndTest()
void mlir::ReductionNode::measureAndTest (const Tester * test)
Calculates and initializes the size and interesting values of the node.
organizeVariants()
void mlir::ReductionNode::organizeVariants (const Tester * test)
Sort the child variants and remove the uninteresting ones.
Referenced by getModule(), and mlir::ReductionTreePass< Reducer, mode >::runOnOperation().
variantsEmpty()
bool mlir::ReductionNode::variantsEmpty () const
Returns true if the vector containing the child variants is empty.
Referenced by getModule(), and mlir::ReductionTreePass< Reducer, mode >::runOnOperation().
The documentation for this class was generated from the following file:
include/mlir/Reducer/ReductionNode.h