MLIR: mlir::Type Class Reference
mlir::Type Class Reference
Instances of the Type class are uniqued, have an immutable identifier and an optional mutable component.
#include "mlir/IR/Types.h"
Public Types
enum Kind {
Function, Opaque, LAST_BUILTIN_TYPE = Opaque, DEFINE_SYM_KIND_RANGE,
DEFINE_SYM_KIND_RANGE
}
Integer identifier for all the concrete type kinds.
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
Utility class for implementing types.
using ImplType = TypeStorage
Public Member Functions
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete type.
unsigned getKind () const
Return the classification for this type.
MLIRContext * getContext () const
Return the LLVMContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex ()
bool isBF16 ()
bool isF16 ()
bool isF32 ()
bool isF64 ()
bool isInteger (unsigned width)
Return true if this is an integer type with the specified width.
bool isSignlessInteger ()
Return true if this is a signless integer type (with the specified width).
bool isSignlessInteger (unsigned width)
bool isSignedInteger ()
Return true if this is a signed integer type (with the specified width).
bool isSignedInteger (unsigned width)
bool isUnsignedInteger ()
Return true if this is an unsigned integer type (with the specified width).
bool isUnsignedInteger (unsigned width)
unsigned getIntOrFloatBitWidth ()
Return the bit width of an integer or a float type, assert failure on other types.
bool isSignlessIntOrIndex ()
Return true if this is a signless integer or index type.
bool isSignlessIntOrIndexOrFloat ()
Return true if this is a signless integer, index, or float type.
bool isSignlessIntOrFloat ()
Return true of this is a signless integer or a float type.
bool isIntOrIndex ()
Return true if this is an integer (of any signedness) or an index type.
bool isIntOrFloat ()
Return true if this is an integer (of any signedness) or a float type.
bool isIntOrIndexOrFloat ()
Return true if this is an integer (of any signedness), index, or float type.
void print (raw_ostream &os)
Print the current type.
void dump ()
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Protected Attributes
ImplType * impl
Friends
::llvm::hash_code hash_value (Type arg)
Detailed Description
Instances of the Type class are uniqued, have an immutable identifier and an optional mutable component.
They wrap a pointer to the storage object owned by MLIRContext. Therefore, instances of Type are passed around by value.
Some types are "primitives" meaning they do not have any parameters, for example the Index type. Parametric types have additional information that differentiates the types of the same kind between them, for example the Integer type has bitwidth, making i8 and i16 belong to the same kind by be different instances of the IntegerType. Type parameters are part of the unique immutable key. The mutable component of the type can be modified after the type is created, but cannot affect the identity of the type.
Types are constructed and uniqued via the 'detail::TypeUniquer' class.
Derived type classes are expected to implement several required implementation hooks:
Optional:
static LogicalResult verifyConstructionInvariants(Location loc, Args... args)
This method is invoked when calling the 'TypeBase::get/getChecked' methods to ensure that the arguments passed in are valid to construct a type instance with.
This method is expected to return failure if a type cannot be constructed with 'args', success otherwise.
'args' must correspond with the arguments passed into the 'TypeBase::get' call after the type kind.
Type storage objects inherit from TypeStorage and contain the following:
The type kind (for LLVM-style RTTI).
The dialect that defined the type.
Any parameters of the type.
An optional mutable component. For non-parametric types, a convenience DefaultTypeStorage is provided. Parametric storage types must derive TypeStorage and respect the following:
Define a type alias, KeyTy, to a type that uniquely identifies the instance of the type within its kind.
The key type must be constructible from the values passed into the detail::TypeUniquer::get call after the type kind.
If the KeyTy does not have an llvm::DenseMapInfo specialization, the storage class must define a hashing method: 'static unsigned hashKey(const KeyTy &)'
Provide a method, 'bool operator==(const KeyTy &) const', to compare the storage instance against an instance of the key type.
Provide a static construction method: 'DerivedStorage *construct(TypeStorageAllocator &, const KeyTy &key)' that builds a unique instance of the derived storage. The arguments to this function are an allocator to store any uniqued data within the context and the key type for this storage.
If they have a mutable component, this component must not be a part of
Definition at line 85 of file Types.h.
Member Typedef Documentation
ImplType
using mlir::Type::ImplType = TypeStorage
Definition at line 110 of file Types.h.
TypeBase
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits> using mlir::Type::TypeBase = detail::StorageUserBase<ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits...>
Utility class for implementing types.
Definition at line 108 of file Types.h.
Member Enumeration Documentation
Kind
enum mlir::Type::Kind
Integer identifier for all the concrete type kinds.
Note: This is not an enum class as each dialect will likely define a separate enumeration for the specific types that they define. Not being an enum class also simplifies the handling of type kinds by not requiring casts for each use.
Enumerator
Function
Opaque
LAST_BUILTIN_TYPE
DEFINE_SYM_KIND_RANGE
DEFINE_SYM_KIND_RANGE
Definition at line 92 of file Types.h.
Constructor & Destructor Documentation
Type() [1/3]
constexpr mlir::Type::Type () inline
Definition at line 112 of file Types.h.
Type() [2/3]
mlir::Type::Type (const ImplType * impl) inline
Definition at line 113 of file Types.h.
References mlir::StandardAttributes::Type.
Type() [3/3]
mlir::Type::Type (const Type & other) default
Member Function Documentation
cast()
template<typename U > U mlir::Type::cast () const
Definition at line 328 of file Types.h.
Referenced by mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castFromStorageType(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), mlir::DenseFPElementsAttr::classof(), mlir::DenseIntElementsAttr::classof(), computeTensorReshapeCollapsedType(), convertReassociationIndicesToMaps(), convertScalarType(), createConstantAllBitsSet(), createFPConstant(), createGlobalVarForEntryPointArgument(), createScopedSubViewIntersection(), doubleBuffer(), extractOne(), mlir::StructBuilder::extractPtr(), extractShape(), foldTransferMaskAttribute(), mlir::quant::ExpressedToQuantizedConverter::forInputType(), generateCopy(), generatePointWiseCopy(), mlir::IntegerAttr::get(), mlir::DenseElementsAttr::get(), getAtomicOpScope(), mlir::spirv::CompositeType::getCapabilities(), mlir::spirv::ArrayType::getCapabilities(), mlir::spirv::RuntimeArrayType::getCapabilities(), mlir::spirv::CooperativeMatrixNVType::getCapabilities(), mlir::DenseElementsAttr::getComplexFloatValues(), mlir::DenseElementsAttr::getComplexIntValues(), mlir::AffineDmaStartOp::getDstMemorySpace(), mlir::AffineDmaStartOp::getDstMemRefRank(), mlir::AffineDmaStartOp::getDstMemRefType(), mlir::MemRefDescriptor::getElementType(), mlir::spirv::MatrixType::getElementType(), mlir::spirv::CompositeType::getExtensions(), mlir::spirv::ArrayType::getExtensions(), mlir::spirv::RuntimeArrayType::getExtensions(), mlir::spirv::CooperativeMatrixNVType::getExtensions(), mlir::DenseElementsAttr::getFloatValues(), getFullMemRefAsRegion(), getInputAndOutputIndices(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getInputOutputShapedTypes(), mlir::detail::FloatAttributeStorage::getKey(), getLocalInvocationDimSize(), getMemRefAlignment(), getMemRefSizes(), getMultiLevelStrides(), getOrCreateUnrolledVectorSlice(), getPhiIncomingBlock(), mlir::quant::QuantizedType::getQuantizedElementType(), mlir::DenseIntOrFPElementsAttr::getRawComplex(), mlir::spirv::CompositeType::getSizeInBytes(), mlir::spirv::ArrayType::getSizeInBytes(), mlir::AffineDmaStartOp::getSrcMemorySpace(), mlir::AffineDmaStartOp::getSrcMemRefType(), mlir::AffineDmaStartOp::getTagMemRefRank(), mlir::AffineDmaWaitOp::getTagMemRefRank(), mlir::AffineDmaStartOp::getTagMemRefType(), mlir::AffineDmaWaitOp::getTagMemRefType(), mlir::Value::getType(), mlir::ElementsAttr::getType(), mlir::SparseElementsAttr::getValue(), mlir::Builder::getZeroAttr(), inferExtractOpResultType(), inferStridedSliceOpResultType(), insertCopies(), insertOne(), mlir::quant::QuantizedType::isCompatibleExpressedType(), isIdentitySuffix(), makeTiledViews(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), mlir::MemRefDescriptor::MemRefDescriptor(), minusOneIntegerAttribute(), mlir::OperandElementTypeIterator::OperandElementTypeIterator(), mlir::DenseElementsAttr::IntElementIterator::operator*(), optionallyTruncateOrExtend(), parseCallOp(), mlir::detail::Parser::parseElementsLiteralType(), parseGenericAtomicRMWOp(), parseNVVMShflSyncBflyOp(), parseSubViewOp(), parseTensorFromElementsOp(), print(), printDenseElementsAttrImpl(), printLandingpadOp(), mlir::LLVMTypeConverter::promoteOneMemRefDescriptor(), mlir::replaceAllMemRefUsesWith(), reshapeLoad(), mlir::ResultElementTypeIterator::ResultElementTypeIterator(), mlir::LLVM::LLVMType::setStructTyBody(), mlir::MemRefDescriptor::size(), mlir::vector::splitFullAndPartialTransfer(), mlir::ComplexStructBuilder::undef(), mlir::MemRefDescriptor::undef(), mlir::UnrankedMemRefDescriptor::undef(), unrollSingleResultStructuredOp(), vectorizeConstant(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), verifyAtomicUpdateOp(), verifyCastOp(), mlir::FloatAttr::verifyConstructionInvariants(), mlir::spirv::MatrixType::verifyConstructionInvariants(), verifyCopyMemory(), verifyLoadStorePtrAndValTypes(), verifyPointerAndCoopMatrixType(), verifyTransferOp(), walkReturnOperations(), and wrapExternalFunction().
classof()
static bool mlir::Type::classof (Type) inline static
Definition at line 133 of file Types.h.
dump()
void Type::dump ()
Definition at line 2351 of file AsmPrinter.cpp.
References print().
Referenced by mlirAttributeDump(), mlirOperationDump(), and mlirTypeDump().
dyn_cast()
template<typename U > U mlir::Type::dyn_cast () const
Definition at line 322 of file Types.h.
Referenced by appendMangledType(), mlir::barePtrFuncArgTypeConverter(), buildLLVMFunctionType(), buildLogicalBinaryOp(), mlir::canFoldIntoConsumerOp(), canRegisterAlias(), mlir::spirv::SPIRVType::classof(), mlir::spirv::ScalarType::classof(), mlir::spirv::CompositeType::classof(), mlir::quant::ExpressedToQuantizedConverter::convert(), convertMemrefType(), convertScalarType(), convertTensorType(), createFPConstant(), mlir::VulkanLayoutUtils::decorateType(), forwardPassthroughAttributes(), generateTransferOpSlices(), getBitWidth(), mlir::DenseElementsAttr::getBoolValues(), mlir::detail::getDenseElementBitWidth(), getElementPtrType(), getElementType(), mlir::getElementTypeOrSelf(), getEnclosingforOps(), getI1SameShape(), getInsertExtractValueElementType(), getLoadStoreElementType(), getPhiIncomingBlock(), mlir::quant::QuantizedType::getQuantizedElementType(), getShape(), getTensorOrVectorElementType(), getTensorTypeFromMemRefType(), getTransferOpAdapter(), getTypeNumBytes(), getUnaryOpResultType(), handleMultidimensionalVectors(), insertCopies(), isAllocationSupported(), isBoolScalarOrVector(), isFnEntryBlock(), mlir::VulkanLayoutUtils::isLegalType(), isMemRefNormalizable(), mlir::isOpaqueTypeWithName(), isSignedIntegerOrVector(), isUnsignedIntegerOrVector(), mlir::spirv::MatrixType::isValidColumnType(), isValidIntOrFloat(), isValidQuantizationSpec(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), mlir::detail::BufferAssignmentCallOpConverter< allowMemrefFunctionResults >::matchAndRewrite(), mlir::TypeConverter::materializeTargetConversion(), minusOneIntegerAttribute(), optionallyBroadcast(), parseAllocaOp(), parseAndVerifyMatrixType(), parseAndVerifyType(), parseAtomicCompareExchangeWeakOp(), parseAtomicUpdateOp(), parseCallOp(), parseCmpOp(), mlir::OpAsmParser::parseColonType(), parseCompositeConstructOp(), parseConstShapeOp(), mlir::detail::Parser::parseDecOrHexAttr(), parseElementAttrHexValues(), parseExtractElementOp(), parseExtractOp(), parseInsertElementOp(), parseInvokeOp(), parseOuterProductOp(), parseShuffleVectorOp(), mlir::detail::Parser::parseToken(), mlir::DialectAsmParser::parseType(), mlir::OpAsmParser::parseType(), parseVariableOp(), print(), printUniformQuantizedPerAxisType(), mlir::quant::quantizeAttr(), mlir::StructBuilder::StructBuilder(), mlir::structFuncArgTypeConverter(), mlir::TypeRange::TypeRange(), unwrap(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), verifyCastOp(), mlir::verifyCompatibleShape(), mlir::quant::QuantizedType::verifyConstructionInvariants(), mlir::IntegerAttr::verifyConstructionInvariants(), and verifyOutputShape().
dyn_cast_or_null()
template<typename U > U mlir::Type::dyn_cast_or_null () const
Definition at line 325 of file Types.h.
Referenced by diag(), getVectorElementwiseOpUnrollState(), isIdentitySuffix(), unrollSingleResultStructuredOp(), and verify().
getAbstractType()
const AbstractType& mlir::Type::getAbstractType () inline
Return the abstract type descriptor for this type.
Definition at line 203 of file Types.h.
getAsOpaquePointer()
const void* mlir::Type::getAsOpaquePointer () const inline
Methods for supporting PointerLikeTypeTraits.
Definition at line 195 of file Types.h.
Referenced by llvm::PointerLikeTypeTraits< mlir::Type >::getAsVoidPointer(), llvm::PointerLikeTypeTraits< mlir::LLVM::LLVMType >::getAsVoidPointer(), mlirParseType(), and mlir::AttributeStorage::setType().
getContext()
MLIRContext * Type::getContext () const
Return the LLVMContext in which this type was uniqued.
Definition at line 28 of file Types.cpp.
Referenced by mlir::LLVM::LLVMType::createStructTy(), mlir::quant::fakeQuantAttrsToType(), mlir::ComplexType::get(), mlir::spirv::ArrayType::get(), mlir::quant::AnyQuantizedType::get(), mlir::spirv::PointerType::get(), mlir::spirv::RuntimeArrayType::get(), mlir::quant::UniformQuantizedType::get(), mlir::LLVM::LLVMArrayType::get(), mlir::LLVM::LLVMFunctionType::get(), mlir::VectorType::get(), mlir::quant::UniformQuantizedPerAxisType::get(), mlir::FloatAttr::get(), mlir::LLVM::LLVMPointerType::get(), mlir::RankedTensorType::get(), mlir::spirv::CooperativeMatrixNVType::get(), mlir::spirv::MatrixType::get(), mlir::UnrankedTensorType::get(), mlir::IntegerAttr::get(), mlir::LLVM::LLVMFixedVectorType::get(), mlir::StringAttr::get(), mlir::LLVM::LLVMScalableVectorType::get(), mlir::UnrankedMemRefType::get(), mlir::TypeAttr::get(), mlir::DenseStringElementsAttr::get(), mlir::OpaqueElementsAttr::get(), mlir::SparseElementsAttr::get(), mlir::MemRefType::getChecked(), mlir::Attribute::getContext(), mlir::Value::getContext(), getI1SameShape(), getPhiIncomingBlock(), mlir::DenseIntOrFPElementsAttr::getRaw(), mlir::LLVM::LLVMType::getStructTy(), getTensorTypeFromMemRefType(), parseSymbol(), mlir::Value::setType(), and unwrap().
getDialect()
Dialect Type::getDialect () const
Get the dialect this type is registered to.
Definition at line 24 of file Types.cpp.
Referenced by mlir::quant::QuantizedType::classof(), mlir::LLVM::LLVMType::classof(), mlir::LLVM::LLVMType::getDialect(), mlir::TensorType::isValidElementType(), parseAndVerifyType(), printDenseElementsAttrImpl(), and verify().
getFromOpaquePointer()
static Type mlir::Type::getFromOpaquePointer (const void * pointer) inline static
Definition at line 198 of file Types.h.
References mlir::StandardAttributes::Type.
Referenced by mlir::DiagnosticArgument::getAsType(), llvm::PointerLikeTypeTraits< mlir::Type >::getFromVoidPointer(), mlir::AttributeStorage::getType(), makeFunctionType(), makeIntegerAttr(), and makeMemRefType().
getIntOrFloatBitWidth()
unsigned Type::getIntOrFloatBitWidth ()
Return the bit width of an integer or a float type, assert failure on other types.
Definition at line 171 of file StandardTypes.cpp.
References mlir::ShapedType::kDynamicSize, and mlir::ShapedType::kDynamicStrideOrOffset.
Referenced by allocBuffer(), buildAttributeAPInt(), mlir::VulkanLayoutUtils::decorateType(), getBitWidth(), mlir::detail::getDenseElementBitWidth(), mlir::ShapedType::getElementTypeBitWidth(), mlir::Builder::getIntegerAttr(), getTypeNumBytes(), and verifyCastOp().
getKind()
unsigned Type::getKind () const
Return the classification for this type.
Definition at line 22 of file Types.cpp.
Referenced by mlir::spirv::SPIRVType::classof(), getTypeKeyword(), mlir::Builder::getZeroAttr(), printDenseElementsAttrImpl(), and verifyShapeOrExtentTensorOp().
getTypeID()
TypeID mlir::Type::getTypeID () inline
Return a unique identifier for the concrete type.
This is used to support dynamic type casting.
Definition at line 137 of file Types.h.
References mlir::hash_value(), and print().
isa() [1/2]
template<typename U > bool mlir::Type::isa () const
Definition at line 312 of file Types.h.
Referenced by mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castFromStorageType(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), mlir::ConstantFloatOp::classof(), mlir::spirv::SPIRVType::classof(), mlir::spirv::CompositeType::classof(), mlir::ShapedType::classof(), mlir::TensorType::classof(), mlir::BaseMemRefType::classof(), mlir::LLVM::LLVMVectorType::classof(), mlir::DenseFPElementsAttr::classof(), convertRangeType(), createConstantAllBitsSet(), mlir::VulkanLayoutUtils::decorateType(), mlir::edsc::op::eq(), mlir::quant::ExpressedToQuantizedConverter::forInputType(), mlir::DenseElementsAttr::get(), mlir::SparseElementsAttr::get(), getAtomicOpScope(), getBitWidth(), mlir::OpTrait::util::getBroadcastedType(), mlir::DenseElementsAttr::getComplexFloatValues(), mlir::DenseElementsAttr::getComplexIntValues(), getI1SameShape(), getPhiIncomingBlock(), mlir::quant::QuantizedType::getQuantizedElementType(), mlir::DenseIntOrFPElementsAttr::getRaw(), getTransferOpAdapter(), getTypeNumBytes(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::hasBufferSemantics(), hasTensorOrVectorType(), mlir::detail::IntegerAttributeStorage::IntegerAttributeStorage(), isAccessIndexInvariant(), mlir::quant::QuantizedType::isCompatibleExpressedType(), mlir::BufferAssignmentTypeConverter::isConvertedMemref(), isFnEntryBlock(), isIdentitySuffix(), isMemRefDereferencingOp(), isMemRefNormalizable(), isQuantizablePrimitiveType(), mlir::VectorType::isValidElementType(), mlir::TensorType::isValidElementType(), mlir::BaseMemRefType::isValidElementType(), isValidIntOrFloat(), mlir::LLVM::LLVMType::isValidPointerElementType(), isValidQuantizationSpec(), mlir::edsc::ops::linalg_generic_pointwise(), mappingHelper(), mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), mlir::ContractionOpLowering::matchAndRewrite(), mlir::edsc::op::ne(), mlir::AffineDmaWaitOp::parse(), parseConstantOp(), parseConstShapeOp(), mlir::detail::Parser::parseDecOrHexAttr(), parseElementAttrHexValues(), mlir::detail::Parser::parseElementsLiteralType(), mlir::detail::Parser::parseFloatAttr(), parseGlobalVariableOp(), print(), printDenseElementsAttrImpl(), printGPUFuncOp(), mlir::edsc::op::sge(), mlir::edsc::op::sgt(), mlir::edsc::op::sle(), mlir::edsc::op::slt(), mlir::structFuncArgTypeConverter(), mlir::edsc::StructuredIndexed::StructuredIndexed(), mlir::edsc::op::uge(), mlir::edsc::op::ugt(), mlir::edsc::op::ule(), mlir::edsc::op::ult(), vectorizeConstant(), vectorizeOperand(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), mlir::quant::AnyQuantizedType::verifyConstructionInvariants(), mlir::quant::UniformQuantizedType::verifyConstructionInvariants(), mlir::quant::UniformQuantizedPerAxisType::verifyConstructionInvariants(), verifyFloatTypeInvariants(), verifyIntegerTypeInvariants(), verifyOutputShape(), verifyPointerAndCoopMatrixType(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), and verifyShapeOrExtentTensorOp().
isa() [2/2]
template<typename First , typename Second , typename... Rest> bool mlir::Type::isa () const
Definition at line 318 of file Types.h.
isBF16()
bool Type::isBF16 ()
Definition at line 25 of file StandardTypes.cpp.
References mlir::StandardTypes::BF16.
Referenced by mlir::quant::QuantizedType::isSigned(), and parseAndVerifyType().
isF16()
bool Type::isF16 ()
Definition at line 26 of file StandardTypes.cpp.
References mlir::StandardTypes::F16.
Referenced by mlir::quant::QuantizedType::isSigned().
isF32()
bool Type::isF32 ()
Definition at line 27 of file StandardTypes.cpp.
References mlir::StandardTypes::F32.
Referenced by getTransferOpAdapter(), mlir::quant::QuantizedType::isSigned(), and verify().
isF64()
bool Type::isF64 ()
Definition at line 28 of file StandardTypes.cpp.
References mlir::StandardTypes::F64.
Referenced by mlir::detail::FloatAttributeStorage::getKey(), getTransferOpAdapter(), mlir::quant::QuantizedType::isSigned(), and verify().
isIndex()
bool Type::isIndex ()
Definition at line 30 of file StandardTypes.cpp.
Referenced by buildAttributeAPInt(), ceilDivPositive(), mlir::ConstantIndexOp::classof(), mlir::IntegerAttr::get(), mlir::detail::getDenseElementBitWidth(), mlir::Builder::getIntegerAttr(), mlir::detail::IntegerAttributeStorage::IntegerAttributeStorage(), mlir::quant::QuantizedType::isSigned(), mlir::isValidDim(), isValidIntOrFloat(), mlir::isValidSymbol(), parseGenericOp(), mlir::DmaStartOp::verify(), mlir::DmaWaitOp::verify(), and verify().
isInteger()
bool Type::isInteger (unsigned width)
Return true if this is an integer type with the specified width.
Definition at line 33 of file StandardTypes.cpp.
Referenced by mlir::detail::DenseIntOrFPElementsAttributeStorage::construct(), mlir::DenseElementsAttr::get(), mlir::SparseElementsAttr::get(), getAtomicOpScope(), mlir::detail::DenseIntOrFPElementsAttributeStorage::getKey(), isBoolScalarOrVector(), mlir::quant::QuantizedType::isSigned(), mlir::edsc::op::negate(), mlir::detail::DenseIntOrFPElementsAttributeStorage::operator==(), mlir::edsc::op::operator||(), and parseElementAttrHexValues().
isIntOrFloat()
bool Type::isIntOrFloat ()
Return true if this is an integer (of any signedness) or a float type.
Definition at line 89 of file StandardTypes.cpp.
Referenced by mlir::DenseElementsAttr::get(), getBitWidth(), isAllocationSupported(), isFnEntryBlock(), mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), parseElementAttrHexValues(), and mlir::ComplexType::verifyConstructionInvariants().
isIntOrIndex()
bool Type::isIntOrIndex ()
Return true if this is an integer (of any signedness) or an index type.
Definition at line 87 of file StandardTypes.cpp.
Referenced by mlir::DenseIntElementsAttr::classof(), mlir::DenseElementsAttr::get(), and parseElementAttrHexValues().
isIntOrIndexOrFloat()
bool Type::isIntOrIndexOrFloat ()
Return true if this is an integer (of any signedness), index, or float type.
Definition at line 91 of file StandardTypes.cpp.
Referenced by mlir::DenseElementsAttr::get(), getAtomicOpScope(), mlir::BaseMemRefType::isValidElementType(), parseElementAttrHexValues(), and verifyRegionAttribute().
isSignedInteger() [1/2]
bool Type::isSignedInteger ()
Return true if this is a signed integer type (with the specified width).
Definition at line 51 of file StandardTypes.cpp.
Referenced by buildAttributeAPInt(), mlir::Builder::getIntegerAttr(), and isSignedIntegerOrVector().
isSignedInteger() [2/2]
bool Type::isSignedInteger (unsigned width)
Definition at line 57 of file StandardTypes.cpp.
isSignlessInteger() [1/2]
bool Type::isSignlessInteger ()
Return true if this is a signless integer type (with the specified width).
Definition at line 39 of file StandardTypes.cpp.
Referenced by mlir::ConstantIntOp::build(), mlir::ConstantIntOp::classof(), mlir::IntegerAttr::get(), getTransferOpAdapter(), and verify().
isSignlessInteger() [2/2]
bool Type::isSignlessInteger (unsigned width)
Definition at line 45 of file StandardTypes.cpp.
isSignlessIntOrFloat()
bool Type::isSignlessIntOrFloat ()
Return true of this is a signless integer or a float type.
Definition at line 83 of file StandardTypes.cpp.
Referenced by mlir::linalg::RegionMatcher::matchAsScalarBinaryOp(), and verify().
isSignlessIntOrIndex()
bool Type::isSignlessIntOrIndex ()
Return true if this is a signless integer or index type.
Definition at line 75 of file StandardTypes.cpp.
Referenced by mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike().
isSignlessIntOrIndexOrFloat()
bool Type::isSignlessIntOrIndexOrFloat ()
Return true if this is a signless integer, index, or float type.
Definition at line 79 of file StandardTypes.cpp.
Referenced by appendMangledType().
isUnsignedInteger() [1/2]
bool Type::isUnsignedInteger ()
Return true if this is an unsigned integer type (with the specified width).
Definition at line 63 of file StandardTypes.cpp.
Referenced by isUnsignedIntegerOrVector(), mlir::detail::Parser::parseDecOrHexAttr(), parseElementAttrHexValues(), and printDenseElementsAttrImpl().
isUnsignedInteger() [2/2]
bool Type::isUnsignedInteger (unsigned width)
Definition at line 69 of file StandardTypes.cpp.
operator bool()
mlir::Type::operator bool () const inline explicit
Definition at line 121 of file Types.h.
operator!()
bool mlir::Type::operator! () const inline
Definition at line 123 of file Types.h.
operator!=()
bool mlir::Type::operator!= (Type other) const inline
Definition at line 120 of file Types.h.
operator=()
Type& mlir::Type::operator= (const Type & other) default
operator==()
bool mlir::Type::operator== (Type other) const inline
Definition at line 119 of file Types.h.
References impl.
print()
void Type::print (raw_ostream & os)
Print the current type.
Definition at line 2349 of file AsmPrinter.cpp.
Referenced by mlir::operator<<().
Friends And Related Function Documentation
hash_value
::llvm::hash_code hash_value (Type arg) friend
Definition at line 308 of file Types.h.
Member Data Documentation
impl
ImplType* mlir::Type::impl protected
Definition at line 206 of file Types.h.
Referenced by mlir::LLVM::LLVMVectorType::getElementType(), mlir::hash_value(), and operator==().
The documentation for this class was generated from the following files:
include/mlir/IR/Types.h
lib/IR/AsmPrinter.cpp
lib/IR/StandardTypes.cpp
lib/IR/Types.cpp
lib/TableGen/Type.cpp