MLIR: mlir::StringAttr Class Reference
mlir::StringAttr Class Reference
#include "mlir/IR/Attributes.h"
Public Types
using ValueType = StringRef
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
StringRef getValue () const
Static Public Member Functions
static StringAttr get (StringRef bytes, MLIRContext *context)
Get an instance of a StringAttr with the given string.
static StringAttr get (StringRef bytes, Type type)
Get an instance of a StringAttr with the given string and Type.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 503 of file Attributes.h.
Member Typedef Documentation
ValueType
using mlir::StringAttr::ValueType = StringRef
Definition at line 507 of file Attributes.h.
Member Function Documentation
get() [1/2]
StringAttr StringAttr::get (StringRef bytes, MLIRContext * context) static
Get an instance of a StringAttr with the given string.
Definition at line 426 of file Attributes.cpp.
References mlir::NoneType::get().
Referenced by convertStructType(), mlir::Builder::getStringAttr(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::iterator_types(), makeStringAttr(), mlir::DenseElementsAttr::AttributeElementIterator::operator*(), mlir::detail::Parser::parseAttribute(), mlir::SymbolTable::setSymbolName(), and mlir::SymbolTable::setSymbolVisibility().
get() [2/2]
StringAttr StringAttr::get (StringRef bytes, Type type) static
Get an instance of a StringAttr with the given string and Type.
Definition at line 431 of file Attributes.cpp.
References mlir::Type::getContext(), and mlir::StandardAttributes::String.
getValue()
StringRef StringAttr::getValue () const
Definition at line 435 of file Attributes.cpp.
Referenced by mlir::spirv::VerCapExtAttr::ext_iterator::ext_iterator(), forwardPassthroughAttributes(), mlir::DenseElementsAttr::get(), getNameIfSymbol(), mlir::SymbolTable::getSymbolVisibility(), mlir::isParallelIterator(), mlir::isReductionIterator(), mlir::isWindowIterator(), parseAffineParallelOp(), parseCmpOp(), verify(), and mlir::detail::verifySymbol().
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp