MLIR: mlir::Value Class Reference
mlir::Value Class Reference
This class represents an instance of an SSA value in the MLIR system, representing a computable value that has a type and a set of users.
#include "mlir/IR/Value.h"
Classes
struct ImplTypeTraits
This value represents the 'owner' of the value and its kind.
Public Types
enum Kind { Kind::OpResult0 = 0, Kind::OpResult1 = 1, Kind::TrailingOpResult = 2, Kind::BlockArgument = 3 }
The enumeration represents the various different kinds of values the internal representation may take.
using ImplType = llvm::PointerIntPair< void *, 2, Kind, ImplTypeTraits >
using use_iterator = ValueUseIterator< OpOperand >
This class implements an iterator over the uses of a value.
using use_range = iterator_range< use_iterator >
using user_iterator = ValueUserIterator< use_iterator, OpOperand >
using user_range = iterator_range< user_iterator >
Public Member Functions
constexpr Value (std::nullptr_t)
Value (ImplType ownerAndKind={})
Value (const Value &)=default
Value & operator= (const Value &)=default
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
operator bool () const
bool operator== (const Value &other) const
bool operator!= (const Value &other) const
Type getType () const
Return the type of this value.
MLIRContext * getContext () const
Utility to get the associated MLIRContext that this value is defined in.
void setType (Type newType)
Mutate the type of this Value to be of the specified type.
Operation * getDefiningOp () const
If this value is the result of an operation, return the operation that defines it.
template<typename OpTy >
OpTy getDefiningOp () const
If this value is the result of an operation of type OpTy, return the operation that defines it.
Location getLoc () const
If this value is the result of an operation, use it as a location, otherwise return an unknown location.
Region * getParentRegion ()
Return the Region in which this Value is defined.
Block * getParentBlock ()
Return the Block in which this Value is defined.
IRObjectWithUseList< OpOperand > * getUseList () const
Provide the use list that is attached to this value.
void dropAllUses () const
Drop all uses of this object from their respective owners.
void replaceAllUsesWith (Value newValue) const
Replace all uses of 'this' value with the new value, updating anything in the IR that uses 'this' to use the other value instead.
void replaceAllUsesExcept (Value newValue, const SmallPtrSetImpl< Operation *> &exceptions) const
Replace all uses of 'this' value with 'newValue', updating anything in the IR that uses 'this' to use the other value instead except if the user is listed in 'exceptions' .
void replaceUsesWithIf (Value newValue, function_ref< bool(OpOperand &)> shouldReplace)
Replace all uses of 'this' value with 'newValue' if the given callback returns true.
bool isUsedOutsideOfBlock (Block *block)
Returns true if the value is used outside of the given block.
use_iterator use_begin () const
use_iterator use_end () const
use_range getUses () const
Returns a range of all uses, which is useful for iterating over all uses.
bool hasOneUse () const
Returns true if this value has exactly one use.
bool use_empty () const
Returns true if this value has no uses.
user_iterator user_begin () const
user_iterator user_end () const
user_range getUsers () const
Kind getKind () const
Returns the kind of this value.
void print (raw_ostream &os)
void print (raw_ostream &os, AsmState &state)
void dump ()
void printAsOperand (raw_ostream &os, AsmState &state)
Print this value as if it were an operand.
void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
Static Public Member Functions
static Value getFromOpaquePointer (const void *pointer)
Protected Member Functions
Value (detail::BlockArgumentImpl *impl)
Construct a value.
Value (Operation *op, unsigned resultNo)
Static Protected Member Functions
static bool canPackResultInline (unsigned resultNo)
Returns true if the given operation result can be packed inline.
Protected Attributes
ImplType ownerAndKind
This value represents the 'owner' of the value and its kind.
Friends
::llvm::hash_code hash_value (Value arg)
Make Value hashable.
Detailed Description
This class represents an instance of an SSA value in the MLIR system, representing a computable value that has a type and a set of users.
An SSA value is either a BlockArgument or the result of an operation. Note: This class has value-type semantics and is just a simple wrapper around a ValueImpl that is either owner by a block(in the case of a BlockArgument) or an Operation(in the case of an OpResult).
Definition at line 40 of file Value.h.
Member Typedef Documentation
ImplType
using mlir::Value::ImplType = llvm::PointerIntPair<void *, 2, Kind, ImplTypeTraits>
Definition at line 72 of file Value.h.
use_iterator
using mlir::Value::use_iterator = ValueUseIterator<OpOperand>
This class implements an iterator over the uses of a value.
Definition at line 176 of file Value.h.
use_range
using mlir::Value::use_range = iterator_range<use_iterator>
Definition at line 177 of file Value.h.
user_iterator
using mlir::Value::user_iterator = ValueUserIterator<use_iterator, OpOperand>
Definition at line 194 of file Value.h.
user_range
using mlir::Value::user_range = iterator_range<user_iterator>
Definition at line 195 of file Value.h.
Member Enumeration Documentation
Kind
enum mlir::Value::Kind strong
The enumeration represents the various different kinds of values the internal representation may take.
We steal 2 bits to support a total of 4 possible values.
Enumerator
OpResult0
The first N kinds are all inline operation results.
An inline operation result means that the kind represents the result number, and the owner pointer is the owning Operation*. Note: These are packed first to make result number lookups more efficient.
OpResult1
TrailingOpResult
The next kind represents a 'trailing' operation result.
This is for results with numbers larger than we can represent inline. The owner here is an TrailingOpResult* that points to a trailing storage on the parent operation.
BlockArgument
The last kind represents a block argument.
The owner here is a BlockArgumentImpl*.
Definition at line 45 of file Value.h.
Constructor & Destructor Documentation
Value() [1/5]
constexpr mlir::Value::Value (std::nullptr_t) inline
Definition at line 75 of file Value.h.
Value() [2/5]
mlir::Value::Value (ImplType ownerAndKind = {}) inline
Definition at line 76 of file Value.h.
Value() [3/5]
mlir::Value::Value (const Value &) default
Value() [4/5]
Value::Value (detail::BlockArgumentImpl * impl) protected
Construct a value.
Definition at line 19 of file Value.cpp.
Value() [5/5]
Value::Value (Operation * op, unsigned resultNo) protected
Definition at line 21 of file Value.cpp.
References canPackResultInline(), mlir::OpResult::getMaxInlineResults(), mlir::Operation::getNumResults(), ownerAndKind, and TrailingOpResult.
Member Function Documentation
canPackResultInline()
static bool mlir::Value::canPackResultInline (unsigned resultNo) inline static protected
Returns true if the given operation result can be packed inline.
Definition at line 226 of file Value.h.
Referenced by Value().
cast()
template<typename U > U mlir::Value::cast () const inline
Definition at line 96 of file Value.h.
Referenced by mlir::detail::ConversionPatternRewriterImpl::applyRewrites(), canRegisterAlias(), createFPConstant(), llvm::PointerLikeTypeTraits< mlir::BlockArgument >::getFromVoidPointer(), getTransferOpAdapter(), mlir::isValidDim(), mlir::DominanceInfo::properlyDominates(), mlir::Liveness::resolveLiveness(), and runRegionDCE().
dropAllUses()
void Value::dropAllUses () const
Drop all uses of this object from their respective owners.
Definition at line 119 of file Value.cpp.
References mlir::IRObjectWithUseList< OperandType >::dropAllUses(), and getUseList().
Referenced by mlir::Block::dropAllDefinedValueUses(), and logFailure().
dump()
void Value::dump ()
Definition at line 2404 of file AsmPrinter.cpp.
References print().
dyn_cast()
template<typename U > U mlir::Value::dyn_cast () const inline
Definition at line 90 of file Value.h.
Referenced by canRegisterAlias(), collapseBranch(), mlir::SDBM::get(), mlir::getForInductionVarOwner(), getInputAndOutputIndices(), mlir::scf::getParallelForInductionVarOwner(), getPhiIncomingBlock(), mlir::isTopLevelValue(), isTopLevelValue(), logFailure(), parseForOp(), runRegionDCE(), and wrapExternalFunction().
dyn_cast_or_null()
template<typename U > U mlir::Value::dyn_cast_or_null () const inline
Definition at line 93 of file Value.h.
getAsOpaquePointer()
void* mlir::Value::getAsOpaquePointer () const inline
Methods for supporting PointerLikeTypeTraits.
Definition at line 215 of file Value.h.
Referenced by mlir::BlockAndValueMapping::clear(), mlir::BlockAndValueMapping::contains(), mlir::BlockAndValueMapping::erase(), llvm::PointerLikeTypeTraits< mlir::Value >::getAsVoidPointer(), llvm::PointerLikeTypeTraits< mlir::BlockArgument >::getAsVoidPointer(), and mlir::BlockAndValueMapping::map().
getContext()
MLIRContext* mlir::Value::getContext () const inline
Utility to get the associated MLIRContext that this value is defined in.
Definition at line 111 of file Value.h.
References mlir::Type::getContext().
Referenced by allocBuffer(), getLoc(), substituteLoopInExpr(), and verify().
getDefiningOp() [1/2]
Operation * Value::getDefiningOp () const
If this value is the result of an operation, return the operation that defines it.
If this value is the result of an Operation, return the operation that defines it.
Definition at line 71 of file Value.cpp.
Referenced by allocBuffer(), mlir::ConstantIndexOp::build(), buildAffineLoopFromValues(), canRegisterAlias(), categorizeValueByAffineType(), defaultDeallocBufferCallBack(), deriveStaticUpperBound(), mlir::DominanceInfo::dominates(), extractConstantIndex(), extractSmallestConstantBoundingSize(), findMatchingStartFinishInsts(), foldExtractOpFromInsertChainAndTranspose(), mlir::fullyComposeAffineMapAndOperands(), mlir::linalg::fuseTensorOps(), getLoc(), mlir::scf::getParallelForInductionVarOwner(), getParentBlock(), getParentRegion(), getPhiIncomingBlock(), mlir::LivenessBlockInfo::getStartOperation(), inferExtractOpResultType(), mlir::inlineCall(), isConstantOne(), isIdentitySuffix(), isInBounds(), isOpLoopInvariant(), isSameSubView(), mlir::isTopLevelValue(), isTopLevelValue(), mlir::isValidDim(), mlir::isValidSymbol(), isZero(), logFailure(), mlir::loopUnrollByFactor(), mlir::linalg::LinalgCopyVTRForwardingPattern::matchAndRewrite(), mlir::linalg::LinalgCopyVTWForwardingPattern::matchAndRewrite(), mlir::detail::matchOperandOrValueAtIndex(), mlir::matchPattern(), normalizeLoop(), parseConstShapeOp(), processParallelLoop(), mlir::DominanceInfo::properlyDominates(), mlir::Liveness::resolveLiveness(), runRegionDCE(), mlir::scf::tileParallelLoop(), transformIndexedGenericOpIndices(), vectorizeOperand(), verify(), verifyGroupNonUniformArithmeticOp(), walkReturnOperations(), wouldOpBeTriviallyDeadImpl(), and wrapExternalFunction().
getDefiningOp() [2/2]
template<typename OpTy > OpTy mlir::Value::getDefiningOp () const inline
If this value is the result of an operation of type OpTy, return the operation that defines it.
Definition at line 128 of file Value.h.
getFromOpaquePointer()
static Value mlir::Value::getFromOpaquePointer (const void * pointer) inline static
Definition at line 216 of file Value.h.
References mlir::hash_value(), and ownerAndKind.
Referenced by mlir::BlockAndValueMapping::clear(), llvm::DenseMapInfo< mlir::Value >::getEmptyKey(), llvm::PointerLikeTypeTraits< mlir::Value >::getFromVoidPointer(), llvm::PointerLikeTypeTraits< mlir::BlockArgument >::getFromVoidPointer(), llvm::DenseMapInfo< mlir::Value >::getTombstoneKey(), and mlir::detail::OpaqueValue::operator Value().
getKind()
Kind mlir::Value::getKind () const inline
Returns the kind of this value.
Definition at line 205 of file Value.h.
References print().
Referenced by mlir::BlockArgument::classof(), mlir::OpResult::classof(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), and getUseList().
getLoc()
Location Value::getLoc () const
If this value is the result of an operation, use it as a location, otherwise return an unknown location.
Definition at line 77 of file Value.cpp.
References mlir::UnknownLoc::get(), getContext(), getDefiningOp(), mlir::Operation::getLoc(), and mlir::Operation::getParentOp().
Referenced by getPhiIncomingBlock(), initUnrolledVectorState(), logFailure(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), mlir::ContractionOpLowering::matchAndRewrite(), mlir::LLVM::detail::vectorOneToOneRewrite(), and walkReturnOperations().
getParentBlock()
Block * Value::getParentBlock ()
Return the Block in which this Value is defined.
Definition at line 95 of file Value.cpp.
References getDefiningOp().
Referenced by runRegionDCE(), and walkReturnOperations().
getParentRegion()
Region * Value::getParentRegion ()
Return the Region in which this Value is defined.
Definition at line 88 of file Value.cpp.
References getDefiningOp(), and mlir::Region::getParentRegion().
Referenced by canonicalizeLoopBounds(), insertCopyLoops(), parseForOp(), print(), and verify().
getType()
Type Value::getType () const
Return the type of this value.
Definition at line 34 of file Value.cpp.
References mlir::Type::cast(), mlir::OpResult::getOwner(), and mlir::OpResult::getResultNumber().
Referenced by broadcast(), mlir::impl::buildBinaryOp(), buildCmpFOp(), buildCmpIOp(), buildLogicalBinaryOp(), ceilDivPositive(), mlir::ConstantFloatOp::classof(), mlir::ConstantIntOp::classof(), mlir::ConstantIndexOp::classof(), computeTensorReshapeCollapsedType(), convertRangeType(), convertReassociationIndicesToMaps(), createBinaryHandle(), createFComparisonExpr(), createIComparisonExpr(), createScopedFullPartialVectorTransferRead(), createScopedSubViewIntersection(), doubleBuffer(), emulateSignedRemainder(), mlir::edsc::op::eq(), extractOne(), extractShape(), mlir::impl::foldCastOp(), foldTransferMaskAttribute(), generateCopy(), generatePointWiseCopy(), getAtomicOpScope(), mlir::AffineDmaStartOp::getDstMemorySpace(), mlir::AffineDmaStartOp::getDstMemRefRank(), mlir::AffineDmaStartOp::getDstMemRefType(), getElementPtrType(), mlir::MemRefDescriptor::getElementType(), mlir::getElementTypeOrSelf(), getEnclosingforOps(), getFullMemRefAsRegion(), getLocalInvocationDimSize(), getMemRefSizes(), getMultiLevelStrides(), getOrCreateUnrolledVectorSlice(), mlir::scf::getParallelForInductionVarOwner(), mlir::AffineDmaStartOp::getSrcMemorySpace(), mlir::AffineDmaStartOp::getSrcMemRefType(), mlir::AffineDmaStartOp::getTagMemRefRank(), mlir::AffineDmaWaitOp::getTagMemRefRank(), mlir::AffineDmaStartOp::getTagMemRefType(), mlir::AffineDmaWaitOp::getTagMemRefType(), getTransferOpAdapter(), getVectorElementwiseOpUnrollState(), handleMultidimensionalVectors(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::hasBufferSemantics(), inferExtractOpResultType(), inferStridedSliceOpResultType(), mlir::inlineCall(), insertCopies(), insertOne(), isAccessIndexInvariant(), isIdentitySuffix(), isMemRefDereferencingOp(), isMemRefNormalizable(), mlir::isValidDim(), mlir::isValidSymbol(), logFailure(), makeTiledViews(), mlir::detail::constant_int_op_binder::match(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), matchAndRewriteOneToOne(), mlir::MemRefDescriptor::MemRefDescriptor(), mlir::edsc::op::ne(), mlir::edsc::op::negate(), mlir::detail::ConversionPatternRewriterImpl::notifyOpReplaced(), mlir::OperationFolder::notifyRemoval(), mlir::LLVM::detail::oneToOneRewrite(), mlir::OperandElementTypeIterator::OperandElementTypeIterator(), mlir::edsc::op::operator||(), optionallyTruncateOrExtend(), parseCallOp(), parseConstShapeOp(), parseSubViewOp(), mlir::detail::Parser::parseToken(), print(), printAtomicUpdateOp(), mlir::impl::printCastOp(), printDenseElementsAttrImpl(), printGroupNonUniformArithmeticOp(), printLandingpadOp(), printLogicalOp(), mlir::impl::printOneResultOp(), printShiftOp(), printStandardBinaryOp(), printStandardCastOp(), printStandardUnaryOp(), printUnaryOp(), mlir::LLVMTypeConverter::promoteOneMemRefDescriptor(), mlir::detail::ConversionPatternRewriterImpl::remapValues(), mlir::replaceAllMemRefUsesWith(), mlir::ResultElementTypeIterator::ResultElementTypeIterator(), mlir::edsc::op::sge(), mlir::edsc::op::sgt(), mlir::edsc::op::sle(), mlir::edsc::op::slt(), mlir::vector::splitFullAndPartialTransfer(), mlir::StructBuilder::StructBuilder(), mlir::edsc::StructuredIndexed::StructuredIndexed(), mlir::edsc::op::uge(), mlir::edsc::op::ugt(), mlir::edsc::op::ule(), mlir::edsc::op::ult(), unrollSingleResultStructuredOp(), vectorizeOperand(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), verifyAtomicUpdateOp(), verifyCastOp(), verifyLoadStorePtrAndValTypes(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsShape(), mlir::OpTrait::impl::verifySameTypeOperands(), verifyShiftOp(), verifyTransferOp(), walkReturnOperations(), and wrapExternalFunction().
getUseList()
IRObjectWithUseList< OpOperand > * Value::getUseList () const
Provide the use list that is attached to this value.
Definition at line 106 of file Value.cpp.
References getKind(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), ownerAndKind, and TrailingOpResult.
Referenced by dropAllUses(), mlir::OpOperand::getUseList(), hasOneUse(), replaceAllUsesWith(), use_begin(), and use_empty().
getUsers()
user_range mlir::Value::getUsers () const inline
Definition at line 199 of file Value.h.
Referenced by mlir::ConstantIndexOp::build(), mlir::createMemRefDataFlowOptPass(), mlir::LivenessBlockInfo::getEndOperation(), hasNonAffineUsersOnThePath(), isIdentitySuffix(), isMemRefNormalizable(), isOpLoopInvariant(), mlir::isOpwiseShiftValid(), isUsedOutsideOfBlock(), mlir::normalizeMemRef(), and mlir::replaceAllMemRefUsesWith().
getUses()
use_range mlir::Value::getUses () const inline
Returns a range of all uses, which is useful for iterating over all uses.
Definition at line 183 of file Value.h.
Referenced by getSubViewUseIfUnique(), mlir::linalg::hoistViewAllocOps(), mlir::linalg::LinalgCopyVTRForwardingPattern::matchAndRewrite(), processValue(), replaceAllUsesExcept(), mlir::replaceAllUsesInRegionWith(), replaceUsesWithIf(), mlir::Liveness::resolveLiveness(), and transformIndexedGenericOpIndices().
hasOneUse()
bool Value::hasOneUse () const
Returns true if this value has exactly one use.
Definition at line 163 of file Value.cpp.
References getUseList(), and mlir::IRObjectWithUseList< OperandType >::hasOneUse().
Referenced by findMatchingStartFinishInsts(), and isIdentitySuffix().
isa() [1/2]
template<typename U > bool mlir::Value::isa () const inline
Definition at line 80 of file Value.h.
Referenced by mlir::detail::ConversionPatternRewriterImpl::applyRewrites(), convertStructType(), and walkReturnOperations().
isa() [2/2]
template<typename First , typename Second , typename... Rest> bool mlir::Value::isa () const inline
Definition at line 86 of file Value.h.
isUsedOutsideOfBlock()
bool Value::isUsedOutsideOfBlock (Block * block)
Returns true if the value is used outside of the given block.
Definition at line 149 of file Value.cpp.
References mlir::Operation::getBlock(), and getUsers().
Referenced by mlir::Operation::isUsedOutsideOfBlock().
operator bool()
mlir::Value::operator bool () const inline explicit
Definition at line 101 of file Value.h.
operator!=()
bool mlir::Value::operator!= (const Value & other) const inline
Definition at line 105 of file Value.h.
operator=()
Value& mlir::Value::operator= (const Value &) default
operator==()
bool mlir::Value::operator== (const Value & other) const inline
Definition at line 102 of file Value.h.
References ownerAndKind.
print() [1/2]
void Value::print (raw_ostream & os)
Definition at line 2388 of file AsmPrinter.cpp.
References mlir::Operation::print().
Referenced by isOpLoopInvariant(), and mlir::operator<<().
print() [2/2]
void Value::print (raw_ostream & os, AsmState & state)
Definition at line 2395 of file AsmPrinter.cpp.
References mlir::Operation::print().
printAsOperand()
void Value::printAsOperand (raw_ostream & os, AsmState & state)
Print this value as if it were an operand.
Definition at line 2409 of file AsmPrinter.cpp.
References mlir::AsmState::getImpl(), and mlir::detail::AsmStateImpl::getSSANameState().
replaceAllUsesExcept()
void Value::replaceAllUsesExcept (Value newValue, const SmallPtrSetImpl< Operation *> & exceptions) const
Replace all uses of 'this' value with 'newValue', updating anything in the IR that uses 'this' to use the other value instead except if the user is listed in 'exceptions' .
Replace all uses of 'this' value with the new value, updating anything in the IR that uses 'this' to use the other value instead except if the user is listed in 'exceptions' .
Definition at line 131 of file Value.cpp.
References getUses().
Referenced by cloneWithLoopRanges(), and mlir::scf::tileParallelLoop().
replaceAllUsesWith()
void Value::replaceAllUsesWith (Value newValue) const
Replace all uses of 'this' value with the new value, updating anything in the IR that uses 'this' to use the other value instead.
When this returns there are zero uses of 'this'.
Definition at line 124 of file Value.cpp.
References getUseList(), and mlir::IRObjectWithUseList< OperandType >::replaceAllUsesWith().
Referenced by mlir::createMemRefDataFlowOptPass(), getLLVMAtomicOrdering(), mlir::inlineCall(), insertCopies(), isConstantOne(), logFailure(), mlir::normalizeMemRef(), mlir::Operation::replaceAllUsesWith(), and mlir::OperationFolder::tryToFold().
replaceUsesWithIf()
void Value::replaceUsesWithIf (Value newValue, function_ref< bool(OpOperand &)> shouldReplace)
Replace all uses of 'this' value with 'newValue' if the given callback returns true.
Definition at line 141 of file Value.cpp.
References getUses().
setType()
void Value::setType (Type newType)
Mutate the type of this Value to be of the specified type.
Note that this is an extremely dangerous operation which can create completely invalid IR very easily. It is strongly recommended that you recreate IR objects with the right types instead of mutating them in place.
Definition at line 47 of file Value.cpp.
References mlir::TupleType::get(), mlir::Type::getContext(), mlir::OpResult::getOwner(), and mlir::OpResult::getResultNumber().
use_begin()
auto Value::use_begin () const
Definition at line 158 of file Value.cpp.
References getUseList(), and mlir::IRObjectWithUseList< OperandType >::use_begin().
use_empty()
bool Value::use_empty () const
Returns true if this value has no uses.
Definition at line 166 of file Value.cpp.
References getUseList(), and mlir::IRObjectWithUseList< OperandType >::use_empty().
Referenced by findMatchingStartFinishInsts(), generateUnrolledLoop(), logFailure(), mlir::loopUnrollJamByFactor(), and mlir::Operation::use_empty().
use_end()
use_iterator mlir::Value::use_end () const inline
Definition at line 180 of file Value.h.
user_begin()
user_iterator mlir::Value::user_begin () const inline
Definition at line 197 of file Value.h.
Referenced by findMatchingStartFinishInsts().
user_end()
user_iterator mlir::Value::user_end () const inline
Definition at line 198 of file Value.h.
Friends And Related Function Documentation
hash_value
::llvm::hash_code hash_value (Value arg) friend
Make Value hashable.
Definition at line 346 of file Value.h.
Member Data Documentation
ownerAndKind
ImplType mlir::Value::ownerAndKind protected
This value represents the 'owner' of the value and its kind.
See the 'Kind' enumeration above for a more detailed description of each kind of owner.
Definition at line 237 of file Value.h.
Referenced by getFromOpaquePointer(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), getUseList(), mlir::hash_value(), operator==(), and Value().
The documentation for this class was generated from the following files:
include/mlir/IR/Value.h
lib/IR/AsmPrinter.cpp
lib/IR/Value.cpp