MLIR: mlir::IndexType Class Reference
mlir::IndexType Class Reference
Index is a special integer-like type with unknown platform-dependent bit width.
#include "mlir/IR/StandardTypes.h"
Static Public Member Functions
static IndexType get (MLIRContext *context)
Get an instance of the IndexType.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concerete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
Static Public Attributes
static constexpr unsigned kInternalStorageBitWidth = 64
Storage bit width used for IndexType by internal compiler data structures.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Index is a special integer-like type with unknown platform-dependent bit width.
Definition at line 103 of file StandardTypes.h.
Member Function Documentation
get()
IndexType IndexType::get (MLIRContext * context) static
Get an instance of the IndexType.
Definition at line 679 of file MLIRContext.cpp.
References mlir::MLIRContext::getImpl(), and mlir::MLIRContextImpl::indexTy.
Referenced by mlir::AffineMap::constantFold(), extractOperandTypes< IndexedGenericOp >(), mlir::AffineDmaWaitOp::fold(), foldMinMaxOp(), mlir::shape::getExtentTensorType(), mlir::Builder::getIndexArrayAttr(), mlir::Builder::getIndexType(), makeIndexType(), parseConstShapeOp(), mlir::LLVMTypeConverter::promoteOneMemRefDescriptor(), and verify().
Member Data Documentation
kInternalStorageBitWidth
constexpr unsigned mlir::IndexType::kInternalStorageBitWidth = 64 static
Storage bit width used for IndexType by internal compiler data structures.
Definition at line 111 of file StandardTypes.h.
Referenced by buildAttributeAPInt(), mlir::IntegerAttr::get(), and mlir::detail::getDenseElementBitWidth().
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/MLIRContext.cpp