MLIR: mlir::RewritePattern Class Reference
mlir::RewritePattern Class Reference
RewritePattern is the common base class for all DAG to DAG replacements.
#include "mlir/IR/PatternMatch.h"
Public Member Functions
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
LogicalResult match (Operation *op) const override
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
Protected Member Functions
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a rewrite pattern with a certain benefit that matches any operation type.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a rewrite pattern that may match any operation type.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
This constructor is used for patterns that match against a specific operation type.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag)
This constructor is used when a pattern may match against multiple different types of operations.
Protected Attributes
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Detailed Description
RewritePattern is the common base class for all DAG to DAG replacements.
There are two possible usages of this class:
Multi-step RewritePattern with "match" and "rewrite"
By overloading the "match" and "rewrite" functions, the user can separate the concerns of matching and rewriting.
Single-step RewritePattern with "matchAndRewrite"
By overloading the "matchAndRewrite" function, the user can perform the rewrite in the same call as the match.
Definition at line 130 of file PatternMatch.h.
Constructor & Destructor Documentation
RewritePattern() [1/4]
mlir::RewritePattern::RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext * context) inline protected
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
Definition at line 168 of file PatternMatch.h.
Referenced by mlir::ConversionPattern::getTypeConverter().
RewritePattern() [2/4]
mlir::RewritePattern::RewritePattern (PatternBenefit benefit, MatchAnyOpTypeTag tag) inline protected
Construct a rewrite pattern with a certain benefit that matches any operation type.
MatchAnyOpTypeTag is just a tag to ensure that the "match any" behavior is what the user actually desired, MatchAnyOpTypeTag() should always be supplied here.
Definition at line 175 of file PatternMatch.h.
RewritePattern() [3/4]
RewritePattern::RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext * context) protected
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
generatedNames contains the names of operations that may be generated during a successful rewrite.
Definition at line 52 of file PatternMatch.cpp.
References generatedOps.
RewritePattern() [4/4]
RewritePattern::RewritePattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext * context, MatchAnyOpTypeTag tag) protected
Construct a rewrite pattern that may match any operation type.
generatedNames contains the names of operations that may be generated during a successful rewrite. MatchAnyOpTypeTag is just a tag to ensure that the "match any" behavior is what the user actually desired, MatchAnyOpTypeTag() should always be supplied here.
Definition at line 62 of file PatternMatch.cpp.
References generatedOps.
Member Function Documentation
getGeneratedOps()
ArrayRef<OperationName> mlir::RewritePattern::getGeneratedOps () const inline
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Definition at line 163 of file PatternMatch.h.
Referenced by mlir::ConversionPattern::matchAndRewrite().
hasBoundedRewriteRecursion()
virtual bool mlir::RewritePattern::hasBoundedRewriteRecursion () const inline virtual
Returns true if this pattern is known to result in recursive application, i.e.
this pattern may generate IR that also matches this pattern, but is known to bound the recursion. This signals to a rewriter that it is safe to apply this pattern recursively to generated IR.
Definition at line 159 of file PatternMatch.h.
Referenced by mlir::ConversionPattern::matchAndRewrite().
match()
LogicalResult RewritePattern::match (Operation * op) const override virtual
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Implements mlir::Pattern.
Reimplemented in mlir::OpRewritePattern< SourceOp >, mlir::OpRewritePattern< OpTy >, mlir::OpRewritePattern< AffineMinOp >, mlir::OpRewritePattern< vector::TransferReadOp >, mlir::OpRewritePattern< vector::TransferWriteOp >, and mlir::OpRewritePattern< vector::ContractionOp >.
Definition at line 48 of file PatternMatch.cpp.
matchAndRewrite()
virtual LogicalResult mlir::RewritePattern::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const inline virtual
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
If successful, this function will automatically perform the rewrite.
Reimplemented in EraseDeadLinalgOp, mlir::VectorTransferRewriter< TransferOpTy >, mlir::VectorTransferRewriter< TransferOpTy >, mlir::linalg::LinalgLoweringPattern< OpTy >, mlir::linalg::LinalgBaseVectorizationPattern, mlir::linalg::LinalgBasePromotionPattern, mlir::ConversionPattern, mlir::linalg::LinalgBaseInterchangePattern, mlir::linalg::LinalgBaseTilingPattern, mlir::OpRewritePattern< SourceOp >, mlir::OpRewritePattern< OpTy >, mlir::OpRewritePattern< AffineMinOp >, mlir::OpRewritePattern< vector::TransferReadOp >, mlir::OpRewritePattern< vector::TransferWriteOp >, mlir::OpRewritePattern< vector::ContractionOp >, mlir::vector::VectorTransferFullPartialRewriter, and mlir::VectorTransferRewriter< TransferOpTy >.
Definition at line 146 of file PatternMatch.h.
References mlir::failure(), mlir::succeeded(), and mlir::success().
Referenced by mlir::PatternApplicator::matchAndRewrite().
rewrite()
void RewritePattern::rewrite (Operation * op, PatternRewriter & rewriter) const virtual
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
If an unexpected error is encountered (an internal compiler error), it is emitted through the normal MLIR diagnostic hooks and the IR is left in a valid state.
Reimplemented in mlir::OpRewritePattern< SourceOp >, mlir::OpRewritePattern< OpTy >, mlir::OpRewritePattern< AffineMinOp >, mlir::OpRewritePattern< vector::TransferReadOp >, mlir::OpRewritePattern< vector::TransferWriteOp >, and mlir::OpRewritePattern< vector::ContractionOp >.
Definition at line 43 of file PatternMatch.cpp.
Member Data Documentation
generatedOps
SmallVector<OperationName, 2> mlir::RewritePattern::generatedOps protected
A list of the potential operations that may be generated when rewriting an op with this pattern.
Definition at line 192 of file PatternMatch.h.
Referenced by RewritePattern().
The documentation for this class was generated from the following files:
include/mlir/IR/PatternMatch.h
lib/IR/PatternMatch.cpp