MLIR: mlir::Simplex Class Reference
mlir::Simplex Class Reference
This class implements a version of the Simplex and Generalized Basis Reduction algorithms, which can perform analysis of integer sets with affine inequalities and equalities.
#include "mlir/Analysis/Presburger/Simplex.h"
Public Types
enum Direction { Direction::Up, Direction::Down }
Public Member Functions
Simplex ()=delete
Simplex (unsigned nVar)
Construct a Simplex object with nVar variables.
Simplex (const FlatAffineConstraints &constraints)
bool isEmpty () const
Returns true if the tableau is empty (has conflicting constraints), false otherwise.
void addInequality (ArrayRef< int64_t > coeffs)
Add an inequality to the tableau.
unsigned numVariables () const
Returns the number of variables in the tableau.
unsigned numConstraints () const
Returns the number of constraints in the tableau.
void addEquality (ArrayRef< int64_t > coeffs)
Add an equality to the tableau.
void markEmpty ()
Mark the tableau as being empty.
unsigned getSnapshot () const
Get a snapshot of the current state. This is used for rolling back.
void rollback (unsigned snapshot)
Rollback to a snapshot. This invalidates all later snapshots.
Optional< Fraction > computeRowOptimum (Direction direction, unsigned row)
Compute the maximum or minimum value of the given row, depending on direction.
Optional< Fraction > computeOptimum (Direction direction, ArrayRef< int64_t > coeffs)
Compute the maximum or minimum value of the given expression, depending on direction.
std::pair< int64_t, int64_t > computeIntegerBounds (ArrayRef< int64_t > coeffs)
Returns a (min, max) pair denoting the minimum and maximum integer values of the given expression.
bool isUnbounded ()
Returns true if the polytope is unbounded, i.e., extends to infinity in some direction.
Optional< SmallVector< int64_t, 8 > > getSamplePointIfIntegral () const
Returns the current sample point if it is integral.
Optional< SmallVector< int64_t, 8 > > findIntegerSample ()
Returns an integer sample point if one exists, or None otherwise.
void print (raw_ostream &os) const
Print the tableau's internal state.
void dump () const
Static Public Member Functions
static Simplex makeProduct (const Simplex &a, const Simplex &b)
Make a tableau to represent a pair of points in the given tableaus, one in tableau A and one in B.
Friends
class GBRSimplex
Detailed Description
This class implements a version of the Simplex and Generalized Basis Reduction algorithms, which can perform analysis of integer sets with affine inequalities and equalities.
A Simplex can be constructed by specifying the dimensionality of the set. It supports adding affine inequalities and equalities, and can perform emptiness checks, i.e., it can find a solution to the set of constraints if one exists, or say that the set is empty if no solution exists. Currently, this only works for bounded sets. Simplex can also be constructed from a FlatAffineConstraints object.
The implementation of this Simplex class, other than the functionality for sampling, is based on the paper "Simplify: A Theorem Prover for Program Checking" by D. Detlefs, G. Nelson, J. B. Saxe.
We define variables, constraints, and unknowns. Consider the example of a two-dimensional set defined by 1 + 2x + 3y >= 0 and 2x - 3y >= 0. Here, x, y, are variables while 1 + 2x + 3y >= 0, 2x - 3y >= 0 are constraints. Unknowns are either variables or constraints, i.e., x, y, 1 + 2x + 3y >= 0, 2x - 3y >= 0 are all unknowns.
The implementation involves a matrix called a tableau, which can be thought of as a 2D matrix of rational numbers having number of rows equal to the number of constraints and number of columns equal to one plus the number of variables. In our implementation, instead of storing rational numbers, we store a common denominator for each row, so it is in fact a matrix of integers with number of rows equal to number of constraints and number of columns equal to two plus the number of variables. For example, instead of storing a row of three rationals [1/2, 2/3, 3], we would store [6, 3, 4, 18] since 3/6 = 1/2, 4/6 = 2/3, and 18/6 = 3.
Every row and column except the first and second columns is associated with an unknown and every unknown is associated with a row or column. The second column represents the constant, explained in more detail below. An unknown associated with a row or column is said to be in row or column position respectively.
The vectors var and con store information about the variables and constraints respectively, namely, whether they are in row or column position, which row or column they are associated with, and whether they correspond to a variable or a constraint.
An unknown is addressed by its index. If the index i is non-negative, then the variable var[i] is being addressed. If the index i is negative, then the constraint con[~i] is being addressed. Effectively this maps 0 -> var[0], 1 -> var[1], -1 -> con[0], -2 -> con[1], etc. rowUnknown[r] and colUnknown[c] are the indexes of the unknowns associated with row r and column c, respectively.
The unknowns in column position are together called the basis. Initially the basis is the set of variables – in our example above, the initial basis is x, y.
The unknowns in row position are represented in terms of the basis unknowns. If the basis unknowns are u_1, u_2, ... u_m, and a row in the tableau is d, c, a_1, a_2, ... a_m, this representats the unknown for that row as (c + a_1*u_1 + a_2*u_2 + ... + a_m*u_m)/d. In our running example, if the basis is the initial basis of x, y, then the constraint 1 + 2x + 3y >= 0 would be represented by the row [1, 1, 2, 3].
The association of unknowns to rows and columns can be changed by a process called pivoting, where a row unknown and a column unknown exchange places and the remaining row variables' representation is changed accordingly by eliminating the old column unknown in favour of the new column unknown. If we had pivoted the column for x with the row for 2x - 3y >= 0, the new row for x would be [2, 1, 3] since x = (1*(2x - 3y) + 3*y)/2. See the documentation for the pivot member function for details.
The association of unknowns to rows and columns is called the tableau configuration. The sample value of an unknown in a particular tableau configuration is its value if all the column unknowns were set to zero. Concretely, for unknowns in column position the sample value is zero and for unknowns in row position the sample value is the constant term divided by the common denominator.
The tableau configuration is called consistent if the sample value of all restricted unknowns is non-negative. Initially there are no constraints, and the tableau is consistent. When a new constraint is added, its sample value in the current tableau configuration may be negative. In that case, we try to find a series of pivots to bring us to a consistent tableau configuration, i.e. we try to make the new constraint's sample value non-negative without making that of any other constraints negative. (See findPivot and findPivotRow for details.) If this is not possible, then the set of constraints is mutually contradictory and the tableau is marked empty, which means the set of constraints has no solution.
This Simplex class also supports taking snapshots of the current state and rolling back to prior snapshots. This works by maintaing an undo log of operations. Snapshots are just pointers to a particular location in the log, and rolling back to a snapshot is done by reverting each log entry's operation from the end until we reach the snapshot's location.
Finding an integer sample is done with the Generalized Basis Reduction algorithm. See the documentation for findIntegerSample and reduceBasis.
Definition at line 123 of file Simplex.h.
Member Enumeration Documentation
Direction
enum mlir::Simplex::Direction strong
Enumerator
Up
Down
Definition at line 125 of file Simplex.h.
Constructor & Destructor Documentation
Simplex() [1/3]
mlir::Simplex::Simplex () delete
Simplex() [2/3]
mlir::Simplex::Simplex (unsigned nVar) explicit
Construct a Simplex object with nVar variables.
Definition at line 19 of file Simplex.cpp.
Simplex() [3/3]
mlir::Simplex::Simplex (const FlatAffineConstraints & constraints) explicit
Definition at line 30 of file Simplex.cpp.
References addEquality(), addInequality(), Down, mlir::FlatAffineConstraints::getEquality(), mlir::FlatAffineConstraints::getInequality(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumInequalities(), mlir::Matrix::getNumRows(), mlir::lcm(), mlir::Matrix::resizeVertically(), mlir::LogicalResult::Success, mlir::success(), and Up.
Member Function Documentation
addEquality()
void mlir::Simplex::addEquality (ArrayRef< int64_t > coeffs)
Add an equality to the tableau.
If coeffs is c_0, c_1, ... c_n, where n is the current number of variables, then the corresponding equality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} == 0.
If coeffs is c_0, c_1, ... c_n, where n is the curent number of variables, then the corresponding equality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} == 0.
We simply add two opposing inequalities, which force the expression to be zero.
Definition at line 375 of file Simplex.cpp.
References addInequality().
Referenced by findIntegerSample(), and Simplex().
addInequality()
void mlir::Simplex::addInequality (ArrayRef< int64_t > coeffs)
Add an inequality to the tableau.
If coeffs is c_0, c_1, ... c_n, where n is the current number of variables, then the corresponding inequality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} >= 0.
If coeffs is c_0, c_1, ... c_n, where n is the curent number of variables, then the corresponding inequality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} >= 0.
We add the inequality and mark it as restricted. We then try to make its sample value non-negative. If this is not possible, the tableau has become empty and we mark it as such.
Definition at line 360 of file Simplex.cpp.
References mlir::failed(), and markEmpty().
Referenced by addEquality(), and Simplex().
computeIntegerBounds()
std::pair< int64_t, int64_t > mlir::Simplex::computeIntegerBounds (ArrayRef< int64_t > coeffs)
Returns a (min, max) pair denoting the minimum and maximum integer values of the given expression.
Compute the minimum and maximum integer values the expression can take.
We compute each separately.
Definition at line 1026 of file Simplex.cpp.
References mlir::ceil(), computeOptimum(), Down, mlir::floor(), and Up.
Referenced by findIntegerSample().
computeOptimum()
Optional< Fraction > mlir::Simplex::computeOptimum (Direction direction, ArrayRef< int64_t > coeffs)
Compute the maximum or minimum value of the given expression, depending on direction.
Compute the optimum of the specified expression in the specified direction, or None if it is unbounded.
Returns a (num, den) pair denoting the optimum, or a null value if no optimum exists, i.e., if the expression is unbounded in this direction.
Definition at line 471 of file Simplex.cpp.
References computeRowOptimum(), getSnapshot(), and rollback().
Referenced by computeIntegerBounds(), and isUnbounded().
computeRowOptimum()
Optional< Fraction > mlir::Simplex::computeRowOptimum (Direction direction, unsigned row)
Compute the maximum or minimum value of the given row, depending on direction.
Returns a (num, den) pair denoting the optimum, or None if no optimum exists, i.e., if the expression is unbounded in this direction.
Definition at line 452 of file Simplex.cpp.
Referenced by computeOptimum().
dump()
void mlir::Simplex::dump () const
Definition at line 1079 of file Simplex.cpp.
References print().
findIntegerSample()
Optional< SmallVector< int64_t, 8 > > mlir::Simplex::findIntegerSample ()
Returns an integer sample point if one exists, or None otherwise.
Search for an integer sample point using a branch and bound algorithm.
This should only be called for bounded sets.
Each row in the basis matrix is a vector, and the set of basis vectors should span the space. Initially this is the identity matrix, i.e., the basis vectors are just the variables.
In every level, a value is assigned to the level-th basis vector, as follows. Compute the minimum and maximum rational values of this direction. If only one integer point lies in this range, constrain the variable to have this value and recurse to the next variable.
If the range has multiple values, perform generalized basis reduction via reduceBasis and then compute the bounds again. Now we try constraining this direction in the first value in this range and "recurse" to the next level. If we fail to find a sample, we try assigning the direction the next value in this range, and so on.
If no integer sample is found from any of the assignments, or if the range contains no integer value, then of course the polytope is empty for the current assignment of the values in previous levels, so we return to the previous level.
If we reach the last level where all the variables have been assigned values already, then we simply return the current sample point if it is integral, and go back to the previous level otherwise.
To avoid potentially arbitrarily large recursion depths leading to stack overflows, this algorithm is implemented iteratively.
Definition at line 931 of file Simplex.cpp.
References addEquality(), computeIntegerBounds(), mlir::Matrix::getNumRows(), mlir::Matrix::getRow(), getSamplePointIfIntegral(), getSnapshot(), mlir::Matrix::identity(), and rollback().
Referenced by mlir::FlatAffineConstraints::findIntegerSample(), and mlir::FlatAffineConstraints::isIntegerEmpty().
getSamplePointIfIntegral()
Optional< SmallVector< int64_t, 8 > > mlir::Simplex::getSamplePointIfIntegral () const
Returns the current sample point if it is integral.
Otherwise, returns an None.
Definition at line 580 of file Simplex.cpp.
Referenced by findIntegerSample().
getSnapshot()
unsigned mlir::Simplex::getSnapshot () const
Get a snapshot of the current state. This is used for rolling back.
Return a snapshot of the curent state.
This is just the current size of the undo log.
Definition at line 388 of file Simplex.cpp.
References Down, mlir::Matrix::resizeVertically(), and Up.
Referenced by computeOptimum(), and findIntegerSample().
isEmpty()
bool mlir::Simplex::isEmpty () const
Returns true if the tableau is empty (has conflicting constraints), false otherwise.
Definition at line 336 of file Simplex.cpp.
References mlir::Matrix::swapRows().
isUnbounded()
bool mlir::Simplex::isUnbounded ()
Returns true if the polytope is unbounded, i.e., extends to infinity in some direction.
Otherwise, returns false.
Definition at line 483 of file Simplex.cpp.
References computeOptimum(), Down, and Up.
Referenced by mlir::FlatAffineConstraints::isIntegerEmpty().
makeProduct()
Simplex mlir::Simplex::makeProduct (const Simplex & a, const Simplex & b) static
Make a tableau to represent a pair of points in the given tableaus, one in tableau A and one in B.
Make a tableau to represent a pair of points in the original tableau.
The product constraints and variables are stored as: first A's, then B's.
The product tableau has row layout: A's rows, B's rows.
It has column layout: denominator, constant, A's columns, B's columns.
Definition at line 513 of file Simplex.cpp.
References mlir::linalg::concat(), numConstraints(), numVariables(), and mlir::Matrix::resizeVertically().
markEmpty()
void mlir::Simplex::markEmpty ()
Mark the tableau as being empty.
Mark this tableau empty and push an entry to the undo stack.
Definition at line 348 of file Simplex.cpp.
Referenced by addInequality().
numConstraints()
unsigned mlir::Simplex::numConstraints () const
Returns the number of constraints in the tableau.
Definition at line 384 of file Simplex.cpp.
Referenced by makeProduct().
numVariables()
unsigned mlir::Simplex::numVariables () const
Returns the number of variables in the tableau.
Definition at line 383 of file Simplex.cpp.
Referenced by makeProduct().
print()
void mlir::Simplex::print (raw_ostream & os) const
Print the tableau's internal state.
Definition at line 1044 of file Simplex.cpp.
Referenced by dump().
rollback()
void mlir::Simplex::rollback (unsigned snapshot)
Rollback to a snapshot. This invalidates all later snapshots.
Rollback to the specified snapshot.
We undo all the log entries until the log size when the snapshot was taken is reached.
Definition at line 445 of file Simplex.cpp.
Referenced by computeOptimum(), and findIntegerSample().
Friends And Related Function Documentation
GBRSimplex
friend class GBRSimplex friend
Definition at line 200 of file Simplex.h.
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/Simplex.h
lib/Analysis/Presburger/Simplex.cpp