MLIR: lib/Interfaces/ControlFlowInterfaces.cpp File Reference
ControlFlowInterfaces.cpp File Reference
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/IR/StandardTypes.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "mlir/Interfaces/ControlFlowInterfaces.cpp.inc"
Functions
static LogicalResult verifyTypesAlongAllEdges (Operation *op, Optional< unsigned > sourceNo, function_ref< TypeRange(Optional< unsigned >)> getInputsTypesForRegion)
Verify that types match along all region control flow edges originating from sourceNo (region # if source is a region, llvm::None if source is parent op).
Function Documentation
verifyTypesAlongAllEdges()
static LogicalResult verifyTypesAlongAllEdges (Operation * op, Optional< unsigned > sourceNo, function_ref< TypeRange(Optional< unsigned >)> getInputsTypesForRegion) static
Verify that types match along all region control flow edges originating from sourceNo (region # if source is a region, llvm::None if source is parent op).
getInputsTypesForRegion is a function that returns the types of the inputs that flow from `sourceIndex' to the given region.
Definition at line 80 of file ControlFlowInterfaces.cpp.
References diag(), mlir::Operation::emitOpError(), mlir::detail::enumerate(), mlir::Operation::getName(), mlir::Region::getNumArguments(), mlir::Operation::getNumOperands(), mlir::Operation::getRegion(), and mlir::success().
Referenced by mlir::detail::verifyTypesAlongControlFlowEdges().