MLIR: lib/Conversion/StandardToSPIRV/ConvertStandardToSPIRV.cpp File Reference
ConvertStandardToSPIRV.cpp File Reference
#include "mlir/Dialect/SPIRV/LayoutUtils.h"
#include "mlir/Dialect/SPIRV/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVLowering.h"
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Support/LogicalResult.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/Debug.h"
Namespaces
mlir
Macros
#define DEBUG_TYPE "std-to-spirv-pattern"
#define CHECK_UNSIGNED_OP(SPIRVOp)
#define DISPATCH(cmpPredicate, spirvOp)
#define DISPATCH(cmpPredicate, spirvOp)
#define DISPATCH(cmpPredicate, spirvOp)
Functions
static bool isBoolScalarOrVector (Type type)
Returns true if the given type is a boolean scalar or vector type.
static BoolAttr convertBoolAttr (Attribute srcAttr, Builder builder)
Converts the given srcAttr into a boolean attribute if it holds an integral value.
static IntegerAttr convertIntegerAttr (IntegerAttr srcAttr, IntegerType dstType, Builder builder)
Converts the given srcAttr to a new attribute of the given dstType.
static FloatAttr convertFloatAttr (FloatAttr srcAttr, FloatType dstType, Builder builder)
Converts the given srcAttr to a new attribute of the given dstType.
static Value emulateSignedRemainder (Location loc, Value lhs, Value rhs, Value signOperand, OpBuilder &builder)
Returns signed remainder for lhs and rhs and lets the result follow the sign of signOperand.
static Value getOffsetForBitwidth (Location loc, Value srcIdx, int sourceBits, int targetBits, OpBuilder &builder)
Returns the offset of the value in targetBits representation.
static Value adjustAccessChainForBitwidth (SPIRVTypeConverter &typeConverter, spirv::AccessChainOp op, int sourceBits, int targetBits, OpBuilder &builder)
Returns an adjusted spirv::AccessChainOp.
static Value shiftValue (Location loc, Value value, Value offset, Value mask, int targetBits, OpBuilder &builder)
Returns the shifted targetBits-bit value with the given offset.
template<typename SPIRVOp >
bool isUnsignedOp ()
Returns true if the operator is operating on unsigned integers.
static bool isAllocationSupported (MemRefType t)
Returns true if the allocations of type t can be lowered to SPIR-V.
static Optional< spirv::Scope > getAtomicOpScope (MemRefType t)
Returns the scope to use for atomic operations use for emulating store operations of unsupported integer bitwidths, based on the memref type.
void mlir::populateStandardToSPIRVPatterns (MLIRContext *context, SPIRVTypeConverter &typeConverter, OwningRewritePatternList &patterns)
Appends to a pattern list additional patterns for translating StandardOps to SPIR-V ops.
Macro Definition Documentation
CHECK_UNSIGNED_OP
#define CHECK_UNSIGNED_OP (SPIRVOp)
Value:
template <>                                                                  \
  bool isUnsignedOp<SPIRVOp>() {                                               \
    return true;                                                               \
  }
Definition at line 198 of file ConvertStandardToSPIRV.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "std-to-spirv-pattern"
Definition at line 23 of file ConvertStandardToSPIRV.cpp.
DISPATCH [1/3]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    rewriter.replaceOpWithNewOp<spirvOp>(cmpFOp, cmpFOp.getResult().getType(), \
                                         cmpFOpOperands.lhs(),                 \
                                         cmpFOpOperands.rhs());                \
    return success();
Referenced by getAtomicOpScope().
DISPATCH [2/3]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    rewriter.replaceOpWithNewOp<spirvOp>(cmpIOp, cmpIOp.getResult().getType(), \
                                         cmpIOpOperands.lhs(),                 \
                                         cmpIOpOperands.rhs());                \
    return success();
DISPATCH [3/3]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    if (isUnsignedOp<spirvOp>() &&                                             \
        operandType != this->typeConverter.convertType(operandType)) {         \
      return cmpIOp.emitError(                                                 \
          "bitwidth emulation is not implemented yet on unsigned op");         \
    }                                                                          \
    rewriter.replaceOpWithNewOp<spirvOp>(cmpIOp, cmpIOp.getResult().getType(), \
                                         cmpIOpOperands.lhs(),                 \
                                         cmpIOpOperands.rhs());                \
    return success();
Function Documentation
adjustAccessChainForBitwidth()
static Value adjustAccessChainForBitwidth (SPIRVTypeConverter & typeConverter, spirv::AccessChainOp op, int sourceBits, int targetBits, OpBuilder & builder) static
Returns an adjusted spirv::AccessChainOp.
Based on the extension/capabilities, certain integer bitwidths sourceBits might not be supported. During conversion if a memref of an unsupported type is used, load/stores to this memref need to be modified to use a supported higher bitwidth targetBits and extracting the required bits. For an accessing a 1D array (spv.array or spv.rt_array), the last index is modified to load the bits needed. The extraction of the actual bits needed are handled separately. Note that this only works for a 1-D tensor.
Definition at line 162 of file ConvertStandardToSPIRV.cpp.
References mlir::TypeConverter::convertType(), mlir::OpBuilder::create(), mlir::Builder::getIntegerAttr(), and mlir::Builder::getIntegerType().
Referenced by getAtomicOpScope().
convertBoolAttr()
static BoolAttr convertBoolAttr (Attribute srcAttr, Builder builder) static
Converts the given srcAttr into a boolean attribute if it holds an integral value.
Returns null attribute if conversion fails.
Definition at line 42 of file ConvertStandardToSPIRV.cpp.
References mlir::Attribute::dyn_cast(), and mlir::Builder::getBoolAttr().
Referenced by getAtomicOpScope().
convertFloatAttr()
static FloatAttr convertFloatAttr (FloatAttr srcAttr, FloatType dstType, Builder builder) static
Converts the given srcAttr to a new attribute of the given dstType.
Returns null attribute if dstType is not 32-bit or conversion fails.
Definition at line 79 of file ConvertStandardToSPIRV.cpp.
References mlir::Builder::getF32FloatAttr(), and mlir::FloatAttr::getValue().
Referenced by getAtomicOpScope().
convertIntegerAttr()
static IntegerAttr convertIntegerAttr (IntegerAttr srcAttr, IntegerType dstType, Builder builder) static
Converts the given srcAttr to a new attribute of the given dstType.
Returns null attribute if conversion fails.
Definition at line 52 of file ConvertStandardToSPIRV.cpp.
References mlir::IntegerAttr::getInt(), mlir::Builder::getIntegerAttr(), mlir::IntegerAttr::getValue(), and mlir::IntegerType::getWidth().
Referenced by getAtomicOpScope().
emulateSignedRemainder()
static Value emulateSignedRemainder (Location loc, Value lhs, Value rhs, Value signOperand, OpBuilder & builder) static
Returns signed remainder for lhs and rhs and lets the result follow the sign of signOperand.
Note that this is needed for Vulkan. Per the Vulkan's SPIR-V environment spec, "for the OpSRem and OpSMod instructions, if either operand is negative the result is undefined." So we cannot directly use spv.SRem/spv.SMod if either operand can be negative. Emulate it via spv.UMod.
Definition at line 107 of file ConvertStandardToSPIRV.cpp.
References mlir::OpBuilder::create(), and mlir::Value::getType().
Referenced by getAtomicOpScope().
getAtomicOpScope()
static Optional<spirv::Scope> getAtomicOpScope (MemRefType t) static
Returns the scope to use for atomic operations use for emulating store operations of unsupported integer bitwidths, based on the memref type.
Returns None on failure.
Definition at line 237 of file ConvertStandardToSPIRV.cpp.
References adjustAccessChainForBitwidth(), mlir::Region::begin(), mlir::Type::cast(), convertBoolAttr(), convertFloatAttr(), convertIntegerAttr(), mlir::PatternRewriter::create(), DISPATCH, emulateSignedRemainder(), mlir::edsc::op::eq(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failure(), mlir::VectorType::get(), mlir::RankedTensorType::get(), mlir::TypeAttr::get(), mlir::DenseElementsAttr::get(), mlir::spirv::getElementPtr(), getElementType(), mlir::Builder::getIntegerAttr(), mlir::MemRefType::getMemorySpace(), mlir::SymbolTable::getNearestSymbolTable(), getOffsetForBitwidth(), mlir::Block::getOps(), mlir::Operation::getRegion(), mlir::SPIRVTypeConverter::getStorageClassForMemorySpace(), mlir::Value::getType(), mlir::IntegerType::getWidth(), mlir::Type::isa(), isAllocationSupported(), isBoolScalarOrVector(), mlir::Type::isInteger(), mlir::Type::isIntOrIndexOrFloat(), mlir::edsc::op::ne(), mlir::ConversionPatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPointToStart(), mlir::edsc::op::sge(), mlir::edsc::op::sgt(), shiftValue(), mlir::edsc::op::sle(), mlir::edsc::op::slt(), mlir::success(), mlir::edsc::op::uge(), mlir::edsc::op::ugt(), mlir::edsc::op::ule(), and mlir::edsc::op::ult().
getOffsetForBitwidth()
static Value getOffsetForBitwidth (Location loc, Value srcIdx, int sourceBits, int targetBits, OpBuilder & builder) static
Returns the offset of the value in targetBits representation.
srcIdx is an index into a 1-D array with each element having sourceBits. It's assumed to be non-negative.
When accessing an element in the array treating as having elements of targetBits, multiple values are loaded in the same time. The method returns the offset where the srcIdx locates in the value. For example, if sourceBits equals to 8 and targetBits equals to 32, the x-th element is located at (x % 4) * 8. Because there are four elements in one i32, and one element has 8 bits.
Definition at line 140 of file ConvertStandardToSPIRV.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getIntegerAttr(), and mlir::Builder::getIntegerType().
Referenced by getAtomicOpScope().
isAllocationSupported()
static bool isAllocationSupported (MemRefType t) static
Returns true if the allocations of type t can be lowered to SPIR-V.
Definition at line 221 of file ConvertStandardToSPIRV.cpp.
References mlir::Type::dyn_cast(), mlir::MemRefType::getMemorySpace(), mlir::SPIRVTypeConverter::getMemorySpaceForStorageClass(), and mlir::Type::isIntOrFloat().
Referenced by getAtomicOpScope().
isBoolScalarOrVector()
static bool isBoolScalarOrVector (Type type) static
Returns true if the given type is a boolean scalar or vector type.
Definition at line 32 of file ConvertStandardToSPIRV.cpp.
References mlir::Type::dyn_cast(), and mlir::Type::isInteger().
Referenced by getAtomicOpScope().
isUnsignedOp()
template<typename SPIRVOp > bool isUnsignedOp ()
Returns true if the operator is operating on unsigned integers.
TODO: Have a TreatOperandsAsUnsignedInteger trait and bake the information to the ops themselves.
Definition at line 194 of file ConvertStandardToSPIRV.cpp.
shiftValue()
static Value shiftValue (Location loc, Value value, Value offset, Value mask, int targetBits, OpBuilder & builder) static
Returns the shifted targetBits-bit value with the given offset.
Definition at line 182 of file ConvertStandardToSPIRV.cpp.
References mlir::OpBuilder::create(), and mlir::Builder::getIntegerType().
Referenced by getAtomicOpScope().