MLIR: lib/Target/LLVMIR/ConvertFromLLVMIR.cpp File Reference
ConvertFromLLVMIR.cpp File Reference
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/Target/LLVMIR.h"
#include "mlir/Target/LLVMIR/TypeTranslation.h"
#include "mlir/Translation.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Type.h"
#include "llvm/IRReader/IRReader.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/SourceMgr.h"
#include "mlir/Dialect/LLVMIR/LLVMConversionEnumsFromLLVM.inc"
Namespaces
mlir
Macros
#define INST(llvm_n, mlir_n) { llvm::Instruction::llvm_n, LLVM::mlir_n##Op::getOperationName() }
Functions
static std::string diag (llvm::Value &v)
static StringRef lookupOperationNameFromOpcode (unsigned opcode)
Return the MLIR OperationName for the given LLVM opcode.
static ICmpPredicate getICmpPredicate (llvm::CmpInst::Predicate p)
static AtomicOrdering getLLVMAtomicOrdering (llvm::AtomicOrdering ordering)
OwningModuleRef translateLLVMIRToModule (llvm::SourceMgr &sourceMgr, MLIRContext *context)
void mlir::registerFromLLVMIRTranslation ()
Macro Definition Documentation
INST
#define INST (llvm_n, mlir_n) { llvm::Instruction::llvm_n, LLVM::mlir_n##Op::getOperationName() }
Referenced by lookupOperationNameFromOpcode().
Function Documentation
diag()
static std::string diag (llvm::Value & v) static
Definition at line 39 of file ConvertFromLLVMIR.cpp.
References mlir::OperationState::addTypes(), mlir::Block::begin(), mlir::Constant, mlir::Type::dyn_cast_or_null(), mlir::emitError(), mlir::Block::end(), mlir::failed(), mlir::FileLineColLoc::get(), mlir::IntegerType::get(), mlir::UnknownLoc::get(), mlir::VectorType::get(), mlir::RankedTensorType::get(), mlir::DenseElementsAttr::get(), mlir::LLVM::LLVMType::getArrayElementType(), mlir::LLVM::LLVMType::getArrayNumElements(), mlir::ModuleOp::getBody(), mlir::FloatType::getF32(), mlir::FloatType::getF64(), mlir::LLVM::LLVMType::getIntegerBitWidth(), mlir::LLVM::LLVMType::getVectorElementCount(), mlir::LLVM::LLVMType::getVectorElementType(), mlir::LLVM::LLVMType::isArrayTy(), mlir::LLVM::LLVMType::isDoubleTy(), mlir::LLVM::LLVMType::isFloatTy(), mlir::LLVM::LLVMType::isIntegerTy(), mlir::LLVM::LLVMType::isVectorTy(), processValue(), and mlir::StandardAttributes::Type.
Referenced by adjustToDivisorsOfTripCounts(), mlir::linalg::LinalgMarker::checkAndNotify(), mlir::DiagnosticEngine::emit(), emitDiag(), mlir::SourceMgrDiagnosticHandler::emitDiagnostic(), mlir::Operation::emitError(), mlir::Operation::emitRemark(), mlir::Operation::emitWarning(), getLLVMAtomicOrdering(), logFailure(), mlir::PatternRewriter::notifyMatchFailure(), mlir::detail::ConversionPatternRewriterImpl::notifyMatchFailure(), mlir::detail::Parser::parseCommaSeparatedListUntil(), mlir::DiagnosticEngine::registerHandler(), mlir::detail::ConversionPatternRewriterImpl::remapValues(), mlir::SourceMgrDiagnosticHandler::SourceMgrDiagnosticHandler(), mlir::SourceMgrDiagnosticVerifierHandler::SourceMgrDiagnosticVerifierHandler(), mlir::SourceMgrDiagnosticVerifierHandler::verify(), and verifyTypesAlongAllEdges().
getICmpPredicate()
static ICmpPredicate getICmpPredicate (llvm::CmpInst::Predicate p) static
Definition at line 460 of file ConvertFromLLVMIR.cpp.
References mlir::edsc::op::eq(), mlir::edsc::op::ne(), mlir::edsc::op::sge(), mlir::edsc::op::sgt(), mlir::edsc::op::sle(), mlir::edsc::op::slt(), mlir::edsc::op::uge(), mlir::edsc::op::ugt(), mlir::edsc::op::ule(), and mlir::edsc::op::ult().
Referenced by getLLVMAtomicOrdering().
getLLVMAtomicOrdering()
static AtomicOrdering getLLVMAtomicOrdering (llvm::AtomicOrdering ordering) static
Definition at line 488 of file ConvertFromLLVMIR.cpp.
References mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Constant, mlir::Operation::create(), diag(), mlir::emitError(), mlir::emitWarning(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::UnknownLoc::get(), mlir::LLVM::LLVMType::getFunctionParamType(), getICmpPredicate(), mlir::Operation::getResult(), lookupOperationNameFromOpcode(), processValue(), mlir::Value::replaceAllUsesWith(), and mlir::success().
lookupOperationNameFromOpcode()
static StringRef lookupOperationNameFromOpcode (unsigned opcode) static
Return the MLIR OperationName for the given LLVM opcode.
Definition at line 406 of file ConvertFromLLVMIR.cpp.
References mlir::Add, INST, and mlir::Mul.
Referenced by getLLVMAtomicOrdering().
translateLLVMIRToModule()
OwningModuleRef translateLLVMIRToModule (llvm::SourceMgr & sourceMgr, MLIRContext * context)
Definition at line 857 of file ConvertFromLLVMIR.cpp.
References mlir::emitError(), mlir::UnknownLoc::get(), and mlir::translateLLVMIRToModule().
Referenced by mlir::registerFromLLVMIRTranslation().