MLIR: lib/Conversion/SPIRVToLLVM/ConvertSPIRVToLLVM.cpp File Reference
ConvertSPIRVToLLVM.cpp File Reference
#include "mlir/Conversion/SPIRVToLLVM/ConvertSPIRVToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "spirv-to-llvm-pattern"
#define DISPATCH(functionControl, llvmAttr)
Functions
static bool isSignedIntegerOrVector (Type type)
Returns true if the given type is a signed integer or vector type.
static bool isUnsignedIntegerOrVector (Type type)
Returns true if the given type is an unsigned integer or vector type.
static unsigned getBitWidth (Type type)
Returns the bit width of integer, float or vector of float or integer values.
static unsigned getLLVMTypeBitWidth (LLVM::LLVMType type)
Returns the bit width of LLVMType integer or vector.
static IntegerAttr minusOneIntegerAttribute (Type type, Builder builder)
Creates IntegerAttribute with all bits set for given type.
static Value createConstantAllBitsSet (Location loc, Type srcType, Type dstType, PatternRewriter &rewriter)
Creates llvm.mlir.constant with all bits set for the given type.
static Value createFPConstant (Location loc, Type srcType, Type dstType, PatternRewriter &rewriter, double value)
Creates llvm.mlir.constant with a floating-point scalar or vector value.
static Value optionallyTruncateOrExtend (Location loc, Value value, Type dstType, PatternRewriter &rewriter)
Utility function for bitfiled ops:
static Value broadcast (Location loc, Value toBroadcast, unsigned numElements, LLVMTypeConverter &typeConverter, ConversionPatternRewriter &rewriter)
Broadcasts the value to vector with numElements number of elements.
static Value optionallyBroadcast (Location loc, Value value, Type srcType, LLVMTypeConverter &typeConverter, ConversionPatternRewriter &rewriter)
Broadcasts the value. If srcType is a scalar, the value remains unchanged.
static Value processCountOrOffset (Location loc, Value value, Type srcType, Type dstType, LLVMTypeConverter &converter, ConversionPatternRewriter &rewriter)
Utility function for bitfiled ops: BitFieldInsert, BitFieldSExtract and BitFieldUExtract.
static Type convertStructTypePacked (spirv::StructType type, LLVMTypeConverter &converter)
Converts SPIR-V struct with no offset to packed LLVM struct.
static Value createI32ConstantOf (Location loc, PatternRewriter &rewriter, unsigned value)
Creates LLVM dialect constant with the given value.
static LogicalResult replaceWithLoadOrStore (Operation *op, ConversionPatternRewriter &rewriter, LLVMTypeConverter &typeConverter, unsigned alignment, bool isVolatile, bool isNonTemporal)
Utility for spv.Load and spv.Store conversion.
static Optional< Type > convertArrayType (spirv::ArrayType type, TypeConverter &converter)
Converts SPIR-V array type to LLVM array.
static Type convertPointerType (spirv::PointerType type, TypeConverter &converter)
Converts SPIR-V pointer type to LLVM pointer.
static Optional< Type > convertRuntimeArrayType (spirv::RuntimeArrayType type, TypeConverter &converter)
Converts SPIR-V runtime array to LLVM array.
static Optional< Type > convertStructType (spirv::StructType type, LLVMTypeConverter &converter)
Converts SPIR-V struct to LLVM struct.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-to-llvm-pattern"
Definition at line 26 of file ConvertSPIRVToLLVM.cpp.
DISPATCH
#define DISPATCH (functionControl, llvmAttr)
Value:
case functionControl:                                                        \
    newFuncOp.setAttr("passthrough", ArrayAttr::get({llvmAttr}, context));     \
    break;
Referenced by convertStructType().
Function Documentation
broadcast()
static Value broadcast (Location loc, Value toBroadcast, unsigned numElements, LLVMTypeConverter & typeConverter, ConversionPatternRewriter & rewriter) static
Broadcasts the value to vector with numElements number of elements.
Definition at line 137 of file ConvertSPIRVToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::VectorType::get(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getIntegerType(), and mlir::Value::getType().
Referenced by optionallyBroadcast().
convertArrayType()
static Optional<Type> convertArrayType (spirv::ArrayType type, TypeConverter & converter) static
Converts SPIR-V array type to LLVM array.
There is no modelling of array stride at the moment.
Definition at line 228 of file ConvertSPIRVToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::spirv::ArrayType::getArrayStride(), mlir::LLVM::LLVMType::getArrayTy(), mlir::spirv::ArrayType::getElementType(), and mlir::spirv::ArrayType::getNumElements().
Referenced by mlir::populateSPIRVToLLVMTypeConversion().
convertPointerType()
static Type convertPointerType (spirv::PointerType type, TypeConverter & converter) static
Converts SPIR-V pointer type to LLVM pointer.
Pointer's storage class is not modelled at the moment.
Definition at line 240 of file ConvertSPIRVToLLVM.cpp.
References mlir::TypeConverter::convertType(), and mlir::spirv::PointerType::getPointeeType().
Referenced by mlir::populateSPIRVToLLVMTypeConversion().
convertRuntimeArrayType()
static Optional<Type> convertRuntimeArrayType (spirv::RuntimeArrayType type, TypeConverter & converter) static
Converts SPIR-V runtime array to LLVM array.
Since LLVM allows indexing over the bounds, the runtime array is converted to a 0-sized LLVM array. There is no modelling of array stride at the moment.
Definition at line 250 of file ConvertSPIRVToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::spirv::RuntimeArrayType::getArrayStride(), mlir::LLVM::LLVMType::getArrayTy(), and mlir::spirv::RuntimeArrayType::getElementType().
Referenced by mlir::populateSPIRVToLLVMTypeConversion().
convertStructType()
static Optional<Type> convertStructType (spirv::StructType type, LLVMTypeConverter & converter) static
Converts SPIR-V struct to LLVM struct.
There is no support of structs with member decorations or with offset.
Definition at line 261 of file ConvertSPIRVToLLVM.cpp.
References mlir::ConversionPatternRewriter::convertRegionTypes(), convertStructTypePacked(), mlir::PatternRewriter::create(), createConstantAllBitsSet(), createFPConstant(), createI32ConstantOf(), DISPATCH, mlir::ConversionPatternRewriter::eraseBlock(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::IntegerType::get(), mlir::VectorType::get(), mlir::StringAttr::get(), mlir::DenseElementsAttr::get(), mlir::Block::getArguments(), getBitWidth(), mlir::OpBuilder::getBlock(), mlir::Builder::getContext(), mlir::Builder::getI32Type(), mlir::Builder::getI64IntegerAttr(), mlir::OpBuilder::getInsertionBlock(), mlir::OpBuilder::getInsertionPoint(), mlir::Builder::getIntegerAttr(), mlir::spirv::StructType::getMemberDecorations(), mlir::Operation::getOperands(), mlir::Block::getOperations(), mlir::Block::getTerminator(), mlir::spirv::StructType::hasOffset(), mlir::ConversionPatternRewriter::inlineRegionBefore(), mlir::Value::isa(), isSignedIntegerOrVector(), isUnsignedIntegerOrVector(), minusOneIntegerAttribute(), mlir::StandardTypes::None, processCountOrOffset(), mlir::ConversionPatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), replaceWithLoadOrStore(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::ConversionPatternRewriter::splitBlock(), and mlir::success().
Referenced by mlir::populateSPIRVToLLVMTypeConversion().
convertStructTypePacked()
static Type convertStructTypePacked (spirv::StructType type, LLVMTypeConverter & converter) static
Converts SPIR-V struct with no offset to packed LLVM struct.
Definition at line 183 of file ConvertSPIRVToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::spirv::StructType::getElementTypes(), and mlir::LLVM::LLVMType::getStructTy().
Referenced by convertStructType().
createConstantAllBitsSet()
static Value createConstantAllBitsSet (Location loc, Type srcType, Type dstType, PatternRewriter & rewriter) static
Creates llvm.mlir.constant with all bits set for the given type.
Definition at line 82 of file ConvertSPIRVToLLVM.cpp.
References mlir::Type::cast(), mlir::PatternRewriter::create(), mlir::DenseElementsAttr::get(), mlir::Type::isa(), and minusOneIntegerAttribute().
Referenced by convertStructType().
createFPConstant()
static Value createFPConstant (Location loc, Type srcType, Type dstType, PatternRewriter & rewriter, double value) static
Creates llvm.mlir.constant with a floating-point scalar or vector value.
Definition at line 95 of file ConvertSPIRVToLLVM.cpp.
References mlir::Value::cast(), mlir::Type::cast(), mlir::PatternRewriter::create(), mlir::Type::dyn_cast(), mlir::DenseElementsAttr::get(), and mlir::Builder::getFloatAttr().
Referenced by convertStructType().
createI32ConstantOf()
static Value createI32ConstantOf (Location loc, PatternRewriter & rewriter, unsigned value) static
Creates LLVM dialect constant with the given value.
Definition at line 194 of file ConvertSPIRVToLLVM.cpp.
References mlir::PatternRewriter::create(), mlir::Builder::getContext(), mlir::Builder::getI32Type(), mlir::LLVM::LLVMType::getInt32Ty(), and mlir::Builder::getIntegerAttr().
Referenced by convertStructType().
getBitWidth()
static unsigned getBitWidth (Type type) static
Returns the bit width of integer, float or vector of float or integer values.
Definition at line 53 of file ConvertSPIRVToLLVM.cpp.
References mlir::Type::dyn_cast(), mlir::Type::getIntOrFloatBitWidth(), mlir::Type::isa(), and mlir::Type::isIntOrFloat().
Referenced by convertStructType(), mlir::LLVM::LLVMType::getIntegerBitWidth(), and optionallyTruncateOrExtend().
getLLVMTypeBitWidth()
static unsigned getLLVMTypeBitWidth (LLVM::LLVMType type) static
Returns the bit width of LLVMType integer or vector.
Definition at line 66 of file ConvertSPIRVToLLVM.cpp.
References mlir::LLVM::LLVMType::getIntegerBitWidth(), mlir::LLVM::LLVMType::getVectorElementType(), and mlir::LLVM::LLVMType::isVectorTy().
Referenced by optionallyTruncateOrExtend().
isSignedIntegerOrVector()
static bool isSignedIntegerOrVector (Type type) static
Returns true if the given type is a signed integer or vector type.
Definition at line 35 of file ConvertSPIRVToLLVM.cpp.
References mlir::Type::dyn_cast(), and mlir::Type::isSignedInteger().
Referenced by convertStructType().
isUnsignedIntegerOrVector()
static bool isUnsignedIntegerOrVector (Type type) static
Returns true if the given type is an unsigned integer or vector type.
Definition at line 44 of file ConvertSPIRVToLLVM.cpp.
References mlir::Type::dyn_cast(), and mlir::Type::isUnsignedInteger().
Referenced by convertStructType().
minusOneIntegerAttribute()
static IntegerAttr minusOneIntegerAttribute (Type type, Builder builder) static
Creates IntegerAttribute with all bits set for given type.
Definition at line 72 of file ConvertSPIRVToLLVM.cpp.
References mlir::Type::cast(), mlir::Type::dyn_cast(), and mlir::Builder::getIntegerAttr().
Referenced by convertStructType(), and createConstantAllBitsSet().
optionallyBroadcast()
static Value optionallyBroadcast (Location loc, Value value, Type srcType, LLVMTypeConverter & typeConverter, ConversionPatternRewriter & rewriter) static
Broadcasts the value. If srcType is a scalar, the value remains unchanged.
Definition at line 154 of file ConvertSPIRVToLLVM.cpp.
References broadcast(), and mlir::Type::dyn_cast().
Referenced by processCountOrOffset().
optionallyTruncateOrExtend()
static Value optionallyTruncateOrExtend (Location loc, Value value, Type dstType, PatternRewriter & rewriter) static
Utility function for bitfiled ops:
BitFieldInsert
BitFieldSExtract
BitFieldUExtract Truncates or extends the value. If the bitwidth of the value is the same as dstType bitwidth, the value remains unchanged.
Definition at line 115 of file ConvertSPIRVToLLVM.cpp.
References mlir::Type::cast(), mlir::PatternRewriter::create(), getBitWidth(), getLLVMTypeBitWidth(), and mlir::Value::getType().
Referenced by processCountOrOffset().
processCountOrOffset()
static Value processCountOrOffset (Location loc, Value value, Type srcType, Type dstType, LLVMTypeConverter & converter, ConversionPatternRewriter & rewriter) static
Utility function for bitfiled ops: BitFieldInsert, BitFieldSExtract and BitFieldUExtract.
Broadcast Offset and Count to match the type of Base. If Base is of a vector type, construct a vector that has:
same number of elements as Base
each element has the type that is the same as the type of Offset or Count
each element has the same value as Offset or Count Then cast Offset and Count if their bit width is different from Base bit width.
Definition at line 174 of file ConvertSPIRVToLLVM.cpp.
References optionallyBroadcast(), and optionallyTruncateOrExtend().
Referenced by convertStructType().
replaceWithLoadOrStore()
static LogicalResult replaceWithLoadOrStore (Operation * op, ConversionPatternRewriter & rewriter, LLVMTypeConverter & typeConverter, unsigned alignment, bool isVolatile, bool isNonTemporal) static
Utility for spv.Load and spv.Store conversion.
Definition at line 202 of file ConvertSPIRVToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::failure(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
Referenced by convertStructType().