MLIR: lib/Dialect/Linalg/Transforms/Fusion.cpp File Reference
Fusion.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h"
#include "mlir/Dialect/Linalg/EDSC/FoldedIntrinsics.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/FoldUtils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
Classes
struct ViewDimension
Macros
#define DEBUG_TYPE "linalg-fusion"
Typedefs
using folded_std_constant_index = FoldedValueBuilder< ConstantIndexOp >
Functions
static LinalgOp cloneWithLoopRanges (OpBuilder &b, Location loc, LinalgOp op, ArrayRef< SubViewOp::Range > loopRanges)
Implements a simple high-level fusion pass of linalg library operations.
static ViewDimension getViewDefiningLoopRange (LinalgOp op, unsigned loopDepth)
static LinalgOp fuse (Value producedView, LinalgOp producer, LinalgOp consumer, unsigned consumerIdx, unsigned producerIdx, OperationFolder *folder)
static bool isStructurallyFusableProducer (LinalgOp producer, Value consumedView, LinalgOp consumer)
static bool isSameSubView (Value a, Value b)
static Optional< FusionInfo > fuseProducerOfDep (OpBuilder &b, LinalgOp consumer, unsigned consumerIdx, const LinalgDependenceGraph &graph, OperationFolder *folder, LinalgDependenceGraph::DependenceType depType)
static void fuseLinalgOpsGreedily (FuncOp f)
static AffineMap linearizeCollapsedDims (AffineMap sourceMap, ArrayRef< int64_t > sourceShape, ArrayRef< AffineMap > reassociationMaps)
Linearize the expressions in sourceMap based on the reassociationMaps provided, given the shape of the source tensor that corresponds to the sourceMap.
static bool isTensorReshapeOpFusible (TensorReshapeOp reshapeOp, AffineMap useIndexMap, bool asProducer)
Checks if the reshapeOp can be fused with it consumer (if asProducer is true) or its producer (if asProducer is false) given the indexing map at its use.
template<typename... Args>
static LinalgOp createLinalgOpOfSameType (LinalgOp op, PatternRewriter &rewriter, Args... args)
Based on the type of op create a linalg op of the same type, i.e.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-fusion"
Definition at line 32 of file Fusion.cpp.
Typedef Documentation
folded_std_constant_index
using folded_std_constant_index = FoldedValueBuilder<ConstantIndexOp>
Definition at line 39 of file Fusion.cpp.
Function Documentation
cloneWithLoopRanges()
static LinalgOp cloneWithLoopRanges (OpBuilder & b, Location loc, LinalgOp op, ArrayRef< SubViewOp::Range > loopRanges) static
Implements a simple high-level fusion pass of linalg library operations.
In each block, linalg ops are processed in reverse textual order. Given a linalg op O, fusion occurs by:
inspecting the linalg ops that write into the views read by O. This uses the SSA value of the views and a simple subview/slice analysis to determine producer-consumer dependences;
greedily fuse the linalg ops that produce subview
inspect the fused ops and determine whether they have other remaining LinalgOp uses. If not, then erase the original producing linalg op.
More advanced use cases, analyses as well as profitability heuristics are left for future work.
Definition at line 61 of file Fusion.cpp.
References mlir::Operation::clone(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::linalg::getAssumedNonViewOperands(), mlir::Value::replaceAllUsesExcept(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by fuse().
createLinalgOpOfSameType()
template<typename... Args> static LinalgOp createLinalgOpOfSameType (LinalgOp op, PatternRewriter & rewriter, Args... args) static
Based on the type of op create a linalg op of the same type, i.e.
if op is a linalg.generic operation, the create a linalg.generic operation with the given args. Expects op to be linalg.generic or linalg.indexed_generic.
Definition at line 748 of file Fusion.cpp.
References mlir::Region::begin(), mlir::Block::begin(), mlir::PatternRewriter::cloneRegionBefore(), mlir::concatAffineMaps(), mlir::PatternRewriter::create(), fuse(), mlir::AffineMapAttr::get(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArgument(), mlir::Builder::getArrayAttr(), mlir::Builder::getI64IntegerAttr(), mlir::Block::getNumArguments(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::Operation::getRegion(), mlir::AffineMap::getResults(), mlir::Operation::getResultTypes(), mlir::Builder::getUnknownLoc(), mlir::inversePermutation(), isTensorReshapeOpFusible(), linearizeCollapsedDims(), and mlir::BlockAndValueMapping::map().
fuse()
static LinalgOp fuse (Value producedView, LinalgOp producer, LinalgOp consumer, unsigned consumerIdx, unsigned producerIdx, OperationFolder * folder) static
Definition at line 157 of file Fusion.cpp.
References cloneWithLoopRanges(), mlir::detail::enumerate(), mlir::AffineMap::getResults(), getViewDefiningLoopRange(), and mlir::linalg::Range.
Referenced by createLinalgOpOfSameType(), fuseLinalgOpsGreedily(), fuseProducerOfDep(), and mlir::linalg::fuseTensorOps().
fuseLinalgOpsGreedily()
static void fuseLinalgOpsGreedily (FuncOp f) static
Definition at line 392 of file Fusion.cpp.
References mlir::Block::addArgument(), mlir::OpBuilder::clone(), mlir::AffineMap::compose(), mlir::PatternRewriter::create(), mlir::detail::enumerate(), mlir::Block::front(), fuse(), mlir::linalg::fuseProducerOf(), mlir::AffineMapAttr::get(), mlir::Block::getArgument(), mlir::Block::getArguments(), mlir::Builder::getArrayAttr(), mlir::OpState::getContext(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getIndexType(), mlir::AffineMap::getNumResults(), mlir::Block::getOperations(), mlir::Operation::getRegion(), mlir::AffineMap::getSubMap(), mlir::Builder::getUnknownLoc(), mlir::inversePermutation(), mlir::AffineMap::isPermutation(), mlir::BlockAndValueMapping::lookupOrNull(), mlir::BlockAndValueMapping::map(), mlir::FuncOp::print(), mlir::Region::push_back(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::OpState::walk().
Referenced by mlir::linalg::fuseTensorOps().
fuseProducerOfDep()
static Optional<FusionInfo> fuseProducerOfDep (OpBuilder & b, LinalgOp consumer, unsigned consumerIdx, const LinalgDependenceGraph & graph, OperationFolder * folder, LinalgDependenceGraph::DependenceType depType) static
Definition at line 323 of file Fusion.cpp.
References fuse(), mlir::linalg::LinalgDependenceGraph::getDependencesInto(), mlir::linalg::isFusableInto(), isSameSubView(), and mlir::OpBuilder::setInsertionPoint().
Referenced by mlir::linalg::fuseProducerOf().
getViewDefiningLoopRange()
static ViewDimension getViewDefiningLoopRange (LinalgOp op, unsigned loopDepth) static
Definition at line 132 of file Fusion.cpp.
References mlir::detail::enumerate().
Referenced by fuse().
isSameSubView()
static bool isSameSubView (Value a, Value b) static
Skip the "viewSource" operand.
Definition at line 294 of file Fusion.cpp.
References mlir::Value::getDefiningOp().
Referenced by fuseProducerOfDep().
isStructurallyFusableProducer()
static bool isStructurallyFusableProducer (LinalgOp producer, Value consumedView, LinalgOp consumer) static
Definition at line 219 of file Fusion.cpp.
Referenced by mlir::linalg::isProducerLastWriteOfView().
isTensorReshapeOpFusible()
static bool isTensorReshapeOpFusible (TensorReshapeOp reshapeOp, AffineMap useIndexMap, bool asProducer) static
Checks if the reshapeOp can be fused with it consumer (if asProducer is true) or its producer (if asProducer is false) given the indexing map at its use.
Definition at line 727 of file Fusion.cpp.
References mlir::AffineMap::isIdentity().
Referenced by createLinalgOpOfSameType().
linearizeCollapsedDims()
static AffineMap linearizeCollapsedDims (AffineMap sourceMap, ArrayRef< int64_t > sourceShape, ArrayRef< AffineMap > reassociationMaps) static
Linearize the expressions in sourceMap based on the reassociationMaps provided, given the shape of the source tensor that corresponds to the sourceMap.
Note that this implicitly assumes that the tensors dimensions are "row-major" ordered logically.
For example:
%0 = op ... : tensor<?x?x4x5xf32> with output index_map affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
and reshape: %1 = linalg.tensor_reshape %0 [affine_map<(i, j, k, l) -> (i)>, affine_map<(i, j, k, l) -> (j, k, l)>] : tensor<?x?x4x5xf32> into tensor<?x?xf32>
would be rewritten into: %0 = op ... : tensor<?x?x4x5xf32> with output index_map affine_map<(d0, d1, d2, d3) -> (d0, d1 * 20 + d2 * 5 + d3)>
Definition at line 699 of file Fusion.cpp.
References mlir::AffineMap::get(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), and mlir::makeCanonicalStridedLayoutExpr().
Referenced by createLinalgOpOfSameType().