MLIR: include/mlir-c/IR.h File Reference
IR.h File Reference
Classes
struct MlirNamedAttribute
Named MLIR attribute.
struct MlirOperationState
An auxiliary class for constructing operations.
Macros
#define DEFINE_C_API_STRUCT(name, storage)
Opaque type declarations.
Typedefs
typedef struct MlirNamedAttribute MlirNamedAttribute
typedef struct MlirOperationState MlirOperationState
Functions
DEFINE_C_API_STRUCT (MlirContext, void)
DEFINE_C_API_STRUCT (MlirOperation, void)
DEFINE_C_API_STRUCT (MlirBlock, void)
DEFINE_C_API_STRUCT (MlirRegion, void)
DEFINE_C_API_STRUCT (MlirValue, const void)
DEFINE_C_API_STRUCT (MlirAttribute, const void)
DEFINE_C_API_STRUCT (MlirType, const void)
DEFINE_C_API_STRUCT (MlirLocation, const void)
DEFINE_C_API_STRUCT (MlirModule, const void)
MlirContext mlirContextCreate ()
Creates an MLIR context and transfers its ownership to the caller.
void mlirContextDestroy (MlirContext context)
Takes an MLIR context owned by the caller and destroys it.
MlirLocation mlirLocationFileLineColGet (MlirContext context, const char *filename, unsigned line, unsigned col)
Creates an File/Line/Column location owned by the given context.
MlirLocation mlirLocationUnknownGet (MlirContext context)
Creates a location with unknown position owned by the given context.
MlirModule mlirModuleCreateEmpty (MlirLocation location)
Creates a new, empty module and transfers ownership to the caller.
MlirModule mlirModuleCreateParse (MlirContext context, const char *module)
Parses a module from the string and transfers ownership to the caller.
void mlirModuleDestroy (MlirModule module)
Takes a module owned by the caller and deletes it.
MlirOperation mlirModuleGetOperation (MlirModule module)
Views the module as a generic operation.
MlirOperationState mlirOperationStateGet (const char *name, MlirLocation loc)
Constructs an operation state from a name and a location.
void mlirOperationStateAddResults (MlirOperationState *state, unsigned n, MlirType *results)
Adds a list of components to the operation state.
void mlirOperationStateAddOperands (MlirOperationState *state, unsigned n, MlirValue *operands)
void mlirOperationStateAddOwnedRegions (MlirOperationState *state, unsigned n, MlirRegion *regions)
void mlirOperationStateAddSuccessors (MlirOperationState *state, unsigned n, MlirBlock *successors)
void mlirOperationStateAddAttributes (MlirOperationState *state, unsigned n, MlirNamedAttribute *attributes)
MlirOperation mlirOperationCreate (const MlirOperationState *state)
Creates an operation and transfers ownership to the caller.
void mlirOperationDestroy (MlirOperation op)
Takes an operation owned by the caller and destroys it.
int mlirOperationIsNull (MlirOperation op)
Checks whether the underlying operation is null.
unsigned mlirOperationGetNumRegions (MlirOperation op)
Returns the number of regions attached to the given operation.
MlirRegion mlirOperationGetRegion (MlirOperation op, unsigned pos)
Returns pos-th region attached to the operation.
MlirOperation mlirOperationGetNextInBlock (MlirOperation op)
Returns an operation immediately following the given operation it its enclosing block.
unsigned mlirOperationGetNumOperands (MlirOperation op)
Returns the number of operands of the operation.
MlirValue mlirOperationGetOperand (MlirOperation op, unsigned pos)
Returns pos-th operand of the operation.
unsigned mlirOperationGetNumResults (MlirOperation op)
Returns the number of results of the operation.
MlirValue mlirOperationGetResult (MlirOperation op, unsigned pos)
Returns pos-th result of the operation.
unsigned mlirOperationGetNumSuccessors (MlirOperation op)
Returns the number of successor blocks of the operation.
MlirBlock mlirOperationGetSuccessor (MlirOperation op, unsigned pos)
Returns pos-th successor of the operation.
unsigned mlirOperationGetNumAttributes (MlirOperation op)
Returns the number of attributes attached to the operation.
MlirNamedAttribute mlirOperationGetAttribute (MlirOperation op, unsigned pos)
Return pos-th attribute of the operation.
MlirAttribute mlirOperationGetAttributeByName (MlirOperation op, const char *name)
Returns an attrbute attached to the operation given its name.
void mlirOperationDump (MlirOperation op)
MlirRegion mlirRegionCreate ()
Creates a new empty region and transfers ownership to the caller.
void mlirRegionDestroy (MlirRegion region)
Takes a region owned by the caller and destroys it.
int mlirRegionIsNull (MlirRegion region)
Checks whether a region is null.
MlirBlock mlirRegionGetFirstBlock (MlirRegion region)
Gets the first block in the region.
void mlirRegionAppendOwnedBlock (MlirRegion region, MlirBlock block)
Takes a block owned by the caller and appends it to the given region.
void mlirRegionInsertOwnedBlock (MlirRegion region, unsigned pos, MlirBlock block)
Takes a block owned by the caller and inserts it at pos to the given region.
MlirBlock mlirBlockCreate (unsigned nArgs, MlirType *args)
Creates a new empty block with the given argument types and transfers ownership to the caller.
void mlirBlockDestroy (MlirBlock block)
Takes a block owned by the caller and destroys it.
int mlirBlockIsNull (MlirBlock block)
Checks whether a block is null.
MlirBlock mlirBlockGetNextInRegion (MlirBlock block)
Returns the block immediately following the given block in its parent region.
MlirOperation mlirBlockGetFirstOperation (MlirBlock block)
Returns the first operation in the block.
void mlirBlockAppendOwnedOperation (MlirBlock block, MlirOperation operation)
Takes an operation owned by the caller and appends it to the block.
void mlirBlockInsertOwnedOperation (MlirBlock block, unsigned pos, MlirOperation operation)
Takes an operation owned by the caller and inserts it as pos to the block.
unsigned mlirBlockGetNumArguments (MlirBlock block)
Returns the number of arguments of the block.
MlirValue mlirBlockGetArgument (MlirBlock block, unsigned pos)
Returns pos-th argument of the block.
MlirType mlirValueGetType (MlirValue value)
Returns the type of the value.
MlirType mlirTypeParseGet (MlirContext context, const char *type)
Parses a type.
void mlirTypeDump (MlirType type)
Prints the type to the standard error stream.
MlirAttribute mlirAttributeParseGet (MlirContext context, const char *attr)
Parses an attribute.
void mlirAttributeDump (MlirAttribute attr)
Prints the attrbute to the standard error stream.
MlirNamedAttribute mlirNamedAttributeGet (const char *name, MlirAttribute attr)
Associates an attribute with the name.
Macro Definition Documentation
DEFINE_C_API_STRUCT
#define DEFINE_C_API_STRUCT (name, storage)
Value:
struct name {                                                                \
    storage *ptr;                                                              \
  };                                                                           \
  typedef struct name name
Opaque type declarations.
Types are exposed to C bindings as structs containing opaque pointers. They are not supposed to be inspected from C. This allows the underlying representation to change without affecting the API users. The use of structs instead of typedefs enables some type safety as structs are not implicitly convertible to each other.
Instaces of these types may or may not own the underlying object (most often only point to an IR fragment without owning it). The ownership semantics is defined by how an instance of the type was obtained.
Definition at line 40 of file IR.h.
Typedef Documentation
MlirNamedAttribute
typedef struct MlirNamedAttribute MlirNamedAttribute
Definition at line 68 of file IR.h.
MlirOperationState
typedef struct MlirOperationState MlirOperationState
Definition at line 136 of file IR.h.
Function Documentation
DEFINE_C_API_STRUCT() [1/9]
DEFINE_C_API_STRUCT (MlirContext , void)
DEFINE_C_API_STRUCT() [2/9]
DEFINE_C_API_STRUCT (MlirOperation , void)
DEFINE_C_API_STRUCT() [3/9]
DEFINE_C_API_STRUCT (MlirBlock , void)
DEFINE_C_API_STRUCT() [4/9]
DEFINE_C_API_STRUCT (MlirRegion , void)
DEFINE_C_API_STRUCT() [5/9]
DEFINE_C_API_STRUCT (MlirValue , const void)
DEFINE_C_API_STRUCT() [6/9]
DEFINE_C_API_STRUCT (MlirAttribute , const void)
DEFINE_C_API_STRUCT() [7/9]
DEFINE_C_API_STRUCT (MlirType , const void)
DEFINE_C_API_STRUCT() [8/9]
DEFINE_C_API_STRUCT (MlirLocation , const void)
DEFINE_C_API_STRUCT() [9/9]
DEFINE_C_API_STRUCT (MlirModule , const void)
mlirAttributeDump()
void mlirAttributeDump (MlirAttribute attr)
Prints the attrbute to the standard error stream.
Definition at line 337 of file IR.cpp.
References mlir::Type::dump(), and unwrap().
mlirAttributeParseGet()
MlirAttribute mlirAttributeParseGet (MlirContext context, const char * attr)
Parses an attribute.
The attribute is owned by the context.
Definition at line 333 of file IR.cpp.
References mlir::parseAttribute(), and unwrap().
mlirBlockAppendOwnedOperation()
void mlirBlockAppendOwnedOperation (MlirBlock block, MlirOperation operation)
Takes an operation owned by the caller and appends it to the block.
Definition at line 289 of file IR.cpp.
References unwrap().
mlirBlockCreate()
MlirBlock mlirBlockCreate (unsigned nArgs, MlirType * args)
Creates a new empty block with the given argument types and transfers ownership to the caller.
Definition at line 271 of file IR.cpp.
References mlir::Block::addArgument(), and unwrap().
mlirBlockDestroy()
void mlirBlockDestroy (MlirBlock block)
Takes a block owned by the caller and destroys it.
Definition at line 299 of file IR.cpp.
References unwrap().
mlirBlockGetArgument()
MlirValue mlirBlockGetArgument (MlirBlock block, unsigned pos)
Returns pos-th argument of the block.
Definition at line 307 of file IR.cpp.
References unwrap().
mlirBlockGetFirstOperation()
MlirOperation mlirBlockGetFirstOperation (MlirBlock block)
Returns the first operation in the block.
Definition at line 282 of file IR.cpp.
References mlir::Block::empty(), mlir::Block::front(), and unwrap().
mlirBlockGetNextInRegion()
MlirBlock mlirBlockGetNextInRegion (MlirBlock block)
Returns the block immediately following the given block in its parent region.
Definition at line 278 of file IR.cpp.
References unwrap().
mlirBlockGetNumArguments()
unsigned mlirBlockGetNumArguments (MlirBlock block)
Returns the number of arguments of the block.
Definition at line 303 of file IR.cpp.
References unwrap().
mlirBlockInsertOwnedOperation()
void mlirBlockInsertOwnedOperation (MlirBlock block, unsigned pos, MlirOperation operation)
Takes an operation owned by the caller and inserts it as pos to the block.
Definition at line 293 of file IR.cpp.
References unwrap().
mlirBlockIsNull()
int mlirBlockIsNull (MlirBlock block)
Checks whether a block is null.
Definition at line 301 of file IR.cpp.
References unwrap().
mlirContextCreate()
MlirContext mlirContextCreate ()
Creates an MLIR context and transfers its ownership to the caller.
Definition at line 63 of file IR.cpp.
mlirContextDestroy()
void mlirContextDestroy (MlirContext context)
Takes an MLIR context owned by the caller and destroys it.
Definition at line 68 of file IR.cpp.
References unwrap().
mlirLocationFileLineColGet()
MlirLocation mlirLocationFileLineColGet (MlirContext context, const char * filename, unsigned line, unsigned col)
Creates an File/Line/Column location owned by the given context.
Definition at line 74 of file IR.cpp.
References mlir::FileLineColLoc::get(), and unwrap().
mlirLocationUnknownGet()
MlirLocation mlirLocationUnknownGet (MlirContext context)
Creates a location with unknown position owned by the given context.
Definition at line 80 of file IR.cpp.
References mlir::UnknownLoc::get(), and unwrap().
mlirModuleCreateEmpty()
MlirModule mlirModuleCreateEmpty (MlirLocation location)
Creates a new, empty module and transfers ownership to the caller.
Definition at line 88 of file IR.cpp.
References mlir::ModuleOp::create(), and unwrap().
mlirModuleCreateParse()
MlirModule mlirModuleCreateParse (MlirContext context, const char * module)
Parses a module from the string and transfers ownership to the caller.
Definition at line 92 of file IR.cpp.
References mlir::Op< ConcreteType, Traits >::getOperation(), mlir::parseSourceString(), mlir::OwningOpRefBase< OpTy >::release(), and unwrap().
mlirModuleDestroy()
void mlirModuleDestroy (MlirModule module)
Takes a module owned by the caller and deletes it.
Definition at line 97 of file IR.cpp.
References unwrap().
mlirModuleGetOperation()
MlirOperation mlirModuleGetOperation (MlirModule module)
Views the module as a generic operation.
Definition at line 102 of file IR.cpp.
References unwrap().
mlirNamedAttributeGet()
MlirNamedAttribute mlirNamedAttributeGet (const char * name, MlirAttribute attr)
Associates an attribute with the name.
Takes ownership of neither.
Definition at line 339 of file IR.cpp.
mlirOperationCreate()
MlirOperation mlirOperationCreate (const MlirOperationState * state)
Creates an operation and transfers ownership to the caller.
Definition at line 159 of file IR.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addSuccessors(), mlir::OperationState::addTypes(), MlirNamedAttribute::attribute, MlirOperationState::attributes, mlir::OperationState::attributes, mlir::Operation::create(), MlirOperationState::location, MlirNamedAttribute::name, MlirOperationState::name, MlirOperationState::nAttributes, MlirOperationState::nOperands, MlirOperationState::nRegions, MlirOperationState::nResults, MlirOperationState::nSuccessors, MlirOperationState::operands, MlirOperationState::regions, mlir::NamedAttrList::reserve(), MlirOperationState::results, MlirOperationState::successors, unwrap(), and unwrapList().
mlirOperationDestroy()
void mlirOperationDestroy (MlirOperation op)
Takes an operation owned by the caller and destroys it.
Definition at line 182 of file IR.cpp.
References unwrap().
mlirOperationDump()
void mlirOperationDump (MlirOperation op)
Definition at line 236 of file IR.cpp.
References mlir::Type::dump(), and unwrap().
mlirOperationGetAttribute()
MlirNamedAttribute mlirOperationGetAttribute (MlirOperation op, unsigned pos)
Return pos-th attribute of the operation.
Definition at line 226 of file IR.cpp.
References unwrap().
mlirOperationGetAttributeByName()
MlirAttribute mlirOperationGetAttributeByName (MlirOperation op, const char * name)
Returns an attrbute attached to the operation given its name.
Definition at line 231 of file IR.cpp.
References unwrap().
mlirOperationGetNextInBlock()
MlirOperation mlirOperationGetNextInBlock (MlirOperation op)
Returns an operation immediately following the given operation it its enclosing block.
Definition at line 194 of file IR.cpp.
References unwrap().
mlirOperationGetNumAttributes()
unsigned mlirOperationGetNumAttributes (MlirOperation op)
Returns the number of attributes attached to the operation.
Definition at line 222 of file IR.cpp.
References unwrap().
mlirOperationGetNumOperands()
unsigned mlirOperationGetNumOperands (MlirOperation op)
Returns the number of operands of the operation.
Definition at line 198 of file IR.cpp.
References unwrap().
mlirOperationGetNumRegions()
unsigned mlirOperationGetNumRegions (MlirOperation op)
Returns the number of regions attached to the given operation.
Definition at line 186 of file IR.cpp.
References unwrap().
mlirOperationGetNumResults()
unsigned mlirOperationGetNumResults (MlirOperation op)
Returns the number of results of the operation.
Definition at line 206 of file IR.cpp.
References unwrap().
mlirOperationGetNumSuccessors()
unsigned mlirOperationGetNumSuccessors (MlirOperation op)
Returns the number of successor blocks of the operation.
Definition at line 214 of file IR.cpp.
References unwrap().
mlirOperationGetOperand()
MlirValue mlirOperationGetOperand (MlirOperation op, unsigned pos)
Returns pos-th operand of the operation.
Definition at line 202 of file IR.cpp.
References unwrap().
mlirOperationGetRegion()
MlirRegion mlirOperationGetRegion (MlirOperation op, unsigned pos)
Returns pos-th region attached to the operation.
Definition at line 190 of file IR.cpp.
References unwrap().
mlirOperationGetResult()
MlirValue mlirOperationGetResult (MlirOperation op, unsigned pos)
Returns pos-th result of the operation.
Definition at line 210 of file IR.cpp.
References unwrap().
mlirOperationGetSuccessor()
MlirBlock mlirOperationGetSuccessor (MlirOperation op, unsigned pos)
Returns pos-th successor of the operation.
Definition at line 218 of file IR.cpp.
References unwrap().
mlirOperationIsNull()
int mlirOperationIsNull (MlirOperation op)
Checks whether the underlying operation is null.
Definition at line 184 of file IR.cpp.
References unwrap().
mlirOperationStateAddAttributes()
void mlirOperationStateAddAttributes (MlirOperationState * state, unsigned n, MlirNamedAttribute * attributes)
Definition at line 150 of file IR.cpp.
References APPEND_ELEMS.
mlirOperationStateAddOperands()
void mlirOperationStateAddOperands (MlirOperationState * state, unsigned n, MlirValue * operands)
Definition at line 138 of file IR.cpp.
References APPEND_ELEMS.
mlirOperationStateAddOwnedRegions()
void mlirOperationStateAddOwnedRegions (MlirOperationState * state, unsigned n, MlirRegion * regions)
Definition at line 142 of file IR.cpp.
References APPEND_ELEMS.
mlirOperationStateAddResults()
void mlirOperationStateAddResults (MlirOperationState * state, unsigned n, MlirType * results)
Adds a list of components to the operation state.
Definition at line 133 of file IR.cpp.
References APPEND_ELEMS.
mlirOperationStateAddSuccessors()
void mlirOperationStateAddSuccessors (MlirOperationState * state, unsigned n, MlirBlock * successors)
Definition at line 146 of file IR.cpp.
References APPEND_ELEMS.
mlirOperationStateGet()
MlirOperationState mlirOperationStateGet (const char * name, MlirLocation loc)
Constructs an operation state from a name and a location.
Definition at line 110 of file IR.cpp.
References MlirOperationState::attributes, MlirOperationState::location, MlirOperationState::name, MlirOperationState::nAttributes, MlirOperationState::nOperands, MlirOperationState::nRegions, MlirOperationState::nResults, MlirOperationState::nSuccessors, MlirOperationState::operands, MlirOperationState::regions, MlirOperationState::results, and MlirOperationState::successors.
mlirRegionAppendOwnedBlock()
void mlirRegionAppendOwnedBlock (MlirRegion region, MlirBlock block)
Takes a block owned by the caller and appends it to the given region.
Definition at line 251 of file IR.cpp.
References unwrap().
mlirRegionCreate()
MlirRegion mlirRegionCreate ()
Creates a new empty region and transfers ownership to the caller.
Definition at line 242 of file IR.cpp.
mlirRegionDestroy()
void mlirRegionDestroy (MlirRegion region)
Takes a region owned by the caller and destroys it.
Definition at line 261 of file IR.cpp.
mlirRegionGetFirstBlock()
MlirBlock mlirRegionGetFirstBlock (MlirRegion region)
Gets the first block in the region.
Definition at line 244 of file IR.cpp.
References mlir::Region::empty(), mlir::Region::front(), and unwrap().
mlirRegionInsertOwnedBlock()
void mlirRegionInsertOwnedBlock (MlirRegion region, unsigned pos, MlirBlock block)
Takes a block owned by the caller and inserts it at pos to the given region.
Definition at line 255 of file IR.cpp.
References unwrap().
mlirRegionIsNull()
int mlirRegionIsNull (MlirRegion region)
Checks whether a region is null.
Definition at line 265 of file IR.cpp.
References unwrap().
mlirTypeDump()
void mlirTypeDump (MlirType type)
Prints the type to the standard error stream.
Definition at line 327 of file IR.cpp.
References mlir::Type::dump(), and unwrap().
mlirTypeParseGet()
MlirType mlirTypeParseGet (MlirContext context, const char * type)
Parses a type.
The type is owned by the context.
Definition at line 323 of file IR.cpp.
References mlir::parseType(), and unwrap().
mlirValueGetType()
MlirType mlirValueGetType (MlirValue value)
Returns the type of the value.
Definition at line 315 of file IR.cpp.
References unwrap().