MLIR: lib/Pass/IRPrinting.cpp File Reference
IRPrinting.cpp File Reference
#include "PassDetail.h"
#include "mlir/IR/Module.h"
#include "mlir/Pass/PassManager.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/SHA1.h"
Functions
static bool isHiddenPass (Pass *pass)
Returns true if the given pass is hidden from IR printing.
static void printIR (Operation *op, bool printModuleScope, raw_ostream &out, OpPrintingFlags flags)
Function Documentation
isHiddenPass()
static bool isHiddenPass (Pass * pass) static
Returns true if the given pass is hidden from IR printing.
Definition at line 99 of file IRPrinting.cpp.
Referenced by printIR().
printIR()
static void printIR (Operation * op, bool printModuleScope, raw_ostream & out, OpPrintingFlags flags) static
Definition at line 103 of file IRPrinting.cpp.
References mlir::Operation::getAttrOfType(), mlir::Operation::getBlock(), mlir::Operation::getName(), mlir::Pass::getName(), mlir::SymbolTable::getSymbolAttrName(), isHiddenPass(), mlir::ModuleOp::print(), mlir::Operation::print(), mlir::OpPrintingFlags::printGenericOpForm(), and mlir::OpPrintingFlags::useLocalScope().