MLIR: lib/Analysis/Liveness.cpp File Reference
Liveness.cpp File Reference
#include "mlir/Analysis/Liveness.h"
#include "mlir/IR/Block.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/Region.h"
#include "mlir/IR/Value.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/raw_ostream.h"
Functions
template<typename FuncT >
static void walkRegions (MutableArrayRef< Region > regions, const FuncT &func)
Walks all regions (including nested regions recursively) and invokes the given function for every block.
static void buildBlockMapping (MutableArrayRef< Region > regions, DenseMap< Block *, BlockInfoBuilder > &builders)
Builds the internal liveness block mapping.
Function Documentation
buildBlockMapping()
static void buildBlockMapping (MutableArrayRef< Region > regions, DenseMap< Block *, BlockInfoBuilder > & builders) static
Builds the internal liveness block mapping.
Definition at line 143 of file Liveness.cpp.
References mlir::Block::pred_begin(), mlir::Block::pred_end(), and walkRegions().
Referenced by mlir::Liveness::Liveness().
walkRegions()
template<typename FuncT > static void walkRegions (MutableArrayRef< Region > regions, const FuncT & func) static
Walks all regions (including nested regions recursively) and invokes the given function for every block.
Definition at line 131 of file Liveness.cpp.
Referenced by buildBlockMapping(), and mlir::Liveness::print().