MLIR: lib/Dialect/LLVMIR/IR/LLVMTypeSyntax.cpp File Reference
LLVMTypeSyntax.cpp File Reference
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/SetVector.h"
Functions
static void printTypeImpl (llvm::raw_ostream &os, LLVMType type, llvm::SetVector< StringRef > &stack)
Prints the given LLVM dialect type recursively.
static StringRef getTypeKeyword (LLVMType type)
Returns the keyword to use for the given type.
static void printStructTypeBody (llvm::raw_ostream &os, LLVMStructType type, llvm::SetVector< StringRef > &stack)
Prints the body of a structure type.
static void printStructType (llvm::raw_ostream &os, LLVMStructType type, llvm::SetVector< StringRef > &stack)
Prints a structure type.
template<typename TypeTy >
static void printArrayOrVectorType (llvm::raw_ostream &os, TypeTy type, llvm::SetVector< StringRef > &stack)
Prints a type containing a fixed number of elements.
static void printFunctionType (llvm::raw_ostream &os, LLVMFunctionType funcType, llvm::SetVector< StringRef > &stack)
Prints a function type.
static LLVMType parseTypeImpl (DialectAsmParser &parser, llvm::SetVector< StringRef > &stack)
Parses one of the LLVM dialect types.
static ParseResult parseTypeImpl (DialectAsmParser &parser, llvm::SetVector< StringRef > &stack, LLVMType &result)
Helper to be chained with other parsing functions.
static LLVMFunctionType parseFunctionType (DialectAsmParser &parser, llvm::SetVector< StringRef > &stack)
Parses an LLVM dialect function type.
static LLVMPointerType parsePointerType (DialectAsmParser &parser, llvm::SetVector< StringRef > &stack)
Parses an LLVM dialect pointer type.
static LLVMVectorType parseVectorType (DialectAsmParser &parser, llvm::SetVector< StringRef > &stack)
Parses an LLVM dialect vector type.
static LLVMArrayType parseArrayType (DialectAsmParser &parser, llvm::SetVector< StringRef > &stack)
Parses an LLVM dialect array type.
static LLVMStructType trySetStructBody (LLVMStructType type, ArrayRef< LLVMType > subtypes, bool isPacked, DialectAsmParser &parser, llvm::SMLoc subtypesLoc, llvm::SetVector< StringRef > &stack)
Attempts to set the body of an identified structure type.
static LLVMStructType parseStructType (DialectAsmParser &parser, llvm::SetVector< StringRef > &stack)
Parses an LLVM dialect structure type.
Function Documentation
getTypeKeyword()
static StringRef getTypeKeyword (LLVMType type) static
Returns the keyword to use for the given type.
Definition at line 25 of file LLVMTypeSyntax.cpp.
References mlir::LLVM::LLVMType::ArrayType, mlir::LLVM::LLVMType::BFloatType, mlir::LLVM::LLVMType::DoubleType, mlir::LLVM::LLVMType::FixedVectorType, mlir::LLVM::LLVMType::FloatType, mlir::LLVM::LLVMType::FP128Type, mlir::LLVM::LLVMType::FunctionType, mlir::Type::getKind(), mlir::LLVM::LLVMType::HalfType, mlir::LLVM::LLVMType::IntegerType, mlir::LLVM::LLVMType::LabelType, mlir::LLVM::LLVMType::MetadataType, mlir::LLVM::LLVMType::PointerType, mlir::LLVM::LLVMType::PPCFP128Type, mlir::LLVM::LLVMType::ScalableVectorType, mlir::LLVM::LLVMType::StructType, mlir::LLVM::LLVMType::TokenType, mlir::LLVM::LLVMType::VoidType, mlir::LLVM::LLVMType::X86FP80Type, and mlir::LLVM::LLVMType::X86MMXType.
parseArrayType()
static LLVMArrayType parseArrayType (DialectAsmParser & parser, llvm::SetVector< StringRef > & stack) static
Parses an LLVM dialect array type.
llvm-type ::= array< integer x llvm-type >
Definition at line 301 of file LLVMTypeSyntax.cpp.
parseFunctionType()
static LLVMFunctionType parseFunctionType (DialectAsmParser & parser, llvm::SetVector< StringRef > & stack) static
Parses an LLVM dialect function type.
llvm-type :: = func< llvm-type (llvm-type-list ...?)>
Definition at line 218 of file LLVMTypeSyntax.cpp.
parsePointerType()
static LLVMPointerType parsePointerType (DialectAsmParser & parser, llvm::SetVector< StringRef > & stack) static
Parses an LLVM dialect pointer type.
llvm-type ::= ptr< llvm-type (, integer)? >
Definition at line 253 of file LLVMTypeSyntax.cpp.
parseStructType()
static LLVMStructType parseStructType (DialectAsmParser & parser, llvm::SetVector< StringRef > & stack) static
Parses an LLVM dialect structure type.
llvm-type ::= struct< (string-literal ,)? packed? (llvm-type-list) > | struct< string-literal > | struct< string-literal , opaque>
Definition at line 344 of file LLVMTypeSyntax.cpp.
parseTypeImpl() [1/2]
static LLVMType parseTypeImpl (DialectAsmParser & parser, llvm::SetVector< StringRef > & stack) static
Parses one of the LLVM dialect types.
Definition at line 423 of file LLVMTypeSyntax.cpp.
parseTypeImpl() [2/2]
static ParseResult parseTypeImpl (DialectAsmParser & parser, llvm::SetVector< StringRef > & stack, LLVMType & result) static
Helper to be chained with other parsing functions.
Definition at line 209 of file LLVMTypeSyntax.cpp.
parseVectorType()
static LLVMVectorType parseVectorType (DialectAsmParser & parser, llvm::SetVector< StringRef > & stack) static
Parses an LLVM dialect vector type.
llvm-type ::= vec< ? x? integer x llvm-type > Supports both fixed and scalable vectors.
Definition at line 271 of file LLVMTypeSyntax.cpp.
printArrayOrVectorType()
template<typename TypeTy > static void printArrayOrVectorType (llvm::raw_ostream & os, TypeTy type, llvm::SetVector< StringRef > & stack) static
Prints a type containing a fixed number of elements.
Definition at line 116 of file LLVMTypeSyntax.cpp.
printFunctionType()
static void printFunctionType (llvm::raw_ostream & os, LLVMFunctionType funcType, llvm::SetVector< StringRef > & stack) static
Prints a function type.
Definition at line 124 of file LLVMTypeSyntax.cpp.
printStructType()
static void printStructType (llvm::raw_ostream & os, LLVMStructType type, llvm::SetVector< StringRef > & stack) static
Prints a structure type.
Uses stack to keep track of the identifiers of the structs being printed. Checks if the identifier of a struct is contained in stack, i.e. whether a self-reference to a recursive stack is being printed, and only prints the name to avoid infinite recursion.
Definition at line 96 of file LLVMTypeSyntax.cpp.
References mlir::LLVM::LLVMStructType::getName(), and mlir::LLVM::LLVMStructType::isIdentified().
printStructTypeBody()
static void printStructTypeBody (llvm::raw_ostream & os, LLVMStructType type, llvm::SetVector< StringRef > & stack) static
Prints the body of a structure type.
Uses stack to avoid printing recursive structs indefinitely.
Definition at line 70 of file LLVMTypeSyntax.cpp.
References mlir::LLVM::LLVMStructType::getBody(), mlir::LLVM::LLVMStructType::getName(), mlir::LLVM::LLVMStructType::isIdentified(), mlir::LLVM::LLVMStructType::isOpaque(), mlir::LLVM::LLVMStructType::isPacked(), and printTypeImpl().
printTypeImpl()
static void printTypeImpl (llvm::raw_ostream & os, LLVMType type, llvm::SetVector< StringRef > & stack) static
Prints the given LLVM dialect type recursively.
This leverages closedness of the LLVM dialect type system to avoid printing the dialect prefix repeatedly. For recursive structures, only prints the name of the structure when printing a self-reference. Note that this does not apply to sibling references. For example, struct<"a", (ptr<struct<"a">>)> struct<"c", (ptr<struct<"b", (ptr<struct<"c">>)>>, ptr<struct<"b", (ptr<struct<"c">>)>>)> note that "b" is printed twice.
Definition at line 149 of file LLVMTypeSyntax.cpp.
Referenced by printStructTypeBody().
trySetStructBody()
static LLVMStructType trySetStructBody (LLVMStructType type, ArrayRef< LLVMType > subtypes, bool isPacked, DialectAsmParser & parser, llvm::SMLoc subtypesLoc, llvm::SetVector< StringRef > & stack) static
Attempts to set the body of an identified structure type.
Reports a parsing error at subtypesLoc in case of failure, uses stack to make sure the types printed in the error message look like they did when parsed.
Definition at line 322 of file LLVMTypeSyntax.cpp.