MLIR: lib/Dialect/Linalg/Transforms/Loops.cpp File Reference
Loops.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/EDSC/Intrinsics.h"
#include "mlir/Dialect/Linalg/EDSC/FoldedIntrinsics.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/SCF/EDSC/Builders.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Classes
struct InputAndOutputIndices
Macros
#define GET_OP_LIST
Functions
static SmallVector< Value, 8 > makeCanonicalAffineApplies (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > vals)
static SmallVector< Value, 4 > permuteIvs (ArrayRef< Value > ivs, Optional< AffineMap > permutation)
static SmallVector< SubViewOp::Range, 4 > emitLoopRanges (OpBuilder &b, Location loc, AffineMap map, ValueRange viewSizes)
Creates a number of ranges equal to the number of dimensions in the map.
template<typename IndexedValueType , typename OpType >
static void inlineRegionAndEmitStore (OpType op, ArrayRef< Value > indexedValues, ArrayRef< SmallVector< Value, 8 >> indexing, ArrayRef< Value > outputBuffers)
template<typename SingleInputPoolingOp >
static InputAndOutputIndices getInputAndOutputIndices (ArrayRef< Value > allIvs, SingleInputPoolingOp op)
template<typename LoopType >
static void lowerLinalgToLoopsImpl (FuncOp funcOp, MLIRContext *context)
template<typename LoopTy >
static Optional< LinalgLoops > linalgOpToLoopsImplSwitch (Operation *op, OpBuilder &builder)
template Optional< LinalgLoops > mlir::linalg::linalgLowerOpToLoops< scf::ForOp > (OpBuilder &builder, Operation *op)
template Optional< LinalgLoops > mlir::linalg::linalgLowerOpToLoops< scf::ParallelOp > (OpBuilder &builder, Operation *op)
Macro Definition Documentation
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
emitLoopRanges()
static SmallVector<SubViewOp::Range, 4> emitLoopRanges (OpBuilder & b, Location loc, AffineMap map, ValueRange viewSizes) static
Creates a number of ranges equal to the number of dimensions in the map.
The returned ranges correspond to the loop ranges, in the proper order, for which new loops will be created. The function supports only maps that are invertible and have results of type DimExpr or (DimExpr + DimExpr - SymbolExpr floordiv ConstExpr). It expects a non-inverted, concatenated map and last values in allViewSizes will be applied to the symbols in the map if it contains any.
Definition at line 68 of file Loops.cpp.
References mlir::Add, mlir::linalg::applyMapToValues(), mlir::Constant, mlir::AffineExpr::dyn_cast(), mlir::FloorDiv, mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::getAffineSymbolExpr(), mlir::AffineExpr::getKind(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineSymbolExpr::getPosition(), mlir::AffineMap::getResult(), mlir::AffineBinaryOpExpr::getRHS(), mlir::Mul, mlir::linalg::Range, and mlir::SymbolId.
Referenced by getInputAndOutputIndices().
getInputAndOutputIndices()
template<typename SingleInputPoolingOp > static InputAndOutputIndices getInputAndOutputIndices (ArrayRef< Value > allIvs, SingleInputPoolingOp op) static
Definition at line 165 of file Loops.cpp.
References mlir::Type::cast(), mlir::concatAffineMaps(), mlir::AffineExpr::dyn_cast(), mlir::Value::dyn_cast(), emitLoopRanges(), mlir::detail::enumerate(), mlir::PatternRewriter::eraseOp(), mlir::failure(), mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), getElementType(), mlir::Operation::getLoc(), mlir::edsc::ScopedContext::getLocation(), mlir::Operation::getOperand(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::AffineMapAttr::getValue(), mlir::linalg::getViewSizes(), InputAndOutputIndices::inputs, mlir::OwningRewritePatternList::insert(), makeCanonicalAffineApplies(), InputAndOutputIndices::outputs, permuteIvs(), mlir::PatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::edsc::op::sge(), mlir::edsc::op::sgt(), mlir::edsc::op::slt(), and mlir::success().
inlineRegionAndEmitStore()
template<typename IndexedValueType , typename OpType > static void inlineRegionAndEmitStore (OpType op, ArrayRef< Value > indexedValues, ArrayRef< SmallVector< Value, 8 >> indexing, ArrayRef< Value > outputBuffers) static
Definition at line 134 of file Loops.cpp.
References mlir::edsc::ScopedContext::getBuilderRef(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::BlockAndValueMapping::lookupOrDefault(), and mlir::BlockAndValueMapping::map().
linalgOpToLoopsImplSwitch()
template<typename LoopTy > static Optional<LinalgLoops> linalgOpToLoopsImplSwitch (Operation * op, OpBuilder & builder) static
Definition at line 657 of file Loops.cpp.
lowerLinalgToLoopsImpl()
template<typename LoopType > static void lowerLinalgToLoopsImpl (FuncOp funcOp, MLIRContext * context) static
Definition at line 604 of file Loops.cpp.
References mlir::applyPatternsAndFoldGreedily().
makeCanonicalAffineApplies()
static SmallVector<Value, 8> makeCanonicalAffineApplies (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > vals) static
Definition at line 33 of file Loops.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), and mlir::AffineMap::isEmpty().
Referenced by getInputAndOutputIndices().
mlir::linalg::linalgLowerOpToLoops< scf::ForOp >()
template Optional<LinalgLoops> mlir::linalg::linalgLowerOpToLoops< scf::ForOp > (OpBuilder & builder, Operation * op)
mlir::linalg::linalgLowerOpToLoops< scf::ParallelOp >()
template Optional<LinalgLoops> mlir::linalg::linalgLowerOpToLoops< scf::ParallelOp > (OpBuilder & builder, Operation * op)
permuteIvs()
static SmallVector<Value, 4> permuteIvs (ArrayRef< Value > ivs, Optional< AffineMap > permutation) static
Definition at line 53 of file Loops.cpp.
References mlir::linalg::applyMapToValues(), mlir::edsc::ScopedContext::getBuilderRef(), and mlir::edsc::ScopedContext::getLocation().
Referenced by getInputAndOutputIndices().