MLIR: lib/Transforms/LoopFusion.cpp File Reference
LoopFusion.cpp File Reference
#include "PassDetail.h"
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/LoopAnalysis.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/Transforms/LoopFusionUtils.h"
#include "mlir/Transforms/LoopUtils.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <iomanip>
#include <sstream>
Macros
#define DEBUG_TYPE "affine-loop-fusion"
Functions
static bool isMemRefDereferencingOp (Operation &op)
static void moveLoadsAccessingMemrefTo (Value memref, SmallVectorImpl< Operation *> *srcLoads, SmallVectorImpl< Operation *> *dstLoads)
static unsigned getInnermostCommonLoopDepth (ArrayRef< Operation *> ops)
static unsigned getMaxLoopDepth (ArrayRef< Operation *> loadOpInsts, ArrayRef< Operation *> storeOpInsts)
static void sinkSequentialLoops (MemRefDependenceGraph::Node *node)
static unsigned getMemRefEltSizeInBytes (MemRefType memRefType)
static Value createPrivateMemRef (AffineForOp forOp, Operation *srcStoreOpInst, unsigned dstLoopDepth, Optional< unsigned > fastMemorySpace, uint64_t localBufSizeThreshold)
static bool hasNonAffineUsersOnThePath (unsigned srcId, unsigned dstId, Value memref, MemRefDependenceGraph *mdg)
Walking from node 'srcId' to node 'dstId' (exclusive of 'srcId' and 'dstId'), if there is any non-affine operation accessing 'memref', return false.
static bool hasNonAffineUsersOnThePath (unsigned srcId, unsigned dstId, MemRefDependenceGraph *mdg)
Check whether a memref value in node 'srcId' has a non-affine that is between node 'srcId' and node 'dstId' (exclusive of 'srcNode' and 'dstNode').
static bool canFuseSrcWhichWritesToLiveOut (unsigned srcId, unsigned dstId, AffineWriteOpInterface srcLiveOutStoreOp, MemRefDependenceGraph *mdg)
static bool isFusionProfitable (Operation *srcOpInst, Operation *srcStoreOpInst, ArrayRef< Operation *> dstLoadOpInsts, ArrayRef< Operation *> dstStoreOpInsts, ComputationSliceState *sliceState, unsigned *dstLoopDepth, bool maximalFusion, double computeToleranceThreshold)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-loop-fusion"
Definition at line 34 of file LoopFusion.cpp.
Function Documentation
canFuseSrcWhichWritesToLiveOut()
static bool canFuseSrcWhichWritesToLiveOut (unsigned srcId, unsigned dstId, AffineWriteOpInterface srcLiveOutStoreOp, MemRefDependenceGraph * mdg) static
Definition at line 1013 of file LoopFusion.cpp.
References mlir::failed(), mlir::OpState::getLoc(), mlir::AffineWriteOpInterface::getMemRef(), and hasNonAffineUsersOnThePath().
Referenced by isFusionProfitable().
createPrivateMemRef()
static Value createPrivateMemRef (AffineForOp forOp, Operation * srcStoreOpInst, unsigned dstLoopDepth, Optional< unsigned > fastMemorySpace, uint64_t localBufSizeThreshold) static
Definition at line 846 of file LoopFusion.cpp.
References mlir::floorDiv(), mlir::AffineMap::get(), mlir::MemRefType::get(), mlir::Builder::getAffineDimExpr(), mlir::Operation::getLoc(), getMemRefEltSizeInBytes(), mlir::replaceAllMemRefUsesWith(), mlir::simplifyAffineExpr(), and mlir::succeeded().
Referenced by isFusionProfitable(), and isMemRefDereferencingOp().
getInnermostCommonLoopDepth()
static unsigned getInnermostCommonLoopDepth (ArrayRef< Operation *> ops) static
Definition at line 745 of file LoopFusion.cpp.
References mlir::getLoopIVs().
Referenced by getMaxLoopDepth(), and isFusionProfitable().
getMaxLoopDepth()
static unsigned getMaxLoopDepth (ArrayRef< Operation *> loadOpInsts, ArrayRef< Operation *> storeOpInsts) static
Definition at line 773 of file LoopFusion.cpp.
References mlir::checkMemrefAccessDependence(), getInnermostCommonLoopDepth(), mlir::getNumCommonSurroundingLoops(), and mlir::hasDependence().
Referenced by isFusionProfitable().
getMemRefEltSizeInBytes()
static unsigned getMemRefEltSizeInBytes (MemRefType memRefType) static
Definition at line 827 of file LoopFusion.cpp.
Referenced by createPrivateMemRef().
hasNonAffineUsersOnThePath() [1/2]
static bool hasNonAffineUsersOnThePath (unsigned srcId, unsigned dstId, Value memref, MemRefDependenceGraph * mdg) static
Walking from node 'srcId' to node 'dstId' (exclusive of 'srcId' and 'dstId'), if there is any non-affine operation accessing 'memref', return false.
Otherwise, return true.
Definition at line 950 of file LoopFusion.cpp.
References mlir::WalkResult::advance(), mlir::Value::getUsers(), mlir::WalkResult::interrupt(), mlir::Operation::isBeforeInBlock(), isMemRefDereferencingOp(), and mlir::Operation::walk().
Referenced by canFuseSrcWhichWritesToLiveOut(), hasNonAffineUsersOnThePath(), and isFusionProfitable().
hasNonAffineUsersOnThePath() [2/2]
static bool hasNonAffineUsersOnThePath (unsigned srcId, unsigned dstId, MemRefDependenceGraph * mdg) static
Check whether a memref value in node 'srcId' has a non-affine that is between node 'srcId' and node 'dstId' (exclusive of 'srcNode' and 'dstNode').
Definition at line 984 of file LoopFusion.cpp.
References mlir::WalkResult::advance(), mlir::Operation::getOperands(), and hasNonAffineUsersOnThePath().
isFusionProfitable()
static bool isFusionProfitable (Operation * srcOpInst, Operation * srcStoreOpInst, ArrayRef< Operation *> dstLoadOpInsts, ArrayRef< Operation *> dstStoreOpInsts, ComputationSliceState * sliceState, unsigned * dstLoopDepth, bool maximalFusion, double computeToleranceThreshold) static
Definition at line 1113 of file LoopFusion.cpp.
References mlir::canFuseLoops(), canFuseSrcWhichWritesToLiveOut(), mlir::canonicalizeMapAndOperands(), mlir::computeSliceUnion(), createPrivateMemRef(), mlir::failed(), mlir::getComputeCost(), mlir::getFusionComputeCost(), getInnermostCommonLoopDepth(), mlir::Operation::getLoc(), mlir::getLoopIVs(), mlir::getLoopNestStats(), getMaxLoopDepth(), mlir::getMemoryFootprintBytes(), mlir::getNestingDepth(), hasNonAffineUsersOnThePath(), mlir::insertBackwardComputationSlice(), mlir::Operation::isBeforeInBlock(), mlir::ComputationSliceState::lbOperands, mlir::ComputationSliceState::lbs, moveLoadsAccessingMemrefTo(), mlir::promoteIfSingleIteration(), mlir::sinkSequentialLoops(), mlir::FusionResult::Success, mlir::ComputationSliceState::ubOperands, mlir::ComputationSliceState::ubs, and mlir::FusionResult::value.
isMemRefDereferencingOp()
static bool isMemRefDereferencingOp (Operation & op) static
Definition at line 72 of file LoopFusion.cpp.
References createPrivateMemRef(), getFusedLoopNestInsertionPoint(), mlir::getLoopIVs(), mlir::Operation::getNumRegions(), mlir::Value::getType(), mlir::Type::isa(), print(), and mlir::Operation::walk().
Referenced by hasNonAffineUsersOnThePath().
moveLoadsAccessingMemrefTo()
static void moveLoadsAccessingMemrefTo (Value memref, SmallVectorImpl< Operation *> * srcLoads, SmallVectorImpl< Operation *> * dstLoads) static
Definition at line 730 of file LoopFusion.cpp.
Referenced by isFusionProfitable().
sinkSequentialLoops()
static void sinkSequentialLoops (MemRefDependenceGraph::Node * node) static
Definition at line 820 of file LoopFusion.cpp.
References mlir::sinkSequentialLoops().