MLIR: lib/Dialect/GPU/Transforms/MemoryPromotion.cpp File Reference
MemoryPromotion.cpp File Reference
#include "mlir/Dialect/GPU/MemoryPromotion.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/SCF/EDSC/Builders.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/LoopUtils.h"
Functions
static StringRef getDimName (unsigned dim)
Returns the textual name of a GPU dimension.
static void insertCopyLoops (OpBuilder &builder, Location loc, MemRefBoundsCapture &bounds, Value from, Value to)
Emits the (imperfect) loop nest performing the copy between "from" and "to" values using the bounds derived from the "from" value.
static void insertCopies (Region &region, Location loc, Value from, Value to)
Emits the loop nests performing the copy to the designated location in the beginning of the region, and from the designated location immediately before the terminator of the first block of the region.
Function Documentation
getDimName()
static StringRef getDimName (unsigned dim) static
Returns the textual name of a GPU dimension.
Definition at line 27 of file MemoryPromotion.cpp.
Referenced by insertCopyLoops().
insertCopies()
static void insertCopies (Region & region, Location loc, Value from, Value to) static
Emits the loop nests performing the copy to the designated location in the beginning of the region, and from the designated location immediately before the terminator of the first block of the region.
The region is expected to have one block. This boils down to the following structure
^bb(...): <loop-bound-computation> for arg0 = ... to ... step ... { ... for argN = <thread-id-x> to ... step <block-dim-x> { %0 = load from[arg0, ..., argN] store %0, to[arg0, ..., argN] } ... } gpu.barrier <... original body ...> gpu.barrier for arg0 = ... to ... step ... { ... for argN = <thread-id-x> to ... step <block-dim-x> { %1 = load to[arg0, ..., argN] store %1, from[arg0, ..., argN] } ... }
Inserts the barriers unconditionally since different threads may be copying values and reading them. An analysis would be required to eliminate barriers in case where value is only used by the thread that copies it. Both copies are inserted unconditionally, an analysis would be required to only copy live-in and live-out values when necessary. This copies the entire memref pointed to by "from". In case a smaller block would be sufficient, the caller can create a subview of the memref and promote it instead.
Definition at line 134 of file MemoryPromotion.cpp.
References mlir::Block::back(), mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::Region::front(), mlir::MemRefType::get(), mlir::Region::getContext(), mlir::MemRefType::getShape(), mlir::Value::getType(), insertCopyLoops(), mlir::promoteToWorkgroupMemory(), mlir::Value::replaceAllUsesWith(), and mlir::OpBuilder::setInsertionPointToStart().
insertCopyLoops()
static void insertCopyLoops (OpBuilder & builder, Location loc, MemRefBoundsCapture & bounds, Value from, Value to) static
Emits the (imperfect) loop nest performing the copy between "from" and "to" values using the bounds derived from the "from" value.
Emits at least GPUDialect::getNumWorkgroupDimensions() loops, completing the nest with single-iteration loops. Maps the innermost loops to thread dimensions, in reverse order to enable access coalescing in the innermost loop.
Definition at line 43 of file MemoryPromotion.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), getDimName(), mlir::Builder::getIndexType(), mlir::edsc::BoundsCapture::getLbs(), mlir::Region::getParentOp(), mlir::Value::getParentRegion(), mlir::edsc::BoundsCapture::getSteps(), mlir::Builder::getStringAttr(), mlir::edsc::BoundsCapture::getUbs(), mlir::edsc::loopNestBuilder(), mlir::mapLoopToProcessorIds(), and mlir::edsc::BoundsCapture::rank().
Referenced by insertCopies().