MLIR: lib/Support/MlirOptMain.cpp File Reference
MlirOptMain.cpp File Reference
#include "mlir/Support/MlirOptMain.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Module.h"
#include "mlir/Parser.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Support/ToolUtilities.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/Support/FileUtilities.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/SourceMgr.h"
Functions
static LogicalResult performActions (raw_ostream &os, bool verifyDiagnostics, bool verifyPasses, SourceMgr &sourceMgr, MLIRContext *context, const PassPipelineCLParser &passPipeline)
Perform the actions on the input file indicated by the command line flags within the specified context.
static LogicalResult processBuffer (raw_ostream &os, std::unique_ptr< MemoryBuffer > ownedBuffer, bool verifyDiagnostics, bool verifyPasses, bool allowUnregisteredDialects, const PassPipelineCLParser &passPipeline)
Parses the memory buffer.
Function Documentation
performActions()
static LogicalResult performActions (raw_ostream & os, bool verifyDiagnostics, bool verifyPasses, SourceMgr & sourceMgr, MLIRContext * context, const PassPipelineCLParser & passPipeline) static
Perform the actions on the input file indicated by the command line flags within the specified context.
This typically parses the main source file, runs zero or more optimization passes, then prints the output.
Definition at line 39 of file MlirOptMain.cpp.
References mlir::PassPipelineCLParser::addToPipeline(), mlir::applyPassManagerCLOptions(), mlir::MLIRContext::disableMultithreading(), mlir::MLIRContext::enableMultithreading(), mlir::failed(), mlir::failure(), mlir::MLIRContext::isMultithreadingEnabled(), mlir::parseSourceFile(), mlir::PassManager::run(), and mlir::success().
Referenced by processBuffer().
processBuffer()
static LogicalResult processBuffer (raw_ostream & os, std::unique_ptr< MemoryBuffer > ownedBuffer, bool verifyDiagnostics, bool verifyPasses, bool allowUnregisteredDialects, const PassPipelineCLParser & passPipeline) static
Parses the memory buffer.
If successfully, run a series of passes against it and print the result.
Definition at line 74 of file MlirOptMain.cpp.
References mlir::MLIRContext::allowUnregisteredDialects(), mlir::MlirOptMain(), performActions(), mlir::MLIRContext::printOpOnDiagnostic(), mlir::splitAndProcessBuffer(), and mlir::SourceMgrDiagnosticVerifierHandler::verify().