MLIR: lib/Target/LLVMIR/ModuleTranslation.cpp File Reference
ModuleTranslation.cpp File Reference
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
#include "DebugTranslation.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/OpenMP/OpenMPDialect.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Target/LLVMIR/TypeTranslation.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "mlir/Dialect/LLVMIR/LLVMConversionEnumsToLLVM.inc"
#include "mlir/Dialect/LLVMIR/LLVMConversions.inc"
Functions
static llvm::Constant * buildSequentialConstant (ArrayRef< llvm::Constant *> &constants, ArrayRef< int64_t > shape, llvm::Type *type, Location loc)
Builds a constant of a sequential LLVM type type, potentially containing other sequential types recursively, from the individual constant values provided in constants.
static llvm::Type * getInnermostElementType (llvm::Type *type)
Returns the first non-sequential type nested in sequential types.
static llvm::CmpInst::Predicate getLLVMCmpPredicate (ICmpPredicate p)
Convert MLIR integer comparison predicate to LLVM IR comparison predicate.
static llvm::CmpInst::Predicate getLLVMCmpPredicate (FCmpPredicate p)
static llvm::AtomicRMWInst::BinOp getLLVMAtomicBinOp (AtomicBinOp op)
static llvm::AtomicOrdering getLLVMAtomicOrdering (AtomicOrdering ordering)
static Value getPHISourceValue (Block *current, Block *pred, unsigned numArguments, unsigned index)
Get the SSA value passed to the current block from the terminator operation of its predecessor.
template<typename T >
static void connectPHINodes (T &func, const DenseMap< Value, llvm::Value *> &valueMapping, const DenseMap< Block *, llvm::BasicBlock *> &blockMapping)
Connect the PHI nodes to the results of preceding blocks.
static void topologicalSortImpl (llvm::SetVector< Block *> &blocks, Block *b)
template<typename T >
static llvm::SetVector< Block * > topologicalSort (T &f)
Sort function blocks topologically.
static LogicalResult checkedAddLLVMFnAttribute (Location loc, llvm::Function *llvmFunc, StringRef key, StringRef value=StringRef())
Attempts to add an attribute identified by key, optionally with the given value to LLVM function llvmFunc.
static LogicalResult forwardPassthroughAttributes (Location loc, Optional< ArrayAttr > attributes, llvm::Function *llvmFunc)
Attaches the attributes listed in the given array attribute to llvmFunc.
Function Documentation
buildSequentialConstant()
static llvm::Constant* buildSequentialConstant (ArrayRef< llvm::Constant *> & constants, ArrayRef< int64_t > shape, llvm::Type * type, Location loc) static
Builds a constant of a sequential LLVM type type, potentially containing other sequential types recursively, from the individual constant values provided in constants.
shape contains the number of elements in nested sequential types. Reports errors at loc and returns nullptr on error.
Definition at line 50 of file ModuleTranslation.cpp.
References mlir::Constant, mlir::emitError(), and mlir::StandardAttributes::Type.
Referenced by getInnermostElementType().
checkedAddLLVMFnAttribute()
static LogicalResult checkedAddLLVMFnAttribute (Location loc, llvm::Function * llvmFunc, StringRef key, StringRef value = StringRef()) static
Attempts to add an attribute identified by key, optionally with the given value to LLVM function llvmFunc.
Reports errors at loc if any. If the attribute has a kind known to LLVM IR, create the attribute of this kind, otherwise keep it as a string attribute. Performs additional checks for attributes known to have or not have a value in order to avoid assertions inside LLVM upon construction.
Definition at line 743 of file ModuleTranslation.cpp.
References mlir::emitError(), mlir::StandardTypes::None, and mlir::success().
Referenced by forwardPassthroughAttributes().
connectPHINodes()
template<typename T > static void connectPHINodes (T & func, const DenseMap< Value, llvm::Value *> & valueMapping, const DenseMap< Block *, llvm::BasicBlock *> & blockMapping) static
Connect the PHI nodes to the results of preceding blocks.
Definition at line 342 of file ModuleTranslation.cpp.
References mlir::detail::enumerate(), mlir::Block::getNumArguments(), getPHISourceValue(), and mlir::Block::getPredecessors().
Referenced by mlir::LLVM::ModuleTranslation::convertOmpParallel(), and forwardPassthroughAttributes().
forwardPassthroughAttributes()
static LogicalResult forwardPassthroughAttributes (Location loc, Optional< ArrayAttr > attributes, llvm::Function * llvmFunc) static
Attaches the attributes listed in the given array attribute to llvmFunc.
Reports error to loc if any and returns immediately. Expects attributes to be an array attribute containing either string attributes, treated as value-less LLVM attributes, or array attributes containing two string attributes, with the first string being the name of the corresponding LLVM attribute and the second string beings its value. Note that even integer attributes are expected to have their values expressed as strings.
Definition at line 783 of file ModuleTranslation.cpp.
References mlir::LLVM::ModuleTranslation::blockMapping, checkedAddLLVMFnAttribute(), connectPHINodes(), mlir::Constant, mlir::LLVM::ModuleTranslation::convertType(), mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::emitError(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::LLVM::ModuleTranslation::functionMapping, mlir::LLVM::ModuleTranslation::getModuleBody(), mlir::BlockArgument::getType(), mlir::StringAttr::getValue(), mlir::success(), mlir::topologicalSort(), mlir::StandardAttributes::Type, and mlir::LLVM::ModuleTranslation::valueMapping.
getInnermostElementType()
static llvm::Type* getInnermostElementType (llvm::Type * type) static
Returns the first non-sequential type nested in sequential types.
Definition at line 85 of file ModuleTranslation.cpp.
References buildSequentialConstant(), mlir::Constant, mlir::Attribute::dyn_cast(), mlir::emitError(), and mlir::StandardAttributes::Type.
getLLVMAtomicBinOp()
static llvm::AtomicRMWInst::BinOp getLLVMAtomicBinOp (AtomicBinOp op) static
Definition at line 248 of file ModuleTranslation.cpp.
getLLVMAtomicOrdering()
static llvm::AtomicOrdering getLLVMAtomicOrdering (AtomicOrdering ordering) static
Definition at line 280 of file ModuleTranslation.cpp.
getLLVMCmpPredicate() [1/2]
static llvm::CmpInst::Predicate getLLVMCmpPredicate (ICmpPredicate p) static
Convert MLIR integer comparison predicate to LLVM IR comparison predicate.
Definition at line 184 of file ModuleTranslation.cpp.
References mlir::edsc::op::eq(), mlir::edsc::op::ne(), mlir::edsc::op::sge(), mlir::edsc::op::sgt(), mlir::edsc::op::sle(), mlir::edsc::op::slt(), mlir::edsc::op::uge(), mlir::edsc::op::ugt(), mlir::edsc::op::ule(), and mlir::edsc::op::ult().
getLLVMCmpPredicate() [2/2]
static llvm::CmpInst::Predicate getLLVMCmpPredicate (FCmpPredicate p) static
Definition at line 210 of file ModuleTranslation.cpp.
References mlir::edsc::op::uge(), mlir::edsc::op::ugt(), mlir::edsc::op::ule(), and mlir::edsc::op::ult().
getPHISourceValue()
static Value getPHISourceValue (Block * current, Block * pred, unsigned numArguments, unsigned index) static
Get the SSA value passed to the current block from the terminator operation of its predecessor.
Definition at line 318 of file ModuleTranslation.cpp.
References mlir::Operation::getOperand(), and mlir::Block::getTerminator().
Referenced by connectPHINodes().
topologicalSort()
template<typename T > static llvm::SetVector<Block *> topologicalSort (T & f) static
Sort function blocks topologically.
Definition at line 375 of file ModuleTranslation.cpp.
References topologicalSortImpl().
topologicalSortImpl()
static void topologicalSortImpl (llvm::SetVector< Block *> & blocks, Block * b) static
Definition at line 365 of file ModuleTranslation.cpp.
References mlir::Block::getSuccessors().
Referenced by topologicalSort().