MLIR: detail Namespace Reference
detail Namespace Reference
Classes
struct Vector1D
struct Vector1D< T, Dim, false >
struct Vector1D< T, Dim, true >
Functions
constexpr bool isPowerOf2 (int N)
constexpr unsigned nextPowerOf2 (int N)
Function Documentation
isPowerOf2()
constexpr bool detail::isPowerOf2 (int N)
Definition at line 41 of file CRunnerUtils.h.
Referenced by nextPowerOf2().
nextPowerOf2()
constexpr unsigned detail::nextPowerOf2 (int N)
Definition at line 43 of file CRunnerUtils.h.
References isPowerOf2().
Referenced by detail::Vector1D< T, Dim, false >::operator[](), detail::Vector1D< T, Dim, true >::Vector1D(), and detail::Vector1D< T, Dim, false >::Vector1D().