MLIR: mlir::linalg Namespace Reference
mlir::linalg Namespace Reference
Classes
struct AffineMinSCFCanonicalizationPattern
Canonicalize AffineMinOp operations in the context of enclosing scf.for and scf.parallel by:
class Aliases
A very primitive alias analysis which just records for each view, either:
struct FusionInfo
struct GenerateLoopNest
Utility class used to generate nested loops with ranges described by loopRanges and loop type described by the iteratorTypes.
struct LinalgBaseInterchangePattern
Linalg interchange patterns.
struct LinalgBasePromotionPattern
Linalg promotion patterns.
struct LinalgBaseTilingPattern
struct LinalgBaseVectorizationPattern
Linalg vectorization patterns.
struct LinalgCopyVTRForwardingPattern
Match and rewrite for the pattern: ``` alloc = ...
struct LinalgCopyVTWForwardingPattern
Match and rewrite for the pattern: ``` alloc = ...
class LinalgDependenceGraph
Data structure for holding a dependence graph that operates on LinalgOp and views as SSA values.
struct LinalgInterchangePattern
struct LinalgLoweringPattern
struct LinalgMarker
Helper class to control common attribute matching and setting behavior.
struct LinalgPromotionOptions
struct LinalgPromotionPattern
struct LinalgTilingOptions
struct LinalgTilingPattern
struct LinalgTransforms
struct LinalgVectorizationPattern
class RangeType
A RangeType represents a minimal range abstraction (min, max, step).
struct RegionMatcher
A struct containing common matchers over linalg op's region.
struct TiledLinalgOp
Typedefs
using ReassociationIndices = SmallVector< int64_t, 2 >
using ReassociationExprs = SmallVector< AffineExpr, 2 >
using LinalgLoops = SmallVector< Operation *, 4 >
using AllocBufferCallbackFn = std::function< Optional< Value >(OpBuilder &b, SubViewOp subView, ArrayRef< Value > boundingSubViewSize, OperationFolder *folder)>
Callback function type used to perform the allocation for the promoted subView.
using DeallocBufferCallbackFn = std::function< LogicalResult(OpBuilder &b, Value buffer)>
Callback function type used to deallocate the buffers used to hold the promoted subview.
using CopyCallbackFn = std::function< LogicalResult(OpBuilder &b, Value src, Value dst)>
Callback function type used to insert copy from original subview to subview of the promoted region for the read operands/subview of promoted region to original subview for the results.
using TileSizeComputationFunction = std::function< SmallVector< Value, 4 >(OpBuilder &, Operation *)>
Enumerations
enum LinalgTypes { Range = Type::FIRST_LINALG_TYPE, LAST_USED_LINALG_TYPE = Range }
enum LinalgTilingLoopType { LinalgTilingLoopType::Loops = 0, LinalgTilingLoopType::AffineLoops = 1, LinalgTilingLoopType::ParallelLoops = 2 }
Linalg tiling patterns.
enum LinalgLoweringType { LinalgLoweringType::LibraryCall = 0, LinalgLoweringType::Loops = 1, LinalgLoweringType::AffineLoops = 2, LinalgLoweringType::ParallelLoops = 3 }
Linalg lowering patterns.
Functions
std::string generateLibraryCallName (Operation *op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
SmallVector< AffineExpr, 4 > makeAffineDimExprs (unsigned num, unsigned &startIdx, MLIRContext *context)
Returns num AffineDimExpr dimensions at positions [startIdx, startIdx + num) and increments startIdx to startIdx + num.
template<typename PoolingOp >
SmallVector< AffineExpr, 4 > weightedPoolingInputIndex (PoolingOp op, ArrayRef< AffineExpr > outputDims, ArrayRef< AffineExpr > windowDims)
Builds the indexing expressions for a ConvOp/PoolingOp op.
AffineMap extractOrIdentityMap (Optional< AffineMap > maybeMap, unsigned rank, MLIRContext *context)
Returns maybeMap.get() if maybeMap is set, otherwise returns the symbol-less identity map of rank.
SmallVector< AffineExpr, 4 > concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
Return the vector that is the concatenation of a and b.
void hoistViewAllocOps (FuncOp func)
Hoist alloc/dealloc pairs and alloca op out of immediately enclosing scf::ForOp if both conditions are true:
void hoistRedundantVectorTransfers (FuncOp func)
Hoist vector.transfer_read/vector.transfer_write pairs out of immediately enclosing scf::ForOp iteratively, if the following conditions are true:
Optional< TiledLinalgOp > tileLinalgOp (OpBuilder &b, LinalgOp op, const LinalgTilingOptions &options)
Performs standalone tiling of a single LinalgOp by tileSizes.
LinalgOp interchange (LinalgOp op, ArrayRef< unsigned > interchangeVector)
Interchanges the iterator_types and iterator_maps dimensions of op.
Optional< LinalgOp > promoteSubViews (OpBuilder &b, LinalgOp op, LinalgPromotionOptions options, OperationFolder *folder=nullptr)
Promotes the subViews into a new buffer allocated at the insertion point b.
void vectorizeLinalgOp (OpBuilder &builder, Operation *op)
Emit a suitable vector form for a Linalg op with fully static shape.
template<typename LoopTy >
Optional< LinalgLoops > linalgLowerOpToLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of LoopTy with the proper body for op.
LogicalResult linalgOpToLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of scf.for with the proper body for op.
LogicalResult linalgOpToParallelLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of scf.parallel with the proper body for op.
LogicalResult linalgOpToAffineLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of affine.for with the proper body for op.
LogicalResult interchangeGenericLinalgOpPrecondition (Operation *op, ArrayRef< unsigned > interchangeVector)
Emits a generic or indexed_generic operation with the indexing_maps and iterator_types permutated according to permutation.
LogicalResult promoteSubviewsPrecondition (Operation *op, LinalgPromotionOptions options)
Promote std.subviews feeding linalg operations.
LogicalResult vectorizeLinalgOpPrecondition (Operation *op)
Rewrite a linalg.generic into a suitable vector.contraction op.
OwningRewritePatternList getLinalgTilingCanonicalizationPatterns (MLIRContext *ctx)
Canonicalization patterns relevant to apply after tiling patterns.
LogicalResult applyStagedPatterns (Operation *op, ArrayRef< OwningRewritePatternList > stage1Patterns, const OwningRewritePatternList &stage2Patterns, function_ref< LogicalResult(Operation *)> stage3Lambda=nullptr)
Helper function to allow applying rewrite patterns, interleaved with more global transformations, in a staged fashion:
bool isParallelIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
bool isReductionIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
bool isWindowIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
bool isProducerLastWriteOfView (const LinalgDependenceGraph &graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether the specific producer is the last write to exactly the whole consumedView.
bool isFusableInto (const LinalgDependenceGraph &graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether fusing the specific producer of the consumedView is feasible.
Optional< FusionInfo > fuseProducerOf (OpBuilder &b, LinalgOp consumer, unsigned consumerIdx, const LinalgDependenceGraph &graph, OperationFolder *folder=nullptr)
Fuses producer into consumer if the producer is structurally feasible and the fusion would not violate dependencies.
Operation * fuseTensorOps (PatternRewriter &rewriter, Operation *consumer, unsigned consumerIdx, OperationFolder *folder=nullptr)
Fuse linalg operation on tensors, with the producer of the operand at position consumerIdx of the consumer.
template<typename ConcreteOp >
SmallVector< Value, 8 > getViewSizes (OpBuilder &builder, ConcreteOp linalgOp)
Returns the linearized list of all view dimensions in a linalgOp.
SmallVector< Value, 4 > applyMapToValues (OpBuilder &b, Location loc, AffineMap map, ValueRange values, OperationFolder *folder=nullptr)
Returns the values obtained by applying map to the list of values.
SmallVector< Value, 4 > getAssumedNonViewOperands (LinalgOp linalgOp)
Returns all the operands of linalgOp that are not views.
template<typename T , unsigned N>
void applyPermutationToVector (SmallVector< T, N > &inVec, ArrayRef< unsigned > permutation)
Apply the permutation defined by permutation to inVec.
static void generateParallelLoopNest (ValueRange lbs, ValueRange ubs, ValueRange steps, ArrayRef< Attribute > iteratorTypes, function_ref< void(ValueRange)> bodyBuilderFn, SmallVectorImpl< Value > &ivStorage)
Generates a loop nest consisting of scf.parallel and scf.for, depending on the `iteratorTypes.
Typedef Documentation
AllocBufferCallbackFn
using mlir::linalg::AllocBufferCallbackFn = typedef std::function<Optional<Value>(OpBuilder &b, SubViewOp subView, ArrayRef<Value> boundingSubViewSize, OperationFolder *folder)>
Callback function type used to perform the allocation for the promoted subView.
In boundingSubViewsize a best attempt is made to find the smallest constant value for the size of the buffer needed for each dimension. If that is not possible, contains the dynamic size of the subview. The call back should return the buffer to use.
Definition at line 69 of file Transforms.h.
CopyCallbackFn
using mlir::linalg::CopyCallbackFn = typedef std::function<LogicalResult(OpBuilder &b, Value src, Value dst)>
Callback function type used to insert copy from original subview to subview of the promoted region for the read operands/subview of promoted region to original subview for the results.
The copy has to happen from src to dst.
Definition at line 81 of file Transforms.h.
DeallocBufferCallbackFn
using mlir::linalg::DeallocBufferCallbackFn = typedef std::function<LogicalResult(OpBuilder &b, Value buffer)>
Callback function type used to deallocate the buffers used to hold the promoted subview.
Definition at line 74 of file Transforms.h.
LinalgLoops
using mlir::linalg::LinalgLoops = typedef SmallVector<Operation *, 4>
Definition at line 26 of file Transforms.h.
ReassociationExprs
using mlir::linalg::ReassociationExprs = typedef SmallVector<AffineExpr, 2>
Definition at line 39 of file LinalgOps.h.
ReassociationIndices
using mlir::linalg::ReassociationIndices = typedef SmallVector<int64_t, 2>
Definition at line 38 of file LinalgOps.h.
TileSizeComputationFunction
using mlir::linalg::TileSizeComputationFunction = typedef std::function<SmallVector<Value, 4>(OpBuilder &, Operation *)>
Definition at line 236 of file Transforms.h.
Enumeration Type Documentation
LinalgLoweringType
enum mlir::linalg::LinalgLoweringType strong
Linalg lowering patterns.
Apply the linalgLowerOpToLoops transformation as a pattern. marker controls LinalgTransformMarker matching and update when specified. See linalgLowerOpToLoops for more details.
Enumerator
LibraryCall
Loops
AffineLoops
ParallelLoops
Definition at line 399 of file Transforms.h.
LinalgTilingLoopType
enum mlir::linalg::LinalgTilingLoopType strong
Linalg tiling patterns.
Apply the tileLinalgOp transformation as a pattern. marker controls LinalgTransformMarker matching and update when specified. See tileLinalgOp for more details.
Enumerator
Loops
AffineLoops
ParallelLoops
Definition at line 230 of file Transforms.h.
LinalgTypes
enum mlir::linalg::LinalgTypes
Enumerator
Range
LAST_USED_LINALG_TYPE
Definition at line 19 of file LinalgTypes.h.
Function Documentation
applyMapToValues()
SmallVector< Value, 4 > mlir::linalg::applyMapToValues (OpBuilder & b, Location loc, AffineMap map, ValueRange values, OperationFolder * folder = nullptr)
Returns the values obtained by applying map to the list of values.
When non-null, the optional pointer folder is used to call into the createAndFold builder method. If folder is null, the regular create method is called.
Definition at line 69 of file Utils.cpp.
References emitOrFoldComposedAffineApply(), mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by emitLoopRanges(), getViewSizes(), makeTiledLoopRanges(), makeTiledViews(), permuteIvs(), and tileLinalgOpImpl().
applyPermutationToVector()
template<typename T , unsigned N> void mlir::linalg::applyPermutationToVector (SmallVector< T, N > & inVec, ArrayRef< unsigned > permutation)
Apply the permutation defined by permutation to inVec.
Element i in inVec is mapped to location j = permutation[i]. E.g.: for an input vector `inVec = ['a', 'b', 'c']and a permutation vector permutation = [2, 0, 1], this function leavesinVec = ['c', 'a', 'b']`.
Definition at line 151 of file Utils.h.
Referenced by interchange(), and tileLinalgOpImpl().
applyStagedPatterns()
LogicalResult mlir::linalg::applyStagedPatterns (Operation * op, ArrayRef< OwningRewritePatternList > stage1Patterns, const OwningRewritePatternList & stage2Patterns, function_ref< LogicalResult(Operation *)> stage3Lambda = nullptr)
Helper function to allow applying rewrite patterns, interleaved with more global transformations, in a staged fashion:
the first stage consists of a list of OwningRewritePatternList. Each OwningRewritePatternList in this list is applied once, in order.
the second stage consists of a single OwningRewritePattern that is applied greedily until convergence.
the third stage consists of applying a lambda, generally used for non-local transformation effects. This allows creating custom fused transformations where patterns can be ordered and applied at a finer granularity than a sequence of traditional compiler passes.
Definition at line 209 of file Transforms.cpp.
References mlir::applyPatternsAndFoldGreedily(), DBGS, mlir::failed(), mlir::failure(), and mlir::success().
concat()
SmallVector< AffineExpr, 4 > mlir::linalg::concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
Return the vector that is the concatenation of a and b.
Definition at line 1110 of file LinalgOps.cpp.
Referenced by mlir::Simplex::makeProduct().
extractOrIdentityMap()
AffineMap mlir::linalg::extractOrIdentityMap (Optional< AffineMap > maybeMap, unsigned rank, MLIRContext * context)
Returns maybeMap.get() if maybeMap is set, otherwise returns the symbol-less identity map of rank.
Definition at line 1062 of file LinalgOps.cpp.
References mlir::AffineMap::get(), and mlir::AffineMap::getMultiDimIdentityMap().
fuseProducerOf()
Optional< FusionInfo > mlir::linalg::fuseProducerOf (OpBuilder & b, LinalgOp consumer, unsigned consumerIdx, const LinalgDependenceGraph & graph, OperationFolder * folder = nullptr)
Fuses producer into consumer if the producer is structurally feasible and the fusion would not violate dependencies.
When non-null, the optional pointer folder is used to call into the createAndFold builder method. If folder is null, the regular create method is called.
Definition at line 377 of file Fusion.cpp.
References fuseProducerOfDep().
Referenced by fuseLinalgOpsGreedily().
fuseTensorOps()
Operation * mlir::linalg::fuseTensorOps (PatternRewriter & rewriter, Operation * consumer, unsigned consumerIdx, OperationFolder * folder = nullptr)
Fuse linalg operation on tensors, with the producer of the operand at position consumerIdx of the consumer.
Definition at line 951 of file Fusion.cpp.
References mlir::applyPatternsAndFoldGreedily(), mlir::PatternRewriter::eraseOp(), mlir::failure(), fuse(), fuseLinalgOpsGreedily(), mlir::Operation::getContext(), mlir::Value::getDefiningOp(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::Operation::getRegions(), mlir::Operation::getResults(), mlir::populateLinalgTensorOpsFusionPatterns(), mlir::PatternRewriter::replaceOp(), and mlir::success().
generateLibraryCallName()
std::string mlir::linalg::generateLibraryCallName (Operation * op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
The name mangling scheme is basic and uses MLIR type names:
form a string which is the concatenation of the linalg op name with all the operand type names, separate by underscores;
drop the linalg. prefix, and the <, >, ? symbols from the type. Assumes op is a LinalgOp.
Examples:
linalg.fill(A, f) : memref<f32>, f32 name mangles into linalg_fill_viewf32_f32_impl
linalg.dot A, B, C : (memref<?xf32, stride_specification>, memref<?xf32, stride_specification>, memref<f32>) name mangles into linalg_dot_viewxf32_viewxf32_viewf32_impl
linalg.matmul(...) : memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification> name mangles into linalg_matmul_viewxxf32_viewxxf32_viewxxf32_impl
Definition at line 1139 of file LinalgOps.cpp.
References appendMangledType(), foldMemRefCast(), foldReshapeOp(), mlir::Operation::getName(), mlir::Operation::getOperandTypes(), mlir::OperationName::getStringRef(), and mlir::succeeded().
generateParallelLoopNest()
static void mlir::linalg::generateParallelLoopNest (ValueRange lbs, ValueRange ubs, ValueRange steps, ArrayRef< Attribute > iteratorTypes, function_ref< void(ValueRange)> bodyBuilderFn, SmallVectorImpl< Value > & ivStorage) static
Generates a loop nest consisting of scf.parallel and scf.for, depending on the `iteratorTypes.
` Consecutive parallel loops create a single scf.parallel operation; each sequential loop creates a new scf.for operation. The body of the innermost loop is populated by bodyBuilderFn that accepts a range of induction variables for all loops. ivStorage is used to store the partial list of induction variables.
Definition at line 188 of file Utils.cpp.
References isParallelIteratorType(), and mlir::edsc::loopNestBuilder().
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit().
getAssumedNonViewOperands()
SmallVector< Value, 4 > mlir::linalg::getAssumedNonViewOperands (LinalgOp linalgOp)
Returns all the operands of linalgOp that are not views.
Asserts that these operands are value types to allow transformations like tiling to just use the values when cloning linalgOp.
Definition at line 90 of file Utils.cpp.
Referenced by cloneWithLoopRanges(), getViewSizes(), and tileLinalgOpImpl().
getLinalgTilingCanonicalizationPatterns()
OwningRewritePatternList mlir::linalg::getLinalgTilingCanonicalizationPatterns (MLIRContext * ctx)
Canonicalization patterns relevant to apply after tiling patterns.
These are applied automatically by the tiling pass but need to be applied manually when tiling is called programmatically.
Definition at line 474 of file Tiling.cpp.
Referenced by applyTilingToLoopPatterns(), and mlir::linalg::LinalgTilingOptions::setLoopType().
getViewSizes()
template<typename ConcreteOp > SmallVector<Value, 8> mlir::linalg::getViewSizes (OpBuilder & builder, ConcreteOp linalgOp)
Returns the linearized list of all view dimensions in a linalgOp.
Applying the inverse, concatenated loopToOperandRangeMaps to this list allows the derivation of loop ranges for any linalgOp.
Definition at line 101 of file Utils.h.
References applyMapToValues(), mlir::OpBuilder::create(), and getAssumedNonViewOperands().
Referenced by getInputAndOutputIndices(), and tileLinalgOpImpl().
hoistRedundantVectorTransfers()
void mlir::linalg::hoistRedundantVectorTransfers (FuncOp func)
Hoist vector.transfer_read/vector.transfer_write pairs out of immediately enclosing scf::ForOp iteratively, if the following conditions are true:
The two ops access the same memref with the same indices.
All operands are invariant under the enclosing scf::ForOp.
No uses of the memref either dominate the transfer_read or are dominated by the transfer_write (i.e. no aliasing between the write and the read across the loop) To improve hoisting opportunities, call the moveLoopInvariantCode helper function on the candidate loop above which to hoist. Hoisting the transfers results in scf::ForOp yielding the value that originally transited through memory.
Definition at line 119 of file Hoisting.cpp.
References mlir::WalkResult::advance(), mlir::cloneWithNewYields(), DBGS, mlir::failed(), mlir::getForwardSlice(), mlir::WalkResult::interrupt(), isDisjoint(), mlir::moveLoopInvariantCode(), mlir::DominanceInfo::properlyDominates(), and mlir::OpState::walk().
hoistViewAllocOps()
void mlir::linalg::hoistViewAllocOps (FuncOp func)
Hoist alloc/dealloc pairs and alloca op out of immediately enclosing scf::ForOp if both conditions are true:
All operands are defined outside the loop.
All uses are ViewLikeOp or DeallocOp.
Definition at line 36 of file Hoisting.cpp.
References DBGS, mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::Operation::getParentOp(), mlir::Operation::getResult(), mlir::Value::getUses(), mlir::Operation::moveAfter(), and mlir::OpState::walk().
interchange()
LinalgOp mlir::linalg::interchange (LinalgOp op, ArrayRef< unsigned > interchangeVector)
Interchanges the iterator_types and iterator_maps dimensions of op.
This is an in-place transformation controlled by interchangeVector. An empty vector is interpreted as the identity permutation and the transformation returns early.
E.g. the permutation (i,j,k) -> (j,k,i) is expressed with interchangeVector = [1,2,0]. All values in interchangeVector must be integers, in the range 0..op.rank without duplications (i.e. [1,1,2] is an invalid permutation).
Definition at line 56 of file Interchange.cpp.
References applyPermutationToVector(), mlir::AffineMap::compose(), mlir::AffineMapAttr::get(), mlir::ArrayAttr::get(), mlir::getIndexingMapsAttrName(), mlir::getIteratorTypesAttrName(), mlir::AffineMap::getPermutationMap(), and mlir::inversePermutation().
Referenced by mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite().
interchangeGenericLinalgOpPrecondition()
LogicalResult mlir::linalg::interchangeGenericLinalgOpPrecondition (Operation * op, ArrayRef< unsigned > interchangeVector)
Emits a generic or indexed_generic operation with the indexing_maps and iterator_types permutated according to permutation.
Definition at line 35 of file Interchange.cpp.
References mlir::failure(), mlir::Operation::getContext(), mlir::AffineMap::getPermutationMap(), mlir::inversePermutation(), and mlir::success().
Referenced by mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite(), and mlir::linalg::LinalgPromotionOptions::setCopyInOutFns().
isFusableInto()
bool mlir::linalg::isFusableInto (const LinalgDependenceGraph & graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether fusing the specific producer of the consumedView is feasible.
This checks producer is the last write of consumedView and that no interleaved dependence would be violated (RAW, WAR or WAW).
Definition at line 265 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::findCoveringDependences(), and isProducerLastWriteOfView().
Referenced by fuseProducerOfDep().
isParallelIteratorType()
bool mlir::linalg::isParallelIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
Definition at line 106 of file Utils.cpp.
References mlir::Attribute::dyn_cast(), and mlir::getParallelIteratorTypeName().
Referenced by generateParallelLoopNest().
isProducerLastWriteOfView()
bool mlir::linalg::isProducerLastWriteOfView (const LinalgDependenceGraph & graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether the specific producer is the last write to exactly the whole consumedView.
This checks structural dominance, that the dependence is a RAW without any interleaved write to any piece of consumedView.
Definition at line 241 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::findCoveringWrites(), and isStructurallyFusableProducer().
Referenced by isFusableInto().
isReductionIteratorType()
bool mlir::linalg::isReductionIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
Definition at line 113 of file Utils.cpp.
References mlir::Attribute::dyn_cast(), and mlir::getReductionIteratorTypeName().
isWindowIteratorType()
bool mlir::linalg::isWindowIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
Definition at line 120 of file Utils.cpp.
References mlir::Attribute::dyn_cast(), and mlir::getWindowIteratorTypeName().
linalgLowerOpToLoops()
template<typename LoopTy > template Optional< LinalgLoops > mlir::linalg::linalgLowerOpToLoops< AffineForOp > (OpBuilder & builder, Operation * op)
Emits a loop nest of LoopTy with the proper body for op.
Emits a loop nest with the proper body for op.
Definition at line 709 of file Loops.cpp.
Referenced by mlir::linalg::LinalgPromotionOptions::setCopyInOutFns().
linalgOpToAffineLoops()
LogicalResult mlir::linalg::linalgOpToAffineLoops (OpBuilder & builder, Operation * op)
Emits a loop nest of affine.for with the proper body for op.
Definition at line 725 of file Loops.cpp.
References mlir::failure(), and mlir::success().
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite(), and mlir::linalg::LinalgPromotionOptions::setCopyInOutFns().
linalgOpToLoops()
LogicalResult mlir::linalg::linalgOpToLoops (OpBuilder & builder, Operation * op)
Emits a loop nest of scf.for with the proper body for op.
Definition at line 732 of file Loops.cpp.
References mlir::failure(), and mlir::success().
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite(), and mlir::linalg::LinalgPromotionOptions::setCopyInOutFns().
linalgOpToParallelLoops()
LogicalResult mlir::linalg::linalgOpToParallelLoops (OpBuilder & builder, Operation * op)
Emits a loop nest of scf.parallel with the proper body for op.
Definition at line 738 of file Loops.cpp.
References mlir::failure(), and mlir::success().
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite(), and mlir::linalg::LinalgPromotionOptions::setCopyInOutFns().
makeAffineDimExprs()
SmallVector< AffineExpr, 4 > mlir::linalg::makeAffineDimExprs (unsigned num, unsigned & startIdx, MLIRContext * context)
Returns num AffineDimExpr dimensions at positions [startIdx, startIdx + num) and increments startIdx to startIdx + num.
Definition at line 1073 of file LinalgOps.cpp.
References mlir::getAffineDimExpr().
promoteSubViews()
Optional< LinalgOp > mlir::linalg::promoteSubViews (OpBuilder & b, LinalgOp op, LinalgPromotionOptions options, OperationFolder * folder = nullptr)
Promotes the subViews into a new buffer allocated at the insertion point b.
Promotion occurs in 3 steps:
Create a new buffer for a full tile (i.e. not clipped at the boundary).
Take a full view on the buffer.
Take a partial slice of the full view in step 2. and copy into it. Infers statically sized buffers from subViews unless dynamicBuffers is true.
Returns the modified linalg op (the modification happens in place) as well as all the copy ops created.
Definition at line 393 of file Promotion.cpp.
References mlir::failed(), promoteSubViews(), promoteSubviewsPrecondition(), mlir::linalg::LinalgPromotionOptions::setDynamicBuffers(), and mlir::linalg::LinalgPromotionOptions::setUseAlloca().
Referenced by mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), and mlir::linalg::LinalgPromotionOptions::setCopyInOutFns().
promoteSubviewsPrecondition()
LogicalResult mlir::linalg::promoteSubviewsPrecondition (Operation * op, LinalgPromotionOptions options)
Promote std.subviews feeding linalg operations.
Definition at line 373 of file Promotion.cpp.
References mlir::detail::enumerate(), mlir::failure(), mlir::linalg::LinalgPromotionOptions::operandsToPromote, and mlir::success().
Referenced by mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), promoteSubViews(), and mlir::linalg::LinalgPromotionOptions::setCopyInOutFns().
tileLinalgOp()
Optional< TiledLinalgOp > mlir::linalg::tileLinalgOp (OpBuilder & b, LinalgOp op, const LinalgTilingOptions & options)
Performs standalone tiling of a single LinalgOp by tileSizes.
and permute the loop nest according to interchangeVector The permutation is expressed as a list of integers that specify the new ordering of the loop nest. The length of interchangeVector must be equal to the length of tileSizes. An empty vector is interpreted as the identity permutation and the transformation returns early.
Returns a struct containing the tiled loops in the specified order and the cloned op if successful, llvm::None otherwise.
E.g. the permutation (i,j,k) -> (j,k,i) is expressed by interchangeVector = [1,2,0]. All values in interchangeVector must be integers, in the range 0..tileSizes.size() without duplications (i.e. [1,1,2] is an invalid permutation).
Definition at line 420 of file Tiling.cpp.
References mlir::Identifier::get(), mlir::OwningRewritePatternList::insert(), mlir::linalg::LinalgTilingOptions::loopType, and options.
Referenced by mlir::linalg::LinalgBaseTilingPattern::matchAndRewrite().
vectorizeLinalgOp()
void mlir::linalg::vectorizeLinalgOp (OpBuilder & builder, Operation * op)
Emit a suitable vector form for a Linalg op with fully static shape.
Definition at line 105 of file Vectorization.cpp.
References DEBUG_TYPE, mlir::VectorType::get(), mlir::Operation::getLoc(), mlir::MemRefType::getShape(), isContraction(), mlir::succeeded(), and vectorizeLinalgOpPrecondition().
Referenced by mlir::linalg::LinalgBaseVectorizationPattern::matchAndRewrite(), and mlir::linalg::LinalgPromotionOptions::setCopyInOutFns().
vectorizeLinalgOpPrecondition()
LogicalResult mlir::linalg::vectorizeLinalgOpPrecondition (Operation * op)
Rewrite a linalg.generic into a suitable vector.contraction op.
Definition at line 89 of file Vectorization.cpp.
References mlir::failure(), mlir::ShapedType::hasStaticShape(), isContraction(), and mlir::success().
Referenced by mlir::linalg::LinalgBaseVectorizationPattern::matchAndRewrite(), mlir::linalg::LinalgPromotionOptions::setCopyInOutFns(), and vectorizeLinalgOp().
weightedPoolingInputIndex()
template<typename PoolingOp > SmallVector< AffineExpr, 4 > mlir::linalg::weightedPoolingInputIndex (PoolingOp op, ArrayRef< AffineExpr > outputDims, ArrayRef< AffineExpr > windowDims)
Builds the indexing expressions for a ConvOp/PoolingOp op.
Returns the vector of AffineMaps representing: stride[i] * outputDims[i] + dilation[i] * windowDims[i] - pad_low[i]
Definition at line 1084 of file LinalgOps.cpp.