MLIR: mlir::edsc::ops Namespace Reference
mlir::edsc::ops Namespace Reference
Typedefs
using UnaryPointwiseOpBuilder = function_ref< Value(Value)>
TODO: In the future we should tie these implementations to something in Tablegen that generates the proper interfaces and the proper sugared named ops.
using BinaryPointwiseOpBuilder = function_ref< Value(Value, Value)>
Binary pointwise operation (with broadcast) entry point.
using MatmulRegionBuilder = function_ref< void(ValueRange args)>
Functions
void mulRegionBuilder (ValueRange args)
Build the body of a region to compute a scalar multiply, under the current ScopedContext, at the current insert point.
void macRegionBuilder (ValueRange args)
Build the body of a region to compute a scalar multiply-accumulate, under the current ScopedContext, at the current insert point.
Operation * linalg_generic_pointwise (UnaryPointwiseOpBuilder unaryOp, StructuredIndexed I, StructuredIndexed O)
Operation * linalg_generic_pointwise_tanh (StructuredIndexed I, StructuredIndexed O)
Build a linalg.pointwise with all parallel iterators and a region that computes O = tanh(I).
Operation * linalg_generic_pointwise (BinaryPointwiseOpBuilder binaryOp, StructuredIndexed I1, StructuredIndexed I2, StructuredIndexed O)
Binary pointwise operation (with broadcast) entry point.
Operation * linalg_generic_pointwise_add (StructuredIndexed I1, StructuredIndexed I2, StructuredIndexed O)
Build a linalg.pointwise with all parallel iterators and a region that computes O = I1 + I2.
Operation * linalg_generic_pointwise_max (StructuredIndexed I1, StructuredIndexed I2, StructuredIndexed O)
Build a linalg.pointwise with all parallel iterators and a region that computes O = max(I1, I2).
Operation * linalg_generic_matmul (Value vA, Value vB, Value vC, MatmulRegionBuilder regionBuilder=macRegionBuilder)
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes:
(m, n, k) = (par, par, seq)
|
|  C(m, n) += A(m, k) * B(k, n)
.
Operation * linalg_generic_matmul (Value vA, Value vB, RankedTensorType tC, MatmulRegionBuilder regionBuilder=mulRegionBuilder)
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes:
(m, n, k) = (par, par, seq)
|
|  C(m, n) = sum_k(A(m, k) * B(k, n))
and returns the tensor C.
Operation * linalg_generic_matmul (Value vA, Value vB, Value vC, RankedTensorType tD, MatmulRegionBuilder regionBuilder=macRegionBuilder)
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes:
(m, n, k) = (par, par, seq)
|
|  D(m, n) = C(m, n) + sum_k(A(m, k) * B(k, n))
and returns the tensor D.
template<typename Container >
Operation * linalg_generic_matmul (Container values, MatmulRegionBuilder regionBuilder=macRegionBuilder)
Operation * linalg_generic_conv_nhwc (Value vI, Value vW, Value vO, ArrayRef< int > strides={}, ArrayRef< int > dilations={})
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes: ``` (batch, f, [h, w, ...], [kh, kw, ...], c) = | (par, par, [par, par, ...], [red, red, ...], red) | | O(batch, [h, w, ...], f) += | I(batch, | [ | stride[0] * h + dilations[0] * kh, | stride[1] * w + dilations[1] * kw, ...
template<typename Container >
Operation * linalg_generic_conv_nhwc (Container values, ArrayRef< int > strides={}, ArrayRef< int > dilations={})
Operation * linalg_generic_dilated_conv_nhwc (Value vI, Value vW, Value vO, int depth_multiplier=1, ArrayRef< int > strides={}, ArrayRef< int > dilations={})
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes: ``` (batch, dm, c, [h, w, ...], [kh, kw, ...]) = | (par, par, par, [par, par, ...], [red, red, ...]) | | O(batch, [h, w, ...], c * depth_multiplier) += | I(batch, | [ | stride[0] * h + dilations[0] * kh, | stride[1] * w + dilations[1] * kw, ...
template<typename Container >
Operation * linalg_generic_dilated_conv_nhwc (Container values, int depth_multiplier, ArrayRef< int > strides={}, ArrayRef< int > dilations={})
Value vector_contraction (StructuredIndexed A, StructuredIndexed B, StructuredIndexed C, ArrayRef< IteratorType > iteratorTypes)
Build a generic vector contraction, that is a vector.contract op with specified iteratorTypes.
Value vector_contraction_matmul (Value A, Value B, Value C)
Build a generic vector contraction that computes a matmul on vectors.
Typedef Documentation
BinaryPointwiseOpBuilder
using mlir::edsc::ops::BinaryPointwiseOpBuilder = typedef function_ref<Value(Value, Value)>
Binary pointwise operation (with broadcast) entry point.
Definition at line 103 of file Builders.h.
MatmulRegionBuilder
using mlir::edsc::ops::MatmulRegionBuilder = typedef function_ref<void(ValueRange args)>
Definition at line 124 of file Builders.h.
UnaryPointwiseOpBuilder
using mlir::edsc::ops::UnaryPointwiseOpBuilder = typedef function_ref<Value(Value)>
TODO: In the future we should tie these implementations to something in Tablegen that generates the proper interfaces and the proper sugared named ops.
Build a linalg.pointwise, under the current ScopedContext, at the current insert point, that computes:
(i0, ..., in) = (par, ..., par)
|
|  O...(some_subset...(i0, ..., in)) =
|    some_pointwise_func...(I...(some_other_subset...(i0, ..., in)))
This is a very generic entry point that can be configured in many ways to build a perfect loop nest of parallel loops with arbitrarily complex innermost loop code and whatever (explicit) broadcast semantics.
This can be used with both out-of-place and in-place semantics. The client is responsible for ensuring the region operations are compatible with in-place semantics and parallelism. Unary pointwise operation (with broadcast) entry point.
Definition at line 92 of file Builders.h.
Function Documentation
linalg_generic_conv_nhwc() [1/2]
Operation * mlir::edsc::ops::linalg_generic_conv_nhwc (Value vI, Value vW, Value vO, ArrayRef< int > strides = {}, ArrayRef< int > dilations = {})
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes: ``` (batch, f, [h, w, ...], [kh, kw, ...], c) = | (par, par, [par, par, ...], [red, red, ...], red) | | O(batch, [h, w, ...], f) += | I(batch, | [ | stride[0] * h + dilations[0] * kh, | stride[1] * w + dilations[1] * kw, ...
], | c) | * | W([kh, kw, ...], c, f) `` Ifdilationsorstridesare left empty, the default value of1` is used along each relevant dimension.
For now ... must be empty (i.e. only 2-D convolutions are supported).
Definition at line 225 of file Builders.cpp.
References mlir::bindDims(), mlir::AffineExpr::cast(), mlir::edsc::ScopedContext::getContext(), macRegionBuilder(), mlir::edsc::makeGenericLinalgOp(), mlir::Parallel, mlir::Reduction, and mlir::simplifyAffineExpr().
linalg_generic_conv_nhwc() [2/2]
template<typename Container > Operation* mlir::edsc::ops::linalg_generic_conv_nhwc (Container values, ArrayRef< int > strides = {}, ArrayRef< int > dilations = {})
Definition at line 196 of file Builders.h.
References linalg_generic_dilated_conv_nhwc().
Referenced by linalg_generic_matmul().
linalg_generic_dilated_conv_nhwc() [1/2]
Operation * mlir::edsc::ops::linalg_generic_dilated_conv_nhwc (Value vI, Value vW, Value vO, int depth_multiplier = 1, ArrayRef< int > strides = {}, ArrayRef< int > dilations = {})
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes: ``` (batch, dm, c, [h, w, ...], [kh, kw, ...]) = | (par, par, par, [par, par, ...], [red, red, ...]) | | O(batch, [h, w, ...], c * depth_multiplier) += | I(batch, | [ | stride[0] * h + dilations[0] * kh, | stride[1] * w + dilations[1] * kw, ...
], | c) | * | W([kh, kw, ...], c, depth_multiplier) `` Ifdilationsorstridesare left empty, the default value of1` is used along each relevant dimension.
For now ... must be empty (i.e. only 2-D convolutions are supported).
Definition at line 259 of file Builders.cpp.
References mlir::bindDims(), mlir::AffineExpr::cast(), mlir::edsc::ScopedContext::getContext(), macRegionBuilder(), mlir::edsc::makeGenericLinalgOp(), mlir::Parallel, mlir::Reduction, and mlir::simplifyAffineExpr().
linalg_generic_dilated_conv_nhwc() [2/2]
template<typename Container > Operation* mlir::edsc::ops::linalg_generic_dilated_conv_nhwc (Container values, int depth_multiplier, ArrayRef< int > strides = {}, ArrayRef< int > dilations = {})
Definition at line 232 of file Builders.h.
Referenced by linalg_generic_conv_nhwc().
linalg_generic_matmul() [1/4]
Operation * mlir::edsc::ops::linalg_generic_matmul (Value vA, Value vB, Value vC, MatmulRegionBuilder regionBuilder = macRegionBuilder)
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes:
(m, n, k) = (par, par, seq)
|
|  C(m, n) += A(m, k) * B(k, n)
.
Definition at line 180 of file Builders.cpp.
References mlir::bindDims(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::makeGenericLinalgOp(), mlir::Parallel, and mlir::Reduction.
linalg_generic_matmul() [2/4]
Operation * mlir::edsc::ops::linalg_generic_matmul (Value vA, Value vB, RankedTensorType tC, MatmulRegionBuilder regionBuilder = mulRegionBuilder)
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes:
(m, n, k) = (par, par, seq)
|
|  C(m, n) = sum_k(A(m, k) * B(k, n))
and returns the tensor C.
Definition at line 195 of file Builders.cpp.
References mlir::bindDims(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::makeGenericLinalgOp(), mlir::Parallel, and mlir::Reduction.
linalg_generic_matmul() [3/4]
Operation * mlir::edsc::ops::linalg_generic_matmul (Value vA, Value vB, Value vC, RankedTensorType tD, MatmulRegionBuilder regionBuilder = macRegionBuilder)
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes:
(m, n, k) = (par, par, seq)
|
|  D(m, n) = C(m, n) + sum_k(A(m, k) * B(k, n))
and returns the tensor D.
Definition at line 210 of file Builders.cpp.
References mlir::bindDims(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::makeGenericLinalgOp(), mlir::Parallel, and mlir::Reduction.
linalg_generic_matmul() [4/4]
template<typename Container > Operation* mlir::edsc::ops::linalg_generic_matmul (Container values, MatmulRegionBuilder regionBuilder = macRegionBuilder)
Definition at line 163 of file Builders.h.
References linalg_generic_conv_nhwc().
linalg_generic_pointwise() [1/2]
Operation * mlir::edsc::ops::linalg_generic_pointwise (UnaryPointwiseOpBuilder unaryOp, StructuredIndexed I, StructuredIndexed O)
Definition at line 112 of file Builders.cpp.
References mlir::edsc::StructuredIndexed::getExprs(), mlir::edsc::StructuredIndexed::getType(), mlir::Type::isa(), mlir::edsc::makeGenericLinalgOp(), and mlir::Parallel.
Referenced by linalg_generic_pointwise_add(), linalg_generic_pointwise_max(), and linalg_generic_pointwise_tanh().
linalg_generic_pointwise() [2/2]
Operation * mlir::edsc::ops::linalg_generic_pointwise (BinaryPointwiseOpBuilder binaryOp, StructuredIndexed I1, StructuredIndexed I2, StructuredIndexed O)
Binary pointwise operation (with broadcast) entry point.
Definition at line 139 of file Builders.cpp.
References mlir::edsc::StructuredIndexed::getExprs(), mlir::edsc::StructuredIndexed::getType(), mlir::Type::isa(), mlir::edsc::makeGenericLinalgOp(), and mlir::Parallel.
linalg_generic_pointwise_add()
Operation * mlir::edsc::ops::linalg_generic_pointwise_add (StructuredIndexed I1, StructuredIndexed I2, StructuredIndexed O)
Build a linalg.pointwise with all parallel iterators and a region that computes O = I1 + I2.
The client is responsible for specifying the proper indexings when creating the StructuredIndexed.
Definition at line 160 of file Builders.cpp.
References linalg_generic_pointwise().
linalg_generic_pointwise_max()
Operation * mlir::edsc::ops::linalg_generic_pointwise_max (StructuredIndexed I1, StructuredIndexed I2, StructuredIndexed O)
Build a linalg.pointwise with all parallel iterators and a region that computes O = max(I1, I2).
The client is responsible for specifying the proper indexings when creating the StructuredIndexed.
Definition at line 169 of file Builders.cpp.
References linalg_generic_pointwise(), and mlir::edsc::op::sgt().
linalg_generic_pointwise_tanh()
Operation * mlir::edsc::ops::linalg_generic_pointwise_tanh (StructuredIndexed I, StructuredIndexed O)
Build a linalg.pointwise with all parallel iterators and a region that computes O = tanh(I).
The client is responsible for specifying the proper indexings when creating the StructuredIndexed.
Definition at line 132 of file Builders.cpp.
References linalg_generic_pointwise().
macRegionBuilder()
void mlir::edsc::ops::macRegionBuilder (ValueRange args)
Build the body of a region to compute a scalar multiply-accumulate, under the current ScopedContext, at the current insert point.
Definition at line 104 of file Builders.cpp.
Referenced by linalg_generic_conv_nhwc(), and linalg_generic_dilated_conv_nhwc().
mulRegionBuilder()
void mlir::edsc::ops::mulRegionBuilder (ValueRange args)
Build the body of a region to compute a scalar multiply, under the current ScopedContext, at the current insert point.
Definition at line 96 of file Builders.cpp.
vector_contraction()
Value mlir::edsc::ops::vector_contraction (StructuredIndexed A, StructuredIndexed B, StructuredIndexed C, ArrayRef< IteratorType > iteratorTypes)
Build a generic vector contraction, that is a vector.contract op with specified iteratorTypes.
The client is responsible for specifying proper indexings when creating the StructuredIndexed. The computation represents a notional (A * B + C) where indexings specify which dimensions are reduced and reordered. Return the result of the vector.contract op
Prerequisites: A, B and C capture values of proper vector types, and indexing expressions that match semantics of the vector.contract op.
Definition at line 21 of file Builders.cpp.
References mlir::edsc::StructuredIndexed::getExprs(), mlir::edsc::StructuredIndexed::getValue(), and mlir::toString().
Referenced by vector_contraction_matmul().
vector_contraction_matmul()
Value mlir::edsc::ops::vector_contraction_matmul (Value A, Value B, Value C)
Build a generic vector contraction that computes a matmul on vectors.
Return the result of C(i, j) + sum_k {A(i, k) * B(k, j)} on vectors.
Prerequisites: A, B and C capture values of proper vector types. For instance A: vector<4x8xf32>, B: vector<8x16f32> and C: vector<4x16xf32>.
Definition at line 32 of file Builders.cpp.
References mlir::bindDims(), mlir::edsc::ScopedContext::getContext(), mlir::Parallel, mlir::Reduction, and vector_contraction().