MLIR: mlir::spirv Namespace Reference
mlir::spirv Namespace Reference
Namespaces
AttrKind
SPIR-V dialect-specific attribute kinds.
detail
TypeKind
Classes
class ArrayType
class CompositeType
class CooperativeMatrixNVType
class ImageType
class InterfaceVarABIAttr
An attribute that specifies the information regarding the interface variable: descriptor set, binding, storage class.
class MatrixType
class OwningSPIRVModuleRef
This class acts as an owning reference to a SPIR-V module, and will automatically destroy the held module on destruction if the held module is valid.
class PointerType
class RuntimeArrayType
class ScalarType
class SPIRVConversionTarget
class SPIRVType
class StructType
class TargetEnv
A wrapper class around a spirv::TargetEnvAttr to provide query methods for allowed version/capabilities/extensions.
class TargetEnvAttr
An attribute that specifies the target version, allowed extensions and capabilities, and resource limits.
class VerCapExtAttr
An attribute that specifies the SPIR-V (version, capabilities, extensions) triple.
Functions
std::unique_ptr< OperationPass< mlir::ModuleOp > > createDecorateSPIRVCompositeTypeLayoutPass ()
Creates a module pass that converts composite types used by objects in the StorageBuffer, PhysicalStorageBuffer, Uniform, and PushConstant storage classes with layout information.
std::unique_ptr< OperationPass< spirv::ModuleOp > > createUpdateVersionCapabilityExtensionPass ()
Creates an operation pass that deduces and attaches the minimal version/ capabilities/extensions requirements for spv.module ops.
std::unique_ptr< OperationPass< spirv::ModuleOp > > createLowerABIAttributesPass ()
Creates an operation pass that lowers the ABI attributes specified during SPIR-V Lowering.
std::unique_ptr< OperationPass< spirv::ModuleOp > > createRewriteInsertsPass ()
Creates an operation pass that rewrites sequential chains of spv.CompositeInsert into spv.CompositeConstruct.
LogicalResult serialize (ModuleOp module, SmallVectorImpl< uint32_t > &binary, bool emitDebugInfo=false)
Serializes the given SPIR-V module and writes to binary.
OwningSPIRVModuleRef deserialize (ArrayRef< uint32_t > binary, MLIRContext *context)
Deserializes the given SPIR-V binary module and creates a MLIR ModuleOp in the given context.
void appendModuleHeader (SmallVectorImpl< uint32_t > &header, spirv::Version version, uint32_t idBound)
Appends a SPRI-V module header to header with the given version and idBound.
uint32_t getPrefixedOpcode (uint32_t wordCount, spirv::Opcode opcode)
Returns the word-count-prefixed opcode for an SPIR-V instruction.
LogicalResult encodeStringLiteralInto (SmallVectorImpl< uint32_t > &binary, StringRef literal)
Encodes an SPIR-V literal string into the given binary vector.
Value getBuiltinVariableValue (Operation *op, BuiltIn builtin, OpBuilder &builder)
Returns the value for the given builtin variable.
spirv::AccessChainOp getElementPtr (SPIRVTypeConverter &typeConverter, MemRefType baseType, Value basePtr, ValueRange indices, Location loc, OpBuilder &builder)
Performs the index computation to get to the element at indices of the memory pointed to by basePtr, using the layout map of baseType.
LogicalResult setABIAttrs (spirv::FuncOp funcOp, EntryPointABIAttr entryPointInfo, ArrayRef< InterfaceVarABIAttr > argABIInfo)
Sets the InterfaceVarABIAttr and EntryPointABIAttr for a function and its arguments.
ArrayRef< Extension > getImpliedExtensions (Version version)
Returns the implied extensions for the given version.
ArrayRef< Capability > getDirectImpliedCapabilities (Capability cap)
Returns the directly implied capabilities for the given capability.
SmallVector< Capability, 0 > getRecursiveImpliedCapabilities (Capability cap)
Returns the recursively implied capabilities for the given capability.
llvm::hash_code hash_value (const StructType::MemberDecorationInfo &memberDecorationInfo)
StringRef getInterfaceVarABIAttrName ()
Returns the attribute name for specifying argument ABI information.
InterfaceVarABIAttr getInterfaceVarABIAttr (unsigned descriptorSet, unsigned binding, Optional< StorageClass > storageClass, MLIRContext *context)
Gets the InterfaceVarABIAttr given its fields.
bool needsInterfaceVarABIAttrs (TargetEnvAttr targetAttr)
Returns whether the given SPIR-V target (described by TargetEnvAttr) needs ABI attributes for interface variables (spv.interface_var_abi).
StringRef getEntryPointABIAttrName ()
Returns the attribute name for specifying entry point information.
EntryPointABIAttr getEntryPointABIAttr (ArrayRef< int32_t > localSize, MLIRContext *context)
Gets the EntryPointABIAttr given its fields.
EntryPointABIAttr lookupEntryPointABI (Operation *op)
Queries the entry point ABI on the nearest function-like op containing the given op.
DenseIntElementsAttr lookupLocalWorkGroupSize (Operation *op)
Queries the local workgroup size from entry point ABI on the nearest function-like op containing the given op.
ResourceLimitsAttr getDefaultResourceLimits (MLIRContext *context)
Returns a default resource limits attribute that uses numbers from "Table 46. Required Limits" of the Vulkan spec.
StringRef getTargetEnvAttrName ()
Returns the attribute name for specifying SPIR-V target environment.
TargetEnvAttr getDefaultTargetEnv (MLIRContext *context)
Returns the default target environment: SPIR-V 1.0 with Shader capability and no extra extensions.
TargetEnvAttr lookupTargetEnv (Operation *op)
Queries the target environment recursively from enclosing symbol table ops containing the given op.
TargetEnvAttr lookupTargetEnvOrDefault (Operation *op)
Queries the target environment recursively from enclosing symbol table ops containing the given op or returns the default target environment as returned by getDefaultTargetEnv() if not provided.
AddressingModel getAddressingModel (TargetEnvAttr targetAttr)
Returns addressing model selected based on target environment.
FailureOr< ExecutionModel > getExecutionModel (TargetEnvAttr targetAttr)
Returns execution model selected based on target environment.
FailureOr< MemoryModel > getMemoryModel (TargetEnvAttr targetAttr)
Returns memory model selected based on target environment.
Variables
constexpr unsigned kHeaderWordCount = 5
SPIR-V binary header word count.
constexpr uint32_t kMagicNumber = 0x07230203
SPIR-V magic number.
constexpr uint32_t kGeneratorNumber = 22
The serializer tool ID registered to the Khronos Group.
Function Documentation
appendModuleHeader()
void mlir::spirv::appendModuleHeader (SmallVectorImpl< uint32_t > & header, spirv::Version version, uint32_t idBound)
Appends a SPRI-V module header to header with the given version and idBound.
Definition at line 18 of file SPIRVBinaryUtils.cpp.
References kGeneratorNumber, kMagicNumber, and MIN_VERSION_CASE.
Referenced by getPhiIncomingBlock().
createDecorateSPIRVCompositeTypeLayoutPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::spirv::createDecorateSPIRVCompositeTypeLayoutPass ()
Creates a module pass that converts composite types used by objects in the StorageBuffer, PhysicalStorageBuffer, Uniform, and PushConstant storage classes with layout information.
Right now this pass only supports Vulkan layout rules.
Definition at line 115 of file DecorateSPIRVCompositeTypeLayoutPass.cpp.
createLowerABIAttributesPass()
std::unique_ptr< OperationPass< spirv::ModuleOp > > mlir::spirv::createLowerABIAttributesPass ()
Creates an operation pass that lowers the ABI attributes specified during SPIR-V Lowering.
Specifically,
Creates the global variables for arguments of entry point function using the specification in the spv.interface_var_abi attribute for each argument.
Inserts the EntryPointOp and the ExecutionModeOp for entry point functions using the specification in the spv.entry_point_abi attribute.
Definition at line 282 of file LowerABIAttributesPass.cpp.
createRewriteInsertsPass()
std::unique_ptr< mlir::OperationPass< spirv::ModuleOp > > mlir::spirv::createRewriteInsertsPass ()
Creates an operation pass that rewrites sequential chains of spv.CompositeInsert into spv.CompositeConstruct.
Definition at line 113 of file RewriteInsertsPass.cpp.
createUpdateVersionCapabilityExtensionPass()
std::unique_ptr< OperationPass< spirv::ModuleOp > > mlir::spirv::createUpdateVersionCapabilityExtensionPass ()
Creates an operation pass that deduces and attaches the minimal version/ capabilities/extensions requirements for spv.module ops.
For each spv.module op, this pass requires a spv.target_env attribute on it or an enclosing module-like op to drive the deduction. The reason is that an op can be enabled by multiple extensions/capabilities. So we need to know which one to pick. spv.target_env gives the hard limit as for what the target environment can support; this pass deduces what are actually needed for a specific spv.module op.
Definition at line 176 of file UpdateVCEPass.cpp.
deserialize()
spirv::OwningSPIRVModuleRef mlir::spirv::deserialize (ArrayRef< uint32_t > binary, MLIRContext * context)
Deserializes the given SPIR-V binary module and creates a MLIR ModuleOp in the given context.
Returns the ModuleOp on success; otherwise, reports errors to the error handler registered with context and returns a null module.
Definition at line 2592 of file Deserializer.cpp.
References mlir::failed().
Referenced by deserializeModule(), isFnEntryBlock(), and roundTripModule().
encodeStringLiteralInto()
LogicalResult mlir::spirv::encodeStringLiteralInto (SmallVectorImpl< uint32_t > & binary, StringRef literal)
Encodes an SPIR-V literal string into the given binary vector.
Definition at line 65 of file SPIRVBinaryUtils.cpp.
References mlir::success().
Referenced by getPhiIncomingBlock().
getAddressingModel()
spirv::AddressingModel mlir::spirv::getAddressingModel (spirv::TargetEnvAttr targetAttr)
Returns addressing model selected based on target environment.
Definition at line 180 of file TargetAndABI.cpp.
References mlir::spirv::TargetEnvAttr::getCapabilities().
Referenced by getDefaultABIAttrs(), and mlir::spirv::TargetEnv::operator TargetEnvAttr().
getBuiltinVariableValue()
Value mlir::spirv::getBuiltinVariableValue (Operation * op, BuiltIn builtin, OpBuilder & builder)
Returns the value for the given builtin variable.
This function gets or inserts the global variable associated for the builtin within the nearest enclosing op that has a symbol table. Returns null Value if such an enclosing op cannot be found.
Referenced by getLaunchConfigIndex(), getLocalInvocationDimSize(), and getOrInsertBuiltinVariable().
getDefaultResourceLimits()
spirv::ResourceLimitsAttr mlir::spirv::getDefaultResourceLimits (MLIRContext * context)
Returns a default resource limits attribute that uses numbers from "Table 46. Required Limits" of the Vulkan spec.
Definition at line 136 of file TargetAndABI.cpp.
References mlir::IntegerType::get(), mlir::VectorType::get(), and mlir::IntegerAttr::get().
Referenced by getDefaultTargetEnv(), and mlir::spirv::TargetEnv::operator TargetEnvAttr().
getDefaultTargetEnv()
spirv::TargetEnvAttr mlir::spirv::getDefaultTargetEnv (MLIRContext * context)
Returns the default target environment: SPIR-V 1.0 with Shader capability and no extra extensions.
Definition at line 148 of file TargetAndABI.cpp.
References mlir::spirv::VerCapExtAttr::get(), mlir::spirv::TargetEnvAttr::get(), and getDefaultResourceLimits().
Referenced by lookupTargetEnvOrDefault(), and mlir::spirv::TargetEnv::operator TargetEnvAttr().
getDirectImpliedCapabilities()
ArrayRef<Capability> mlir::spirv::getDirectImpliedCapabilities (Capability cap)
Returns the directly implied capabilities for the given capability.
These capabilities are implicitly declared by the given capability.
Referenced by getRecursiveImpliedCapabilities().
getElementPtr()
spirv::AccessChainOp mlir::spirv::getElementPtr (SPIRVTypeConverter & typeConverter, MemRefType baseType, Value basePtr, ValueRange indices, Location loc, OpBuilder & builder)
Performs the index computation to get to the element at indices of the memory pointed to by basePtr, using the layout map of baseType.
Definition at line 604 of file SPIRVLowering.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failed(), mlir::IntegerAttr::get(), mlir::Builder::getContext(), mlir::MemRefType::getDynamicStrideOrOffset(), getEntryPointABIAttrName(), mlir::SPIRVTypeConverter::getIndexType(), getInterfaceVarABIAttrName(), mlir::getStridesAndOffset(), setABIAttrs(), and mlir::success().
Referenced by getAtomicOpScope(), and getLocalInvocationDimSize().
getEntryPointABIAttr()
spirv::EntryPointABIAttr mlir::spirv::getEntryPointABIAttr (ArrayRef< int32_t > localSize, MLIRContext * context)
Gets the EntryPointABIAttr given its fields.
Definition at line 106 of file TargetAndABI.cpp.
References mlir::IntegerType::get(), and mlir::VectorType::get().
Referenced by mlir::spirv::TargetEnv::operator TargetEnvAttr().
getEntryPointABIAttrName()
StringRef mlir::spirv::getEntryPointABIAttrName ()
Returns the attribute name for specifying entry point information.
Definition at line 103 of file TargetAndABI.cpp.
Referenced by getElementPtr(), lookupEntryPointABI(), lowerEntryPointABIAttr(), mlir::spirv::TargetEnv::operator TargetEnvAttr(), and print().
getExecutionModel()
FailureOr< spirv::ExecutionModel > mlir::spirv::getExecutionModel (spirv::TargetEnvAttr targetAttr)
Returns execution model selected based on target environment.
Returns failure if it cannot be selected.
Definition at line 192 of file TargetAndABI.cpp.
References mlir::failure(), and mlir::spirv::TargetEnvAttr::getCapabilities().
Referenced by lowerEntryPointABIAttr(), and mlir::spirv::TargetEnv::operator TargetEnvAttr().
getImpliedExtensions()
ArrayRef< Extension > mlir::spirv::getImpliedExtensions (Version version)
Returns the implied extensions for the given version.
These extensions are incorporated into the current version so they are implicitly declared when targeting the given version.
Definition at line 35 of file SPIRVTypes.cpp.
References V_1_3_IMPLIED_EXTS, V_1_4_IMPLIED_EXTS, and V_1_5_IMPLIED_EXTS.
Referenced by mlir::spirv::TargetEnv::TargetEnv().
getInterfaceVarABIAttr()
InterfaceVarABIAttr mlir::spirv::getInterfaceVarABIAttr (unsigned descriptorSet, unsigned binding, Optional< StorageClass > storageClass, MLIRContext * context)
Gets the InterfaceVarABIAttr given its fields.
Referenced by getDefaultABIAttrs(), getInterfaceVarABIAttrName(), and mlir::spirv::TargetEnv::operator TargetEnvAttr().
getInterfaceVarABIAttrName()
StringRef mlir::spirv::getInterfaceVarABIAttrName ()
Returns the attribute name for specifying argument ABI information.
Definition at line 81 of file TargetAndABI.cpp.
References mlir::spirv::InterfaceVarABIAttr::get(), and getInterfaceVarABIAttr().
Referenced by getDefaultABIAttrs(), getElementPtr(), lowerEntryPointABIAttr(), mlir::spirv::TargetEnv::operator TargetEnvAttr(), and verifyRegionAttribute().
getMemoryModel()
FailureOr< spirv::MemoryModel > mlir::spirv::getMemoryModel (spirv::TargetEnvAttr targetAttr)
Returns memory model selected based on target environment.
Returns failure if it cannot be selected.
Definition at line 203 of file TargetAndABI.cpp.
References mlir::failure(), and mlir::spirv::TargetEnvAttr::getCapabilities().
Referenced by getDefaultABIAttrs(), and mlir::spirv::TargetEnv::operator TargetEnvAttr().
getPrefixedOpcode()
uint32_t mlir::spirv::getPrefixedOpcode (uint32_t wordCount, spirv::Opcode opcode)
Returns the word-count-prefixed opcode for an SPIR-V instruction.
Definition at line 60 of file SPIRVBinaryUtils.cpp.
Referenced by encodeInstructionInto().
getRecursiveImpliedCapabilities()
SmallVector< Capability, 0 > mlir::spirv::getRecursiveImpliedCapabilities (Capability cap)
Returns the recursively implied capabilities for the given capability.
These capabilities are implicitly declared by the given capability. Compared to the above function, this function collects implied capabilities recursively: if an implicitly declared capability implicitly declares a third one, the third one will also be returned.
Definition at line 85 of file SPIRVTypes.cpp.
References getDirectImpliedCapabilities().
Referenced by mlir::spirv::TargetEnv::TargetEnv().
getTargetEnvAttrName()
StringRef mlir::spirv::getTargetEnvAttrName ()
Returns the attribute name for specifying SPIR-V target environment.
Definition at line 146 of file TargetAndABI.cpp.
Referenced by lookupTargetEnv(), mlir::spirv::TargetEnv::operator TargetEnvAttr(), and print().
hash_value()
llvm::hash_code mlir::spirv::hash_value (const StructType::MemberDecorationInfo & memberDecorationInfo)
Definition at line 954 of file SPIRVTypes.cpp.
References mlir::spirv::StructType::MemberDecorationInfo::decoration, and mlir::spirv::StructType::MemberDecorationInfo::memberIndex.
Referenced by llvm::DenseMapInfo< mlir::spirv::FuncOp >::getHashValue(), mlir::detail::DenseIntOrFPElementsAttributeStorage::getKey(), mlir::detail::DenseStringElementsAttributeStorage::getKey(), mlir::detail::DenseIntOrFPElementsAttributeStorage::getKeyForBoolData(), mlir::SDBMExpr::hash_value(), mlir::detail::IntegerTypeStorage::hashKey(), mlir::detail::FloatAttributeStorage::hashKey(), and mlir::detail::IntegerAttributeStorage::hashKey().
lookupEntryPointABI()
spirv::EntryPointABIAttr mlir::spirv::lookupEntryPointABI (Operation * op)
Queries the entry point ABI on the nearest function-like op containing the given op.
Returns null attribute if not found.
Definition at line 115 of file TargetAndABI.cpp.
References mlir::Operation::getAttrOfType(), getEntryPointABIAttrName(), mlir::Operation::getParentOp(), and mlir::Operation::hasTrait().
Referenced by getDefaultABIAttrs(), lookupLocalWorkGroupSize(), and mlir::spirv::TargetEnv::operator TargetEnvAttr().
lookupLocalWorkGroupSize()
DenseIntElementsAttr mlir::spirv::lookupLocalWorkGroupSize (Operation * op)
Queries the local workgroup size from entry point ABI on the nearest function-like op containing the given op.
Returns null attribute if not found.
Definition at line 128 of file TargetAndABI.cpp.
References lookupEntryPointABI().
Referenced by getLaunchConfigIndex(), getLocalInvocationDimSize(), and mlir::spirv::TargetEnv::operator TargetEnvAttr().
lookupTargetEnv()
spirv::TargetEnvAttr mlir::spirv::lookupTargetEnv (Operation * op)
Queries the target environment recursively from enclosing symbol table ops containing the given op.
Definition at line 156 of file TargetAndABI.cpp.
References mlir::Operation::getAttrOfType(), mlir::SymbolTable::getNearestSymbolTable(), mlir::Operation::getParentOp(), and getTargetEnvAttrName().
Referenced by checkAndUpdateCapabilityRequirements(), lookupTargetEnvOrDefault(), lowerEntryPointABIAttr(), and mlir::spirv::TargetEnv::operator TargetEnvAttr().
lookupTargetEnvOrDefault()
spirv::TargetEnvAttr mlir::spirv::lookupTargetEnvOrDefault (Operation * op)
Queries the target environment recursively from enclosing symbol table ops containing the given op or returns the default target environment as returned by getDefaultTargetEnv() if not provided.
Definition at line 172 of file TargetAndABI.cpp.
References mlir::Operation::getContext(), getDefaultTargetEnv(), and lookupTargetEnv().
Referenced by getDefaultABIAttrs(), and mlir::spirv::TargetEnv::operator TargetEnvAttr().
needsInterfaceVarABIAttrs()
bool mlir::spirv::needsInterfaceVarABIAttrs (spirv::TargetEnvAttr targetAttr)
Returns whether the given SPIR-V target (described by TargetEnvAttr) needs ABI attributes for interface variables (spv.interface_var_abi).
Definition at line 93 of file TargetAndABI.cpp.
References mlir::spirv::TargetEnvAttr::getCapabilities().
Referenced by getDefaultABIAttrs(), and mlir::spirv::TargetEnv::operator TargetEnvAttr().
serialize()
LogicalResult mlir::spirv::serialize (ModuleOp module, SmallVectorImpl< uint32_t > & binary, bool emitDebugInfo = false)
Serializes the given SPIR-V module and writes to binary.
On failure, reports errors to the error handler registered with the MLIR context for module.
Referenced by getPhiIncomingBlock(), roundTripModule(), and serializeModule().
setABIAttrs()
LogicalResult mlir::spirv::setABIAttrs (spirv::FuncOp funcOp, EntryPointABIAttr entryPointInfo, ArrayRef< InterfaceVarABIAttr > argABIInfo)
Sets the InterfaceVarABIAttr and EntryPointABIAttr for a function and its arguments.
Referenced by getElementPtr(), and lowerAsEntryFunction().
Variable Documentation
kGeneratorNumber
constexpr uint32_t mlir::spirv::kGeneratorNumber = 22
The serializer tool ID registered to the Khronos Group.
Definition at line 31 of file SPIRVBinaryUtils.h.
Referenced by appendModuleHeader().
kHeaderWordCount
constexpr unsigned mlir::spirv::kHeaderWordCount = 5
SPIR-V binary header word count.
Definition at line 25 of file SPIRVBinaryUtils.h.
Referenced by getPhiIncomingBlock(), and isFnEntryBlock().
kMagicNumber
constexpr uint32_t mlir::spirv::kMagicNumber = 0x07230203
SPIR-V magic number.
Definition at line 28 of file SPIRVBinaryUtils.h.
Referenced by appendModuleHeader(), and isFnEntryBlock().