MLIR: mlir::OpTrait::impl Namespace Reference
mlir::OpTrait::impl Namespace Reference
Functions
LogicalResult verifyCompatibleOperandBroadcast (Operation *op)
LogicalResult verifyZeroOperands (Operation *op)
LogicalResult verifyOneOperand (Operation *op)
LogicalResult verifyNOperands (Operation *op, unsigned numOperands)
LogicalResult verifyAtLeastNOperands (Operation *op, unsigned numOperands)
LogicalResult verifyOperandsAreFloatLike (Operation *op)
LogicalResult verifyOperandsAreSignlessIntegerLike (Operation *op)
LogicalResult verifySameTypeOperands (Operation *op)
LogicalResult verifyZeroRegion (Operation *op)
LogicalResult verifyOneRegion (Operation *op)
LogicalResult verifyNRegions (Operation *op, unsigned numRegions)
LogicalResult verifyAtLeastNRegions (Operation *op, unsigned numRegions)
LogicalResult verifyZeroResult (Operation *op)
LogicalResult verifyOneResult (Operation *op)
LogicalResult verifyNResults (Operation *op, unsigned numOperands)
LogicalResult verifyAtLeastNResults (Operation *op, unsigned numOperands)
LogicalResult verifySameOperandsShape (Operation *op)
LogicalResult verifySameOperandsAndResultShape (Operation *op)
LogicalResult verifySameOperandsElementType (Operation *op)
LogicalResult verifySameOperandsAndResultElementType (Operation *op)
LogicalResult verifySameOperandsAndResultType (Operation *op)
LogicalResult verifyResultsAreBoolLike (Operation *op)
LogicalResult verifyResultsAreFloatLike (Operation *op)
LogicalResult verifyResultsAreSignlessIntegerLike (Operation *op)
LogicalResult verifyIsTerminator (Operation *op)
LogicalResult verifyZeroSuccessor (Operation *op)
LogicalResult verifyOneSuccessor (Operation *op)
LogicalResult verifyNSuccessors (Operation *op, unsigned numSuccessors)
LogicalResult verifyAtLeastNSuccessors (Operation *op, unsigned numSuccessors)
LogicalResult verifyOperandSizeAttr (Operation *op, StringRef sizeAttrName)
LogicalResult verifyResultSizeAttr (Operation *op, StringRef sizeAttrName)
LogicalResult verifyNoRegionArguments (Operation *op)
Function Documentation
verifyAtLeastNOperands()
LogicalResult mlir::OpTrait::impl::verifyAtLeastNOperands (Operation * op, unsigned numOperands)
Definition at line 704 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumOperands(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), verifySameOperandsAndResultElementType(), verifySameOperandsAndResultShape(), verifySameOperandsAndResultType(), verifySameOperandsElementType(), verifySameOperandsShape(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::verifyTrait(), and mlir::OpTrait::AtLeastNOperands< N >::Impl< ConcreteType >::verifyTrait().
verifyAtLeastNRegions()
LogicalResult mlir::OpTrait::impl::verifyAtLeastNRegions (Operation * op, unsigned numRegions)
Definition at line 775 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumRegions(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::AtLeastNRegions< N >::Impl< ConcreteType >::verifyTrait().
verifyAtLeastNResults()
LogicalResult mlir::OpTrait::impl::verifyAtLeastNResults (Operation * op, unsigned numOperands)
Definition at line 801 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumResults(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), verifySameOperandsAndResultElementType(), verifySameOperandsAndResultShape(), verifySameOperandsAndResultType(), and mlir::OpTrait::AtLeastNResults< N >::Impl< ConcreteType >::verifyTrait().
verifyAtLeastNSuccessors()
LogicalResult mlir::OpTrait::impl::verifyAtLeastNSuccessors (Operation * op, unsigned numSuccessors)
Definition at line 942 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumSuccessors(), and verifyTerminatorSuccessors().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::AtLeastNSuccessors< N >::Impl< ConcreteType >::verifyTrait().
verifyCompatibleOperandBroadcast()
LogicalResult mlir::OpTrait::impl::verifyCompatibleOperandBroadcast (Operation * op)
Definition at line 189 of file Traits.cpp.
References areCompatibleShapes(), mlir::Operation::emitError(), mlir::Operation::emitOpError(), mlir::OpTrait::util::getBroadcastedShape(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), getShape(), getShapeString(), hasTensorOrVectorType(), and mlir::success().
Referenced by mlir::OpTrait::ResultsBroadcastableShape< ConcreteType >::verifyTrait().
verifyIsTerminator()
LogicalResult mlir::OpTrait::impl::verifyIsTerminator (Operation * op)
Definition at line 900 of file Operation.cpp.
References mlir::Block::back(), mlir::Operation::emitOpError(), mlir::Operation::getBlock(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::IsTerminator< ConcreteType >::verifyTrait().
verifyNOperands()
LogicalResult mlir::OpTrait::impl::verifyNOperands (Operation * op, unsigned numOperands)
Definition at line 695 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumOperands(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::NOperands< N >::Impl< ConcreteType >::verifyTrait().
verifyNoRegionArguments()
LogicalResult mlir::OpTrait::impl::verifyNoRegionArguments (Operation * op)
Definition at line 1020 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumRegions(), mlir::Operation::getRegions(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::NoRegionArguments< ConcrentType >::verifyTrait().
verifyNRegions()
LogicalResult mlir::OpTrait::impl::verifyNRegions (Operation * op, unsigned numRegions)
Definition at line 768 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumRegions(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::NRegions< N >::Impl< ConcreteType >::verifyTrait().
verifyNResults()
LogicalResult mlir::OpTrait::impl::verifyNResults (Operation * op, unsigned numOperands)
Definition at line 794 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumResults(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::NResults< N >::Impl< ConcreteType >::verifyTrait().
verifyNSuccessors()
LogicalResult mlir::OpTrait::impl::verifyNSuccessors (Operation * op, unsigned numSuccessors)
Definition at line 933 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumSuccessors(), and verifyTerminatorSuccessors().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::NSuccessors< N >::Impl< ConcreteType >::verifyTrait().
verifyOneOperand()
LogicalResult mlir::OpTrait::impl::verifyOneOperand (Operation * op)
Definition at line 689 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumOperands(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::OneOperand< ConcreteType >::verifyTrait().
verifyOneRegion()
LogicalResult mlir::OpTrait::impl::verifyOneRegion (Operation * op)
Definition at line 762 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumRegions(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::OneRegion< ConcreteType >::verifyTrait().
verifyOneResult()
LogicalResult mlir::OpTrait::impl::verifyOneResult (Operation * op)
Definition at line 788 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumResults(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::OneResult< ConcreteType >::verifyTrait().
verifyOneSuccessor()
LogicalResult mlir::OpTrait::impl::verifyOneSuccessor (Operation * op)
Definition at line 926 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumSuccessors(), and verifyTerminatorSuccessors().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::OneSuccessor< ConcreteType >::verifyTrait().
verifyOperandsAreFloatLike()
LogicalResult mlir::OpTrait::impl::verifyOperandsAreFloatLike (Operation * op)
Definition at line 734 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getOperandTypes(), getTensorOrVectorElementType(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::OperandsAreFloatLike< ConcreteType >::verifyTrait().
verifyOperandsAreSignlessIntegerLike()
LogicalResult mlir::OpTrait::impl::verifyOperandsAreSignlessIntegerLike (Operation * op)
Definition at line 725 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getOperandTypes(), getTensorOrVectorElementType(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::OperandsAreSignlessIntegerLike< ConcreteType >::verifyTrait().
verifyOperandSizeAttr()
LogicalResult mlir::OpTrait::impl::verifyOperandSizeAttr (Operation * op, StringRef sizeAttrName)
Definition at line 1010 of file Operation.cpp.
References verifyValueSizeAttr().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::AttrSizedOperandSegments< ConcreteType >::verifyTrait().
verifyResultsAreBoolLike()
LogicalResult mlir::OpTrait::impl::verifyResultsAreBoolLike (Operation * op)
Definition at line 952 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getResultTypes(), getTensorOrVectorElementType(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::ResultsAreBoolLike< ConcreteType >::verifyTrait().
verifyResultsAreFloatLike()
LogicalResult mlir::OpTrait::impl::verifyResultsAreFloatLike (Operation * op)
Definition at line 963 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getResultTypes(), getTensorOrVectorElementType(), mlir::Type::isa(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::ResultsAreFloatLike< ConcreteType >::verifyTrait().
verifyResultsAreSignlessIntegerLike()
LogicalResult mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike (Operation * op)
Definition at line 972 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getResultTypes(), getTensorOrVectorElementType(), mlir::Type::isSignlessIntOrIndex(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::ResultsAreSignlessIntegerLike< ConcreteType >::verifyTrait().
verifyResultSizeAttr()
LogicalResult mlir::OpTrait::impl::verifyResultSizeAttr (Operation * op, StringRef sizeAttrName)
Definition at line 1015 of file Operation.cpp.
References verifyValueSizeAttr().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::AttrSizedResultSegments< ConcreteType >::verifyTrait().
verifySameOperandsAndResultElementType()
LogicalResult mlir::OpTrait::impl::verifySameOperandsAndResultElementType (Operation * op)
Definition at line 854 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::getElementTypeOrSelf(), mlir::Operation::getOperands(), mlir::Operation::getResult(), mlir::Operation::getResults(), mlir::success(), verifyAtLeastNOperands(), and verifyAtLeastNResults().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::SameOperandsAndResultElementType< ConcreteType >::verifyTrait().
verifySameOperandsAndResultShape()
LogicalResult mlir::OpTrait::impl::verifySameOperandsAndResultShape (Operation * op)
Definition at line 821 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Operation::getOperand(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), mlir::Value::getType(), mlir::success(), verifyAtLeastNOperands(), verifyAtLeastNResults(), and mlir::verifyCompatibleShape().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::SameOperandsAndResultShape< ConcreteType >::verifyTrait().
verifySameOperandsAndResultType()
LogicalResult mlir::OpTrait::impl::verifySameOperandsAndResultType (Operation * op)
Definition at line 878 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::getElementTypeOrSelf(), mlir::Operation::getOperandTypes(), mlir::Operation::getResult(), mlir::Operation::getResultTypes(), mlir::Value::getType(), mlir::success(), verifyAtLeastNOperands(), verifyAtLeastNResults(), and mlir::verifyCompatibleShape().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::SameOperandsAndResultType< ConcreteType >::verifyTrait().
verifySameOperandsElementType()
LogicalResult mlir::OpTrait::impl::verifySameOperandsElementType (Operation * op)
Definition at line 840 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::getElementTypeOrSelf(), mlir::Operation::getOperand(), mlir::Operation::getOperands(), mlir::success(), and verifyAtLeastNOperands().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::SameOperandsElementType< ConcreteType >::verifyTrait().
verifySameOperandsShape()
LogicalResult mlir::OpTrait::impl::verifySameOperandsShape (Operation * op)
Definition at line 809 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Operation::getOperand(), mlir::Operation::getOperandTypes(), mlir::Value::getType(), mlir::success(), verifyAtLeastNOperands(), and mlir::verifyCompatibleShape().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::SameOperandsShape< ConcreteType >::verifyTrait().
verifySameTypeOperands()
LogicalResult mlir::OpTrait::impl::verifySameTypeOperands (Operation * op)
Definition at line 743 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::Operation::getOperandTypes(), mlir::Value::getType(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::SameTypeOperands< ConcreteType >::verifyTrait().
verifyZeroOperands()
LogicalResult mlir::OpTrait::impl::verifyZeroOperands (Operation * op)
Definition at line 683 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumOperands(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::ZeroOperands< ModuleTerminatorOp >::verifyTrait().
verifyZeroRegion()
LogicalResult mlir::OpTrait::impl::verifyZeroRegion (Operation * op)
Definition at line 756 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumRegions(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::ZeroRegion< ConcreteType >::verifyTrait().
verifyZeroResult()
LogicalResult mlir::OpTrait::impl::verifyZeroResult (Operation * op)
Definition at line 782 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumResults(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::ZeroResult< ConcreteType >::verifyTrait().
verifyZeroSuccessor()
LogicalResult mlir::OpTrait::impl::verifyZeroSuccessor (Operation * op)
Definition at line 918 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumSuccessors(), and mlir::success().
Referenced by mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold(), and mlir::OpTrait::ZeroSuccessor< ConcreteType >::verifyTrait().