MLIR: mlir::LLVM Namespace Reference
mlir::LLVM Namespace Reference
Namespaces
detail
Classes
class LLVMArrayType
LLVM dialect array type.
class LLVMFixedVectorType
LLVM dialect fixed vector type, represents a sequence of elements of known length that can be processed as one.
class LLVMFunctionType
LLVM dialect function type.
class LLVMIntegerType
LLVM dialect signless integer type parameterized by bitwidth.
class LLVMPointerType
LLVM dialect pointer type.
class LLVMScalableVectorType
LLVM dialect scalable vector type, represents a sequence of elements of unknown length that is known to be divisible by some constant.
class LLVMStructType
LLVM dialect structure type representing a collection of different-typed elements manipulated together.
class LLVMType
Base class for LLVM dialect types.
class LLVMVectorType
LLVM dialect vector type, represents a sequence of elements that can be processed as one, typically in SIMD context.
class ModuleTranslation
Implementation class for module translation.
class TypeFromLLVMIRTranslator
Utility class to translate LLVM IR types to the MLIR LLVM dialect.
class TypeToLLVMIRTranslator
Utility class to translate MLIR LLVM dialect types to LLVM IR.
Functions
Value createGlobalString (Location loc, OpBuilder &builder, StringRef name, StringRef value, LLVM::Linkage linkage)
Create an LLVM global containing the string "value" at the module containing surrounding the insertion point of builder.
bool satisfiesLLVMModule (Operation *op)
LLVM requires some operations to be inside of a Module operation.
DEFINE_TRIVIAL_LLVM_TYPE (LLVMVoidType, LLVMType::VoidType)
DEFINE_TRIVIAL_LLVM_TYPE (LLVMHalfType, LLVMType::HalfType)
DEFINE_TRIVIAL_LLVM_TYPE (LLVMBFloatType, LLVMType::BFloatType)
DEFINE_TRIVIAL_LLVM_TYPE (LLVMFloatType, LLVMType::FloatType)
DEFINE_TRIVIAL_LLVM_TYPE (LLVMDoubleType, LLVMType::DoubleType)
DEFINE_TRIVIAL_LLVM_TYPE (LLVMFP128Type, LLVMType::FP128Type)
DEFINE_TRIVIAL_LLVM_TYPE (LLVMX86FP80Type, LLVMType::X86FP80Type)
DEFINE_TRIVIAL_LLVM_TYPE (LLVMPPCFP128Type, LLVMType::PPCFP128Type)
DEFINE_TRIVIAL_LLVM_TYPE (LLVMX86MMXType, LLVMType::X86MMXType)
DEFINE_TRIVIAL_LLVM_TYPE (LLVMTokenType, LLVMType::TokenType)
DEFINE_TRIVIAL_LLVM_TYPE (LLVMLabelType, LLVMType::LabelType)
DEFINE_TRIVIAL_LLVM_TYPE (LLVMMetadataType, LLVMType::MetadataType)
void ensureDistinctSuccessors (Operation *op)
Make argument-taking successors of each block distinct.
std::unique_ptr< Pass > createLegalizeForExportPass ()
Creates a pass that legalizes the LLVM dialect operations so that they can be translated to LLVM IR.
Function Documentation
createGlobalString()
Value mlir::LLVM::createGlobalString (Location loc, OpBuilder & builder, StringRef name, StringRef value, LLVM::Linkage linkage)
Create an LLVM global containing the string "value" at the module containing surrounding the insertion point of builder.
Obtain the address of that global and use it to compute the address of the first character in the string (operations inserted at the builder insertion point).
Definition at line 1755 of file LLVMDialect.cpp.
References mlir::OpBuilder::create(), mlir::LLVM::LLVMType::getArrayTy(), mlir::Builder::getContext(), mlir::Builder::getIndexType(), mlir::OpBuilder::getInsertionBlock(), mlir::LLVM::LLVMType::getInt64Ty(), mlir::LLVM::LLVMType::getInt8PtrTy(), mlir::LLVM::LLVMType::getInt8Ty(), mlir::Builder::getIntegerAttr(), mlir::Operation::getParentOfType(), mlir::Block::getParentOp(), and mlir::Builder::getStringAttr().
createLegalizeForExportPass()
std::unique_ptr< Pass > mlir::LLVM::createLegalizeForExportPass ()
Creates a pass that legalizes the LLVM dialect operations so that they can be translated to LLVM IR.
Definition at line 68 of file LegalizeForExport.cpp.
DEFINE_TRIVIAL_LLVM_TYPE() [1/12]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMVoidType , LLVMType::VoidType)
DEFINE_TRIVIAL_LLVM_TYPE() [2/12]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMHalfType , LLVMType::HalfType)
DEFINE_TRIVIAL_LLVM_TYPE() [3/12]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMBFloatType , LLVMType::BFloatType)
DEFINE_TRIVIAL_LLVM_TYPE() [4/12]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMFloatType , LLVMType::FloatType)
DEFINE_TRIVIAL_LLVM_TYPE() [5/12]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMDoubleType , LLVMType::DoubleType)
DEFINE_TRIVIAL_LLVM_TYPE() [6/12]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMFP128Type , LLVMType::FP128Type)
DEFINE_TRIVIAL_LLVM_TYPE() [7/12]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMX86FP80Type , LLVMType::X86FP80Type)
DEFINE_TRIVIAL_LLVM_TYPE() [8/12]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMPPCFP128Type , LLVMType::PPCFP128Type)
DEFINE_TRIVIAL_LLVM_TYPE() [9/12]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMX86MMXType , LLVMType::X86MMXType)
DEFINE_TRIVIAL_LLVM_TYPE() [10/12]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMTokenType , LLVMType::TokenType)
DEFINE_TRIVIAL_LLVM_TYPE() [11/12]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMLabelType , LLVMType::LabelType)
DEFINE_TRIVIAL_LLVM_TYPE() [12/12]
mlir::LLVM::DEFINE_TRIVIAL_LLVM_TYPE (LLVMMetadataType , LLVMType::MetadataType)
ensureDistinctSuccessors()
void mlir::LLVM::ensureDistinctSuccessors (Operation * op)
Make argument-taking successors of each block distinct.
PHI nodes in LLVM IR use the predecessor ID to identify which value to take. They do not support different values coming from the same predecessor. If a block has another block as a successor more than once with different values, insert a new dummy block for LLVM PHI nodes to tell the sources apart.
Definition at line 51 of file LegalizeForExport.cpp.
References ensureDistinctSuccessors(), and mlir::Operation::walk().
Referenced by mlir::LLVM::ModuleTranslation::translateModule().
satisfiesLLVMModule()
bool mlir::LLVM::satisfiesLLVMModule (Operation * op)
LLVM requires some operations to be inside of a Module operation.
This function confirms that the Operation has the desired properties.
Definition at line 1783 of file LLVMDialect.cpp.
References mlir::Operation::hasTrait().
Referenced by lookupSymbolInModule(), mlir::LLVM::ModuleTranslation::ModuleTranslation(), mlir::LLVM::ModuleTranslation::translateModule(), and verify().