MLIR: mlir::gpu Namespace Reference
mlir::gpu Namespace Reference
Classes
struct KernelDim3
Utility class for the GPU dialect to represent triples of Values accessible through .x, .y, and .z similarly to CUDA notation.
Functions
StringRef getMappingAttrName ()
Name of the mapping attribute produced by loop mappers.
Processor getProcessor (ParallelLoopDimMapping attr)
Get the value of the processor in the ParallelLoopDimMapping attribute.
ParallelLoopDimMapping getParallelLoopDimMappingAttr (Processor processor, AffineMap map, AffineMap bound)
Helper function to create a ParallelDimMapperAttr.
LogicalResult setMappingAttr (scf::ParallelOp ploopOp, ArrayRef< ParallelLoopDimMapping > mapping)
Sets the mapping attribute of a scf.parallel operation.
Function Documentation
getMappingAttrName()
StringRef mlir::gpu::getMappingAttrName ()
Name of the mapping attribute produced by loop mappers.
Definition at line 32 of file ParallelLoopMapper.cpp.
Referenced by mapParallelOp(), processParallelLoop(), and setMappingAttr().
getParallelLoopDimMappingAttr()
ParallelLoopDimMapping mlir::gpu::getParallelLoopDimMappingAttr (Processor processor, AffineMap map, AffineMap bound)
Helper function to create a ParallelDimMapperAttr.
TODO: Replace its uses with an auto-gened method.
Definition at line 34 of file ParallelLoopMapper.cpp.
References mlir::AffineMapAttr::get(), mlir::AffineMap::getContext(), and mlir::Builder::getI64IntegerAttr().
Referenced by getProcessor(), and mapParallelOp().
getProcessor()
Processor mlir::gpu::getProcessor (ParallelLoopDimMapping attr) inline
Get the value of the processor in the ParallelLoopDimMapping attribute.
Definition at line 42 of file ParallelLoopMapper.h.
References getParallelLoopDimMappingAttr(), mlir::greedilyMapParallelSCFToGPU(), and setMappingAttr().
Referenced by processParallelLoop(), and setMappingAttr().
setMappingAttr()
LogicalResult mlir::gpu::setMappingAttr (scf::ParallelOp ploopOp, ArrayRef< ParallelLoopDimMapping > mapping)
Sets the mapping attribute of a scf.parallel operation.
Verifies that the mapping passed is valid.
the number of DimMapperAttr provided is same as the number of loops of the ploopOp.
the mapping does not map multiple loops to the same processor.
Definition at line 44 of file ParallelLoopMapper.cpp.
References mlir::ArrayAttr::get(), getMappingAttrName(), getProcessor(), and mlir::success().
Referenced by getProcessor(), and mapParallelOp().