MLIR: lib/Transforms/NormalizeMemRefs.cpp File Reference
NormalizeMemRefs.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/Utils.h"
Macros
#define DEBUG_TYPE "normalize-memrefs"
Functions
static bool isMemRefDereferencingOp (Operation &op)
static bool isMemRefNormalizable (Value::user_range opUsers)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "normalize-memrefs"
Definition at line 19 of file NormalizeMemRefs.cpp.
Function Documentation
isMemRefDereferencingOp()
static bool isMemRefDereferencingOp (Operation & op) static
Definition at line 82 of file NormalizeMemRefs.cpp.
Referenced by isMemRefNormalizable().
isMemRefNormalizable()
static bool isMemRefNormalizable (Value::user_range opUsers) static
Definition at line 90 of file NormalizeMemRefs.cpp.
References mlir::WalkResult::advance(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::FuncOp::eraseArgument(), mlir::failed(), mlir::FunctionType::get(), mlir::MemRefType::getAffineMaps(), mlir::FunctionType::getResults(), mlir::Value::getType(), mlir::BlockArgument::getType(), mlir::Value::getUsers(), mlir::WalkResult::interrupt(), mlir::Type::isa(), isMemRefDereferencingOp(), mlir::normalizeMemRef(), mlir::normalizeMemRefType(), mlir::replaceAllMemRefUsesWith(), and mlir::OpState::walk().