MLIR: lib/Dialect/LLVMIR/IR/NVVMDialect.cpp File Reference
NVVMDialect.cpp File Reference
#include "mlir/Dialect/LLVMIR/NVVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/StandardTypes.h"
#include "llvm/AsmParser/Parser.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/SourceMgr.h"
#include "mlir/Dialect/LLVMIR/NVVMOps.cpp.inc"
Namespaces
mlir
mlir::NVVM
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static void printNVVMIntrinsicOp (OpAsmPrinter &p, Operation *op)
static ParseResult parseNVVMShflSyncBflyOp (OpAsmParser &parser, OperationState &result)
static ParseResult parseNVVMVoteBallotOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (MmaOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 151 of file NVVMDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parseNVVMShflSyncBflyOp()
static ParseResult parseNVVMShflSyncBflyOp (OpAsmParser & parser, OperationState & result) static
Definition at line 47 of file NVVMDialect.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::LLVM::LLVMType::getInt32Ty(), mlir::OpAsmParser::getNameLoc(), mlir::LLVM::LLVMType::getStructElementType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseNVVMVoteBallotOp()
static ParseResult parseNVVMVoteBallotOp (OpAsmParser & parser, OperationState & result) static
Definition at line 72 of file NVVMDialect.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::LLVM::LLVMType::getInt1Ty(), mlir::LLVM::LLVMType::getInt32Ty(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
printNVVMIntrinsicOp()
static void printNVVMIntrinsicOp (OpAsmPrinter & p, Operation * op) static
Definition at line 38 of file NVVMDialect.cpp.
References mlir::Operation::getName(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), and mlir::Operation::getResultTypes().
verify()
static LogicalResult verify (MmaOp op) static
Definition at line 88 of file NVVMDialect.cpp.
References mlir::LLVM::LLVMType::getFloatTy(), mlir::LLVM::LLVMType::getHalfTy(), mlir::LLVM::LLVMType::getStructTy(), mlir::StringAttr::getValue(), mlir::LLVM::LLVMType::getVectorTy(), and mlir::success().