MLIR: lib/Dialect/StandardOps/IR/Ops.cpp File Reference
Ops.cpp File Reference
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/IR/Value.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/StandardOps/IR/OpsEnums.cpp.inc"
#include "mlir/Dialect/StandardOps/IR/Ops.cpp.inc"
Namespaces
saturated_arith
Helpers to write more idiomatic operations.
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static void printStandardUnaryOp (Operation *op, OpAsmPrinter &p)
A custom unary operation printer that omits the "std." prefix from the operation names.
static void printStandardBinaryOp (Operation *op, OpAsmPrinter &p)
A custom binary operation printer that omits the "std." prefix from the operation names.
static void printStandardCastOp (Operation *op, OpAsmPrinter &p)
A custom cast operation printer that omits the "std." prefix from the operation names.
template<typename T >
static LogicalResult verifyCastOp (T op)
A custom cast operation verifier.
static detail::op_matcher< ConstantIndexOp > m_ConstantIndex ()
Matches a ConstantIndexOp.
static LogicalResult foldMemRefCast (Operation *op)
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
template<typename AllocLikeOp >
static void printAllocLikeOp (OpAsmPrinter &p, AllocLikeOp op, StringRef name)
static void print (OpAsmPrinter &p, AllocOp op)
static void print (OpAsmPrinter &p, AllocaOp op)
static ParseResult parseAllocLikeOp (OpAsmParser &parser, OperationState &result)
template<typename AllocLikeOp >
static LogicalResult verify (AllocLikeOp op)
static LogicalResult verify (AssumeAlignmentOp op)
static LogicalResult verify (AtomicRMWOp op)
static LogicalResult verify (GenericAtomicRMWOp op)
static ParseResult parseGenericAtomicRMWOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, GenericAtomicRMWOp op)
static LogicalResult verify (AtomicYieldOp op)
static LogicalResult collapseBranch (Block *&successor, ValueRange &successorOperands, SmallVectorImpl< Value > &argStorage)
Given a successor, try to collapse it to a new destination if it only contains a passthrough unconditional branch.
static LogicalResult verify (CallOp op)
static Type getI1SameShape (Type type)
static void buildCmpIOp (OpBuilder &build, OperationState &result, CmpIPredicate predicate, Value lhs, Value rhs)
static void buildCmpFOp (OpBuilder &build, OperationState &result, CmpFPredicate predicate, Value lhs, Value rhs)
static void print (OpAsmPrinter &p, ConstantOp &op)
static ParseResult parseConstantOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (ConstantOp &op)
The constant op requires an attribute, and furthermore requires that it matches the return type.
static LogicalResult verify (DeallocOp op)
static LogicalResult verify (DimOp op)
static LogicalResult verify (ExtractElementOp op)
static ParseResult parseTensorFromElementsOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, TensorFromElementsOp op)
static LogicalResult verify (TensorFromElementsOp op)
static LogicalResult verify (LoadOp op)
static void print (OpAsmPrinter &p, PrefetchOp op)
static ParseResult parsePrefetchOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (PrefetchOp op)
static LogicalResult verify (ReturnOp op)
static void print (OpAsmPrinter &p, SelectOp op)
static ParseResult parseSelectOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (SelectOp op)
static LogicalResult verify (SignExtendIOp op)
static LogicalResult verify (SplatOp op)
static LogicalResult verify (StoreOp op)
static void printSubViewListOfOperandsOrIntegers (OpAsmPrinter &p, ValueRange values, ArrayAttr arrayAttr, llvm::function_ref< bool(int64_t)> isDynamic)
Print a list with either (1) the static integer value in arrayAttr if isDynamic evaluates to false or (2) the next value otherwise.
static ParseResult parseListOfOperandsOrIntegers (OpAsmParser &parser, OperationState &result, StringRef attrName, int64_t dynVal, SmallVectorImpl< OpAsmParser::OperandType > &ssa)
Parse a mixed list with either (1) static integer values or (2) SSA values.
static void print (OpAsmPrinter &p, SubViewOp op)
Print SubViewOp in the form: `` subview ssa-name[offset-list][size-list][stride-list] :strided-memref-typetostrided-memref-type ``.
static ParseResult parseSubViewOp (OpAsmParser &parser, OperationState &result)
Parse SubViewOp of the form: `` subview ssa-name[offset-list][size-list][stride-list] :strided-memref-typetostrided-memref-type ``.
static LogicalResult verifySubViewOpPart (SubViewOp op, StringRef name, StringRef attrName, ArrayAttr attr, llvm::function_ref< bool(int64_t)> isDynamic, ValueRange values)
Verify that a particular offset/size/stride static attribute is well-formed.
static SmallVector< int64_t, 4 > extractFromI64ArrayAttr (Attribute attr)
Helper function extracts int64_t from the assumedArrayAttr of IntegerAttr.
static LogicalResult verify (SubViewOp op)
Verifier for SubViewOp.
static unsigned getNumDynamicEntriesUpToIdx (ArrayAttr attr, llvm::function_ref< bool(int64_t)> isDynamic, unsigned idx)
static Type getTensorTypeFromMemRefType (Type type)
static LogicalResult verify (TruncateIOp op)
static ParseResult parseViewOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ViewOp op)
static LogicalResult verify (ViewOp op)
static LogicalResult verify (ZeroExtendIOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 3275 of file Ops.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
buildCmpFOp()
static void buildCmpFOp (OpBuilder & build, OperationState & result, CmpFPredicate predicate, Value lhs, Value rhs) static
Definition at line 858 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), getI1SameShape(), mlir::Builder::getI64IntegerAttr(), mlir::Value::getType(), and mlir::OperationState::types.
buildCmpIOp()
static void buildCmpIOp (OpBuilder & build, OperationState & result, CmpIPredicate predicate, Value lhs, Value rhs) static
Definition at line 804 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), getI1SameShape(), mlir::Builder::getI64IntegerAttr(), mlir::Value::getType(), and mlir::OperationState::types.
collapseBranch()
static LogicalResult collapseBranch (Block *& successor, ValueRange & successorOperands, SmallVectorImpl< Value > & argStorage) static
Given a successor, try to collapse it to a new destination if it only contains a passthrough unconditional branch.
If the successor is collapsable, successor and successorOperands are updated to reference the new destination and values. argStorage is an optional storage to use if operands to the collapsed successor need to be remapped.
Definition at line 602 of file Ops.cpp.
References mlir::Block::args_empty(), mlir::Block::begin(), mlir::Value::dyn_cast(), mlir::Block::end(), mlir::PatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::BlockArgument::getArgNumber(), mlir::Block::getArguments(), mlir::BlockArgument::getOwner(), mlir::Block::getPredecessors(), mlir::Block::getTerminator(), mlir::Operation::getUsers(), mlir::OwningRewritePatternList::insert(), mlir::PatternRewriter::mergeBlocks(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
Referenced by mlir::applyCmpPredicate().
extractFromI64ArrayAttr()
static SmallVector<int64_t, 4> extractFromI64ArrayAttr (Attribute attr) static
Helper function extracts int64_t from the assumedArrayAttr of IntegerAttr.
Definition at line 2565 of file Ops.cpp.
References mlir::Attribute::cast().
Referenced by mlir::canFoldIntoConsumerOp(), getNumDynamicEntriesUpToIdx(), and verify().
foldMemRefCast()
static LogicalResult foldMemRefCast (Operation * op) static
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
It folds the source of any memref_cast into the root operation directly.
Definition at line 208 of file Ops.cpp.
References mlir::Operation::getOpOperands(), mlir::m_Zero(), mlir::matchPattern(), and mlir::success().
Referenced by mlir::DmaStartOp::fold(), mlir::DmaWaitOp::fold(), and verify().
getI1SameShape()
static Type getI1SameShape (Type type) static
Definition at line 789 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::IntegerType::get(), mlir::VectorType::get(), mlir::RankedTensorType::get(), mlir::UnrankedTensorType::get(), mlir::Type::getContext(), and mlir::Type::isa().
Referenced by buildCmpFOp(), buildCmpIOp(), and verify().
getNumDynamicEntriesUpToIdx()
static unsigned getNumDynamicEntriesUpToIdx (ArrayAttr attr, llvm::function_ref< bool(int64_t)> isDynamic, unsigned idx) static
Definition at line 2618 of file Ops.cpp.
References mlir::Attribute::cast(), mlir::PatternRewriter::create(), mlir::OpBuilder::create(), extractFromI64ArrayAttr(), mlir::failure(), mlir::IntegerAttr::getInt(), mlir::ArrayAttr::getValue(), mlir::ShapedType::isDynamic(), mlir::ShapedType::isDynamicStrideOrOffset(), m_ConstantIndex(), mlir::matchPattern(), mlir::linalg::Range, mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
getTensorTypeFromMemRefType()
static Type getTensorTypeFromMemRefType (Type type) static
Definition at line 2984 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::NoneType::get(), mlir::RankedTensorType::get(), mlir::UnrankedTensorType::get(), and mlir::Type::getContext().
m_ConstantIndex()
static detail::op_matcher<ConstantIndexOp> m_ConstantIndex () static
Matches a ConstantIndexOp.
TODO: This should probably just be a general matcher that uses m_Constant and checks the operation for an index type.
Definition at line 197 of file Ops.cpp.
Referenced by mlir::canFoldIntoConsumerOp(), getNumDynamicEntriesUpToIdx(), and verify().
parseAllocLikeOp()
static ParseResult parseAllocLikeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 268 of file Ops.cpp.
References mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::parseDimAndSymbolList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::success(), and mlir::OperationState::types.
parseConstantOp()
static ParseResult parseConstantOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1080 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::Attribute::getType(), mlir::Attribute::isa(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOptionalAttrDict(), and mlir::OperationState::types.
parseGenericAtomicRMWOp()
static ParseResult parseGenericAtomicRMWOp (OpAsmParser & parser, OperationState & result) static
Definition at line 552 of file Ops.cpp.
References mlir::OperationState::addRegion(), mlir::Type::cast(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, mlir::success(), and mlir::OperationState::types.
parseListOfOperandsOrIntegers()
static ParseResult parseListOfOperandsOrIntegers (OpAsmParser & parser, OperationState & result, StringRef attrName, int64_t dynVal, SmallVectorImpl< OpAsmParser::OperandType > & ssa) static
Parse a mixed list with either (1) static integer values or (2) SSA values.
Fill result with the integer ArrayAttr named attrName where dynVal encode the position of SSA values. Add the parsed SSA values to ssa in-order. E.g. after parsing "[%arg0, 7, 42, %arg42]":
result is filled with the i64 ArrayAttr "[`dynVal`, 7, 42, `dynVal`]"
ssa is filled with "[%arg0, %arg1]".
Definition at line 2339 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::Attribute::cast(), mlir::OpAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI64ArrayAttr(), mlir::IntegerAttr::getInt(), mlir::OpAsmParser::getNameLoc(), mlir::Attribute::isa(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseLSquare(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalOperand(), mlir::OpAsmParser::parseOptionalRSquare(), mlir::OpAsmParser::parseRSquare(), mlir::succeeded(), and mlir::success().
Referenced by parseSubViewOp().
parsePrefetchOp()
static ParseResult parsePrefetchOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1985 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::Builder::getBoolAttr(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerType(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseGreater(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseLess(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::success().
parseSelectOp()
static ParseResult parseSelectOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2104 of file Ops.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI1Type(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperands(), and mlir::succeeded().
parseSubViewOp()
static ParseResult parseSubViewOp (OpAsmParser & parser, OperationState & result) static
Parse SubViewOp of the form: `` subview ssa-name[offset-list][size-list][stride-list] :strided-memref-typetostrided-memref-type ``.
Definition at line 2475 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addAttributes(), mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexType(), mlir::Value::getType(), mlir::ShapedType::kDynamicSize, mlir::ShapedType::kDynamicStrideOrOffset, mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeywordType(), parseListOfOperandsOrIntegers(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseTensorFromElementsOp()
static ParseResult parseTensorFromElementsOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1682 of file Ops.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::failure(), mlir::ShapedType::getElementType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColon(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseViewOp()
static ParseResult parseViewOp (OpAsmParser & parser, OperationState & result) static
Definition at line 3072 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::OperationState::types.
print() [1/9]
static void print (OpAsmPrinter & p, AllocOp op) static
Definition at line 260 of file Ops.cpp.
References printAllocLikeOp().
print() [2/9]
static void print (OpAsmPrinter & p, AllocaOp op) static
Definition at line 264 of file Ops.cpp.
References printAllocLikeOp().
print() [3/9]
static void print (OpAsmPrinter & p, GenericAtomicRMWOp op) static
Definition at line 573 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
print() [4/9]
static void print (OpAsmPrinter & p, ConstantOp & op) static
Definition at line 1067 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [5/9]
static void print (OpAsmPrinter & p, TensorFromElementsOp op) static
Definition at line 1700 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [6/9]
static void print (OpAsmPrinter & p, PrefetchOp op) static
Definition at line 1973 of file Ops.cpp.
References mlir::OpAsmPrinter::printOperands(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [7/9]
static void print (OpAsmPrinter & p, SelectOp op) static
Definition at line 2095 of file Ops.cpp.
References mlir::Type::dyn_cast(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [8/9]
static void print (OpAsmPrinter & p, SubViewOp op) static
Print SubViewOp in the form: `` subview ssa-name[offset-list][size-list][stride-list] :strided-memref-typetostrided-memref-type ``.
Definition at line 2455 of file Ops.cpp.
References mlir::ShapedType::isDynamic(), mlir::ShapedType::isDynamicStrideOrOffset(), mlir::OpAsmPrinter::printOptionalAttrDict(), and printSubViewListOfOperandsOrIntegers().
print() [9/9]
static void print (OpAsmPrinter & p, ViewOp op) static
Definition at line 3097 of file Ops.cpp.
References mlir::OpAsmPrinter::printOperand(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printAllocLikeOp()
template<typename AllocLikeOp > static void printAllocLikeOp (OpAsmPrinter & p, AllocLikeOp op, StringRef name) static
Definition at line 247 of file Ops.cpp.
References mlir::printDimAndSymbolList(), and mlir::OpAsmPrinter::printOptionalAttrDict().
Referenced by print().
printStandardBinaryOp()
static void printStandardBinaryOp (Operation * op, OpAsmPrinter & p) static
A custom binary operation printer that omits the "std." prefix from the operation names.
Definition at line 105 of file Ops.cpp.
References mlir::Operation::getAttrs(), mlir::Operation::getName(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::OperationName::getStringRef(), mlir::Value::getType(), mlir::OpAsmPrinter::printGenericOp(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printStandardCastOp()
static void printStandardCastOp (Operation * op, OpAsmPrinter & p) static
A custom cast operation printer that omits the "std." prefix from the operation names.
Definition at line 129 of file Ops.cpp.
References mlir::Operation::getName(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::OperationName::getStringRef(), and mlir::Value::getType().
printStandardUnaryOp()
static void printStandardUnaryOp (Operation * op, OpAsmPrinter & p) static
A custom unary operation printer that omits the "std." prefix from the operation names.
Definition at line 92 of file Ops.cpp.
References mlir::Operation::getAttrs(), mlir::Operation::getName(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::OperationName::getStringRef(), mlir::Value::getType(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printSubViewListOfOperandsOrIntegers()
static void printSubViewListOfOperandsOrIntegers (OpAsmPrinter & p, ValueRange values, ArrayAttr arrayAttr, llvm::function_ref< bool(int64_t)> isDynamic) static
Print a list with either (1) the static integer value in arrayAttr if isDynamic evaluates to false or (2) the next value otherwise.
This allows idiomatic printing of mixed value and integer attributes in a list. E.g. [arg0, 7, 42, arg42].
Definition at line 2315 of file Ops.cpp.
References mlir::Attribute::cast().
Referenced by print().
verify() [1/22]
template<typename AllocLikeOp > static LogicalResult verify (AllocLikeOp op) static
Definition at line 295 of file Ops.cpp.
References mlir::PatternRewriter::create(), mlir::PatternRewriter::eraseOp(), mlir::failure(), mlir::AffineMap::getNumSymbols(), mlir::OwningRewritePatternList::insert(), m_ConstantIndex(), mlir::m_ConstantInt(), mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), mlir::PatternRewriter::replaceOp(), mlir::MemRefType::Builder::setShape(), and mlir::success().
verify() [2/22]
static LogicalResult verify (AssumeAlignmentOp op) static
Definition at line 470 of file Ops.cpp.
References mlir::success().
verify() [3/22]
static LogicalResult verify (AtomicRMWOp op) static
Definition at line 481 of file Ops.cpp.
References mlir::Region::addArgument(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::Type::dyn_cast(), mlir::Value::getType(), mlir::Region::push_back(), and mlir::success().
verify() [4/22]
static LogicalResult verify (GenericAtomicRMWOp op) static
Definition at line 531 of file Ops.cpp.
References mlir::WalkResult::advance(), mlir::Operation::emitError(), mlir::failure(), mlir::WalkResult::interrupt(), and mlir::success().
verify() [5/22]
static LogicalResult verify (AtomicYieldOp op) static
Definition at line 584 of file Ops.cpp.
References mlir::success().
verify() [6/22]
static LogicalResult verify (CallOp op) static
Definition at line 720 of file Ops.cpp.
References mlir::OpState::emitOpError(), mlir::failure(), mlir::FunctionType::get(), mlir::OwningRewritePatternList::insert(), mlir::m_Constant(), mlir::matchPattern(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
verify() [7/22]
static LogicalResult verify (ConstantOp & op) static
The constant op requires an attribute, and furthermore requires that it matches the return type.
Definition at line 1100 of file Ops.cpp.
References mlir::Type::cast(), mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::Attribute::getType(), mlir::IntegerType::getWidth(), mlir::Attribute::isa(), mlir::Type::isa(), and mlir::success().
verify() [8/22]
static LogicalResult verify (DeallocOp op) static
Definition at line 1273 of file Ops.cpp.
References mlir::OpBuilder::create(), foldMemRefCast(), mlir::Builder::getIndexType(), mlir::OwningRewritePatternList::insert(), mlir::OperationState::location, and mlir::success().
verify() [9/22]
static LogicalResult verify (DimOp op) static
Definition at line 1313 of file Ops.cpp.
References mlir::Type::dyn_cast(), foldMemRefCast(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexAttr(), mlir::Value::getType(), mlir::Type::isa(), mlir::succeeded(), and mlir::success().
verify() [10/22]
static LogicalResult verify (ExtractElementOp op) static
Definition at line 1640 of file Ops.cpp.
References mlir::IntegerAttr::getInt(), mlir::ElementsAttr::getValue(), and mlir::success().
verify() [11/22]
static LogicalResult verify (TensorFromElementsOp op) static
Definition at line 1706 of file Ops.cpp.
References mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::failure(), mlir::IntegerAttr::get(), mlir::ShapedType::getElementType(), mlir::ShapedType::getShape(), mlir::OwningRewritePatternList::insert(), mlir::Type::isa(), mlir::Type::isIndex(), mlir::Type::isSignlessInteger(), mlir::m_ConstantInt(), mlir::matchPattern(), mlir::PatternRewriter::replaceOp(), and mlir::success().
verify() [12/22]
static LogicalResult verify (LoadOp op) static
Definition at line 1834 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::failed(), mlir::impl::foldCastOp(), foldMemRefCast(), mlir::MemRefType::getAffineMaps(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::MemRefType::getMemorySpace(), mlir::UnrankedMemRefType::getMemorySpace(), mlir::getStridesAndOffset(), mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), mlir::succeeded(), and mlir::success().
verify() [13/22]
static LogicalResult verify (PrefetchOp op) static
Definition at line 2026 of file Ops.cpp.
References mlir::Type::dyn_cast(), foldMemRefCast(), mlir::IndexType::get(), mlir::IntegerAttr::get(), and mlir::success().
verify() [14/22]
static LogicalResult verify (ReturnOp op) static
Definition at line 2057 of file Ops.cpp.
References mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), and mlir::success().
verify() [15/22]
static LogicalResult verify (SelectOp op) static
Definition at line 2127 of file Ops.cpp.
References getI1SameShape(), mlir::Type::isa(), mlir::Type::isSignlessInteger(), and mlir::success().
verify() [16/22]
static LogicalResult verify (SignExtendIOp op) static
Definition at line 2152 of file Ops.cpp.
References mlir::IntegerAttr::get(), mlir::getElementTypeOrSelf(), mlir::IntegerAttr::getValue(), mlir::IntegerType::getWidth(), mlir::Type::isa(), mlir::Type::isSignlessInteger(), and mlir::success().
verify() [17/22]
static LogicalResult verify (SplatOp op) static
Definition at line 2240 of file Ops.cpp.
References mlir::DenseElementsAttr::get(), getElementType(), and mlir::success().
verify() [18/22]
static LogicalResult verify (StoreOp op) static
Definition at line 2269 of file Ops.cpp.
References foldMemRefCast(), mlir::Builder::getZeroAttr(), mlir::m_Zero(), mlir::matchPattern(), and mlir::success().
verify() [19/22]
static LogicalResult verify (SubViewOp op) static
Verifier for SubViewOp.
Definition at line 2573 of file Ops.cpp.
References extractFromI64ArrayAttr(), mlir::failed(), mlir::failure(), mlir::MemRefType::getMemorySpace(), mlir::ShapedType::isDynamic(), mlir::ShapedType::isDynamicStrideOrOffset(), mlir::isStrided(), mlir::success(), and verifySubViewOpPart().
verify() [20/22]
static LogicalResult verify (TruncateIOp op) static
Definition at line 2996 of file Ops.cpp.
References mlir::IntegerAttr::get(), mlir::getElementTypeOrSelf(), mlir::IntegerAttr::getValue(), mlir::IntegerType::getWidth(), and mlir::success().
verify() [21/22]
static LogicalResult verify (ViewOp op) static
Definition at line 3105 of file Ops.cpp.
References mlir::PatternRewriter::create(), mlir::failed(), mlir::failure(), mlir::MemRefType::getAffineMaps(), mlir::Value::getDefiningOp(), mlir::MemRefType::getMemorySpace(), mlir::getStridesAndOffset(), mlir::Builder::getZeroAttr(), mlir::OwningRewritePatternList::insert(), mlir::ShapedType::isDynamic(), m_ConstantIndex(), mlir::m_Zero(), mlir::matchPattern(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::MemRefType::Builder::setShape(), and mlir::success().
verify() [22/22]
static LogicalResult verify (ZeroExtendIOp op) static
Definition at line 3254 of file Ops.cpp.
References mlir::getElementTypeOrSelf(), mlir::IntegerType::getWidth(), and mlir::success().
verifyCastOp()
template<typename T > static LogicalResult verifyCastOp (T op) static
A custom cast operation verifier.
Definition at line 138 of file Ops.cpp.
References mlir::OpBuilder::create(), materializeConstant(), and mlir::success().
verifySubViewOpPart()
static LogicalResult verifySubViewOpPart (SubViewOp op, StringRef name, StringRef attrName, ArrayAttr attr, llvm::function_ref< bool(int64_t)> isDynamic, ValueRange values) static
Verify that a particular offset/size/stride static attribute is well-formed.
Check static and dynamic offsets/sizes/strides breakdown.
Definition at line 2547 of file Ops.cpp.
References mlir::IntegerAttr::getInt(), mlir::ArrayAttr::getValue(), mlir::ArrayAttr::size(), and mlir::success().
Referenced by verify().