MLIR: lib/Pass/Pass.cpp File Reference
Pass.cpp File Reference
#include "mlir/Pass/Pass.h"
#include "PassDetail.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/CrashRecoveryContext.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/Parallel.h"
#include "llvm/Support/Signals.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/ToolOutputFile.h"
Classes
struct mlir::detail::OpPassManagerImpl
struct mlir::detail::PassInstrumentorImpl
Namespaces
mlir
mlir::detail
Functions
static void printAsTextualPipeline (ArrayRef< std::unique_ptr< Pass >> passes, raw_ostream &os)
Prints out the given passes as the textual representation of a pipeline.
static LogicalResult runPipeline (OpPassManager &pm, Operation *op, AnalysisManager am)
Utility to run the given operation and analysis manager on a provided op pass manager.
static OpPassManager * findPassManagerFor (MutableArrayRef< OpPassManager > mgrs, const OperationName &name)
Find an operation pass manager that can operate on an operation of the given type, or nullptr if one does not exist.
static bool hasSizeMismatch (ArrayRef< OpPassManager > lhs, ArrayRef< OpPassManager > rhs)
Utility functor that checks if the two ranges of pass managers have a size mismatch.
Function Documentation
findPassManagerFor()
static OpPassManager* findPassManagerFor (MutableArrayRef< OpPassManager > mgrs, const OperationName & name) static
Find an operation pass manager that can operate on an operation of the given type, or nullptr if one does not exist.
Definition at line 370 of file Pass.cpp.
References mlir::OpPassManager::getOpName().
Referenced by hasSizeMismatch(), mlir::detail::OpToOpPassAdaptor::mergeInto(), and mlir::detail::OpToOpPassAdaptor::runOnOperation().
hasSizeMismatch()
static bool hasSizeMismatch (ArrayRef< OpPassManager > lhs, ArrayRef< OpPassManager > rhs) static
Utility functor that checks if the two ranges of pass managers have a size mismatch.
Definition at line 451 of file Pass.cpp.
References mlir::Op< ConcreteType, Traits >::clone(), mlir::OpState::emitError(), mlir::ParallelDiagnosticHandler::eraseOrderIDForThread(), mlir::failed(), mlir::failure(), findPassManagerFor(), mlir::OpPassManager::getContext(), mlir::Operation::getName(), mlir::AnalysisManager::getPassInstrumentor(), mlir::openOutputFile(), mlir::ModuleOp::print(), mlir::OpPassManager::printAsTextualPipeline(), runPipeline(), mlir::ParallelDiagnosticHandler::setOrderIDForThread(), mlir::AnalysisManager::slice(), mlir::succeeded(), and mlir::success().
printAsTextualPipeline()
static void printAsTextualPipeline (ArrayRef< std::unique_ptr< Pass >> passes, raw_ostream & os) static
Prints out the given passes as the textual representation of a pipeline.
Definition at line 330 of file Pass.cpp.
Referenced by mlir::OpPassManager::addNestedPass(), and mlir::Pass::ListOption< DataType, OptionParser >::ListOption().
runPipeline()
static LogicalResult runPipeline (OpPassManager & pm, Operation * op, AnalysisManager am) static
Utility to run the given operation and analysis manager on a provided op pass manager.
Definition at line 355 of file Pass.cpp.
References mlir::AnalysisManager::clear(), and mlir::OpPassManager::run().
Referenced by hasSizeMismatch(), and mlir::detail::OpToOpPassAdaptor::runOnOperation().