MLIR: lib/Dialect/Linalg/Transforms/Promotion.cpp File Reference
Promotion.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/EDSC/Intrinsics.h"
#include "mlir/Dialect/Linalg/EDSC/FoldedIntrinsics.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/FoldUtils.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "linalg-promotion"
Typedefs
using folded_affine_min = FoldedValueBuilder< AffineMinOp >
using folded_linalg_range = FoldedValueBuilder< linalg::RangeOp >
using folded_std_dim = FoldedValueBuilder< DimOp >
using folded_std_subview = FoldedValueBuilder< SubViewOp >
using folded_std_view = FoldedValueBuilder< ViewOp >
Functions
static Value extractSmallestConstantBoundingSize (OpBuilder &b, Location loc, Value size)
If size comes from an AffineMinOp and one of the values of AffineMinOp is a constant then return a new value set to the smallest such constant.
static Value allocBuffer (const LinalgPromotionOptions &options, Type elementType, Value size, bool dynamicBuffers, OperationFolder *folder, Optional< unsigned > alignment=None)
Alloc a new buffer of size.
static Optional< Value > defaultAllocBufferCallBack (const LinalgPromotionOptions &options, OpBuilder &builder, SubViewOp subView, ArrayRef< Value > boundingSubViewSize, bool dynamicBuffers, Optional< unsigned > alignment, OperationFolder *folder)
Default allocation callback function.
static LogicalResult defaultDeallocBufferCallBack (const LinalgPromotionOptions &options, OpBuilder &b, Value fullLocalView)
Default implementation of deallocation of the buffer use for promotion.
static Optional< PromotionInfo > promoteSubviewAsNewBuffer (OpBuilder &b, Location loc, SubViewOp subView, LinalgOpInstancePromotionOptions const &options, OperationFolder *folder)
static Optional< MapVector< unsigned, PromotionInfo > > promoteSubViews (OpBuilder &b, Location loc, LinalgOpInstancePromotionOptions options, OperationFolder *folder)
static Optional< LinalgOp > promoteSubViews (OpBuilder &b, LinalgOp op, LinalgOpInstancePromotionOptions options, OperationFolder *folder)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-promotion"
Definition at line 45 of file Promotion.cpp.
Typedef Documentation
folded_affine_min
using folded_affine_min = FoldedValueBuilder<AffineMinOp>
Definition at line 39 of file Promotion.cpp.
folded_linalg_range
using folded_linalg_range = FoldedValueBuilder<linalg::RangeOp>
Definition at line 40 of file Promotion.cpp.
folded_std_dim
using folded_std_dim = FoldedValueBuilder<DimOp>
Definition at line 41 of file Promotion.cpp.
folded_std_subview
using folded_std_subview = FoldedValueBuilder<SubViewOp>
Definition at line 42 of file Promotion.cpp.
folded_std_view
using folded_std_view = FoldedValueBuilder<ViewOp>
Definition at line 43 of file Promotion.cpp.
Function Documentation
allocBuffer()
static Value allocBuffer (const LinalgPromotionOptions & options, Type elementType, Value size, bool dynamicBuffers, OperationFolder * folder, Optional< unsigned > alignment = None) static
Alloc a new buffer of size.
If dynamicBuffers is true allocate exactly the size needed, otherwise try to allocate a static bounding box.
Definition at line 70 of file Promotion.cpp.
References mlir::IntegerType::get(), mlir::IntegerAttr::get(), mlir::MemRefType::get(), mlir::Value::getContext(), mlir::Value::getDefiningOp(), mlir::Type::getIntOrFloatBitWidth(), and mlir::linalg::LinalgPromotionOptions::useAlloca.
Referenced by defaultAllocBufferCallBack().
defaultAllocBufferCallBack()
static Optional<Value> defaultAllocBufferCallBack (const LinalgPromotionOptions & options, OpBuilder & builder, SubViewOp subView, ArrayRef< Value > boundingSubViewSize, bool dynamicBuffers, Optional< unsigned > alignment, OperationFolder * folder) static
Default allocation callback function.
This allocates a promoted buffer when no call back to do so is provided. The default is to allocate a memref<..xi8> and return a view to get a memref type of shape boundingSubViewSize.
Definition at line 106 of file Promotion.cpp.
References allocBuffer(), mlir::detail::enumerate(), mlir::MemRefType::get(), mlir::ShapedType::getElementType(), mlir::ShapedType::getRank(), and mlir::ShapedType::kDynamicSize.
Referenced by defaultDeallocBufferCallBack().
defaultDeallocBufferCallBack()
static LogicalResult defaultDeallocBufferCallBack (const LinalgPromotionOptions & options, OpBuilder & b, Value fullLocalView) static
Default implementation of deallocation of the buffer use for promotion.
It expects to get the same value that the default allocation method returned, i.e. result of a ViewOp.
Definition at line 134 of file Promotion.cpp.
References mlir::linalg::LinalgPromotionOptions::alignment, mlir::linalg::LinalgPromotionOptions::allocationFn, mlir::linalg::LinalgPromotionOptions::copyInFn, mlir::linalg::LinalgPromotionOptions::copyOutFn, mlir::linalg::LinalgPromotionOptions::deallocationFn, defaultAllocBufferCallBack(), mlir::linalg::LinalgPromotionOptions::dynamicBuffers, mlir::Value::getDefiningOp(), mlir::linalg::LinalgPromotionOptions::operandsToPromote, options, mlir::success(), mlir::linalg::LinalgPromotionOptions::useAlloca, mlir::linalg::LinalgPromotionOptions::useFullTileBuffers, and mlir::linalg::LinalgPromotionOptions::useFullTileBuffersDefault.
extractSmallestConstantBoundingSize()
static Value extractSmallestConstantBoundingSize (OpBuilder & b, Location loc, Value size) static
If size comes from an AffineMinOp and one of the values of AffineMinOp is a constant then return a new value set to the smallest such constant.
Otherwise return size.
Definition at line 50 of file Promotion.cpp.
References mlir::OpBuilder::create(), and mlir::Value::getDefiningOp().
Referenced by promoteSubviewAsNewBuffer().
promoteSubviewAsNewBuffer()
static Optional<PromotionInfo> promoteSubviewAsNewBuffer (OpBuilder & b, Location loc, SubViewOp subView, LinalgOpInstancePromotionOptions const & options, OperationFolder * folder) static
Definition at line 237 of file Promotion.cpp.
References mlir::detail::enumerate(), and extractSmallestConstantBoundingSize().
Referenced by promoteSubViews().
promoteSubViews() [1/2]
static Optional<MapVector<unsigned, PromotionInfo> > promoteSubViews (OpBuilder & b, Location loc, LinalgOpInstancePromotionOptions options, OperationFolder * folder) static
Definition at line 271 of file Promotion.cpp.
References mlir::failed(), mlir::FloatAttr::get(), and promoteSubviewAsNewBuffer().
Referenced by mlir::linalg::promoteSubViews(), and promoteSubViews().
promoteSubViews() [2/2]
static Optional<LinalgOp> promoteSubViews (OpBuilder & b, LinalgOp op, LinalgOpInstancePromotionOptions options, OperationFolder * folder) static
Definition at line 313 of file Promotion.cpp.
References mlir::detail::enumerate(), mlir::failed(), promoteSubViews(), and mlir::OpBuilder::setInsertionPointAfter().