MLIR: lib/Transforms/Utils/RegionUtils.cpp File Reference
RegionUtils.cpp File Reference
#include "mlir/Transforms/RegionUtils.h"
#include "mlir/IR/Block.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/RegionGraphTraits.h"
#include "mlir/IR/Value.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/SmallSet.h"
Functions
static LogicalResult eraseUnreachableBlocks (MutableArrayRef< Region > regions)
Erase the unreachable blocks within the provided regions.
static bool isUseSpeciallyKnownDead (OpOperand &use, LiveMap &liveMap)
static void processValue (Value value, LiveMap &liveMap)
static bool isOpIntrinsicallyLive (Operation *op)
static void propagateLiveness (Region &region, LiveMap &liveMap)
static void propagateTerminatorLiveness (Operation *op, LiveMap &liveMap)
static void propagateLiveness (Operation *op, LiveMap &liveMap)
static void eraseTerminatorSuccessorOperands (Operation *terminator, LiveMap &liveMap)
static LogicalResult deleteDeadness (MutableArrayRef< Region > regions, LiveMap &liveMap)
static LogicalResult runRegionDCE (MutableArrayRef< Region > regions)
static bool ableToUpdatePredOperands (Block *block)
Returns true if the predecessor terminators of the given block can not have their operands updated.
static LogicalResult mergeIdenticalBlocks (Region &region)
Identify identical blocks within the given region and merge them, inserting new block arguments as necessary.
static LogicalResult mergeIdenticalBlocks (MutableArrayRef< Region > regions)
Identify identical blocks within the given regions and merge them, inserting new block arguments as necessary.
Function Documentation
ableToUpdatePredOperands()
static bool ableToUpdatePredOperands (Block * block) static
Returns true if the predecessor terminators of the given block can not have their operands updated.
Definition at line 536 of file RegionUtils.cpp.
References mlir::Block::addArgument(), mlir::Block::begin(), mlir::detail::enumerate(), mlir::Block::erase(), mlir::failure(), mlir::Block::pred_begin(), mlir::Block::pred_end(), mlir::IRObjectWithUseList< OperandType >::replaceAllUsesWith(), and mlir::success().
deleteDeadness()
static LogicalResult deleteDeadness (MutableArrayRef< Region > regions, LiveMap & liveMap) static
Definition at line 297 of file RegionUtils.cpp.
References mlir::Region::empty(), eraseTerminatorSuccessorOperands(), mlir::Region::front(), mlir::Region::getBlocks(), mlir::succeeded(), and mlir::success().
Referenced by runRegionDCE().
eraseTerminatorSuccessorOperands()
static void eraseTerminatorSuccessorOperands (Operation * terminator, LiveMap & liveMap) static
Definition at line 268 of file RegionUtils.cpp.
References mlir::Block::getArgument(), mlir::Operation::getNumSuccessors(), and mlir::Operation::getSuccessor().
Referenced by deleteDeadness().
eraseUnreachableBlocks()
static LogicalResult eraseUnreachableBlocks (MutableArrayRef< Region > regions) static
Erase the unreachable blocks within the provided regions.
Returns success if any blocks were erased, failure otherwise.
Definition at line 78 of file RegionUtils.cpp.
References mlir::Region::begin(), mlir::Region::empty(), mlir::Region::end(), mlir::Region::front(), and mlir::success().
Referenced by mlir::simplifyRegions().
isOpIntrinsicallyLive()
static bool isOpIntrinsicallyLive (Operation * op) static
Definition at line 195 of file RegionUtils.cpp.
References mlir::Operation::getNumRegions(), mlir::Operation::isKnownNonTerminator(), and propagateLiveness().
Referenced by propagateLiveness().
isUseSpeciallyKnownDead()
static bool isUseSpeciallyKnownDead (OpOperand & use, LiveMap & liveMap) static
Definition at line 162 of file RegionUtils.cpp.
References mlir::OpOperand::getOperandNumber(), mlir::IROperand< DerivedT, IRValueTy >::getOwner(), and mlir::Operation::isKnownTerminator().
Referenced by processValue().
mergeIdenticalBlocks() [1/2]
static LogicalResult mergeIdenticalBlocks (Region & region) static
Identify identical blocks within the given region and merge them, inserting new block arguments as necessary.
Returns success if any blocks were merged, failure otherwise.
Definition at line 620 of file RegionUtils.cpp.
References mlir::Region::empty(), mlir::failure(), mlir::Operation::getRegions(), mlir::Block::getSuccessors(), mlir::succeeded(), and mlir::success().
Referenced by mergeIdenticalBlocks(), and mlir::simplifyRegions().
mergeIdenticalBlocks() [2/2]
static LogicalResult mergeIdenticalBlocks (MutableArrayRef< Region > regions) static
Identify identical blocks within the given regions and merge them, inserting new block arguments as necessary.
Definition at line 666 of file RegionUtils.cpp.
References mergeIdenticalBlocks(), mlir::succeeded(), and mlir::success().
processValue()
static void processValue (Value value, LiveMap & liveMap) static
Definition at line 185 of file RegionUtils.cpp.
References mlir::Value::getUses(), and isUseSpeciallyKnownDead().
Referenced by diag(), getLLVMAtomicOrdering(), and propagateLiveness().
propagateLiveness() [1/2]
static void propagateLiveness (Region & region, LiveMap & liveMap) static
Definition at line 254 of file RegionUtils.cpp.
References mlir::Region::empty(), mlir::Region::front(), and processValue().
Referenced by isOpIntrinsicallyLive(), propagateLiveness(), and runRegionDCE().
propagateLiveness() [2/2]
static void propagateLiveness (Operation * op, LiveMap & liveMap) static
Definition at line 228 of file RegionUtils.cpp.
References mlir::Operation::getRegions(), mlir::Operation::getResults(), mlir::Operation::isKnownTerminator(), isOpIntrinsicallyLive(), processValue(), propagateLiveness(), and propagateTerminatorLiveness().
propagateTerminatorLiveness()
static void propagateTerminatorLiveness (Operation * op, LiveMap & liveMap) static
Definition at line 206 of file RegionUtils.cpp.
References mlir::Block::getArguments(), mlir::Operation::getNumSuccessors(), mlir::Operation::getSuccessor(), and mlir::Operation::getSuccessors().
Referenced by propagateLiveness().
runRegionDCE()
static LogicalResult runRegionDCE (MutableArrayRef< Region > regions) static
Definition at line 358 of file RegionUtils.cpp.
References mlir::Block::begin(), mlir::Value::cast(), mlir::OperationEquivalence::computeHash(), deleteDeadness(), mlir::Value::dyn_cast(), mlir::Block::end(), mlir::failure(), mlir::Block::getArgumentTypes(), mlir::Value::getDefiningOp(), mlir::Block::getNumArguments(), mlir::Value::getParentBlock(), mlir::OpResult::getResultNumber(), mlir::OperationEquivalence::isEquivalentTo(), propagateLiveness(), and mlir::success().
Referenced by mlir::simplifyRegions().