MLIR: include/mlir/ExecutionEngine/RunnerUtils.h File Reference
RunnerUtils.h File Reference
#include <assert.h>
#include <iostream>
#include "mlir/ExecutionEngine/CRunnerUtils.h"
Classes
struct impl::StaticSizeMult< Dims >
struct impl::StaticSizeMult< N, Dims... >
struct impl::VectorDataPrinter< T, M, Dims >
struct impl::MemRefDataPrinter< T >
Namespaces
impl
Macros
#define MLIR_RUNNERUTILS_EXPORT
Functions
template<typename T , typename StreamType >
void printMemRefMetaData (StreamType &os, const DynamicMemRefType< T > &V)
template<typename StreamType , typename T , int N>
void printMemRefMetaData (StreamType &os, StridedMemRefType< T, N > &V)
template<typename StreamType , typename T >
void printUnrankedMemRefMetaData (StreamType &os, UnrankedMemRefType< T > &V)
template<typename T , int M, int... Dims>
std::ostream & impl::operator<< (std::ostream &os, const Vector< T, M, Dims... > &v)
static void impl::printSpace (std::ostream &os, int count)
template<typename T >
void impl::printMemRef (const DynamicMemRefType< T > &M)
template<typename T , int N>
void impl::printMemRef (StridedMemRefType< T, N > &M)
template<typename T >
void impl::printMemRef (UnrankedMemRefType< T > &M)
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_i8 (UnrankedMemRefType< int8_t > *M)
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_f32 (UnrankedMemRefType< float > *M)
MLIR_RUNNERUTILS_EXPORT void print_memref_i32 (int64_t rank, void *ptr)
MLIR_RUNNERUTILS_EXPORT void print_memref_f32 (int64_t rank, void *ptr)
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_0d_f32 (StridedMemRefType< float, 0 > *M)
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_1d_f32 (StridedMemRefType< float, 1 > *M)
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_2d_f32 (StridedMemRefType< float, 2 > *M)
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_3d_f32 (StridedMemRefType< float, 3 > *M)
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_4d_f32 (StridedMemRefType< float, 4 > *M)
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_vector_4x4xf32 (StridedMemRefType< Vector2D< 4, 4, float >, 2 > *M)
Macro Definition Documentation
MLIR_RUNNERUTILS_EXPORT
#define MLIR_RUNNERUTILS_EXPORT
Definition at line 30 of file RunnerUtils.h.
Referenced by impl::printMemRef().
Function Documentation
_mlir_ciface_print_memref_0d_f32()
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_0d_f32 (StridedMemRefType< float, 0 > * M)
Definition at line 50 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
_mlir_ciface_print_memref_1d_f32()
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_1d_f32 (StridedMemRefType< float, 1 > * M)
Definition at line 54 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
_mlir_ciface_print_memref_2d_f32()
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_2d_f32 (StridedMemRefType< float, 2 > * M)
Definition at line 58 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
_mlir_ciface_print_memref_3d_f32()
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_3d_f32 (StridedMemRefType< float, 3 > * M)
Definition at line 62 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
_mlir_ciface_print_memref_4d_f32()
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_4d_f32 (StridedMemRefType< float, 4 > * M)
Definition at line 66 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
_mlir_ciface_print_memref_f32()
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_f32 (UnrankedMemRefType< float > * M)
Definition at line 35 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by print_memref_f32(), and impl::printMemRef().
_mlir_ciface_print_memref_i8()
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_i8 (UnrankedMemRefType< int8_t > * M)
Definition at line 27 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
_mlir_ciface_print_memref_vector_4x4xf32()
MLIR_RUNNERUTILS_EXPORT void _mlir_ciface_print_memref_vector_4x4xf32 (StridedMemRefType< Vector2D< 4, 4, float >, 2 > * M)
Definition at line 22 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
print_memref_f32()
MLIR_RUNNERUTILS_EXPORT void print_memref_f32 (int64_t rank, void * ptr)
Definition at line 44 of file RunnerUtils.cpp.
References _mlir_ciface_print_memref_f32().
Referenced by impl::printMemRef().
print_memref_i32()
MLIR_RUNNERUTILS_EXPORT void print_memref_i32 (int64_t rank, void * ptr)
Definition at line 39 of file RunnerUtils.cpp.
References _mlir_ciface_print_memref_i32().
Referenced by impl::printMemRef().
printMemRefMetaData() [1/2]
template<typename T , typename StreamType > void printMemRefMetaData (StreamType & os, const DynamicMemRefType< T > & V)
Definition at line 39 of file RunnerUtils.h.
References DynamicMemRefType< T >::data, DynamicMemRefType< T >::offset, print(), DynamicMemRefType< T >::rank, DynamicMemRefType< T >::sizes, and DynamicMemRefType< T >::strides.
Referenced by impl::printMemRef(), printMemRefMetaData(), and printUnrankedMemRefMetaData().
printMemRefMetaData() [2/2]
template<typename StreamType , typename T , int N> void printMemRefMetaData (StreamType & os, StridedMemRefType< T, N > & V)
Definition at line 57 of file RunnerUtils.h.
References printMemRefMetaData().
printUnrankedMemRefMetaData()
template<typename StreamType , typename T > void printUnrankedMemRefMetaData (StreamType & os, UnrankedMemRefType< T > & V)
Definition at line 64 of file RunnerUtils.h.
References printMemRefMetaData().