MLIR: lib/ExecutionEngine/RunnerUtils.cpp File Reference
RunnerUtils.cpp File Reference
#include "mlir/ExecutionEngine/RunnerUtils.h"
#include <sys/time.h>
Functions
void _mlir_ciface_print_memref_vector_4x4xf32 (StridedMemRefType< Vector2D< 4, 4, float >, 2 > *M)
void _mlir_ciface_print_memref_i8 (UnrankedMemRefType< int8_t > *M)
void _mlir_ciface_print_memref_i32 (UnrankedMemRefType< int32_t > *M)
void _mlir_ciface_print_memref_f32 (UnrankedMemRefType< float > *M)
void print_memref_i32 (int64_t rank, void *ptr)
void print_memref_f32 (int64_t rank, void *ptr)
void _mlir_ciface_print_memref_0d_f32 (StridedMemRefType< float, 0 > *M)
void _mlir_ciface_print_memref_1d_f32 (StridedMemRefType< float, 1 > *M)
void _mlir_ciface_print_memref_2d_f32 (StridedMemRefType< float, 2 > *M)
void _mlir_ciface_print_memref_3d_f32 (StridedMemRefType< float, 3 > *M)
void _mlir_ciface_print_memref_4d_f32 (StridedMemRefType< float, 4 > *M)
void print_flops (double flops)
Prints GFLOPS rating.
double rtclock ()
Returns the number of seconds since Epoch 1970-01-01 00:00:00 +0000 (UTC).
Function Documentation
_mlir_ciface_print_memref_0d_f32()
void _mlir_ciface_print_memref_0d_f32 (StridedMemRefType< float, 0 > * M)
Definition at line 50 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
_mlir_ciface_print_memref_1d_f32()
void _mlir_ciface_print_memref_1d_f32 (StridedMemRefType< float, 1 > * M)
Definition at line 54 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
_mlir_ciface_print_memref_2d_f32()
void _mlir_ciface_print_memref_2d_f32 (StridedMemRefType< float, 2 > * M)
Definition at line 58 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
_mlir_ciface_print_memref_3d_f32()
void _mlir_ciface_print_memref_3d_f32 (StridedMemRefType< float, 3 > * M)
Definition at line 62 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
_mlir_ciface_print_memref_4d_f32()
void _mlir_ciface_print_memref_4d_f32 (StridedMemRefType< float, 4 > * M)
Definition at line 66 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
_mlir_ciface_print_memref_f32()
void _mlir_ciface_print_memref_f32 (UnrankedMemRefType< float > * M)
Definition at line 35 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by print_memref_f32(), and impl::printMemRef().
_mlir_ciface_print_memref_i32()
void _mlir_ciface_print_memref_i32 (UnrankedMemRefType< int32_t > * M)
Definition at line 31 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by print_memref_i32().
_mlir_ciface_print_memref_i8()
void _mlir_ciface_print_memref_i8 (UnrankedMemRefType< int8_t > * M)
Definition at line 27 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
_mlir_ciface_print_memref_vector_4x4xf32()
void _mlir_ciface_print_memref_vector_4x4xf32 (StridedMemRefType< Vector2D< 4, 4, float >, 2 > * M)
Definition at line 22 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by impl::printMemRef().
print_flops()
void print_flops (double flops)
Prints GFLOPS rating.
Definition at line 71 of file RunnerUtils.cpp.
print_memref_f32()
void print_memref_f32 (int64_t rank, void * ptr)
Definition at line 44 of file RunnerUtils.cpp.
References _mlir_ciface_print_memref_f32().
Referenced by impl::printMemRef().
print_memref_i32()
void print_memref_i32 (int64_t rank, void * ptr)
Definition at line 39 of file RunnerUtils.cpp.
References _mlir_ciface_print_memref_i32().
Referenced by impl::printMemRef().
rtclock()
double rtclock ()
Returns the number of seconds since Epoch 1970-01-01 00:00:00 +0000 (UTC).
Definition at line 76 of file RunnerUtils.cpp.