MLIR: lib/Dialect/SPIRV/SPIRVLowering.cpp File Reference
SPIRVLowering.cpp File Reference
#include "mlir/Dialect/SPIRV/SPIRVLowering.h"
#include "mlir/Dialect/SPIRV/LayoutUtils.h"
#include "mlir/Dialect/SPIRV/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Debug.h"
#include <functional>
Macros
#define DEBUG_TYPE "mlir-spirv-lowering"
#define STORAGE_SPACE_MAP_LIST(MAP_FN)
Mapping between SPIR-V storage classes to memref memory spaces.
#define STORAGE_SPACE_MAP_FN(storage, space)
#define STORAGE_SPACE_MAP_FN(storage, space)
Functions
template<typename LabelT >
static LogicalResult checkExtensionRequirements (LabelT label, const spirv::TargetEnv &targetEnv, const spirv::SPIRVType::ExtensionArrayRefVector &candidates)
Checks that candidates extension requirements are possible to be satisfied with the given targetEnv.
template<typename LabelT >
static LogicalResult checkCapabilityRequirements (LabelT label, const spirv::TargetEnv &targetEnv, const spirv::SPIRVType::CapabilityArrayRefVector &candidates)
Checks that candidatescapability requirements are possible to be satisfied with the given isAllowedFn.
static Optional< int64_t > getTypeNumBytes (Type t)
static Optional< Type > convertScalarType (const spirv::TargetEnv &targetEnv, spirv::ScalarType type, Optional< spirv::StorageClass > storageClass={})
Converts a scalar type to a suitable type under the given targetEnv.
static Optional< Type > convertVectorType (const spirv::TargetEnv &targetEnv, VectorType type, Optional< spirv::StorageClass > storageClass={})
Converts a vector type to a suitable type under the given targetEnv.
static Optional< Type > convertTensorType (const spirv::TargetEnv &targetEnv, TensorType type)
Converts a tensor type to a suitable type under the given targetEnv.
static Optional< Type > convertMemrefType (const spirv::TargetEnv &targetEnv, MemRefType type)
static spirv::GlobalVariableOp getBuiltinVariable (Block &body, spirv::BuiltIn builtin)
static std::string getBuiltinVarName (spirv::BuiltIn builtin)
Gets name of global variable for a builtin.
static spirv::GlobalVariableOp getOrInsertBuiltinVariable (Block &body, Location loc, spirv::BuiltIn builtin, OpBuilder &builder)
Gets or inserts a global variable for a builtin within body block.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mlir-spirv-lowering"
Definition at line 23 of file SPIRVLowering.cpp.
STORAGE_SPACE_MAP_FN [1/2]
#define STORAGE_SPACE_MAP_FN (storage, space)
Value:
case storage:                                                                \
    return space;
Referenced by mlir::SPIRVTypeConverter::getMemorySpaceForStorageClass(), and mlir::SPIRVTypeConverter::getStorageClassForMemorySpace().
STORAGE_SPACE_MAP_FN [2/2]
#define STORAGE_SPACE_MAP_FN (storage, space)
Value:
case space:                                                                  \
    return storage;
STORAGE_SPACE_MAP_LIST
#define STORAGE_SPACE_MAP_LIST (MAP_FN)
Value:
MAP_FN(spirv::StorageClass::Generic, 1)                                      \
  MAP_FN(spirv::StorageClass::StorageBuffer, 0)                                \
  MAP_FN(spirv::StorageClass::Workgroup, 3)                                    \
  MAP_FN(spirv::StorageClass::Uniform, 4)                                      \
  MAP_FN(spirv::StorageClass::Private, 5)                                      \
  MAP_FN(spirv::StorageClass::Function, 6)                                     \
  MAP_FN(spirv::StorageClass::PushConstant, 7)                                 \
  MAP_FN(spirv::StorageClass::UniformConstant, 8)                              \
  MAP_FN(spirv::StorageClass::Input, 9)                                        \
  MAP_FN(spirv::StorageClass::Output, 10)                                      \
  MAP_FN(spirv::StorageClass::CrossWorkgroup, 11)                              \
  MAP_FN(spirv::StorageClass::AtomicCounter, 12)                               \
  MAP_FN(spirv::StorageClass::Image, 13)                                       \
  MAP_FN(spirv::StorageClass::CallableDataNV, 14)                              \
  MAP_FN(spirv::StorageClass::IncomingCallableDataNV, 15)                      \
  MAP_FN(spirv::StorageClass::RayPayloadNV, 16)                                \
  MAP_FN(spirv::StorageClass::HitAttributeNV, 17)                              \
  MAP_FN(spirv::StorageClass::IncomingRayPayloadNV, 18)                        \
  MAP_FN(spirv::StorageClass::ShaderRecordBufferNV, 19)                        \
  MAP_FN(spirv::StorageClass::PhysicalStorageBuffer, 20)
Mapping between SPIR-V storage classes to memref memory spaces.
Note: memref does not have a defined semantics for each memory space; it depends on the context where it is used. There are no particular reasons behind the number assignments; we try to follow NVVM conventions and largely give common storage classes a smaller number. The hope is use symbolic memory space representation eventually after memref supports it.
Definition at line 109 of file SPIRVLowering.cpp.
Referenced by mlir::SPIRVTypeConverter::getMemorySpaceForStorageClass(), and mlir::SPIRVTypeConverter::getStorageClassForMemorySpace().
Function Documentation
checkCapabilityRequirements()
template<typename LabelT > static LogicalResult checkCapabilityRequirements (LabelT label, const spirv::TargetEnv & targetEnv, const spirv::SPIRVType::CapabilityArrayRefVector & candidates) static
Checks that candidatescapability requirements are possible to be satisfied with the given isAllowedFn.
candidates is a vector of vector for capability requirements following ((Capability::A OR Capability::B) AND (Capability::C OR Capability::D)) convention.
Definition at line 65 of file SPIRVLowering.cpp.
References mlir::spirv::TargetEnv::allows(), mlir::failure(), and mlir::success().
Referenced by convertScalarType(), convertVectorType(), and mlir::spirv::SPIRVConversionTarget::get().
checkExtensionRequirements()
template<typename LabelT > static LogicalResult checkExtensionRequirements (LabelT label, const spirv::TargetEnv & targetEnv, const spirv::SPIRVType::ExtensionArrayRefVector & candidates) static
Checks that candidates extension requirements are possible to be satisfied with the given targetEnv.
candidates is a vector of vector for extension requirements following ((Extension::A OR Extension::B) AND (Extension::C OR Extension::D)) convention.
Definition at line 38 of file SPIRVLowering.cpp.
References mlir::spirv::TargetEnv::allows(), mlir::failure(), and mlir::success().
Referenced by convertScalarType(), convertVectorType(), and mlir::spirv::SPIRVConversionTarget::get().
convertMemrefType()
static Optional<Type> convertMemrefType (const spirv::TargetEnv & targetEnv, MemRefType type) static
Definition at line 343 of file SPIRVLowering.cpp.
References convertScalarType(), convertVectorType(), mlir::Type::dyn_cast(), mlir::spirv::ArrayType::get(), mlir::spirv::PointerType::get(), mlir::spirv::RuntimeArrayType::get(), mlir::spirv::StructType::get(), mlir::MemRefType::getMemorySpace(), mlir::SPIRVTypeConverter::getStorageClassForMemorySpace(), and getTypeNumBytes().
Referenced by mlir::SPIRVTypeConverter::SPIRVTypeConverter().
convertScalarType()
static Optional<Type> convertScalarType (const spirv::TargetEnv & targetEnv, spirv::ScalarType type, Optional< spirv::StorageClass > storageClass = {}) static
Converts a scalar type to a suitable type under the given targetEnv.
Definition at line 234 of file SPIRVLowering.cpp.
References mlir::Type::cast(), checkCapabilityRequirements(), checkExtensionRequirements(), mlir::Type::dyn_cast(), mlir::IntegerType::get(), mlir::spirv::ScalarType::getCapabilities(), mlir::spirv::TargetEnv::getContext(), mlir::spirv::ScalarType::getExtensions(), and mlir::succeeded().
Referenced by convertMemrefType(), convertTensorType(), convertVectorType(), and mlir::SPIRVTypeConverter::SPIRVTypeConverter().
convertTensorType()
static Optional<Type> convertTensorType (const spirv::TargetEnv & targetEnv, TensorType type) static
Converts a tensor type to a suitable type under the given targetEnv.
Note that this is mainly for lowering constant tensors.In SPIR-V one can create composite constants with OpConstantComposite to embed relative large constant values and use OpCompositeExtract and OpCompositeInsert to manipulate, like what we do for vectors.
Definition at line 305 of file SPIRVLowering.cpp.
References convertScalarType(), mlir::Type::dyn_cast(), mlir::spirv::ArrayType::get(), mlir::ShapedType::getElementType(), getTypeNumBytes(), and mlir::ShapedType::hasStaticShape().
Referenced by mlir::SPIRVTypeConverter::SPIRVTypeConverter().
convertVectorType()
static Optional<Type> convertVectorType (const spirv::TargetEnv & targetEnv, VectorType type, Optional< spirv::StorageClass > storageClass = {}) static
Converts a vector type to a suitable type under the given targetEnv.
Definition at line 270 of file SPIRVLowering.cpp.
References checkCapabilityRequirements(), checkExtensionRequirements(), convertScalarType(), mlir::VectorType::get(), mlir::VectorType::getShape(), mlir::spirv::CompositeType::isValid(), and mlir::succeeded().
Referenced by convertMemrefType(), and mlir::SPIRVTypeConverter::SPIRVTypeConverter().
getBuiltinVariable()
static spirv::GlobalVariableOp getBuiltinVariable (Block & body, spirv::BuiltIn builtin) static
Definition at line 521 of file SPIRVLowering.cpp.
References mlir::Block::getOps().
Referenced by getOrInsertBuiltinVariable().
getBuiltinVarName()
static std::string getBuiltinVarName (spirv::BuiltIn builtin) static
Gets name of global variable for a builtin.
Definition at line 539 of file SPIRVLowering.cpp.
Referenced by getOrInsertBuiltinVariable().
getOrInsertBuiltinVariable()
static spirv::GlobalVariableOp getOrInsertBuiltinVariable (Block & body, Location loc, spirv::BuiltIn builtin, OpBuilder & builder) static
Gets or inserts a global variable for a builtin within body block.
Definition at line 545 of file SPIRVLowering.cpp.
References mlir::Region::begin(), mlir::OpBuilder::create(), mlir::emitError(), mlir::Operation::emitError(), mlir::spirv::PointerType::get(), mlir::VectorType::get(), getBuiltinVariable(), mlir::spirv::getBuiltinVariableValue(), getBuiltinVarName(), mlir::Builder::getIntegerType(), mlir::Operation::getLoc(), mlir::SymbolTable::getNearestSymbolTable(), mlir::Operation::getParentOp(), mlir::Operation::getRegion(), and mlir::OpBuilder::setInsertionPointToStart().
getTypeNumBytes()
static Optional<int64_t> getTypeNumBytes (Type t) static
Definition at line 160 of file SPIRVLowering.cpp.
References mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::failed(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::Type::getIntOrFloatBitWidth(), mlir::getStridesAndOffset(), mlir::Type::isa(), and mlir::ShapedType::kDynamicSize.
Referenced by convertMemrefType(), convertTensorType(), and mlir::SPIRVTypeConverter::getConvertedTypeNumBytes().