MLIR: lib/IR/StandardTypes.cpp File Reference
StandardTypes.cpp File Reference
#include "mlir/IR/StandardTypes.h"
#include "TypeDetail.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dialect.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/Twine.h"
Functions
static LogicalResult checkTensorElementType (Location location, Type elementType)
static void extractStridesFromTerm (AffineExpr e, AffineExpr multiplicativeFactor, MutableArrayRef< AffineExpr > strides, AffineExpr &offset)
static LogicalResult extractStrides (AffineExpr e, AffineExpr multiplicativeFactor, MutableArrayRef< AffineExpr > strides, AffineExpr &offset)
Takes a single AffineExpr e and populates the strides array with the strides expressions for each dim position.
Function Documentation
checkTensorElementType()
static LogicalResult checkTensorElementType (Location location, Type elementType) static
Definition at line 304 of file StandardTypes.cpp.
References mlir::emitError(), mlir::TensorType::isValidElementType(), and mlir::success().
Referenced by mlir::RankedTensorType::verifyConstructionInvariants(), and mlir::UnrankedTensorType::verifyConstructionInvariants().
extractStrides()
static LogicalResult extractStrides (AffineExpr e, AffineExpr multiplicativeFactor, MutableArrayRef< AffineExpr > strides, AffineExpr & offset) static
Takes a single AffineExpr e and populates the strides array with the strides expressions for each dim position.
The convention is that the strides for dimensions d0, .. dn appear in order to make indexing intuitive into the result.
Definition at line 509 of file StandardTypes.cpp.
References mlir::Add, mlir::CeilDiv, mlir::AffineExpr::dyn_cast(), extractStridesFromTerm(), mlir::failure(), mlir::FloorDiv, mlir::Mod, mlir::Mul, mlir::succeeded(), and mlir::success().
Referenced by mlir::getStridesAndOffset().
extractStridesFromTerm()
static void extractStridesFromTerm (AffineExpr e, AffineExpr multiplicativeFactor, MutableArrayRef< AffineExpr > strides, AffineExpr & offset) static
Definition at line 494 of file StandardTypes.cpp.
References mlir::AffineExpr::dyn_cast().
Referenced by extractStrides().