MLIR: mlir::vector::UnrollVectorPattern< OpTy > Struct Template Reference
mlir::vector::UnrollVectorPattern< OpTy > Struct Template Reference
Pattern to apply unrollSingleResultVectorOp to a targetShape declaratively.
#include "mlir/Dialect/Vector/VectorTransforms.h"
Public Types
using FilterConstraintType = std::function< LogicalResult(OpTy op)>
Public Member Functions
UnrollVectorPattern (ArrayRef< int64_t > targetShape, MLIRContext *context, FilterConstraintType constraint=[](OpTy op) { return success();})
LogicalResult matchAndRewrite (OpTy op, PatternRewriter &rewriter) const override
Public Member Functions inherited from mlir::OpRewritePattern< OpTy >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
virtual void rewrite (OpTy op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult match (OpTy op) const
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a rewrite pattern with a certain benefit that matches any operation type.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a rewrite pattern that may match any operation type.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
This constructor is used for patterns that match against a specific operation type.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag)
This constructor is used when a pattern may match against multiple different types of operations.
Protected Attributes inherited from mlir::RewritePattern
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Detailed Description
template<typename OpTy>
struct mlir::vector::UnrollVectorPattern< OpTy >
Pattern to apply unrollSingleResultVectorOp to a targetShape declaratively.
Definition at line 75 of file VectorTransforms.h.
Member Typedef Documentation
FilterConstraintType
template<typename OpTy > using mlir::vector::UnrollVectorPattern< OpTy >::FilterConstraintType = std::function<LogicalResult(OpTy op)>
Definition at line 76 of file VectorTransforms.h.
Constructor & Destructor Documentation
UnrollVectorPattern()
template<typename OpTy > mlir::vector::UnrollVectorPattern< OpTy >::UnrollVectorPattern (ArrayRef< int64_t > targetShape, MLIRContext * context, FilterConstraintType constraint = [](OpTy op) { return success(); }) inline
Definition at line 77 of file VectorTransforms.h.
References mlir::success().
Member Function Documentation
matchAndRewrite()
template<typename OpTy > LogicalResult mlir::vector::UnrollVectorPattern< OpTy >::matchAndRewrite (OpTy op, PatternRewriter & rewriter) const inline override virtual
Reimplemented from mlir::OpRewritePattern< OpTy >.
Definition at line 83 of file VectorTransforms.h.
References mlir::failed(), mlir::failure(), options, mlir::PatternRewriter::replaceOp(), mlir::shapeRatio(), mlir::vector::splitFullAndPartialTransfer(), mlir::vector::splitFullAndPartialTransferPrecondition(), mlir::success(), and mlir::vector::unrollSingleResultVectorOp().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Vector/VectorTransforms.h