MLIR: mlir::detail::OpaqueTypeStorage Struct Reference
mlir::detail::OpaqueTypeStorage Struct Reference
Opaque Type Storage and Uniquing.
#include "IR/TypeDetail.h"
Public Types
using KeyTy = std::pair< Identifier, StringRef >
The hash key used for uniquing.
Public Member Functions
OpaqueTypeStorage (Identifier dialectNamespace, StringRef typeData)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::TypeStorage
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static OpaqueTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Public Attributes
Identifier dialectNamespace
StringRef typeData
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage ()
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
Opaque Type Storage and Uniquing.
Definition at line 31 of file TypeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::OpaqueTypeStorage::KeyTy = std::pair<Identifier, StringRef>
The hash key used for uniquing.
Definition at line 36 of file TypeDetail.h.
Constructor & Destructor Documentation
OpaqueTypeStorage()
mlir::detail::OpaqueTypeStorage::OpaqueTypeStorage (Identifier dialectNamespace, StringRef typeData) inline
Definition at line 32 of file TypeDetail.h.
Referenced by construct().
Member Function Documentation
construct()
static OpaqueTypeStorage* mlir::detail::OpaqueTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 41 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), mlir::StorageUniquer::StorageAllocator::copyInto(), and OpaqueTypeStorage().
operator==()
bool mlir::detail::OpaqueTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 37 of file TypeDetail.h.
References dialectNamespace, and typeData.
Member Data Documentation
dialectNamespace
Identifier mlir::detail::OpaqueTypeStorage::dialectNamespace
Definition at line 49 of file TypeDetail.h.
Referenced by operator==().
typeData
StringRef mlir::detail::OpaqueTypeStorage::typeData
Definition at line 52 of file TypeDetail.h.
Referenced by operator==().
The documentation for this struct was generated from the following file:
lib/IR/TypeDetail.h