MLIR: mlir::linalg::LinalgMarker Struct Reference
mlir::linalg::LinalgMarker Struct Reference
Helper class to control common attribute matching and setting behavior.
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
Public Member Functions
LinalgMarker (ArrayRef< Identifier > matchDisjunction={}, Optional< Identifier > replacement=None)
LinalgMarker (LinalgMarker &&)=default
LinalgMarker (const LinalgMarker &)=default
LogicalResult checkAndNotify (PatternRewriter &rewriter, Operation *op) const
void replaceLinalgMarker (PatternRewriter &rewriter, Operation *op) const
Detailed Description
Helper class to control common attribute matching and setting behavior.
Definition at line 211 of file Transforms.h.
Constructor & Destructor Documentation
LinalgMarker() [1/3]
mlir::linalg::LinalgMarker::LinalgMarker (ArrayRef< Identifier > matchDisjunction = {}, Optional< Identifier > replacement = None) explicit
Definition at line 47 of file Transforms.cpp.
LinalgMarker() [2/3]
mlir::linalg::LinalgMarker::LinalgMarker (LinalgMarker &&) default
LinalgMarker() [3/3]
mlir::linalg::LinalgMarker::LinalgMarker (const LinalgMarker &) default
Member Function Documentation
checkAndNotify()
LogicalResult mlir::linalg::LinalgMarker::checkAndNotify (PatternRewriter & rewriter, Operation * op) const
Definition at line 53 of file Transforms.cpp.
References diag(), mlir::linalg::LinalgTransforms::kLinalgTransformMarker, mlir::PatternRewriter::notifyMatchFailure(), and mlir::success().
Referenced by mlir::linalg::LinalgBaseTilingPattern::matchAndRewrite(), mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite(), mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), and mlir::linalg::LinalgBaseVectorizationPattern::matchAndRewrite().
replaceLinalgMarker()
void mlir::linalg::LinalgMarker::replaceLinalgMarker (PatternRewriter & rewriter, Operation * op) const
Definition at line 82 of file Transforms.cpp.
References mlir::Identifier::get(), mlir::Builder::getContext(), mlir::Builder::getStringAttr(), mlir::linalg::LinalgTransforms::kLinalgTransformMarker, mlir::Operation::removeAttr(), and mlir::Operation::setAttr().
Referenced by mlir::linalg::LinalgBaseTilingPattern::matchAndRewrite(), mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite(), and mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/Transforms/Transforms.h
lib/Dialect/Linalg/Transforms/Transforms.cpp