MLIR: mlir::detail::DenseStringElementsAttributeStorage Struct Reference
mlir::detail::DenseStringElementsAttributeStorage Struct Reference
An attribute representing a reference to a dense vector or tensor object containing strings.
#include "IR/AttributeDetail.h"
Classes
struct KeyTy
Public Member Functions
DenseStringElementsAttributeStorage (ShapedType ty, ArrayRef< StringRef > data, bool isSplat=false)
bool operator== (const KeyTy &key) const
Compare this storage instance with the provided key.
Public Member Functions inherited from mlir::detail::DenseElementsAttributeStorage
DenseElementsAttributeStorage (ShapedType ty, bool isSplat)
Public Member Functions inherited from mlir::AttributeStorage
Type getType () const
Get the type of this attribute.
const AbstractAttribute & getAbstractAttribute () const
Return the abstract descriptor for this attribute.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static KeyTy getKey (ShapedType ty, ArrayRef< StringRef > data, bool isKnownSplat)
Construct a key from a shaped type, StringRef data buffer, and a flag that signals if the data is already known to be a splat.
static llvm::hash_code hashKey (const KeyTy &key)
Hash the key for the storage.
static DenseStringElementsAttributeStorage * construct (AttributeStorageAllocator &allocator, KeyTy key)
Construct a new storage instance.
Public Attributes
ArrayRef< StringRef > data
Public Attributes inherited from mlir::detail::DenseElementsAttributeStorage
bool isSplat
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
AttributeStorage (Type type)
Construct a new attribute storage instance with the given type.
AttributeStorage ()
void setType (Type type)
Set the type of this attribute.
void initialize (const AbstractAttribute &abstractAttr)
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
An attribute representing a reference to a dense vector or tensor object containing strings.
Definition at line 525 of file AttributeDetail.h.
Constructor & Destructor Documentation
DenseStringElementsAttributeStorage()
mlir::detail::DenseStringElementsAttributeStorage::DenseStringElementsAttributeStorage (ShapedType ty, ArrayRef< StringRef > data, bool isSplat = false) inline
Definition at line 527 of file AttributeDetail.h.
Member Function Documentation
construct()
static DenseStringElementsAttributeStorage* mlir::detail::DenseStringElementsAttributeStorage::construct (AttributeStorageAllocator & allocator, KeyTy key) inline static
Construct a new storage instance.
Definition at line 599 of file AttributeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), mlir::detail::DenseStringElementsAttributeStorage::KeyTy::data, mlir::detail::DenseStringElementsAttributeStorage::KeyTy::isSplat, and mlir::detail::DenseStringElementsAttributeStorage::KeyTy::type.
getKey()
static KeyTy mlir::detail::DenseStringElementsAttributeStorage::getKey (ShapedType ty, ArrayRef< StringRef > data, bool isKnownSplat) inline static
Construct a key from a shaped type, StringRef data buffer, and a flag that signals if the data is already known to be a splat.
Callers to this function are expected to tag preknown splat values when possible, e.g. one element shapes.
Definition at line 563 of file AttributeDetail.h.
References mlir::ShapedType::getNumElements(), and mlir::spirv::hash_value().
hashKey()
static llvm::hash_code mlir::detail::DenseStringElementsAttributeStorage::hashKey (const KeyTy & key) inline static
Hash the key for the storage.
Definition at line 593 of file AttributeDetail.h.
References mlir::detail::DenseStringElementsAttributeStorage::KeyTy::hashCode, and mlir::detail::DenseStringElementsAttributeStorage::KeyTy::type.
operator==()
bool mlir::detail::DenseStringElementsAttributeStorage::operator== (const KeyTy & key) const inline
Compare this storage instance with the provided key.
Definition at line 550 of file AttributeDetail.h.
References mlir::detail::DenseStringElementsAttributeStorage::KeyTy::data, mlir::AttributeStorage::getType(), and mlir::detail::DenseStringElementsAttributeStorage::KeyTy::type.
Member Data Documentation
data
ArrayRef<StringRef> mlir::detail::DenseStringElementsAttributeStorage::data
Definition at line 638 of file AttributeDetail.h.
The documentation for this struct was generated from the following file:
lib/IR/AttributeDetail.h