MLIR: mlir::linalg::LinalgBasePromotionPattern Struct Reference
mlir::linalg::LinalgBasePromotionPattern Struct Reference
Linalg promotion patterns.
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
Public Member Functions
LinalgBasePromotionPattern (StringRef opName, MLIRContext *context, LinalgPromotionOptions options, LinalgMarker marker=LinalgMarker(), PatternBenefit benefit=1)
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const override
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
LogicalResult match (Operation *op) const override
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a rewrite pattern with a certain benefit that matches any operation type.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a rewrite pattern that may match any operation type.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
This constructor is used for patterns that match against a specific operation type.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag)
This constructor is used when a pattern may match against multiple different types of operations.
Protected Attributes inherited from mlir::RewritePattern
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Detailed Description
Linalg promotion patterns.
Apply the promoteSubViews transformation as a pattern. marker controls LinalgTransformMarker matching and update when specified. See promoteSubViews for more details.
Definition at line 342 of file Transforms.h.
Constructor & Destructor Documentation
LinalgBasePromotionPattern()
mlir::linalg::LinalgBasePromotionPattern::LinalgBasePromotionPattern (StringRef opName, MLIRContext * context, LinalgPromotionOptions options, LinalgMarker marker = LinalgMarker(), PatternBenefit benefit = 1)
Definition at line 162 of file Transforms.cpp.
Member Function Documentation
matchAndRewrite()
LogicalResult mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const override virtual
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
If successful, this function will automatically perform the rewrite.
Reimplemented from mlir::RewritePattern.
Definition at line 168 of file Transforms.cpp.
References mlir::PatternRewriter::cancelRootUpdate(), mlir::linalg::LinalgMarker::checkAndNotify(), mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::PatternRewriter::finalizeRootUpdate(), mlir::linalg::promoteSubViews(), mlir::linalg::promoteSubviewsPrecondition(), mlir::linalg::LinalgMarker::replaceLinalgMarker(), mlir::PatternRewriter::startRootUpdate(), and mlir::success().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/Transforms/Transforms.h
lib/Dialect/Linalg/Transforms/Transforms.cpp