MLIR: mlir::edsc::StructuredIndexed Struct Reference
mlir::edsc::StructuredIndexed Struct Reference
A StructuredIndexed represents an indexable quantity that is either:
#include "mlir/EDSC/Builders.h"
Public Member Functions
StructuredIndexed (Value v)
StructuredIndexed (Type t)
StructuredIndexed operator() (ArrayRef< AffineExpr > indexings)
StructuredIndexed (Value v, ArrayRef< AffineExpr > indexings)
StructuredIndexed (Type t, ArrayRef< AffineExpr > indexings)
bool hasValue () const
Value getValue () const
Type getType () const
ArrayRef< AffineExpr > getExprs () const
operator Value () const
operator Type () const
Detailed Description
A StructuredIndexed represents an indexable quantity that is either:
a captured value, which is suitable for buffer and tensor operands, or;
a captured type, which is suitable for tensor return values.
A StructuredIndexed itself is indexed and passed to makeGenericLinalgOp. It enable an idiomatic syntax for index expressions such as:
StructuredIndexed A(buffer_or_tensor_value), B(buffer_or_tensor_value),
  C(buffer_value_or_tensor_type);
makeGenericLinalgOp({A({m, n}), B({k, n})}, {C({m, n})}, ...);
Definition at line 132 of file Builders.h.
Constructor & Destructor Documentation
StructuredIndexed() [1/4]
mlir::edsc::StructuredIndexed::StructuredIndexed (Value v) inline
Definition at line 133 of file Builders.h.
StructuredIndexed() [2/4]
mlir::edsc::StructuredIndexed::StructuredIndexed (Type t) inline
Definition at line 134 of file Builders.h.
StructuredIndexed() [3/4]
mlir::edsc::StructuredIndexed::StructuredIndexed (Value v, ArrayRef< AffineExpr > indexings) inline
Definition at line 140 of file Builders.h.
References mlir::Value::getType(), and mlir::Type::isa().
StructuredIndexed() [4/4]
mlir::edsc::StructuredIndexed::StructuredIndexed (Type t, ArrayRef< AffineExpr > indexings) inline
Definition at line 145 of file Builders.h.
References mlir::Type::isa().
Member Function Documentation
getExprs()
ArrayRef<AffineExpr> mlir::edsc::StructuredIndexed::getExprs () const inline
Definition at line 160 of file Builders.h.
Referenced by mlir::edsc::ops::linalg_generic_pointwise(), and mlir::edsc::ops::vector_contraction().
getType()
Type mlir::edsc::StructuredIndexed::getType () const inline
Definition at line 156 of file Builders.h.
Referenced by mlir::edsc::ops::linalg_generic_pointwise().
getValue()
Value mlir::edsc::StructuredIndexed::getValue () const inline
Definition at line 152 of file Builders.h.
Referenced by mlir::edsc::ops::vector_contraction().
hasValue()
bool mlir::edsc::StructuredIndexed::hasValue () const inline
Definition at line 151 of file Builders.h.
operator Type()
mlir::edsc::StructuredIndexed::operator Type () const inline
Definition at line 162 of file Builders.h.
operator Value()
mlir::edsc::StructuredIndexed::operator Value () const inline
Definition at line 161 of file Builders.h.
operator()()
StructuredIndexed mlir::edsc::StructuredIndexed::operator() (ArrayRef< AffineExpr > indexings) inline
Definition at line 135 of file Builders.h.
The documentation for this struct was generated from the following file:
include/mlir/EDSC/Builders.h