MLIR: mlir::edsc::intrinsics::FoldedValueBuilder< Op > Struct Template Reference
mlir::edsc::intrinsics::FoldedValueBuilder< Op > Struct Template Reference
#include "mlir/Dialect/Linalg/EDSC/FoldedIntrinsics.h"
Public Member Functions
template<typename... Args>
FoldedValueBuilder (OperationFolder *folder, Args... args)
operator Value ()
Public Attributes
Value value
Detailed Description
template<typename Op>
struct mlir::edsc::intrinsics::FoldedValueBuilder< Op >
Definition at line 21 of file FoldedIntrinsics.h.
Constructor & Destructor Documentation
FoldedValueBuilder()
template<typename Op > template<typename... Args> mlir::edsc::intrinsics::FoldedValueBuilder< Op >::FoldedValueBuilder (OperationFolder * folder, Args... args) inline
Definition at line 24 of file FoldedIntrinsics.h.
References mlir::OperationFolder::create(), mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getLocation(), and mlir::edsc::intrinsics::FoldedValueBuilder< Op >::value.
Member Function Documentation
operator Value()
template<typename Op > mlir::edsc::intrinsics::FoldedValueBuilder< Op >::operator Value () inline
Definition at line 31 of file FoldedIntrinsics.h.
References mlir::edsc::intrinsics::FoldedValueBuilder< Op >::value.
Member Data Documentation
value
template<typename Op > Value mlir::edsc::intrinsics::FoldedValueBuilder< Op >::value
Definition at line 32 of file FoldedIntrinsics.h.
Referenced by mlir::edsc::intrinsics::FoldedValueBuilder< Op >::FoldedValueBuilder(), and mlir::edsc::intrinsics::FoldedValueBuilder< Op >::operator Value().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Linalg/EDSC/FoldedIntrinsics.h