MLIR: mlir::linalg::LinalgCopyVTRForwardingPattern Struct Reference
mlir::linalg::LinalgCopyVTRForwardingPattern Struct Reference
Match and rewrite for the pattern: ``` alloc = ...
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
Public Member Functions
LogicalResult matchAndRewrite (vector::TransferReadOp xferOp, PatternRewriter &rewriter) const override
TODO: use interfaces, side-effects and aliasing analysis as appropriate, when available.
Public Member Functions inherited from mlir::OpRewritePattern< vector::TransferReadOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
virtual void rewrite (vector::TransferReadOp op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult match (vector::TransferReadOp op) const
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a rewrite pattern with a certain benefit that matches any operation type.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a rewrite pattern that may match any operation type.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
This constructor is used for patterns that match against a specific operation type.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag)
This constructor is used when a pattern may match against multiple different types of operations.
Protected Attributes inherited from mlir::RewritePattern
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Detailed Description
Match and rewrite for the pattern: ``` alloc = ...
[optional] view = std.view alloc ... subView = subview allocOrView ... [optional] linalg.fill(allocOrView, cst) ... ... linalg.copy(in, subView) ... vector.transfer_read allocOrView[...], cst ...
into
[unchanged] alloc = ... [unchanged] [optional] view = std.view alloc ... [unchanged] [unchanged] subView = subview allocOrView ... ... vector.transfer_read in[...], cst ... ``` Where there is no interleaved use between linalg.copy and transfer_read as well as no interleaved use between linalg.fill and linalg.copy (if linalg.fill is specified). This is a custom rewrite to forward partial reads (with optional fills) to vector.transfer_read.
Definition at line 470 of file Transforms.h.
Member Function Documentation
matchAndRewrite()
LogicalResult LinalgCopyVTRForwardingPattern::matchAndRewrite (vector::TransferReadOp xferOp, PatternRewriter & rewriter) const override virtual
TODO: use interfaces, side-effects and aliasing analysis as appropriate, when available.
Reimplemented from mlir::OpRewritePattern< vector::TransferReadOp >.
Definition at line 249 of file Vectorization.cpp.
References mlir::PatternRewriter::create(), DEBUG_TYPE, mlir::PatternRewriter::eraseOp(), mlir::failure(), mlir::Value::getDefiningOp(), getSubViewUseIfUnique(), mlir::Value::getUses(), mayExistInterleavedUses(), mlir::PatternRewriter::replaceOp(), and mlir::success().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/Transforms/Transforms.h
lib/Dialect/Linalg/Transforms/Vectorization.cpp