MLIR: mlir::edsc::OperationBuilder< Op > Struct Template Reference
mlir::edsc::OperationBuilder< Op > Struct Template Reference
#include "mlir/EDSC/Builders.h"
Public Member Functions
template<typename... Args>
OperationBuilder (Args... args)
operator Op ()
operator Operation * ()
Public Attributes
Op op
Detailed Description
template<typename Op>
struct mlir::edsc::OperationBuilder< Op >
Definition at line 80 of file Builders.h.
Constructor & Destructor Documentation
OperationBuilder()
template<typename Op> template<typename... Args> mlir::edsc::OperationBuilder< Op >::OperationBuilder (Args... args) inline
Definition at line 82 of file Builders.h.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), and mlir::edsc::ScopedContext::getLocation().
Member Function Documentation
operator Op()
template<typename Op> mlir::edsc::OperationBuilder< Op >::operator Op () inline
Definition at line 86 of file Builders.h.
operator Operation *()
template<typename Op> mlir::edsc::OperationBuilder< Op >::operator Operation * () inline
Definition at line 87 of file Builders.h.
Member Data Documentation
op
template<typename Op> Op mlir::edsc::OperationBuilder< Op >::op
Definition at line 88 of file Builders.h.
The documentation for this struct was generated from the following file:
include/mlir/EDSC/Builders.h