MLIR: mlir::LowerToLLVMOptions Struct Reference
mlir::LowerToLLVMOptions Struct Reference
Options to control the Standard dialect to LLVM lowering.
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
Static Public Member Functions
static const LowerToLLVMOptions & getDefaultOptions ()
Get a statically allocated copy of the default LowerToLLVMOptions.
Public Attributes
bool useBarePtrCallConv = false
bool emitCWrappers = false
unsigned indexBitwidth = kDeriveIndexBitwidthFromDataLayout
bool useAlignedAlloc = false
Use aligned_alloc for heap allocations.
Detailed Description
Options to control the Standard dialect to LLVM lowering.
The struct is used to share lowering options between passes, patterns, and type converter.
Definition at line 27 of file ConvertStandardToLLVMPass.h.
Member Function Documentation
getDefaultOptions()
static const LowerToLLVMOptions& mlir::LowerToLLVMOptions::getDefaultOptions () inline static
Get a statically allocated copy of the default LowerToLLVMOptions.
Definition at line 35 of file ConvertStandardToLLVMPass.h.
References mlir::createLowerToLLVMPass(), options, mlir::populateStdToLLVMConversionPatterns(), mlir::populateStdToLLVMFuncOpConversionPattern(), mlir::populateStdToLLVMMemoryConversionPatterns(), and mlir::populateStdToLLVMNonMemoryConversionPatterns().
Member Data Documentation
emitCWrappers
bool mlir::LowerToLLVMOptions::emitCWrappers = false
Definition at line 29 of file ConvertStandardToLLVMPass.h.
Referenced by mlir::createLowerToLLVMPass().
indexBitwidth
unsigned mlir::LowerToLLVMOptions::indexBitwidth = kDeriveIndexBitwidthFromDataLayout
Definition at line 30 of file ConvertStandardToLLVMPass.h.
Referenced by mlir::createLowerToLLVMPass(), mlir::LLVMTypeConverter::getIndexTypeBitwidth(), and mlir::LLVMTypeConverter::LLVMTypeConverter().
useAlignedAlloc
bool mlir::LowerToLLVMOptions::useAlignedAlloc = false
Use aligned_alloc for heap allocations.
Definition at line 32 of file ConvertStandardToLLVMPass.h.
Referenced by mlir::createLowerToLLVMPass(), and mlir::LLVM::detail::vectorOneToOneRewrite().
useBarePtrCallConv
bool mlir::LowerToLLVMOptions::useBarePtrCallConv = false
Definition at line 28 of file ConvertStandardToLLVMPass.h.
Referenced by mlir::LLVMTypeConverter::convertFunctionSignature(), mlir::createLowerToLLVMPass(), and mlir::populateStdToLLVMFuncOpConversionPattern().
The documentation for this struct was generated from the following file:
include/mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h