MLIR: mlir::detail::DenseIntOrFPElementsAttributeStorage Struct Reference
mlir::detail::DenseIntOrFPElementsAttributeStorage Struct Reference
An attribute representing a reference to a dense vector or tensor object.
#include "IR/AttributeDetail.h"
Classes
struct KeyTy
Public Member Functions
DenseIntOrFPElementsAttributeStorage (ShapedType ty, ArrayRef< char > data, bool isSplat=false)
bool operator== (const KeyTy &key) const
Compare this storage instance with the provided key.
Public Member Functions inherited from mlir::detail::DenseElementsAttributeStorage
DenseElementsAttributeStorage (ShapedType ty, bool isSplat)
Public Member Functions inherited from mlir::AttributeStorage
Type getType () const
Get the type of this attribute.
const AbstractAttribute & getAbstractAttribute () const
Return the abstract descriptor for this attribute.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static KeyTy getKey (ShapedType ty, ArrayRef< char > data, bool isKnownSplat)
Construct a key from a shaped type, raw data buffer, and a flag that signals if the data is already known to be a splat.
static KeyTy getKeyForBoolData (ShapedType ty, ArrayRef< char > data, size_t numElements)
Construct a key with a set of boolean data.
static llvm::hash_code hashKey (const KeyTy &key)
Hash the key for the storage.
static DenseIntOrFPElementsAttributeStorage * construct (AttributeStorageAllocator &allocator, KeyTy key)
Construct a new storage instance.
Public Attributes
ArrayRef< char > data
Public Attributes inherited from mlir::detail::DenseElementsAttributeStorage
bool isSplat
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
AttributeStorage (Type type)
Construct a new attribute storage instance with the given type.
AttributeStorage ()
void setType (Type type)
Set the type of this attribute.
void initialize (const AbstractAttribute &abstractAttr)
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
An attribute representing a reference to a dense vector or tensor object.
Definition at line 371 of file AttributeDetail.h.
Constructor & Destructor Documentation
DenseIntOrFPElementsAttributeStorage()
mlir::detail::DenseIntOrFPElementsAttributeStorage::DenseIntOrFPElementsAttributeStorage (ShapedType ty, ArrayRef< char > data, bool isSplat = false) inline
Definition at line 373 of file AttributeDetail.h.
Member Function Documentation
construct()
static DenseIntOrFPElementsAttributeStorage* mlir::detail::DenseIntOrFPElementsAttributeStorage::construct (AttributeStorageAllocator & allocator, KeyTy key) inline static
Construct a new storage instance.
Definition at line 501 of file AttributeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), mlir::detail::DenseIntOrFPElementsAttributeStorage::KeyTy::data, mlir::ShapedType::getElementType(), mlir::Type::isInteger(), mlir::detail::DenseIntOrFPElementsAttributeStorage::KeyTy::isSplat, and mlir::detail::DenseIntOrFPElementsAttributeStorage::KeyTy::type.
getKey()
static KeyTy mlir::detail::DenseIntOrFPElementsAttributeStorage::getKey (ShapedType ty, ArrayRef< char > data, bool isKnownSplat) inline static
Construct a key from a shaped type, raw data buffer, and a flag that signals if the data is already known to be a splat.
Callers to this function are expected to tag preknown splat values when possible, e.g. one element shapes.
Definition at line 419 of file AttributeDetail.h.
References mlir::detail::getDenseElementBitWidth(), mlir::ShapedType::getElementType(), mlir::ShapedType::getNumElements(), mlir::spirv::hash_value(), and mlir::Type::isInteger().
getKeyForBoolData()
static KeyTy mlir::detail::DenseIntOrFPElementsAttributeStorage::getKeyForBoolData (ShapedType ty, ArrayRef< char > data, size_t numElements) inline static
Construct a key with a set of boolean data.
Definition at line 460 of file AttributeDetail.h.
References mlir::spirv::hash_value().
hashKey()
static llvm::hash_code mlir::detail::DenseIntOrFPElementsAttributeStorage::hashKey (const KeyTy & key) inline static
Hash the key for the storage.
Definition at line 495 of file AttributeDetail.h.
References mlir::detail::DenseIntOrFPElementsAttributeStorage::KeyTy::hashCode, and mlir::detail::DenseIntOrFPElementsAttributeStorage::KeyTy::type.
operator==()
bool mlir::detail::DenseIntOrFPElementsAttributeStorage::operator== (const KeyTy & key) const inline
Compare this storage instance with the provided key.
Definition at line 396 of file AttributeDetail.h.
References mlir::detail::DenseIntOrFPElementsAttributeStorage::KeyTy::data, mlir::ShapedType::getElementType(), mlir::AttributeStorage::getType(), mlir::Type::isInteger(), mlir::detail::DenseIntOrFPElementsAttributeStorage::KeyTy::isSplat, and mlir::detail::DenseIntOrFPElementsAttributeStorage::KeyTy::type.
Member Data Documentation
data
ArrayRef<char> mlir::detail::DenseIntOrFPElementsAttributeStorage::data
Definition at line 520 of file AttributeDetail.h.
The documentation for this struct was generated from the following file:
lib/IR/AttributeDetail.h