MLIR: mlir::VectorTransferRewriter< TransferOpTy > Struct Template Reference
mlir::VectorTransferRewriter< TransferOpTy > Struct Template Reference
Implements lowering of TransferReadOp and TransferWriteOp to a proper abstraction for the hardware.
#include "mlir/Conversion/VectorToSCF/VectorToSCF.h"
Public Member Functions
VectorTransferRewriter (VectorTransferToSCFOptions options, MLIRContext *context)
MemRefType tmpMemRefType (TransferOpTy transfer) const
Used for staging the transfer in a local buffer.
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const override
Performs the rewrite.
template<>
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const
Lowers TransferReadOp into a combination of:
template<>
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const
Lowers TransferWriteOp into a combination of:
Public Member Functions inherited from mlir::RewritePattern
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
LogicalResult match (Operation *op) const override
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
Public Attributes
VectorTransferToSCFOptions options
See description of VectorTransferToSCFOptions.
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a rewrite pattern with a certain benefit that matches any operation type.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a rewrite pattern with a certain benefit that matches the operation with the given root name.
RewritePattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a rewrite pattern that may match any operation type.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
This constructor is used for patterns that match against a specific operation type.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag)
This constructor is used when a pattern may match against multiple different types of operations.
Protected Attributes inherited from mlir::RewritePattern
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Detailed Description
template<typename TransferOpTy>
struct mlir::VectorTransferRewriter< TransferOpTy >
Implements lowering of TransferReadOp and TransferWriteOp to a proper abstraction for the hardware.
There are multiple cases.
Case A: Permutation Map does not permute or broadcast.
Progressive lowering occurs to 1-D vector transfer ops according to the description in VectorTransferToSCFOptions.
Case B: Permutation Map permutes and/or broadcasts.
This path will be progressively deprecated and folded into the case above by using vector broadcast and transpose operations.
This path only emits a simple loop nest that performs clipped pointwise copies from a remote to a locally allocated memory.
Consider the case:
// Read the slice `%A[%i0, %i1:%i1+256, %i2:%i2+32]` into
// vector<32x256xf32> and pad with %f0 to handle the boundary case:
%f0 = constant 0.0f : f32
scf.for %i0 = 0 to %0 {
  scf.for %i1 = 0 to %1 step %c256 {
    scf.for %i2 = 0 to %2 step %c32 {
      %v = vector.transfer_read %A[%i0, %i1, %i2], %f0
           {permutation_map: (d0, d1, d2) -> (d2, d1)} :
           memref<?x?x?xf32>, vector<32x256xf32>
}}}
The rewriters construct loop and indices that access MemRef A in a pattern resembling the following (while guaranteeing an always full-tile abstraction):
scf.for %d2 = 0 to %c256 {
  scf.for %d1 = 0 to %c32 {
    %s = %A[%i0, %i1 + %d1, %i2 + %d2] : f32
    %tmp[%d2, %d1] = %s
  }
}
In the current state, only a clipping transfer is implemented by clip, which creates individual indexing expressions of the form:
auto condMax = i + ii < N;
auto max = std_select(condMax, i + ii, N - one)
auto cond = i + ii < zero;
std_select(cond, zero, max);
In the future, clipping should not be the only way and instead we should load vectors + mask them. Similarly on the write side, load/mask/store for implementing RMW behavior.
Lowers TransferOp into a combination of:
local memory allocation;
perfect loop nest over: a. scalar load/stores from local buffers (viewed as a scalar memref); a. scalar store/load to original memref (with clipping).
vector_load/store
local memory deallocation. Minor variations occur depending on whether a TransferReadOp or a TransferWriteOp is rewritten.
Definition at line 148 of file VectorToSCF.h.
Constructor & Destructor Documentation
VectorTransferRewriter()
template<typename TransferOpTy > mlir::VectorTransferRewriter< TransferOpTy >::VectorTransferRewriter (VectorTransferToSCFOptions options, MLIRContext * context) explicit
Definition at line 478 of file VectorToSCF.cpp.
Member Function Documentation
matchAndRewrite() [1/3]
template<typename TransferOpTy> LogicalResult mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const override virtual
Performs the rewrite.
Reimplemented from mlir::RewritePattern.
matchAndRewrite() [2/3]
template<> LogicalResult mlir::VectorTransferRewriter< TransferReadOp >::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const virtual
Lowers TransferReadOp into a combination of:
local memory allocation;
perfect loop nest over: a. scalar load from local buffers (viewed as a scalar memref); a. scalar store to original memref (with clipping).
vector_load from local buffer (viewed as a memref<1 x vector>);
local memory deallocation.
Lowers the data transfer part of a TransferReadOp while ensuring no out-of-bounds accesses are possible. Out-of-bounds behavior is handled by clipping. This means that a given value in memory can be read multiple times and concurrently.
Important notes about clipping and "full-tiles only" abstraction:
When using clipping for dealing with boundary conditions, the same edge value will appear multiple times (a.k.a edge padding). This is fine if the subsequent vector operations are all data-parallel but is generally incorrect in the presence of reductions or extract operations.
More generally, clipping is a scalar abstraction that is expected to work fine as a baseline for CPUs and GPUs but not for vector_load and DMAs. To deal with real vector_load and DMAs, a "padded allocation + view" abstraction with the ability to read out-of-memref-bounds (but still within the allocated region) is necessary.
Whether using scalar loops or vector_load/DMAs to perform the transfer, junk values will be materialized in the vectors and generally need to be filtered out and replaced by the "neutral element". This neutral element is op-dependent so, in the future, we expect to create a vector filter and apply it to a splatted constant vector with the proper neutral element at each ssa-use. This filtering is not necessary for pure data-parallel operations.
In the case of vector_store/DMAs, Read-Modify-Write will be required, which also have concurrency implications. Note that by using clipped scalar stores in the presence of data-parallel only operations, we generate code that writes the same value multiple time on the edge locations.
TODO: implement alternatives to clipping. TODO: support non-data-parallel operations. Performs the rewrite.
Reimplemented from mlir::RewritePattern.
Definition at line 536 of file VectorToSCF.cpp.
References clip(), computeCoalescedIndex(), mlir::failure(), mlir::edsc::loopNestBuilder(), mlir::PatternRewriter::replaceOp(), mlir::success(), and mlir::VectorTransferRewriter< TransferOpTy >::tmpMemRefType().
matchAndRewrite() [3/3]
template<> LogicalResult mlir::VectorTransferRewriter< TransferWriteOp >::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const virtual
Lowers TransferWriteOp into a combination of:
local memory allocation;
vector_store to local buffer (viewed as a memref<1 x vector>);
perfect loop nest over: a. scalar load from local buffers (viewed as a scalar memref); a. scalar store to original memref (with clipping).
local memory deallocation.
More specifically, lowers the data transfer part while ensuring no out-of-bounds accesses are possible. Out-of-bounds behavior is handled by clipping. This means that a given value in memory can be written to multiple times and concurrently.
See Important notes about clipping and full-tiles only abstraction in the description of readClipped above.
TODO: implement alternatives to clipping. TODO: support non-data-parallel operations.
Reimplemented from mlir::RewritePattern.
Definition at line 609 of file VectorToSCF.cpp.
References clip(), computeCoalescedIndex(), mlir::PatternRewriter::eraseOp(), mlir::failure(), mlir::edsc::loopNestBuilder(), mlir::success(), and mlir::VectorTransferRewriter< TransferOpTy >::tmpMemRefType().
tmpMemRefType()
template<typename TransferOpTy > MemRefType mlir::VectorTransferRewriter< TransferOpTy >::tmpMemRefType (TransferOpTy transfer) const
Used for staging the transfer in a local buffer.
Definition at line 485 of file VectorToSCF.cpp.
References mlir::MemRefType::get().
Referenced by mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite().
Member Data Documentation
options
template<typename TransferOpTy> VectorTransferToSCFOptions mlir::VectorTransferRewriter< TransferOpTy >::options
See description of VectorTransferToSCFOptions.
Definition at line 160 of file VectorToSCF.h.
Referenced by mlir::createConvertVectorToSCFPass(), and mlir::populateVectorToSCFConversionPatterns().
The documentation for this struct was generated from the following files:
include/mlir/Conversion/VectorToSCF/VectorToSCF.h
lib/Conversion/VectorToSCF/VectorToSCF.cpp