MLIR: mlir::edsc::ValueBuilder< Op > Struct Template Reference
mlir::edsc::ValueBuilder< Op > Struct Template Reference
#include "mlir/EDSC/Builders.h"
Public Member Functions
template<typename... Args>
ValueBuilder (Args... args)
operator Value ()
Public Attributes
Value value
Detailed Description
template<typename Op>
struct mlir::edsc::ValueBuilder< Op >
Definition at line 68 of file Builders.h.
Constructor & Destructor Documentation
ValueBuilder()
template<typename Op> template<typename... Args> mlir::edsc::ValueBuilder< Op >::ValueBuilder (Args... args) inline
Definition at line 70 of file Builders.h.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), and mlir::edsc::ScopedContext::getLocation().
Member Function Documentation
operator Value()
template<typename Op> mlir::edsc::ValueBuilder< Op >::operator Value () inline
Definition at line 75 of file Builders.h.
Member Data Documentation
value
template<typename Op> Value mlir::edsc::ValueBuilder< Op >::value
Definition at line 76 of file Builders.h.
The documentation for this struct was generated from the following file:
include/mlir/EDSC/Builders.h