MLIR: lib/Dialect/Traits.cpp File Reference
Traits.cpp File Reference
#include "mlir/Dialect/Traits.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/Support/FormatVariadic.h"
Functions
static ArrayRef< int64_t > getShape (Type type)
Returns the shape of the given type.
template<typename iterator_range >
static std::tuple< bool, bool > hasTensorOrVectorType (iterator_range types)
Returns a tuple corresponding to whether range has tensor or vector type.
static bool areCompatibleShapes (ArrayRef< int64_t > shape1, ArrayRef< int64_t > shape2)
static std::string getShapeString (ArrayRef< int64_t > shape)
Function Documentation
areCompatibleShapes()
static bool areCompatibleShapes (ArrayRef< int64_t > shape1, ArrayRef< int64_t > shape2) static
Definition at line 169 of file Traits.cpp.
Referenced by mlir::OpTrait::impl::verifyCompatibleOperandBroadcast().
getShape()
static ArrayRef<int64_t> getShape (Type type) static
Returns the shape of the given type.
Scalars will be considered as having a shape with zero dimensions.
Definition at line 91 of file Traits.cpp.
References mlir::Type::dyn_cast().
Referenced by mlir::OpTrait::util::getBroadcastedType(), mlir::ShapedType::getDimSize(), mlir::ShapedType::getDynamicDimIndex(), mlir::ShapedType::getNumDynamicDims(), mlir::ShapedType::getNumElements(), mlir::spirv::MatrixType::getNumRows(), mlir::ShapedType::getRank(), mlir::ShapedType::getShape(), mlir::ShapedType::hasStaticShape(), mlir::ShapedType::isDynamicDim(), mlir::VectorType::isValidElementType(), mlir::MemRefType::Builder::operator MemRefType(), mlir::detail::VectorTypeStorage::operator==(), mlir::detail::RankedTensorTypeStorage::operator==(), mlir::detail::MemRefTypeStorage::operator==(), parseElementAttrHexValues(), mlir::OpTrait::impl::verifyCompatibleOperandBroadcast(), and mlir::spirv::MatrixType::verifyConstructionInvariants().
getShapeString()
static std::string getShapeString (ArrayRef< int64_t > shape) static
Definition at line 182 of file Traits.cpp.
Referenced by mlir::OpTrait::impl::verifyCompatibleOperandBroadcast().
hasTensorOrVectorType()
template<typename iterator_range > static std::tuple<bool, bool> hasTensorOrVectorType (iterator_range types) static
Returns a tuple corresponding to whether range has tensor or vector type.
Definition at line 163 of file Traits.cpp.
References mlir::Type::isa().
Referenced by mlir::OpTrait::impl::verifyCompatibleOperandBroadcast().