MLIR: lib/Dialect/Linalg/Transforms/Transforms.cpp File Reference
Transforms.cpp File Reference
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/EDSC/Intrinsics.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <type_traits>
Macros
#define DEBUG_TYPE "linalg-transforms"
#define DBGS() (llvm::dbgs() << "[" DEBUG_TYPE << "]: ")
Functions
static AffineExpr substWithMin (AffineExpr e, AffineExpr dim, AffineExpr min, AffineExpr max, bool positivePath=true)
Traverse e and return an AffineExpr where all occurrences of dim have been replaced by either:
static AffineExpr substituteLoopInExpr (AffineExpr expr, AffineExpr dimExpr, Value lbVal, Value ubVal, Value stepVal, SmallVectorImpl< Value > &dims, SmallVectorImpl< Value > &symbols)
Given the lbVal, ubVal and stepVal of a loop, append lbVal and ubVal to dims and stepVal to symbols.
static AffineMap substitute (AffineMap map, SmallVectorImpl< Value > &dims, SmallVectorImpl< Value > &symbols)
Traverse the dims and substitute known min or max expressions in place of induction variables in exprs.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << "[" DEBUG_TYPE << "]: ")
Definition at line 38 of file Transforms.cpp.
Referenced by mlir::linalg::applyStagedPatterns(), mlir::linalg::AffineMinSCFCanonicalizationPattern::matchAndRewrite(), substitute(), and substituteLoopInExpr().
DEBUG_TYPE
#define DEBUG_TYPE "linalg-transforms"
Definition at line 31 of file Transforms.cpp.
Function Documentation
substitute()
static AffineMap substitute (AffineMap map, SmallVectorImpl< Value > & dims, SmallVectorImpl< Value > & symbols) static
Traverse the dims and substitute known min or max expressions in place of induction variables in exprs.
Definition at line 299 of file Transforms.cpp.
References mlir::canonicalizeMapAndOperands(), DBGS, mlir::fullyComposeAffineMapAndOperands(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::AffineMap::getContext(), mlir::scf::getForInductionVarOwner(), mlir::AffineMap::getNumDims(), mlir::scf::getParallelForInductionVarOwner(), mlir::AffineMap::getResults(), mlir::simplifyAffineMap(), and substituteLoopInExpr().
Referenced by mlir::linalg::AffineMinSCFCanonicalizationPattern::matchAndRewrite().
substituteLoopInExpr()
static AffineExpr substituteLoopInExpr (AffineExpr expr, AffineExpr dimExpr, Value lbVal, Value ubVal, Value stepVal, SmallVectorImpl< Value > & dims, SmallVectorImpl< Value > & symbols) static
Given the lbVal, ubVal and stepVal of a loop, append lbVal and ubVal to dims and stepVal to symbols.
Create new AffineDimExpr (lb and ub) and AffineSymbolExpr (step) with positions matching the newly appended values. Substitute occurrences of dimExpr by either the min expression (i.e. lb) or the max expression (i.e. lb + step * floordiv(ub -1 - lb, step)), depending on whether the induction variable is used with a positive or negative coefficient.
Definition at line 279 of file Transforms.cpp.
References DBGS, mlir::floorDiv(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::Value::getContext(), and substWithMin().
Referenced by substitute().
substWithMin()
static AffineExpr substWithMin (AffineExpr e, AffineExpr dim, AffineExpr min, AffineExpr max, bool positivePath = true) static
Traverse e and return an AffineExpr where all occurrences of dim have been replaced by either:
min if positivePath is true when we reach an occurrence of dim
max if positivePath is true when we reach an occurrence of dim positivePath is negated each time we hit a multiplicative or divisive binary op with a constant negative coefficient.
Definition at line 246 of file Transforms.cpp.
References mlir::Add, mlir::AffineExpr::dyn_cast(), mlir::getAffineBinaryOpExpr(), and mlir::AffineConstantExpr::getValue().
Referenced by substituteLoopInExpr().