MLIR: lib/Dialect/SPIRV/Transforms/UpdateVCEPass.cpp File Reference
UpdateVCEPass.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/SPIRV/Passes.h"
#include "mlir/Dialect/SPIRV/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/SPIRVTypes.h"
#include "mlir/Dialect/SPIRV/TargetAndABI.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Visitors.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallSet.h"
Functions
static LogicalResult checkAndUpdateExtensionRequirements (Operation *op, const spirv::TargetEnv &targetEnv, const spirv::SPIRVType::ExtensionArrayRefVector &candidates, llvm::SetVector< spirv::Extension > &deducedExtensions)
Checks that candidates extension requirements are possible to be satisfied with the given targetEnv and updates deducedExtensions if so.
static LogicalResult checkAndUpdateCapabilityRequirements (Operation *op, const spirv::TargetEnv &targetEnv, const spirv::SPIRVType::CapabilityArrayRefVector &candidates, llvm::SetVector< spirv::Capability > &deducedCapabilities)
Checks that candidatescapability requirements are possible to be satisfied with the given targetEnv and updates deducedCapabilities if so.
Function Documentation
checkAndUpdateCapabilityRequirements()
static LogicalResult checkAndUpdateCapabilityRequirements (Operation * op, const spirv::TargetEnv & targetEnv, const spirv::SPIRVType::CapabilityArrayRefVector & candidates, llvm::SetVector< spirv::Capability > & deducedCapabilities) static
Checks that candidatescapability requirements are possible to be satisfied with the given targetEnv and updates deducedCapabilities if so.
Emits errors attaching to the given op on failures.
candidates is a vector of vector for capability requirements following ((Capability::A OR Capability::B) AND (Capability::C OR Capability::D)) convention.
Definition at line 70 of file UpdateVCEPass.cpp.
References mlir::WalkResult::advance(), mlir::spirv::TargetEnv::allows(), checkAndUpdateExtensionRequirements(), mlir::Operation::emitError(), mlir::failed(), mlir::spirv::VerCapExtAttr::get(), mlir::Operation::getName(), mlir::spirv::TargetEnvAttr::getVersion(), mlir::WalkResult::interrupt(), mlir::spirv::lookupTargetEnv(), mlir::Operation::operand_type_begin(), mlir::Operation::operand_type_end(), mlir::Operation::result_type_begin(), mlir::Operation::result_type_end(), mlir::success(), and mlir::WalkResult::wasInterrupted().
checkAndUpdateExtensionRequirements()
static LogicalResult checkAndUpdateExtensionRequirements (Operation * op, const spirv::TargetEnv & targetEnv, const spirv::SPIRVType::ExtensionArrayRefVector & candidates, llvm::SetVector< spirv::Extension > & deducedExtensions) static
Checks that candidates extension requirements are possible to be satisfied with the given targetEnv and updates deducedExtensions if so.
Emits errors attaching to the given op on failures.
candidates is a vector of vector for extension requirements following ((Extension::A OR Extension::B) AND (Extension::C OR Extension::D)) convention.
Definition at line 42 of file UpdateVCEPass.cpp.
References mlir::spirv::TargetEnv::allows(), mlir::Operation::emitError(), mlir::Operation::getName(), and mlir::success().
Referenced by checkAndUpdateCapabilityRequirements().