MLIR: lib/Dialect/Linalg/Transforms/Vectorization.cpp File Reference
Vectorization.cpp File Reference
#include "mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/EDSC/Intrinsics.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <type_traits>
Macros
#define DEBUG_TYPE "linalg-vectorization"
Functions
static bool hasMultiplyAddBody (Region &r)
static LogicalResult isContraction (Operation *op)
static bool mayExistInterleavedUses (Operation *firstOp, Operation *secondOp, ValueRange values)
Check whether there is any interleaved use of any values between firstOp and secondOp.
static SubViewOp getSubViewUseIfUnique (Value v)
Return the unique subview use of v if it is indeed unique, null otherwise.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-vectorization"
Definition at line 37 of file Vectorization.cpp.
Referenced by mlir::linalg::LinalgCopyVTRForwardingPattern::matchAndRewrite(), mayExistInterleavedUses(), and mlir::linalg::vectorizeLinalgOp().
Function Documentation
getSubViewUseIfUnique()
static SubViewOp getSubViewUseIfUnique (Value v) static
Return the unique subview use of v if it is indeed unique, null otherwise.
Definition at line 235 of file Vectorization.cpp.
References mlir::Value::getUses().
Referenced by mlir::linalg::LinalgCopyVTRForwardingPattern::matchAndRewrite(), and mlir::linalg::LinalgCopyVTWForwardingPattern::matchAndRewrite().
hasMultiplyAddBody()
static bool hasMultiplyAddBody (Region & r) static
Definition at line 39 of file Vectorization.cpp.
References mlir::Block::back(), mlir::Block::begin(), mlir::Block::end(), mlir::Region::front(), mlir::Region::getArgument(), and mlir::matchers::m_Val().
Referenced by isContraction().
isContraction()
static LogicalResult isContraction (Operation * op) static
Definition at line 69 of file Vectorization.cpp.
References mlir::failure(), hasMultiplyAddBody(), mlir::AffineMap::isProjectedPermutation(), and mlir::success().
Referenced by mlir::linalg::vectorizeLinalgOp(), and mlir::linalg::vectorizeLinalgOpPrecondition().
mayExistInterleavedUses()
static bool mayExistInterleavedUses (Operation * firstOp, Operation * secondOp, ValueRange values) static
Check whether there is any interleaved use of any values between firstOp and secondOp.
Conservatively return true if any op or value is in a different block.
Definition at line 205 of file Vectorization.cpp.
References DEBUG_TYPE, mlir::Operation::getBlock(), and mlir::Operation::isBeforeInBlock().
Referenced by mlir::linalg::LinalgCopyVTRForwardingPattern::matchAndRewrite(), and mlir::linalg::LinalgCopyVTWForwardingPattern::matchAndRewrite().